### ISSUE TITLE
Error when attampting to login after upgrade from 2.1.20 to 2.1.24

### ISSUE THREAD

**Issue by Aeein** [nilsteampassnet/TeamPass#1137]
PHP Fatal error:  Uncaught exception 'DomainException' with message 'Unsupported Password Hash Supplied' in /var/www/concrete5/teampass/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/concrete5/teampass/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\Password\Factory->verifyHash('admin', '*****************_...')\n#1 /var/www/concrete5/teampass/sources/identify.php(480): PasswordLib\PasswordLib->verifyPasswordHash('admin', '**_********************_...')\n#2 /var/www/concrete5/teampass/sources/identify.php(77): identifyUser('**_*******************')\n#3 {main}\n  thrown in /var/www/concrete5/teampass/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: http://www.mtservices.biz/teampass/index.php?page=items

At this point, i am unable to login or do anything.  Any help would be appreciated.

**Comment by Aeein** [comment]
in this instance, I attempted from Microsoft Edge browser, and my actual password was in the error log where the phrase "MY ACTUAL PASSWORD" is.  This could be a major issue allowing users who may have log access on a webserver to obtain passwords for the admin account or other users acccounts and gaining access to areas they are otherwise restricted from.  

PHP Fatal error:  Uncaught exception 'DomainException' with message 'Unsupported Password Hash Supplied' in /var/www/concrete5/teampass/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/concrete5/teampass/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash('MY ACTUAL PASSWORD', '************')\n#1 /var/www/concrete5/teampass/sources/identify.php(480): PasswordLib\\PasswordLib->verifyPasswordHash('MY ACTUAL PASSWORD', '***********************************')\n#2 /var/www/concrete5/teampass/sources/identify.php(77): identifyUser('*************************')\n#3 {main}\n  thrown in /var/www/concrete5/teampass/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: http://www.mtservices.biz/teampass/index.php?page=items

**Comment by Aeein** [comment]
In further examination, my sk.php did not contain my salt key from the upgrade process.  Once i manually added it to this file, i was able to login and access my files.  Any idea why this would not have happened in step 5 when the file was created?
