### ISSUE TITLE
After login redirected to root domain

### ISSUE THREAD

**Issue by uhlhosting** [nilsteampassnet/TeamPass#1247]
Hello,

I have deployed teampass on /vault folder on uhl.host vault.uhl.hosting or uhl.hosting/vault . When I go to uhl.hosting/vault I see the right page, after login I get redirected to uhl.hosting that hosts a WP site, when I do go to vault.uhl.hosting I get this endlessly: http://vault.uhl.hosting/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install.php .

Any idea?

**Comment by nilsteampassnet** [comment]
Never heard about something similar.
Perhaps hosting issue.

**Comment by highacid** [comment]
I get a blank page on vault.uhl.hosting I have all the steps done completely. Any idea how to debug this issue?

**Comment by nilsteampassnet** [comment]
No errors in logs?

**Comment by highacid** [comment]
I get a blank page, I just worked around a new install, all installation steps completed succesfully. When I hit the http://vault.uhl.hosting nothing blank page. 

```
[31-Mar-2016 07:25:52 UTC] PHP Fatal error:  Uncaught exception 'configFileNotFoundException' with message 'configuration file not found for CSRFProtector!' in /home/uhl/public_html/vault/includes/libraries/csrfp/libs/csrf/csrfprotector.php:82
Stack trace:
#0 /home/uhl/public_html/vault/index.php(31): csrfProtector::init()
#1 {main}
  thrown in /home/uhl/public_html/vault/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 82
[31-Mar-2016 07:25:54 UTC] PHP Fatal error:  Uncaught exception 'configFileNotFoundException' with message 'configuration file not found for CSRFProtector!' in /home/uhl/public_html/vault/includes/libraries/csrfp/libs/csrf/csrfprotector.php:82
Stack trace:
#0 /home/uhl/public_html/vault/index.php(31): csrfProtector::init()
#1 {main}
  thrown in /home/uhl/public_html/vault/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 82
[31-Mar-2016 07:26:56 UTC] PHP Fatal error:  Uncaught exception 'configFileNotFoundException' with message 'configuration file not found for CSRFProtector!' in /home/uhl/public_html/vault/includes/libraries/csrfp/libs/csrf/csrfprotector.php:82
Stack trace:
#0 /home/uhl/public_html/vault/index.php(31): csrfProtector::init()
#1 {main}
  thrown in /home/uhl/public_html/vault/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 82
```
