### ISSUE TITLE
2.1.27 - New user can't log in - Possibly 2FA issue

### ISSUE THREAD

**Issue by maxallen123** [nilsteampassnet/TeamPass#1660]
### Steps to reproduce
1. Add a new user
2. E-mail 2FA code to new user
3. Attempt to log in as new user with 2FA code & new username

### Expected behaviour
Should log in

### Actual behaviour
Icon at top starts spinning, spins endlessly.

### Server configuration
**Operating system**:
Ubuntu Server 16.04.1 LTS

**Web server:**
Apache 2.4.18

**Database:**
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.15

**Teampass version:** 
2.1.27

**Updated from an older Teampass or fresh install:**
Updated from 2.1.26_2

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### Web server error log
```
[Tue Feb 28 18:14:11.582801 2017] [:error] [pid 29944] [client 192.168.253.3:50872] PHP Fatal error:  Uncaught Error: Call to undefined function Authentication\\TwoFactorAuth\\Providers\\Qr\\curl_init() in /var/www/TeamPass/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/BaseHTTPQRCodeProvider.php:12\nStack trace:\n#0 /var/www/TeamPass/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/GoogleQRCodeProvider.php(30): Authentication\\TwoFactorAuth\\Providers\\Qr\\BaseHTTPQRCodeProvider->getContent('https://chart.g...')\n#1 /var/www/TeamPass/includes/libraries/Authentication/TwoFactorAuth/TwoFactorAuth.php(151): Authentication\\TwoFactorAuth\\Providers\\Qr\\GoogleQRCodeProvider->getQRCodeImage('otpauth://totp/...', 200)\n#2 /var/www/TeamPass/sources/identify.php(608): Authentication\\TwoFactorAuth\\TwoFactorAuth->getQRCodeImageAsDataUri('Teampass - ball...', 'ZKDYS32FHPNOOGZ...')\n#3 /var/www/TeamPass/sources/identify.php(200): identifyUser('zQI+FTUStlgSaci...')\n#4 {main}\n  thrown in /var/www/TeamPass/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/BaseHTTPQRCodeProvider.php on line 12, referer: https://REDACTED/index.php?page=items
```

Found the above error in error.log after trying to log in. I've got TeamPass tied to an AD LDAP server, I tried once with a new user from scratch and once with a new user created on the AD server.

**Comment by maxallen123** [comment]
Found issue - php-curl needs to be installed. If this is a new requirement, it would be nice if upgrade script reports on either missing packages or new requirements.
