### ISSUE TITLE
2FA Google Authenticator Error

### ISSUE THREAD

**Issue by spikarbr** [nilsteampassnet/TeamPass#1694]
### Steps to reproduce
1. AD-User created
2. 2FA activated
3. First time pass (2FA) send to user
4. User tried to login with the first time password for 2FA

### Expected behaviour
1. You will then have the opportunity to set up your one-time credentials for Teampass password manager

### Actual behaviour
1. Site is loading and loading and loading and stays in login screen

### Server configuration
**Operating system**: Ubuntu 16.04 Server

**Web server:** Apache/2.4.18

**Database:** MySQL 5.7.17

**PHP version:** 7.0.15

**Teampass version:** 2.1.27

**Updated from an older Teampass or fresh install:** Fresh Install 

### Client configuration
**Browser:** All browsers tested 

**Operating system:** Win10

#### Web server error log
/var/log/apache2/error.log

Insert your webserver log here
3. Thu Mar 16 17:32:48.476189 2017] [:error] [pid 1672] [client X.X.X.X:58763] PHP Fatal error:  Uncaught Error: Call to undefined function Authentication\\TwoFactorAuth\\Providers\\Qr\\curl_init() in /var/www/html/teampass/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/BaseHTTPQRCodeProvider.php:12\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/GoogleQRCodeProvider.php(30): Authentication\\TwoFactorAuth\\Providers\\Qr\\BaseHTTPQRCodeProvider->getContent('https://chart.g...')\n#1 /var/www/html/teampass/includes/libraries/Authentication/TwoFactorAuth/TwoFactorAuth.php(151): Authentication\\TwoFactorAuth\\Providers\\Qr\\GoogleQRCodeProvider->getQRCodeImage('otpauth://totp/...', 200)\n#2 /var/www/html/teampass/sources/identify.php(608): Authentication\\TwoFactorAuth\\TwoFactorAuth->getQRCodeImageAsDataUri('Teampass - skar...', 'ZJNQ5M2GT24EBDJ...')\n#3 /var/www/html/teampass/sources/identify.php(200): identifyUser('vgGT1TC+ylhjur2...')\n#4 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Authentication/TwoFactorAuth/Providers/Qr/BaseHTTPQRCodeProvider.php on line 12, referer: http://X.X.X.X/teampass/index.php?page=items

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by spikarbr** [comment]
Top! 

Problem solved throught #1687

apt-get install php-curl
