### ISSUE TITLE
Can not add salt to new user account - Internal Server Error [500]

### ISSUE THREAD

**Issue by Jurik81** [nilsteampassnet/TeamPass#1824]
### Steps to reproduce
1. Create new (first) user account with your admin account 
2. Login with this new user account
3. Go to profile settings
4. Try to create personal salt
5. Enter new salt (old salt is automatically "0")
6. Click "Change"

### Expected behaviour
New salt should be saved for later use.

### Actual behaviour
Javascript Popup with "Internal Server Error [500]" and nothing more. Spinning loading symbol and 0% progress.

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.6
**Teampass version:** 
2.1.27
**Updated from an older Teampass or fresh install:**
Fresh install
### Client configuration
**Browser:**
Chrome version 59.0.3071.115 (Official Build) (64-Bit)
**Operating system:**
MacOSX 10.12.5
#### Web server error log
```[Mon Jul 24 11:33:54.339161 2017] [:error] [pid 30351] [client 141.16.127.34:53760] script '/srv/teampass/install.php' not found or unable to stat
[Mon Jul 24 18:06:16.694819 2017] [:error] [pid 13114] [client 141.16.127.34:55843] PHP Notice:  Undefined index: user_privilege in /srv/teampass/profile.php on line 89, referer: https://pass.patientus.de/index.php?page=manage_main
[Mon Jul 24 18:06:16.694864 2017] [:error] [pid 13114] [client 141.16.127.34:55843] PHP Notice:  Undefined index: pwComplexity in /srv/teampass/profile.php on line 221, referer: https://pass.patientus.de/index.php?page=manage_main
[Mon Jul 24 18:26:15.596813 2017] [:error] [pid 13689] [client 141.16.127.34:59824] PHP Warning:  require(../includes/libraries/Encryption/Crypt/aesctr.php): failed to open stream: No such file or directory in /srv/teampass/sources/SplClassLoader.php on line 133, referer: https://pass.patientus.de/index.php?page=manage_folders
[Mon Jul 24 18:26:15.596827 2017] [:error] [pid 13689] [client 141.16.127.34:59824] PHP Fatal error:  require(): Failed opening required '../includes/libraries/Encryption/Crypt/aesctr.php' (include_path='.:/usr/share/php:/usr/share/pear') in /srv/teampass/sources/SplClassLoader.php on line 133, referer: https://pass.patientus.de/index.php?page=manage_folders
[Mon Jul 24 18:29:16.133785 2017] [:error] [pid 13845] [client 141.16.127.34:59872] PHP Warning:  require(../includes/libraries/Encryption/Crypt/aesctr.php): failed to open stream: No such file or directory in /srv/teampass/sources/SplClassLoader.php on line 133, referer: https://pass.patientus.de/index.php?page=manage_main
[Mon Jul 24 18:29:16.133811 2017] [:error] [pid 13845] [client 141.16.127.34:59872] PHP Fatal error:  require(): Failed opening required '../includes/libraries/Encryption/Crypt/aesctr.php' (include_path='.:/usr/share/php:/usr/share/pear') in /srv/teampass/sources/SplClassLoader.php on line 133, referer: https://pass.patientus.de/index.php?page=manage_main
[Mon Jul 24 18:29:32.613749 2017] [:error] [pid 13845] [client 141.16.127.34:59878] PHP Warning:  require(../includes/libraries/Encryption/Crypt/aesctr.php): failed to open stream: No such file or directory in /srv/teampass/sources/SplClassLoader.php on line 133, referer: https://pass.patientus.de/index.php?page=manage_main
[Mon Jul 24 18:29:32.613765 2017] [:error] [pid 13845] [client 141.16.127.34:59878] PHP Fatal error:  require(): Failed opening required '../includes/libraries/Encryption/Crypt/aesctr.php' (include_path='.:/usr/share/php:/usr/share/pear') in /srv/teampass/sources/SplClassLoader.php on line 133, referer: https://pass.patientus.de/index.php?page=manage_main
[Mon Jul 24 18:34:16.705456 2017] [:error] [pid 13876] [client 141.16.127.34:59951] PHP Fatal error:  Call to undefined function prefix_table() in /srv/teampass/sources/kb.queries.categories.php on line 42, referer: https://pass.patientus.de/index.php?page=kb
[Mon Jul 24 18:35:47.522416 2017] [:error] [pid 13925] [client 141.16.127.34:59985] PHP Fatal error:  Call to undefined function prefix_table() in /srv/teampass/sources/kb.queries.categories.php on line 42, referer: https://pass.patientus.de/index.php?page=kb
[Mon Jul 24 18:35:49.197972 2017] [:error] [pid 13876] [client 141.16.127.34:59986] PHP Fatal error:  Call to undefined function prefix_table() in /srv/teampass/sources/kb.queries.categories.php on line 42, referer: https://pass.patientus.de/index.php?page=kb
[Tue Jul 25 10:23:31.981267 2017] [:error] [pid 1021] [client 141.16.127.34:62012] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=manage_roles
[Tue Jul 25 10:24:36.371782 2017] [:error] [pid 1054] [client 141.16.127.34:62026] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=kb
[Tue Jul 25 10:24:57.769103 2017] [:error] [pid 994] [client 141.16.127.34:62033] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=kb
[Tue Jul 25 10:25:02.084457 2017] [:error] [pid 994] [client 141.16.127.34:62033] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=manage_settings
[Tue Jul 25 10:27:37.290815 2017] [:error] [pid 1166] [client 141.16.127.34:62082] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=manage_main
[Tue Jul 25 11:12:08.578720 2017] [:error] [pid 2584] [client 141.16.127.34:63251] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=manage_folders
[Tue Jul 25 12:05:59.417532 2017] [:error] [pid 4248] [client 141.16.127.34:64638] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=manage_folders
[Tue Jul 25 12:20:35.750838 2017] [:error] [pid 4839] [client 141.16.127.34:65046] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=manage_main
[Tue Jul 25 12:29:19.202292 2017] [:error] [pid 5204] [client 141.16.127.34:65227] PHP Notice:  Undefined index: file_is_now_ready in /srv/teampass/admin.settings.load.php on line 337, referer: https://pass.patientus.de/index.php?page=manage_settings
[Tue Jul 25 12:41:40.283106 2017] [:error] [pid 5680] [client 141.16.127.34:50145] PHP Notice:  Undefined index: please_confirm_operation in /srv/teampass/profile.php on line 205, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:41:40.283129 2017] [:error] [pid 5680] [client 141.16.127.34:50145] PHP Notice:  Undefined index: continue in /srv/teampass/profile.php on line 209, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:42:14.074238 2017] [:error] [pid 5547] [client 141.16.127.34:50289] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /srv/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', '')\n#1 /srv/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString('')\n#2 /srv/teampass/sources/main.queries.php(580): defuse_validate_personal_key('0', '')\n#3 /srv/teampass/sources/main.queries.php(39): mainQuery()\n#4 {main}\n  thrown in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:42:32.923661 2017] [:error] [pid 5733] [client 141.16.127.34:50367] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /srv/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', '')\n#1 /srv/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString('')\n#2 /srv/teampass/sources/main.queries.php(580): defuse_validate_personal_key('0', '')\n#3 /srv/teampass/sources/main.queries.php(39): mainQuery()\n#4 {main}\n  thrown in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:42:46.379909 2017] [:error] [pid 5654] [client 141.16.127.34:50412] PHP Notice:  Undefined index: please_confirm_operation in /srv/teampass/profile.php on line 205, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:42:46.379930 2017] [:error] [pid 5654] [client 141.16.127.34:50412] PHP Notice:  Undefined index: continue in /srv/teampass/profile.php on line 209, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:43:17.336232 2017] [:error] [pid 5756] [client 141.16.127.34:50558] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /srv/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', '')\n#1 /srv/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString('')\n#2 /srv/teampass/sources/main.queries.php(580): defuse_validate_personal_key('', '')\n#3 /srv/teampass/sources/main.queries.php(39): mainQuery()\n#4 {main}\n  thrown in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:43:22.547154 2017] [:error] [pid 5732] [client 141.16.127.34:50582] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /srv/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', '')\n#1 /srv/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString('')\n#2 /srv/teampass/sources/main.queries.php(580): defuse_validate_personal_key('0', '')\n#3 /srv/teampass/sources/main.queries.php(39): mainQuery()\n#4 {main}\n  thrown in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:50:48.968959 2017] [:error] [pid 6076] [client 141.16.127.34:52533] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /srv/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', '')\n#1 /srv/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString('')\n#2 /srv/teampass/sources/main.queries.php(580): defuse_validate_personal_key('0', '')\n#3 /srv/teampass/sources/main.queries.php(39): mainQuery()\n#4 {main}\n  thrown in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://pass.patientus.de/index.php?page=items
[Tue Jul 25 12:51:26.556583 2017] [:error] [pid 6099] [client 141.16.127.34:52695] PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168\nStack trace:\n#0 /srv/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', '')\n#1 /srv/teampass/sources/main.functions.php(457): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString('')\n#2 /srv/teampass/sources/main.queries.php(580): defuse_validate_personal_key('0', '')\n#3 /srv/teampass/sources/main.queries.php(39): mainQuery()\n#4 {main}\n  thrown in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://pass.patientus.de/index.php?page=items
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log)) <= URL doesn't work anymore
```
POST https://pass.patientus.de/sources/main.queries.php 500 (Internal Server Error)
  | new_send | @ | csrfprotector.js:272
-- | -- | -- | --
  | send | @ | jquery.js:8706
  | ajax | @ | jquery.js:8136
  | jQuery.(anonymous function) | @ | jquery.js:8282
  | (anonymous) | @ | VM6303:284
  | dispatch | @ | jquery.js:5095
  | elemData.handle | @ | jquery.js:4766
```

**Comment by nilsteampassnet** [comment]
The log shows that some files are missing.
Did you copy the complete package of files?
Can you try to download once again the release package and copy-paste the files back to your Teampass folder?

**Comment by Jurik81** [comment]
Yes, all of these files are inside the project. Today, the missing file error message disappeared, but this one still occurs:
```
[26-Jul-2017 10:27:23 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Defuse\Crypto\Exception\BadFormatException' with message 'Encoded data is shorter than expected.' in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php:168
Stack trace:
#0 /srv/teampass/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\Crypto\Encoding::loadBytesFromChecksummedAsciiSafeString('\xDE\xF1\x00\x00', '')
#1 /srv/teampass/sources/main.functions.php(457): Defuse\Crypto\KeyProtectedByPassword::loadFromAsciiSafeString('')
#2 /srv/teampass/sources/main.queries.php(580): defuse_validate_personal_key('0', '')
#3 /srv/teampass/sources/main.queries.php(39): mainQuery()
#4 {main}
  thrown in /srv/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 168
```

But I was able to change my salt over "My Profile -> Tasks -> Change my personal salt key" - bad thing is that all of my personal passwords are gone now. But I guess this is another bug.

**Comment by nilsteampassnet** [comment]
This error indicates that the validation of your psk failed and couldn't be validated.
Now regarding all your logs, it seems that this is related each time to operation "Change my personal saltkey" where you defined `Old saltkey` to `0` and `NEw saltkey` to empty.
But such condition is blocked by a test, but that contains an copy-paste error :(
This may be why you could lead to this situation.

In file `./profile.php`, please replace
```
    // manage CHANGE OF PERSONAL SALTKEY
    $("#button_change_psk").click(function() {
        $("#psk_change_wait").show();

        if ($("#new_personal_saltkey").val() === "" || $("#new_personal_saltkey").val() === "") {
            $("#psk_change_wait").hide();
```
by
```
    // manage CHANGE OF PERSONAL SALTKEY
    $("#button_change_psk").click(function() {
        $("#psk_change_wait").show();

        if ($("#new_personal_saltkey").val() === "" || $("#old_personal_saltkey").val() === "") {
            $("#psk_change_wait").hide();
```

Impact: your personal passwords are lost.

How to test: set your personal saltkey, open existing item and change its password. Close session and relog in. Set your psk and display password of your modified item.

> But I was able to change my salt over "My Profile -> Tasks -> Change my personal salt key" - bad thing is that all of my personal passwords are gone now. But I guess this is another bug.

No the 2 things are related. As on your Teampass instance, the decryption fails then re-encrypting over it will just encrypt dummy data.

**Comment by nilsteampassnet** [comment]
I've committed a fix to prevent such case to occur.
