### ISSUE TITLE
Problem with personal salt keys after upgrade 2.1.25 to 2.1.27

### ISSUE THREAD

**Issue by jpch** [nilsteampassnet/TeamPass#2154]
### Steps to reproduce
1. Upgraded from 2.1.25 to 2.1.27 -  tp.config.php was missing, but renamed old settings.php to tp.config.php
2. Logged in with no problems, could see all shared folders and items/passwords. 
3. Personal folder had no items. Check screenshot.
![screenshot 2018-03-20 11 54 57](https://user-images.githubusercontent.com/1645240/37656721-c141eee4-2c40-11e8-831e-e1f490a2e4bf.png)

4.1 By clicking on "set personal set key" and simply clicking ok (using the auto-fill input), it shows the personal items but without the passwords
4.2 When trying to change the personal salt key, it accepts the new password and shows the items with passwords, but it keeps prompting the personal salt key everytime I choose one item (after logout/login)
4.2.1 The first time I made this procedure, got the error shown at the log below. However, after that, other users changed the salt key with no problem.
4.3 If the salt key is reseted, all items are lost (as expected). By adding new items and after logout/login), it keeps prompting the salt key everytime I choose one item (as the behaviour on 4.2), and only after that the itens are fully shown.

### Expected behaviour
Login and see all items (personal and shared)

### Actual behaviour
After login, the personal folder is not available and it shows the error shown on the screenshot
After setting or changing the salt key, it does not store the salk key information and keeps prompting the personal salk key in order to show the items

### Server configuration
**Operating system**: Linux server.domain.com 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64

**Web server:** Apache/2.4.6

**Database:** 5.5.56-MariaDB

**PHP version:** 5.6.25

**Teampass version:** 2.1.27.11

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/home/teampass/public_html',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/home/teampass/public_html/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'path_to_files_folder' => '/home/teampass/public_html/files',
'url_to_files_folder' => 'https://teampass2.domain.com/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '1',
'richtext' => '0',
'allow_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => 'mail.domain.com',
'email_smtp_auth' => '0',
'email_auth_username' => '',
'email_auth_pwd' => '',
'email_port' => '',
'email_from' => '',
'email_from_name' => '',
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '1',
'send_stats_time' => '0',
'tree_counters' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'copy_to_clipboard_small_icons' => '0',
'can_create_root_folder' => '0',
'ldap_type' => 'posix',
'ldap_domain_dn' => 'dc=domain,dc=com',
'ldap_domain_controler' => 'ldap.domain.com,ldap2.domain.com',
'ldap_user_attribute' => 'uid',
'ldap_suffix' => 'ou=people',
'menu_type' => 'context',
'item_duplicate_in_same_folder' => '0',
'roles_allowed_to_print' => '0',
'get_tp_info' => '1',
'ga_website_name' => 'TeamPass for ChangeMe',
'email_security' => 'none',
'enable_email_notification_on_user_pw_change' => '0',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'email_server_url' => '',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'item_extra_fields' => '0',
'enable_attachment_encryption' => '0',
'settings_offline_mode' => '0',
'offline_key_level' => '0',
'bck_script_filename' => 'bck_cpassman',
'bck_script_path' => '/home/teampass/backups',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'saltkey_ante_2127' => 'salk_key',
'ldap_object_class' => '0',
'teampass_version' => '2.1.27',
'migration_to_2127' => 'done',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;st',
'agses_authentication_enabled' => '0',
'timezone' => 'UTC',
'personal_saltkey_security_level' => '0',
'ldap_new_user_is_administrated_by' => '0',
'ldap_port' => '389',
'enable_http_request_login' => '0',
'otv_is_enabled' => '0',
'ldap_and_local_authentication' => '0',
'files_with_defuse' => 'done',
);
```

**Updated from an older Teampass or fresh install:**

Updated from 2.1.25

### Client configuration

**Browser:** Safari - 11.0.3

**Operating system:** OS X - 32bits

#### Web server error log
```

First time error:
[Tue Mar 20 12:27:16.468955 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Defuse\\Crypto\\Exception\\BadFormatException' with message 'Encoded data is shorter than expected.' in /home/teampass/public_html/includes/libraries/Encryption/Encryption/Encoding.php:168, referer: https://teampass2.domain.com/index.php?page=items
[Tue Mar 20 12:27:16.469049 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr: Stack trace:, referer: https://teampass2.domain.com/index.php?page=items
[Tue Mar 20 12:27:16.469060 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr: #0 /home/teampass/public_html/includes/libraries/Encryption/Encryption/KeyProtectedByPassword.php(52): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString('\\xDE\\xF1\\x00\\x00', ''), referer: https://teampass2.domain.com/index.php?page=items
[Tue Mar 20 12:27:16.469071 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr: #1 /home/teampass/public_html/sources/main.functions.php(481): Defuse\\Crypto\\KeyProtectedByPassword::loadFromAsciiSafeString(''), referer: https://teampass2.domain.com/index.php?page=items
[Tue Mar 20 12:27:16.469080 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr: #2 /home/teampass/public_html/sources/main.queries.php(676): defuse_validate_personal_key('8e4()..)75a...', ''), referer: https://teampass2.domain.com/index.php?page=items
[Tue Mar 20 12:27:16.469088 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr: #3 /home/teampass/public_html/sources/main.queries.php(53): mainQuery(), referer: https://teampass2.domain.com/index.php?page=items
[Tue Mar 20 12:27:16.469118 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr: #4 {main}, referer: https://teampass2.domain.com/index.php?page=items
[Tue Mar 20 12:27:16.469127 2018] [fcgid:warn] [pid 15872] [client IP_ADDRESS:64580] mod_fcgid: stderr:   thrown in /home/teampass/public_html/includes/libraries/Encryption/Encryption/Encoding.php on line 168, referer: https://teampass2.domain.com/index.php?page=items

```

#### Teampass 10 last system errors
```
(for some reason the teampass system logs are not being written correctly)
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```

First time error:
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (main.queries.php, line 0)

```

**Comment by nilsteampassnet** [comment]
Can you please get the teampass errors?
Run this mysql query `SELECT * FROM `teampass_log_system` WHERE type="error" order by date DESC limit 0,50 `

**Comment by jpch** [comment]
Hi, here are the results attached. However, the errors are kind of outdated, it seems that the current version is not updating that table.. weird..
Should I upgraded other minor versions from 2.1.25 to 2.1.27.11, instead of doing it directly? I've tried to search on the documentation for that info, but i couldn't find it.
[errors_teampass.xlsx](https://github.com/nilsteampassnet/TeamPass/files/1844279/errors_teampass.xlsx)
Thanks!

**Comment by nilsteampassnet** [comment]
No the current version absolutely updates this table on mysql errors.
If nothing added here then there is no error.

Can you contact me by skype: nils.teampass

**Comment by nilsteampassnet** [comment]
Can you please do the next

Open file `/sources/core.php`
Replace
```
if (isset($SETTINGS['enable_personal_saltkey_cookie']) === true
    && $SETTINGS['enable_personal_saltkey_cookie'] == 1
    && isset($_SESSION['user_id']) === true
    && isset($_COOKIE['TeamPass_PFSK_'.md5($_SESSION['user_id'])]) === true
) {
    $_SESSION['user_settings']['clear_psk'] = decrypt($_COOKIE['TeamPass_PFSK_'.md5($_SESSION['user_id'])], '');
}
```
by
```
if (isset($SETTINGS['enable_personal_saltkey_cookie']) === true
    && $SETTINGS['enable_personal_saltkey_cookie'] == 1
    && isset($_SESSION['user_id']) === true
    && isset($_COOKIE['TeamPass_PFSK_'.md5($_SESSION['user_id'])]) === true
) {
    $_SESSION['user_settings']['session_psk'] = $_COOKIE['TeamPass_PFSK_'.md5($_SESSION['user_id'])];
}
```

Open file `/sources/main.queries.php`
Replace
```
                    // Store PSK
                    $_SESSION['user_settings']['session_psk'] = $user_key_encoded;
                    setcookie(
                        "TeamPass_PFSK_".md5($_SESSION['user_id']),
                        encrypt($filter_psk, ""),
                        (!isset($SETTINGS['personal_saltkey_cookie_duration']) || $SETTINGS['personal_saltkey_cookie_duration'] == 0) ? time() + 60 * 60 * 24 : time() + 60 * 60 * 24 * $SETTINGS['personal_saltkey_cookie_duration'],
                        '/'
                    );
```
by
```
                    // Store PSK
                    $_SESSION['user_settings']['session_psk'] = $user_key_encoded;
                    setcookie(
                        "TeamPass_PFSK_".md5($_SESSION['user_id']),
                        $user_key_encoded,
                        (!isset($SETTINGS['personal_saltkey_cookie_duration']) || $SETTINGS['personal_saltkey_cookie_duration'] == 0) ? time() + 60 * 60 * 24 : time() + 60 * 60 * 24 * $SETTINGS['personal_saltkey_cookie_duration'],
                        '/'
                    );
```

**Comment by nilsteampassnet** [comment]
Ok I think it is corrected now.
I'will commit the change in branch, and merge in a new package for 2.1.27.11

**Comment by jpch** [comment]
Hi,
I've updated teampass installation, but it keeps happening. Apparently teampass saves the cookie on session (it starts with "def"), but when I log in the cookie appears to be deleted..
Thanks!
