### ISSUE TITLE
Cant Login as Users, Admin Cant Change Passwords

### ISSUE THREAD

**Issue by slamanna212** [nilsteampassnet/TeamPass#2418]
### Steps to reproduce
1. Log in as Initial Admin User
2. Change a users password
3. try to log in as user

### Expected behaviour
Tell us what should happen - user logs in

### Actual behaviour
Tell us what happens instead
The admin can change the password with no errors, when the user then tries to login, it says  Login credentials do not correspond!

### Server configuration
**Operating system**: Ubuntu Server 16.04

**Web server:**
nginx version: nginx/1.14.0

**Database:**
mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )

**Teampass version:** 
2.1.27.22
**Teampass configuration file:**
Not sure where this is?
**Updated from an older Teampass or fresh install:** 
Fresh install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome 69 and mobile safari

**Operating system:** Windows 10 and iOS 12

#### Web server error log

```
2018/09/25 01:52:46 [error] 10601#10601: *262335 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: conversion_utf8 in /var/www/pass.bene-it.com/public_html/install/upgrade.php on line 615
PHP message: PHP Notice:  Undefined variable: conversion_utf8 in /var/www/pass.bene-it.com/public_html/install/upgrade.php on line 623" while reading upstream, client: 174.49.168.14, server: pass.bene-it.com, request: "POST /install/upgrade.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "pass.bene-it.com", referrer: "https://pass.bene-it.com/install/upgrade.php"
2018/09/25 01:53:16 [error] 10601#10601: *262338 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: conversion_utf8 in /var/www/pass.bene-it.com/public_html/install/upgrade.php on line 615
PHP message: PHP Notice:  Undefined variable: conversion_utf8 in /var/www/pass.bene-it.com/public_html/install/upgrade.php on line 623" while reading upstream, client: 174.49.168.14, server: pass.bene-it.com, request: "POST /install/upgrade.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "pass.bene-it.com", referrer: "https://pass.bene-it.com/install/upgrade.php"
2018/09/25 02:07:25 [error] 10601#10601: *262508 FastCGI sent in stderr: "PHP message: PHP Warning:  chmod(): Operation not permitted in /var/www/pass.bene-it.com/public_html/sources/main.functions.php on line 2289" while reading response header from upstream, client: 174.49.168.14, server: pass.bene-it.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "pass.bene-it.com", referrer: "https://pass.bene-it.com/install/install.php"
2018/09/25 03:05:42 [error] 10601#10601: *264220 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Expected positive integer in /var/www/pass.bene-it.com/public_html/includes/libraries/PasswordGenerator/Generator/ComputerPasswordGenerator.php:128
Stack trace:
#0 /var/www/pass.bene-it.com/public_html/sources/main.queries.php(1007): PasswordGenerator\Generator\ComputerPasswordGenerator->setLength(0)
#1 /var/www/pass.bene-it.com/public_html/sources/main.queries.php(53): mainQuery()
#2 {main}
  thrown in /var/www/pass.bene-it.com/public_html/includes/libraries/PasswordGenerator/Generator/ComputerPasswordGenerator.php on line 128" while reading response header from upstream, client: 174.49.168.14, server: pass.bene-it.com, request: "POST /sources/main.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "pass.bene-it.com", referrer: "https://pass.bene-it.com/index.php?page=manage_users"

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
nothing appeared in the console
```

**Comment by nilsteampassnet** [comment]
Ok it is not the change process that fails but the generation of a new password.

I will fix it.

**Comment by slamanna212** [comment]
Thank you very much for the quick response! Is there a way to pull this latest data to test?
