### ISSUE TITLE
When enabling LDAPS in settings, LDAP connection fails

### ISSUE THREAD

**Issue by turekg** [nilsteampassnet/TeamPass#2973]
Setting port 636, and clicking to `Use LDAP through SSL (LDAPS)` to 'Yes' results in failed connection when testing with known user which previously worked in unsecured mode

**Comment by FooBarTrixibell** [comment]
I also have this issue, in my logs I see -

PHP Warning:  Illegal offset type in /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php on line 494

Following this it looks like the page expects an array of server names, adding a second server name (even if it is the same one) causes the error to change to -

PHP Fatal error:  Uncaught ErrorException: ldap_connect(): Could not create session handle: Bad parameter to an ldap routine in /var/www/html/TeamPass/includes/libraries/LdapRecord/Ldap.php:194\nStack trace:\n#0 [internal function]: LdapRecord\\LdapBase->LdapRecord\\{closure}()\n#1 /var/www/html/TeamPass/includes/libraries/LdapRecord/Ldap.php(194): ldap_connect()\n#2 /var/www/html/TeamPass/includes/libraries/LdapRecord/LdapBase.php(160): LdapRecord\\Ldap->LdapRecord\\{closure}()\n#3 /var/www/html/TeamPass/includes/libraries/LdapRecord/Ldap.php(195): LdapRecord\\LdapBase->executeFailableOperation()\n#4 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(169): LdapRecord\\Ldap->connect()\n#5 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(141): LdapRecord\\Connection->initialize()\n#6 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(99): LdapRecord\\Connection->setLdapConnection()\n#7 /var/www/html/TeamPass/sources/ldap.queries.php(164): LdapRecord\\Connection->__construct()\n#8 {main}\n\nNext L in /var/www/html/TeamPass/includes/libraries/LdapRecord/LdapRecordException.php on line 26

**Comment by ServiceMRE** [comment]
hi,
Did you try this https://github.com/nilsteampassnet/TeamPass/issues/1256 ?
Regards

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
