### ISSUE TITLE
Installation Stuck on Database Population

### ISSUE THREAD

**Issue by royalaigle** [nilsteampassnet/TeamPass#3012]
### Steps to reproduce
1. Install wamp3_x86_x64
2. Download TeamPass 3.0.0.9
3. Configure Database based on instructions https://teampass.readthedocs.io/en/latest/install/install-windows/
4. Start installing Teampass
5. Stuck on "Database population"

### Expected behaviour
Tell us what should happen
Database should populate and installation to proceed to the next step
### Actual behaviour
Tell us what happens instead
Database population did not complete, it got stuck on the 4th or 5th table
### Server configuration
**Operating system**:
Windows Server 2019
**Web server:**
WAMP server
**Database:**
Mysql
**PHP version:**
5.6.40
7.4.26
8.0.13
8.1.0
**Teampass version:** 
3.0.0.9
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** No
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => 'D:/wamp64/www/teampass',
    'cpassman_url' => 'http://localhost/teampass',
    'favicon' => 'http://localhost/teampass/favicon.ico',
    'path_to_upload_folder' => 'D:/wamp64/www/teampass/upload',
    'url_to_upload_folder' => 'http://localhost/teampass/upload',
    'path_to_files_folder' => 'D:/wamp64/www/teampass/files',
    'url_to_files_folder' => 'http://localhost/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1640644267',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => 'D:/wamp64/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'h7ZJFsHn9dLrEQDtwgXUbmWhNws9bN28X755QzGV',
    'admin_2fa_required' => '1',
);
### Client configuration
**Browser:**
Chrome
Edge
**Operating system:**
Windows Server 2019
Windows Server 2016
Windows 10
#### Web server error log
```
VM167:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16:11709)
    at Object.complete (install.js:127:34)
    at Object.resolveWith (jquery.min.js:16:15493)
    at w (jquery.min.js:18:8574)
    at XMLHttpRequest.d (jquery.min.js:18:14247)
parseJSON @ jquery.min.js:16
complete @ install.js:127
resolveWith @ jquery.min.js:16
w @ jquery.min.js:18
d @ jquery.min.js:18
XMLHttpRequest.send (async)
send @ jquery.min.js:18
ajax @ jquery.min.js:18
checkPage @ install.js:108
onclick @ install.php:71
VM169:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16:11709)
    at Object.complete (install.js:127:34)
    at Object.resolveWith (jquery.min.js:16:15493)
    at w (jquery.min.js:18:8574)
    at XMLHttpRequest.d (jquery.min.js:18:14247)
parseJSON @ jquery.min.js:16
complete @ install.js:127
resolveWith @ jquery.min.js:16
w @ jquery.min.js:18
d @ jquery.min.js:18
XMLHttpRequest.send (async)
send @ jquery.min.js:18
ajax @ jquery.min.js:18
checkPage @ install.js:108
onclick @ install.php:71
VM171:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16:11709)
    at Object.complete (install.js:127:34)
    at Object.resolveWith (jquery.min.js:16:15493)
    at w (jquery.min.js:18:8574)
    at XMLHttpRequest.d (jquery.min.js:18:14247)
Insert your webserver log here
```
[{error: "", index: "3", multiple: "true", task: "misc", activity: "table"}]
0: {error: "", index: "3", multiple: "true", task: "misc", activity: "table"}

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
install.php:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16:11709)
    at Object.complete (install.js:127:34)
    at Object.resolveWith (jquery.min.js:16:15493)
    at w (jquery.min.js:18:8574)
    at XMLHttpRequest.d (jquery.min.js:18:14247)

**Comment by hitenmandalia** [comment]
Hi @royalaigle ,

One thing to try.  I was getting issues at the Database stage of the installation.  No matter what I did, i just couldnt get past it.

The one thing that worked for me, was to use MariaDB instead of MySQL.  Although it doesnt sound exactly like the issue you are getting, it might be worth a try,

**Comment by royalaigle** [comment]
> Hi @royalaigle ,
> 
> One thing to try. I was getting issues at the Database stage of the installation. No matter what I did, i just couldnt get past it.
> 
> The one thing that worked for me, was to use MariaDB instead of MySQL. Although it doesnt sound exactly like the issue you are getting, it might be worth a try,

Thank you @hitenmandalia I will give that a try

**Comment by royalaigle** [comment]
> 

That did not work, TeamPass does not seem to pickup MariaDB database. I have tried and tried but TeamPass does not seem to see the database. What did you do to get passed this stage?

Did you use Wamp server?

**Comment by hitenmandalia** [comment]
I didn't use WAMP, but I don't see why that should be a blocker.  

I used a docker container running Apache / php / Teampass and used AWS RDS MariaDB to run the database.  When using any version of MySQL, I was unable to get any version of Teampass after 3.0.0.6 to get past the DB install phase.  But when I switched it over to MariaDB, passed the DB population without a problem.

**Comment by royalaigle** [comment]
> I didn't use WAMP, but I don't see why that should be a blocker.
> 
> I used a docker container running Apache / php / Teampass and used AWS RDS MariaDB to run the database. When using any version of MySQL, I was unable to get any version of Teampass after 3.0.0.6 to get past the DB install phase. But when I switched it over to MariaDB, passed the DB population without a problem.

Hey, I tried it with no luck. Any other alternatives?

**Comment by nilsteampassnet** [comment]
What are the version of Mysql or MariaDB used?

**Comment by royalaigle** [comment]
> Mysql version: 8.0.27
> MariaDB version: 10.5.13
> PP version: 7.4.26

Mysql version: 8.0.27
MariaDB version: 10.5.13
PP version: 7.4.26

**Comment by royalaigle** [comment]
> What are the version of Mysql or MariaDB used?

Mysql version: 8.0.27
MariaDB version: 10.5.13
PP version: 7.4.26

**Comment by royalaigle** [comment]
Any update?

**Comment by bavarialogy** [comment]
I (unintentionally) reproduced this today using the same versions and was also unable to get past DB population until I used the install.queries.php from 3.0.0.6.

**Comment by royalaigle** [comment]
> > I didn't use WAMP, but I don't see why that should be a blocker.
> > I used a docker container running Apache / php / Teampass and used AWS RDS MariaDB to run the database. When using any version of MySQL, I was unable to get any version of Teampass after 3.0.0.6 to get past the DB install phase. But when I switched it over to MariaDB, passed the DB population without a problem.
> 
> Hey, I tried it with no luck. Any other alternatives?

I was able to install TeamPass 3.0.0.9 and authenticate LDAP but am unable to create AD users in TeamPass. Any help will be greatly appreciated.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
