### ISSUE TITLE
Upgrade of DB fails because of missing collation name in install/upgrade_run_3.0.0.php:302

### ISSUE THREAD

**Issue by kmerachev** [nilsteampassnet/TeamPass#3029]
### Steps to reproduce
1. Start upgrade
2. reach DB upgrade step
3. execute DB upgrade step

### Expected behaviour
DB upgrade step should succeed

### Actual behaviour
Loop#1 step is running forever. When check /var/log/apache2/error.log there is message:
PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL' at line 1 in /var/www/html/teampass/install/upgrade_run_3.0.0.php:302\nStack trace:\n#0 /var/www/html/teampass/install/upgrade_run_3.0.0.php(302): mysqli_query()\n#1 {main}\n  thrown in /var/www/html/teampass/install/upgrade_run_3.0.0.php on line 302, referer: http://teampass-url.tld/teampass/install/upgrade.php

After manually adding collation to SQL query passes this line successfully and fails at another line:
PHP Fatal error:  Uncaught mysqli_sql_exception: BLOB, TEXT, GEOMETRY or JSON column 'encrypted' can't have a default value in /var/www/html/teampass/install/tp.functions.php:124\nStack trace:\n#0 /var/www/html/teampass/install/tp.functions.php(124): mysqli_query()\n#1 /var/www/html/teampass/install/upgrade_run_3.0.0.php(334): addColumnIfNotExist()\n#2 {main}\n  thrown in /var/www/html/teampass/install/tp.functions.php on line 124, referer: http://teampass-url.tld/teampass/install/upgrade.php

### Server configuration
**Operating system**: Ubuntu 20.04 LTS

**Web server:**
Apache/2.4.41
**Database:**
mysql  Ver 8.0.27-0ubuntu0.20.04.1
**PHP version:**
PHP Version => 8.1.2
**Teampass version:** 
3.0.11 git latest from 8th of Februrary
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
96.0.3 (64-bit)
**Operating system:**
Mac OS X 12.1
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by kmerachev** [comment]
Hi Nils,
here is the sql_mode:
 sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
