### ISSUE TITLE
Installation stuck on Finalization step

### ISSUE THREAD

**Issue by royalaigle** [nilsteampassnet/TeamPass#3039]
### Steps to reproduce
1. Install wamp
2. Install teampass 3.0.0.10
3. Installation stucks on Finalizaiton step

### Expected behaviour
Tell us what should happen
Installation will carry onto the next step

### Actual behaviour
Tell us what happens instead
Finalization steps stuck on creating these:
**Create sk.php file 
Chmod some folders and files
Create settings files
Initiate CSRF protection
Clean temporary installation data**

### Server configuration
**Operating system**:
Windows Server 2019
**Web server:**
Chrome
**Database:**
MariaDB
**PHP version:**
PHP ver 7.4.26
**Teampass version:** 
TeamPass ver 3.0.0.10
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Fresh Install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => 'D:/wamp64/www/TeamPass-3.0.0.10',
    'cpassman_url' => 'http://localhost/TeamPass-3.0.0.10',
    'favicon' => 'http://localhost/TeamPass-3.0.0.10/favicon.ico',
    'path_to_upload_folder' => 'D:/wamp64/www/TeamPass-3.0.0.10/upload',
    'path_to_files_folder' => 'D:/wamp64/www/TeamPass-3.0.0.10/files',
    'url_to_files_folder' => 'http://localhost/TeamPass-3.0.0.10/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.10',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1642359466',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => 'D:/wamp64/www/TeamPass-3.0.0.10/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'CyVGuFz85WXrzjrW6jtdLAHDunfFbBdxe26q7vwW',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
);
### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
install.js:154 {readyState: 4, setRequestHeader: ƒ, getAllResponseHeaders: ƒ, getResponseHeader: ƒ, overrideMimeType: ƒ, …}
install.js:154 {readyState: 4, setRequestHeader: ƒ, getAllResponseHeaders: ƒ, getResponseHeader: ƒ, overrideMimeType: ƒ, …}
VM107:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16:11709)
    at Object.<anonymous> (install.js:160:30)
    at Object.resolveWith (jquery.min.js:16:15493)
    at Object.done [as complete] (jquery.min.js:16:15379)
    at doGetJson (install.js:154:14)
    at Object.resolveWith (jquery.min.js:16:15493)
    at Object.done (jquery.min.js:16:15379)
    at Object.then (jquery.min.js:16:15781)
    at install.js:190:28
parseJSON @ jquery.min.js:16
(anonymous) @ install.js:160
resolveWith @ jquery.min.js:16
done @ jquery.min.js:16
doGetJson @ install.js:154
resolveWith @ jquery.min.js:16
done @ jquery.min.js:16
then @ jquery.min.js:16
(anonymous) @ install.js:190
checkPage @ install.js:189
onclick @ install.php:72
Insert your webserver log here
Insert the log here and especially the answer of the query that failed.
```
![image](https://user-images.githubusercontent.com/84419884/154131845-98f845b6-7f5b-43d5-b791-7f9203abb2f8.png)

**Comment by nilsteampassnet** [comment]
Hi @royalaigle 
This issue should normally have been fixed with latest commit on master branch.
You can over write your existing instance with files from the master branch and relaunch installation process.

**Comment by kerneus** [comment]
> Hi @royalaigle This issue should normally have been fixed with latest commit on master branch. You can over write your existing instance with files from the master branch and relaunch installation process.
#3036 https://github.com/nilsteampassnet/TeamPass/issues/3036#issuecomment-1042576495
Problem is not here. 
Try new installation on empty DB for reproduce this error

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
