### ISSUE TITLE
Can not edit item or get the saved password

### ISSUE THREAD

**Issue by kolsan** [nilsteampassnet/TeamPass#3055]
### Page on which it happened
index.php?page=items

### Steps to reproduce
1. Create new item and fill with all the neccesary data
2. Press edit button (the page start to spin and no answer)

Another way
1. Go to search, a message appears: "DataTables warning: table id=search-results-items - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

Another symptom
1. Using the copy password function
2.  the page start to spin and nothing happen
### Expected behaviour
Tell us what should happen

An item can not be edited or get the saved password.

### Actual behaviour
Nothing happen, the page start to spin

### Server configuration
**Operating system**: Linux TEAMPASS 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64

**Web server:** Apache/2.4.52 (Debian)

**Database:** 5.5.5-10.1.48-MariaDB-0+deb9u2

**PHP version:** 7.4.28

**Teampass version:** 3.0.0.11

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'http://<anonym_url>/teampass
'favicon' => 'http://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'http://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.11',
'ldap_mode' => '1',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'mail',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '1',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1642953925',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Madrid',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_akey' => '',
'duo_ikey' => '',
'duo_skey' => '',
'duo_host' => '',
'teampass_version' => '',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '0',
'email_debug_level' => '2',
'ldap_hosts' => '172.16.31.8',
'ldap_bdn' => 'OU=department,DC=domain,DC=com',
'ldap_username' => 'CN=user,OU=department,DC=domain,DC=com',
'ldap_password' => 'pass',
'settings_ldap_user_dn_attribute' => 'distinguishedName',
'ldap_user_object_filter' => '(objectCategory=Person)(sAMAccountName=*)',
'ldap-test-config-username' => 'user@domain.com',
'ldap-test-config-pwd' => 'pass',

```

**Updated from an older Teampass or fresh install:**
Fresh install
### Client configuration

**Browser:** Firefox - 97.0

**Operating system:** Windows - 64bits

#### Web server error log
```
[Wed Feb 23 10:42:20.537005 2022] [php7:error] [pid 43588] [client 172.16.32.164:50613] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/teampass/sources/main.functions.php:2731\nStack trace:\n#0 /var/www/html/teampass/sources/main.functions.php(2731): base64_encode()\n#1 /var/www/html/teampass/sources/items.queries.php(4088): decryptUserObjectKey()\n#2 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 2731, referer: http://teampass.domain.com/index.php?page=items
[Wed Feb 23 10:54:48.333046 2022] [php7:error] [pid 43578] [client 172.16.32.164:55898] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/teampass/sources/main.functions.php:2731\nStack trace:\n#0 /var/www/html/teampass/sources/main.functions.php(2731): base64_encode()\n#1 /var/www/html/teampass/sources/items.queries.php(2413): decryptUserObjectKey()\n#2 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 2731, referer: http://teampass.domain.com/index.php?page=items
[Wed Feb 23 10:56:16.139781 2022] [php7:error] [pid 43581] [client 172.16.32.164:55919] PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/teampass/sources/main.functions.php:2731\nStack trace:\n#0 /var/www/html/teampass/sources/main.functions.php(2731): base64_encode()\n#1 /var/www/html/teampass/sources/items.queries.php(4088): decryptUserObjectKey()\n#2 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 2731, referer: http://teampass.domain.com/index.php?page=items

**Comment by kolsan** [comment]
More info, this behaviour just happen with AD users, using local one is working.

**Comment by kdubowik** [comment]
I experience the same issue with 3.0.0.13

**Comment by nilsteampassnet** [comment]
I cannot reproduce.
Logged with an AD user, I can create an item and edit it without error.

Can you please follow instruction from https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console to get the exact error?
If you have access to the server, can you also provide the error you get when doing `tail -f /var/log/apache2/error.log`?

**Comment by c0r3dump3d** [comment]
I have the same issue:
### Steps to reproduce
1. Edit an Item


### Expected behaviour
 Edit a previously created item

### Actual behaviour
It doesn't work. I can't access to the item. 

### Server configuration
**Operating system**:  AlmaLinux release 8.5 (Arctic Sphynx)

**Web server:** Apache/2.4.37 (AlmaLinux)

**Database:** 10.3.28-MariaDB

**PHP version:** PHP 7.4.28

**Teampass version:** 3.0.0.14

**Teampass configuration file:**

```
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'https://pwmanager',
    'favicon' => 'https://pwmanager/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'https://pwmanager/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.14',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1645458739',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'ScFjPL8U5sUkg5BC7epGhHq652ADP8t5srkhwGM3',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
```


**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox 98.0.2

**Operating system:** Manjaro Linux

### Logs
#### Web server error log
```
No errors in server log, but 500 internal server error in web-browser console.
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
POST https://pwmanager/sources/items.queries.php
[[HTTP/1.1 500 Internal Server Error 78ms]]()
```
### php -m

```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
zlib
```

**Comment by rastorguevai** [comment]
any issues?

**Comment by antoweb** [comment]
Same problem here after upgrade from 2.1.27.36 to 3
After login as admin and goes to Users:
DataTables warning: table id=table-users - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by e4rthdog** [comment]
> Same problem here after upgrade from 2.1.27.36 to 3 After login as admin and goes to Users: DataTables warning: table id=table-users - Ajax error. For more information about this error, please see http://datatables.net/tn/7

I have the same error with latest 3.1.1. Did you find any solution?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
