### ISSUE TITLE
Not possible to modify password when underscore in label or login

### ISSUE THREAD

**Issue by lluisoxigen** [nilsteampassnet/TeamPass#3071]
### Steps to reproduce
When showing items with an underscore (_) in label or login, message "In progress" doesn't disappear, and it is not possible to modify the password.

### Expected behaviour
Modify passwords of items with underscore in label or login should be possible.

### Server configuration

Operating system: debian 11

Web server: nginx

Database: mariadb

PHP version: 7.4

Teampass version: 3.0.0.13

Updated from an older Teampass or fresh install: updated

#### Web server error log
No server logs

#### Log from the web-browser developer console (CTRL + SHIFT + i)
No web-browser errors.

**Comment by nilsteampassnet** [comment]
I cannot reproduce

Here label with _
![image](https://user-images.githubusercontent.com/1197546/158008084-d7d6ea04-0041-4b7b-bf3a-53fa5cc141a6.png)

Here login with _
![image](https://user-images.githubusercontent.com/1197546/158008153-9faeaf64-3188-40e9-a40b-9ecd32b0211d.png)

In both case I could save, edit, display, etc...

Something is behind your issue.
Please can you provide info as defined here https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console

**Comment by lluisoxigen** [comment]
The new testings I've done always show "In progress" after pressing edit, I get the follwing browser log:

```
RECEIVED STEP2
index.php?page=items&group=4&id=1713:7872 {attachments: Array(0), favourite: 0, users_list: Array(4), roles_list: Array(2), has_change_proposal: 0, …}
index.php?page=items&group=4&id=1713:8004 History:
index.php?page=items&group=4&id=1713:8005 {error: '', history: Array(5)}
index.php?page=items&group=4&id=1713:3270 JSTREE BIND
index.php?page=items&group=4&id=1713:3288 SELECTED NODE 2 -- true
index.php?page=items&group=4&id=1713:3289 {id: 'li_2', text: '<i class="fas fa-folder tree-folder mr-2" data-fol…e-light ml-2 items_count" id="itcount_2">0</span>', icon: true, parent: '#', parents: Array(1), …}
index.php?page=items&group=4&id=1713:3290 0
index.php?page=items&group=4&id=1713:1617 {error: false, message: '', queryResults: {…}}
index.php?page=items&group=4&id=1713:6211 TREE
index.php?page=items&group=4&id=1713:6212 {error: 'false', html_json: {…}}
index.php?page=items&group=4&id=1713:6299 [4,2]
index.php?page=items&group=4&id=1713:6259 <option value="0" disabled="disabled">Root</option><option value="4" data-parent-id="0">&nbsp;Informatica</option><option value="2" data-parent-id="0">&nbsp;Prova</option>
index.php?page=items&group=4&id=1713:3845 SHOW EDIT ITEM
index.php?page=items&group=4&id=1713:8349 Get privilege for folder 2
index.php?page=items&group=4&id=1713:8377 GET COMPLEXITY LEVEL
index.php?page=items&group=4&id=1713:8378 {folderId: 2, error: false, val: 0, visibility: 'Informatica', complexity: 'Very weak', …}
index.php?page=items&group=4&id=1713:4116 User did a change on #form-item > true - Element form-item-restrictedto
index.php?page=items&group=4&id=1713:4116 User did a change on #form-item > true - Element form-item-anounce
index.php?page=items&group=4&id=1713:4116 User did a change on #form-item > true - Element form-item-restrictedto
index.php?page=items&group=4&id=1713:4040 >>> .item-details-card -- 
index.php?page=items&group=4&id=1713:6042 SHOW EDIT ITEM 2
jquery.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'rights') TypeError: Cannot read properties of undefined (reading 'rights')
    at showItemEditForm (https://teampass.xxxxx.com/index.php?page=items&group=4&id=1713:6089:69)
    at Object.<anonymous> (https://teampass.xxxxx.com/index.php?page=items&group=4&id=1713:3877:17)
    at e (https://teampass.xxxxx.com/plugins/jquery/jquery.min.js:2:30038)
    at t (https://teampass.xxxxx.com/plugins/jquery/jquery.min.js:2:30340) undefined
```

After this, I can not modify the item, and get this browser log:

```
index.php?page=items:5698 Uncaught TypeError: Cannot read properties of undefined (reading 'rights')
    at HTMLButtonElement.<anonymous> (index.php?page=items:5698:69)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at HTMLButtonElement.v.handle (jquery.min.js:2:41048)
```

**Comment by nilsteampassnet** [comment]
OK, thing doesn't come from underscores but from the "diffusion list" while using feature "announce".
I will fix this

**Comment by lluisoxigen** [comment]
Sorry, but I have installed the commit and still receiving the same error.

```
PREV: 1398 - NEXT: undefined
index.php?page=items:7872 RECEIVED STEP2
index.php?page=items:7873 {attachments: Array(0), favourite: 0, users_list: Array(4), roles_list: Array(2), has_change_proposal: 0, …}
index.php?page=items:8005 History:
index.php?page=items:8006 {error: '', history: Array(1)}
index.php?page=items:3846 SHOW EDIT ITEM
index.php?page=items:8350 Get privilege for folder 2
index.php?page=items:8378 GET COMPLEXITY LEVEL
index.php?page=items:8379 {folderId: 2, error: false, val: 0, visibility: 'Informatica', complexity: 'Weak', …}
index.php?page=items:4117 User did a change on #form-item > true - Element form-item-restrictedto
index.php?page=items:4117 User did a change on #form-item > true - Element form-item-anounce
index.php?page=items:4117 User did a change on #form-item > true - Element form-item-restrictedto
index.php?page=items:4041 >>> .item-details-card -- 
index.php?page=items:6043 SHOW EDIT ITEM 2
jquery.min.js:2 jQuery.Deferred exception: Cannot read properties of undefined (reading 'rights') TypeError: Cannot read properties of undefined (reading 'rights')
    at showItemEditForm (https://teampass.xxxxx.com/index.php?page=items:6090:69)
    at Object.<anonymous> (https://teampass.xxxxx.com/index.php?page=items:3878:17)
    at e (https://teampass.xxxxx.com/plugins/jquery/jquery.min.js:2:30038)
    at t (https://teampass.xxxxx.com/plugins/jquery/jquery.min.js:2:30340) undefined
```
No server logs.

**Comment by amilhub** [comment]
Hello,
As commented in #3448 I have a very similar issue.

[lluisoxigen](https://github.com/lluisoxigen) & @nilsteampassnet any news regarding this issue? 
There are any fix or workaround for this issue at this time?

Thanks in advance.

**Comment by lluisoxigen** [comment]
Hello,

the issues we had were not exclusively related to underscores.

Commit 0fb5de (3 december 2022) seems to have fixed many issues we had, even this one.

Even though it works far better now, from time to time, some items cannot be modified because the code fails to detect the change, and shows something like Nothing to modifiy.  But the main issue was solved.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
