### ISSUE TITLE
3.0.0.14 - change password

### ISSUE THREAD

**Issue by michaldejmek** [nilsteampassnet/TeamPass#3094]
When I try to change the password, I end at step "Encrypting keys - Logs [0 - 100] ... Please wait!".

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to decryptUserObjectKey() must be of the type string, null given, called in /var/www/html/teampass/sources/main.queries.php on line 1954 and defined in /var/www/html/teampass/sources/main.functions.php:2727\nStack trace:\n#0 /var/www/html/teampass/sources/main.queries.php(1954): decryptUserObjectKey()\n#1 /var/www/html/teampass/sources/main.queries.php(1729): continueReEncryptingUserSharekeysStep2()\n#2 /var/www/html/teampass/sources/main.queries.php(408): continueReEncryptingUserSharekeys()\n#3 /var/www/html/teampass/sources/main.queries.php(74): mainQuery()\n#4 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 2727, referer: https://xxxxx/teampass/index.php?page=users

**Comment by klebadi** [comment]
Hello, I have same problem

**Comment by antoweb** [comment]
Same peoblemt when tey to download an attachment

**Comment by OK-Now-I-Will-Do-Backups** [comment]
Hello!
Same problem after upgrade from 2.1.27.36 to 3.0.0.16
While testing upgraded version i added new user, login with it, created folder, created item, tried to change password 2 days after and temporary get this problem

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to decryptUserObjectKey() must be of the type string, null given, called in /var/www/teampass/sources/main.queries.php on line 1954 and defined in /var/www/teampass/sources/main.functions.php:2727\nStack trace:\n#0 /var/www/teampass/sources/main.queries.php(1954): decryptUserObjectKey()\n#1 /var/www/teampass/sources/main.queries.php(1729): continueReEncryptingUserSharekeysStep2()\n#2 /var/www/teampass/sources/main.queries.php(408): continueReEncryptingUserSharekeys()\n#3 /var/www/teampass/sources/main.queries.php(74): mainQuery()\n#4 {main}\n  thrown in /var/www/teampass/sources/main.functions.php on line 2727, referer: https://my-domain/index.php?page=users`

I tried to delete user and add it again, but the same error appears.

Next step i deleted item and folder which i created under test user. And tried again to change password - and its done!

So could it be some folder or item properties causes that error?

Now i trying to reproduce this error again but no success, all users adding correctly and all passwords successfuly changing.
Would be great if someone knows what exactly causes this problem and how to escape it in future.

**Comment by OK-Now-I-Will-Do-Backups** [comment]
I think i catch something:
got this error again twice in a raw while trying to change password as a manager role account
but when I login into admin account I can successfully change password for the same user

I hope this information will be useful for someone

**Comment by Jenlain** [comment]
Same issue after upgrade from 2.1.27.36 to 3.0.0.19. 

Same issue also when trying to generate new OTP for a user. 

Same kind of issue when entering saltkey for my personal folder as well.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
