### ISSUE TITLE
Errors upgrading from 2.1.27.36 to 3.0.0.X

### ISSUE THREAD

**Issue by fapgomes** [nilsteampassnet/TeamPass#3095]
### Steps to reproduce
1. Download teampass 3 (from master o 3.0.0.14
2. Run upgrade from version 2.1.27.36

### Expected behaviour
The expected behaviour is that Teampass should upgrade to version 3.0 after all checks successfully complete.

### Actual behaviour
Upgrade runs, without fail, but when logging in with an existing user, passwords are not displayed.
If I try to change the user passwords, from the admin user interface, in the apache logs we can see:
```
PHP Fatal error:  Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/teampass/sources/main.functions.php:2737
Stack trace:
#0 /var/www/html/teampass/sources/main.functions.php(2737): base64_encode()
#1 /var/www/html/teampass/sources/main.queries.php(1862): decryptUserObjectKey()
#2 /var/www/html/teampass/sources/main.queries.php(1716): continueReEncryptingUserSharekeysStep1()
#3 /var/www/html/teampass/sources/main.queries.php(408): continueReEncryptingUserSharekeys()
#4 /var/www/html/teampass/sources/main.queries.php(74): mainQuery()
#5 {main}
  thrown in /var/www/html/teampass/sources/main.functions.php on line 2737
```
If I try to create a new user, the same error appears.

### Server configuration
**Operating system**: Rocky Linux 8

**Web server:** Apache 2.4.37-43

**Database:** mariadb-server-10.3.28-1

**PHP version:** php-fpm-7.4.19-1

**Teampass version:** last from master (and I try'ed with 3.0.0.14, also)

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
Attached.

### Client configuration
**Browser:** Chrome 99.0.4844.82 (I try'ed with diferent browsers)

**Operating system:** Fedora Linux 35

#### Web server error log
See above.

![Screenshot_20220322_163244](https://user-images.githubusercontent.com/39247306/159530071-1278b40a-03e6-4a2d-a271-76e14c9efb59.png)
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/8326262/tp.config.php.zip)

**Comment by fapgomes** [comment]
Hi,

 Anyone can help?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
