### ISSUE TITLE
Upgrade from 2.1.27.35 to 2.1.27.36 hits crash in upgrade_run_defuse_for_custfields.php

### ISSUE THREAD

**Issue by ImNtReal** [nilsteampassnet/TeamPass#3098]
### Steps to reproduce
1. Run TeamPass for several years through many upgrades
2. Get a database entry into a corrupted state?
3. Watch the upgrade_run_defuse_for_custfields.php appear to hang with a crash reported in logs.

### Expected behaviour
Upgrade completes

### Actual behaviour
Upgrade hangs

### Server configuration
**Operating system**: CentOS Stream release 8

**Web server**: nginx-1.14.1-9.module_el8.0.0+184+e34fea82.x86_64

**Database**: mariadb-server-10.5.9-1.module_el8.4.0+801+647c4915.x86_64

**PHP version**: php-7.4.19-1.module_el8.5.0+815+1c4fd2e5.x86_64

**Teampass version:** 2.1.27.35 -> 2.1.27.36

**Teampass configuration file**:
```
<?php
global $lang, $txt, $k, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "mariadb.nghs.com";
$user = "teampass";
$pass = "secretpassword";
$database = "teampass";
$port = 3306;
$pre = "teampass_";
$encoding = "utf8";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/var/sk');
require_once "/var/sk/sk.php";
@define('COST', '13'); // Don't change this
```

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser**: Firefox 98.0.1

**Operating system** Windows 10

#### Web server error log
```
2022/03/24 18:52:45 [error] 56790#0: *11222 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Defuse\Crypto\Exception\BadFormatException: Encoded data is shorter than expected. in /var/www/TeamPass-2.1.27.36/includes/libraries/Encryption/Encryption/Encoding.php:168
Stack trace:
#0 /var/www/TeamPass-2.1.27.36/includes/libraries/Encryption/Encryption/Key.php(38): Defuse\Crypto\Encoding::loadBytesFromChecksummedAsciiSafeString()
#1 /var/www/TeamPass-2.1.27.36/sources/main.functions.php(386): Defuse\Crypto\Key::loadFromAsciiSafeString()
#2 /var/www/TeamPass-2.1.27.36/install/upgrade_run_defuse_for_custfields.php(123): cryption()
#3 {main}
  thrown in /var/www/TeamPass-2.1.27.36/includes/libraries/Encryption/Encryption/Encoding.php on line 168" while reading response header from upstream, client: 172.19.171.6, server: vmasteampasst01.nghs.com, request: "POST /install/upgrade_run_defuse_for_custfields.php HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "teampasstest.nghs.com", referrer: "https://teampasstest.nghs.com/install/upgrade.php"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/8346514/tp.config.php.txt)
I'm not sure which info from the console you need here.

**Comment by ImNtReal** [comment]
I think this is probably just a broken record or two in my database, but I don't know how to find them.

**Comment by ImNtReal** [comment]
I was able to clean enough from the table to get this step to complete. Mostly using where raison is NULL, raison_iv is NULL and raison_iv = ''
