### ISSUE TITLE
Roles tab missing functions

### ISSUE THREAD

**Issue by AniTexs** [nilsteampassnet/TeamPass#3109]
### Steps to reproduce
1. Fresh 3.0.0.14 Version
2. Login as administrator
3. Press Roles

### Expected behaviour
It would be expected to be able to see, edit, create & delete roles, it is also not able to press any items from the sidebar

### Actual behaviour
Buttons unavailable no information shown

### Server configuration
**Operating system**: Ubuntu

**Web server:** NIGNX

**Database:** MySQL (MariaDB)

**PHP version:** 7.4.28

**Teampass version:** 3.0.0.14

**Teampass configuration file:** 
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/8371299/tp.config.php.txt)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Google Chrome & Microsoft Egde (Both use Chrome Engine)

**Operating system:** Windows 10 Enterprise 20H2

#### Web server error log
```
Mar 29 14:09:43 MYIP - - [29/Mar/2022:12:09:43 +0000] "GET /index.php?page=roles HTTP/1.1" 200 4543 "https://MYURLISREDACTED/index.php?page=admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
Mar 29 14:09:43 MYIP - - [29/Mar/2022:12:09:43 +0000] "GET /plugins/alertifyjs/css/alertify.min.css HTTP/1.1" 200 3846 "https://MYURLISREDACTED/index.php?page=roles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
Mar 29 14:09:43 MYIP - - [29/Mar/2022:12:09:43 +0000] "GET /plugins/alertifyjs/css/themes/bootstrap.min.css HTTP/1.1" 200 657 "https://MYURLISREDACTED/index.php?page=roles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
Mar 29 14:09:43 MYIP - - [29/Mar/2022:12:09:43 +0000] "GET /includes/images/teampass-logo2-home.png HTTP/1.1" 304 - "https://MYURLISREDACTED/index.php?page=roles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
​          GET https://MYURLISREDACTED/index.php?page=roles 500
(anonymous) @ /index.php?page=admin:1088
dispatch @ /plugins/jquery/jquery.min.js:2
v.handle @ /plugins/jquery/jquery.min.js:2
msgport.js:70 {"notify":"init_tab"}
csrfprotector.js:152 TypeError: Cannot read properties of null (reading 'value')
    at Object._init (csrfprotector.js:150:86)
    at csrfprotector_init (csrfprotector.js:174:11)
    at csrfprotector.js:336:5
_init @ csrfprotector.js:152
csrfprotector_init @ csrfprotector.js:174
(anonymous) @ csrfprotector.js:336
csrfprotector.js:153 [ERROR] [CSRF Protector] unable to parse blacklisted url fields.
_init @ csrfprotector.js:153
csrfprotector_init @ csrfprotector.js:174
(anonymous) @ csrfprotector.js:336
```

**Comment by nilsteampassnet** [comment]
Can you provide a screen capture please ?

**Comment by AniTexs** [comment]
I will reinstall since I can see there is a new version.
I will see if this issue persists.

**Comment by AniTexs** [comment]
It's not an issue after the reinstallation from 3.0.0.14 to 3.0.0.16 so somehow it fixed it.
