### ISSUE TITLE
cant import csv

### ISSUE THREAD

**Issue by antoweb** [nilsteampassnet/TeamPass#3111]
### Steps to reproduce
1. Export csv from teampass 2.1.27.36
2. Import csv to teampass 3.0.0.14
3. Reading file gear stuck
4. An error logged in web server error log

[Wed Mar 30 08:42:25.453506 2022] [php7:error] [pid 11017] [client 10.7.8.55:63267] PHP Fatal error:  Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in /var/www/html/teampass/sources/import.queries.php:228\nStack trace:\n#0 /var/www/html/teampass/sources/import.queries.php(228): htmlspecialchars()\n#1 {main}\n  thrown in /var/www/html/teampass/sources/import.queries.php on line 228, referer: https://teampassnew.discoverydam.com/index.php?page=import

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Debian 11

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.7

**PHP version:**
7.4

**Teampass version:** 
3.0.0.14

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
@antoweb 
I'm pretty sure we are facing here a corruption of the csv file.
The error line indicates it fails on a value in the login column.
Would it be possible for you to check if a login has special characters.
The import process sanitizes values but perhaps did I not sanitize enough...

**Comment by antoweb** [comment]
Hello,
the error occur after selecting file csv and before press Perform button

Are 1 error and 1 notice


[Sun Apr 03 11:57:50.023051 2022] [php7:notice] [pid 31622] [client 10.7.192.2:63676] PHP Notice:  Undefined offset: 4 in /var/www/html/teampass/sources/import.queries.php on line 174, referer: https://teampassnew.discoverydam.com/index.php?page=import
[Sun Apr 03 11:57:50.023463 2022] [php7:error] [pid 31622] [client 10.7.192.2:63676] PHP Fatal error:  Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in /var/www/html/teampass/sources/import.queries.php:228\nStack trace:\n#0 /var/www/html/teampass/sources/import.queries.php(228): htmlspecialchars()\n#1 {main}\n  thrown in /var/www/html/teampass/sources/import.queries.php on line 228, referer: https://teampassnew.discoverydam.com/index.php?page=import

In the csv there are no special carachters 
Only id, label, description, perso (false) and url
The only special caracther is a - in label value is AS-STAGE

**Comment by antoweb** [comment]
Sorry,
there is another row in csv with special carachters like (# and ? and < >) in a url string

**Comment by nilsteampassnet** [comment]
@antoweb 
Can you please do a screenshot of the first rows of the csv file?
Blur the sensitive data ;)

**Comment by antoweb** [comment]
![image](https://user-images.githubusercontent.com/32364871/162169323-4760442d-fec0-4367-b8d6-6c653463bdc2.png)

**Comment by nilsteampassnet** [comment]
@antoweb 
Hum the csv file is not following the recommendation https://teampass.readthedocs.io/en/latest/features/feat-impexp/

**Comment by antoweb** [comment]
Hum, the csv is downloaded from Teampass 2.1.27.36 :-D

**Comment by nilsteampassnet** [comment]
Yes but there is no relation between both.

**Comment by antoweb** [comment]
Ok because we have some peoblems after upgrade (see my ticket regardinfg the password blank) we want try to export and reimport all items from 2.1.27.35 to 3.0.0.16 but seems to be not a good way

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
