### ISSUE TITLE
upgrade 2.1.27.36 to a 3.0.0.14 forever rotating gear

### ISSUE THREAD

**Issue by elkekou** [nilsteampassnet/TeamPass#3113]
### Steps to reproduce
1.  Replace all the 2.1.27.36 files with the 3.0.0.14
2.  Run https://xxx/install/upgrade.php
3.  Enter credantial and start button

### Expected behaviour
upgrade process starting?

### Actual behaviour
 --> Gear rotating forever
With good or bad credential same behavior nothing happen except the rotating gear....

Tried on a production server, and a new one with reinstalled from scratch.

### Server configuration
Centos 7 (up to date)
**Web server:**
apache 2.4.6-7

**Database:**
Mariadb

**PHP version:**
PHP 7.0 (but same with 7.2)

**Teampass version:** 
2.1.27.36
3.0.14 
also  tried 3.0.11

[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/8387317/tp.config.txt)

### Client configuration
Firefox latest version on a windows 10 and centos client.
Edge on windows 10

**Operating system:**
Windows 10 / Centos 8

#### Web server error log
no log ....

"POST /install/upgrade_ajax.php HTTP/1.1" 500 - "https://xxx/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.55"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    complete https://xxx/install/upgrade.php:216
    jQuery 6
        c
        fireWith
        l
        o
        send
        ajax
    <anonymous> https://xxx/install/upgrade.php:208
    jQuery 2
        dispatch
        handle
upgrade.php:216:26

```

**Comment by rveupen** [comment]
I also had the gear loop.
After trying many things i found this somewhere in the issues that helped me:

mysql -uroot -p
ALTER TABLE `teampass`.`teampass_users` 
CHANGE COLUMN `favourites` `favourites` VARCHAR(1000) NULL DEFAULT NULL ,
CHANGE COLUMN `latest_items` `latest_items` VARCHAR(1000) NULL DEFAULT NULL ;

**Comment by elkekou** [comment]
Hi,

thank you for your response, i tried your workaround but nothing change.
In fact it's like the ajax part does not work.

**Comment by nilsteampassnet** [comment]
@elkekou 
please provide the apache logs

**Comment by elkekou** [comment]
hi nils, 
tried just now un upgrade providing a bad password (no error only gear..)
And here apache log (nothing seems interesting) :

```
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /install/upgrade.php HTTP/1.1" 200 29606 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /install/css/install.css HTTP/1.1" 200 1820 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/alertifyjs/css/alertify.min.css HTTP/1.1" 200 21412 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/alertifyjs/css/themes/bootstrap.min.css HTTP/1.1" 200 1489 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /install/js/aes.min.js HTTP/1.1" 200 19535 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/fontawesome-free/css/all.css HTTP/1.1" 200 73625 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/popper/umd/popper.min.js HTTP/1.1" 200 21233 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/adminlte/js/adminlte.min.js HTTP/1.1" 200 46369 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/alertifyjs/alertify.min.js HTTP/1.1" 200 36978 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/jquery/jquery.min.js HTTP/1.1" 200 89501 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 200 83253 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /includes/images/teampass-logo2-home.png HTTP/1.1" 200 3970 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /plugins/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 80300 "https://xx.fqdn.fr/plugins/fontawesome-free/css/all.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:46 +0200] "GET /includes/images/install_background.jpg HTTP/1.1" 304 - "https://xx.fqdn.fr/install/css/install.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:47 +0200] "GET /favicon.ico HTTP/1.1" 200 99678 "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
192.168.201.68 - - [05/Apr/2022:11:29:55 +0200] "POST /install/upgrade_ajax.php HTTP/1.1" 200 - "https://xx.fqdn.fr/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
```

**Comment by Knoppix1** [comment]
Hi,
Same issue here but i have is error on apache log : 

`[Mon Jun 27 00:36:01.900285 2022] [php7:error] [pid 23616] [client 192.168.1.2:51802] PHP Fatal error:  Uncaught Defuse\\Crypto\\Exception\\BadFormatException: Encoded data is shorter than expected. in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php:225\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Encryption/Encryption/Key.php(49): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString()\n#1 /var/www/html/teampass/install/tp.functions.php(44): Defuse\\Crypto\\Key::loadFromAsciiSafeString()\n#2 /var/www/html/teampass/install/tp.functions.php(84): defuseCryption()\n#3 /var/www/html/teampass/install/upgrade_ajax.php(252): defuse_return_decrypted()\n#4 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 225, referer: https://_url_/install/upgrade.php
`

php 7.4
Try to upgrade last build : 3.0.18

**Comment by Kyogre** [comment]
php 7.4
Trying to upgrade from 3.0.0.22 to [3.0.0.23](https://github.com/nilsteampassnet/TeamPass/commit/bc7a0cbea7210205f3d237db31090258cc836b01).
Gives error
`Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

<details>
  <summary>error in browser console</summary>
  
```
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
complete http://10.81.3.139/install/upgrade.php:216 
    jQuery 6
        c
        fireWith
        l
        o
        send
        ajax
    <anonymous> http://10.81.3.139/install/upgrade.php:208
    jQuery 9
        dispatch
        handle
        add
        Ee
        each
        each
        Ee
        on
        n
    <anonymous> http://10.81.3.139/install/upgrade.php:151
    jQuery 13
        e
        t
        setTimeout handler*Deferred/then/l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
```

</details>

<details>
  <summary>There is nothing interesting written into /var/log/httpd/error_log* when this error appears</summary>

```
[Tue Feb 21 15:08:25.434210 2023] [proxy:debug] [pid 12327:tid 12347] proxy_util.c(2820): [client 10.81.3.125:55827] AH00947: connected /var/www/teampass/install/upgrade.php to httpd-UDS:0
[Tue Feb 21 15:08:25.434259 2023] [proxy:debug] [pid 12327:tid 12347] proxy_util.c(3194): AH02823: FCGI: connection established with Unix domain socket /run/php-fpm/www.sock (*:80)
[Tue Feb 21 15:08:25.435021 2023] [proxy:debug] [pid 12327:tid 12347] proxy_util.c(2557): AH00943: FCGI: has released connection for (*:80)
[Tue Feb 21 15:08:25.496717 2023] [authz_core:debug] [pid 12327:tid 12349] mod_authz_core.c(818): [client 10.81.3.125:55827] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.496748 2023] [authz_core:debug] [pid 12327:tid 12349] mod_authz_core.c(818): [client 10.81.3.125:55827] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.497623 2023] [authz_core:debug] [pid 12327:tid 12353] mod_authz_core.c(818): [client 10.81.3.125:55827] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.497635 2023] [authz_core:debug] [pid 12327:tid 12353] mod_authz_core.c(818): [client 10.81.3.125:55827] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498163 2023] [authz_core:debug] [pid 12327:tid 12358] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498174 2023] [authz_core:debug] [pid 12327:tid 12358] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498314 2023] [authz_core:debug] [pid 12326:tid 12354] mod_authz_core.c(818): [client 10.81.3.125:55828] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498362 2023] [authz_core:debug] [pid 12326:tid 12354] mod_authz_core.c(818): [client 10.81.3.125:55828] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498559 2023] [authz_core:debug] [pid 12327:tid 12348] mod_authz_core.c(818): [client 10.81.3.125:55830] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498570 2023] [authz_core:debug] [pid 12327:tid 12348] mod_authz_core.c(818): [client 10.81.3.125:55830] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498890 2023] [authz_core:debug] [pid 12327:tid 12360] mod_authz_core.c(818): [client 10.81.3.125:55832] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.498900 2023] [authz_core:debug] [pid 12327:tid 12360] mod_authz_core.c(818): [client 10.81.3.125:55832] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.499435 2023] [authz_core:debug] [pid 12327:tid 12359] mod_authz_core.c(818): [client 10.81.3.125:55830] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.499446 2023] [authz_core:debug] [pid 12327:tid 12359] mod_authz_core.c(818): [client 10.81.3.125:55830] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.499451 2023] [authz_core:debug] [pid 12325:tid 12338] mod_authz_core.c(818): [client 10.81.3.125:55831] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.499500 2023] [authz_core:debug] [pid 12325:tid 12338] mod_authz_core.c(818): [client 10.81.3.125:55831] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.499618 2023] [authz_core:debug] [pid 12326:tid 12355] mod_authz_core.c(818): [client 10.81.3.125:55828] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.499626 2023] [authz_core:debug] [pid 12326:tid 12355] mod_authz_core.c(818): [client 10.81.3.125:55828] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.500929 2023] [authz_core:debug] [pid 12326:tid 12357] mod_authz_core.c(818): [client 10.81.3.125:55828] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.500944 2023] [authz_core:debug] [pid 12326:tid 12357] mod_authz_core.c(818): [client 10.81.3.125:55828] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.501066 2023] [authz_core:debug] [pid 12325:tid 12332] mod_authz_core.c(818): [client 10.81.3.125:55831] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.501074 2023] [authz_core:debug] [pid 12325:tid 12332] mod_authz_core.c(818): [client 10.81.3.125:55831] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.501622 2023] [authz_core:debug] [pid 12327:tid 12344] mod_authz_core.c(818): [client 10.81.3.125:55827] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.501771 2023] [authz_core:debug] [pid 12327:tid 12344] mod_authz_core.c(818): [client 10.81.3.125:55827] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.529459 2023] [authz_core:debug] [pid 12327:tid 12389] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.529495 2023] [authz_core:debug] [pid 12327:tid 12389] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.570398 2023] [authz_core:debug] [pid 12327:tid 12381] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/css/install.css
[Tue Feb 21 15:08:25.570426 2023] [authz_core:debug] [pid 12327:tid 12381] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/css/install.css
[Tue Feb 21 15:08:25.571030 2023] [authz_core:debug] [pid 12327:tid 12407] mod_authz_core.c(818): [client 10.81.3.125:55830] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/plugins/fontawesome-free-6/css/all.css
[Tue Feb 21 15:08:25.571084 2023] [authz_core:debug] [pid 12327:tid 12407] mod_authz_core.c(818): [client 10.81.3.125:55830] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/plugins/fontawesome-free-6/css/all.css
[Tue Feb 21 15:08:25.586170 2023] [authz_core:debug] [pid 12327:tid 12409] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:25.586191 2023] [authz_core:debug] [pid 12327:tid 12409] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046722 2023] [authz_core:debug] [pid 12327:tid 12411] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of Require all granted: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046772 2023] [authz_core:debug] [pid 12327:tid 12411] mod_authz_core.c(818): [client 10.81.3.125:55829] AH01626: authorization result of <RequireAny>: granted, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046833 2023] [proxy:debug] [pid 12327:tid 12411] mod_proxy.c(1505): [client 10.81.3.125:55829] AH01143: Running scheme unix handler (attempt 0), referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046841 2023] [proxy_ajp:debug] [pid 12327:tid 12411] mod_proxy_ajp.c(769): [client 10.81.3.125:55829] AH00894: declining URL fcgi://localhost/var/www/teampass/install/upgrade_ajax.php, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046864 2023] [proxy_fcgi:debug] [pid 12327:tid 12411] mod_proxy_fcgi.c(1056): [client 10.81.3.125:55829] AH01076: url: fcgi://localhost/var/www/teampass/install/upgrade_ajax.php proxyname: (null) proxyport: 0, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046866 2023] [proxy_fcgi:debug] [pid 12327:tid 12411] mod_proxy_fcgi.c(1063): [client 10.81.3.125:55829] AH01078: serving URL fcgi://localhost/var/www/teampass/install/upgrade_ajax.php, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046872 2023] [proxy:debug] [pid 12327:tid 12411] proxy_util.c(2541): AH00942: FCGI: has acquired connection for (*:80)
[Tue Feb 21 15:08:29.046880 2023] [proxy:debug] [pid 12327:tid 12411] proxy_util.c(2597): [client 10.81.3.125:55829] AH00944: connecting fcgi://localhost/var/www/teampass/install/upgrade_ajax.php to localhost:8000, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.046883 2023] [proxy:debug] [pid 12327:tid 12411] proxy_util.c(2634): [client 10.81.3.125:55829] AH02545: fcgi: has determined UDS as /run/php-fpm/www.sock, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.047024 2023] [proxy:debug] [pid 12327:tid 12411] proxy_util.c(2820): [client 10.81.3.125:55829] AH00947: connected /var/www/teampass/install/upgrade_ajax.php to httpd-UDS:0, referer: http://10.81.3.139/install/upgrade.php
[Tue Feb 21 15:08:29.047067 2023] [proxy:debug] [pid 12327:tid 12411] proxy_util.c(3194): AH02823: FCGI: connection established with Unix domain socket /run/php-fpm/www.sock (*:80)
[Tue Feb 21 15:08:29.047984 2023] [proxy:debug] [pid 12327:tid 12411] proxy_util.c(2557): AH00943: FCGI: has released connection for (*:80)
```

</details>

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
