### ISSUE TITLE
Rotating gear and upgrade process does not go beyond the home screen

### ISSUE THREAD

**Issue by Blubmann** [nilsteampassnet/TeamPass#3135]
### Steps to reproduce
1. Installed 2.1.27.36
2. Try Upgrade to 3.0.0.16
3. Rotating gear and upgrade process does not go beyond the home screen

### Expected behaviour
Upgrade Proces starting

### Actual behaviour
Endless loop at the beginning of the upgradeprocess

### Server configuration
**Operating system**: Version 9.3

**Web server:** Version 2.4.25

**Database:** Version 14.14 Distrib 5.7.20

**PHP version:** Version 7.0.30

**Teampass version:** 2.1.27.36 to 3.0.0.16

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Update
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
No Error logged

Insert your webserver log here
192.168.11.1 - - [27/Apr/2022:08:15:29 +0200] "GET /teampass/plugins/adminlte/js/adminlte.min.js.map HTTP/1.1" 200 31252 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:15:29 +0200] "GET /teampass/plugins/popper/umd/popper.min.js.map HTTP/1.1" 200 35719 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:15:29 +0200] "GET /teampass/plugins/bootstrap/js/bootstrap.bundle.min.js.map HTTP/1.1" 200 83350 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:15:29 +0200] "GET /teampass/plugins/adminlte/css/adminlte.min.css.map HTTP/1.1" 200 394294 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:15:30 +0200] "POST /teampass/install/upgrade_ajax.php HTTP/1.1" 500 298 "http://192.168.11.128/teampass/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:16:16 +0200] "POST /teampass/install/upgrade_ajax.php HTTP/1.1" 500 298 "http://192.168.11.128/teampass/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:33:19 +0200] "POST /teampass/install/upgrade_ajax.php HTTP/1.1" 500 298 "http://192.168.11.128/teampass/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:33:34 +0200] "GET /teampass/install/upgrade.php HTTP/1.1" 200 7400 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:33:34 +0200] "GET /teampass/plugins/popper/umd/popper.min.js.map HTTP/1.1" 200 35718 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:33:34 +0200] "GET /teampass/plugins/bootstrap/js/bootstrap.bundle.min.js.map HTTP/1.1" 200 83350 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:33:34 +0200] "GET /teampass/plugins/adminlte/js/adminlte.min.js.map HTTP/1.1" 200 31252 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:33:34 +0200] "GET /teampass/plugins/adminlte/css/adminlte.min.css.map HTTP/1.1" 200 394294 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
192.168.11.1 - - [27/Apr/2022:08:33:50 +0200] "POST /teampass/install/upgrade_ajax.php HTTP/1.1" 500 298 "http://192.168.11.128/teampass/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

#### Log from the web-browser developer console (CTRL + SHIFT + i)
jquery.min.js:2          POST http://192.168.11.128/teampass/install/upgrade_ajax.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
VM265:1 Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)

Insert the log here and especially the answer of the query that failed.
```

**Comment by Blubmann** [comment]
Ok solved it. The problem occures if I use chrome. I used Firefox instead and the upgrade started.
