### ISSUE TITLE
Unable to connect on new account

### ISSUE THREAD

**Issue by Laurentimbert** [nilsteampassnet/TeamPass#3161]
### Page on which it happened
index.php?page=users

### Steps to reproduce
1. after upgrade to 3.0.14 to 3.0.16. 
2.Unable to create a new account from the administration
3.blocking during encryption key generation

### Expected behaviour
Tell us what should happen
blocking during encryption key generation

### Actual behaviour
Tell us what happens instead
create the account and send an email or display the temporary password

### Server configuration
**Operating system**: Linux DsiOutils.in.ac-corse.fr 4.18.0-305.3.1.el8_4.x86_64 #1 SMP Mon May 17 10:08:25 EDT 2021 x86_64

**Web server:** Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k mod_fcgid/2.3.9

**Database:** 5.5.5-10.3.28-MariaDB

**PHP version:** 7.4.19

**Teampass version:** 3.0.0.16

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '0',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'https://<anonym_url>/teampass
'favicon' => 'https://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'https://172.17.0.20/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '1',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.16',
'ldap_mode' => '0',
'ldap_type' => 'OpenLDAP',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'uid',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '1',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '1',
'roles_allowed_to_print' => '0',
'show_description' => '0',
'anyone_can_modify' => '1',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '5',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '1',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '1',
'custom_logo' => 'https://educor.ac-corse.fr/communication/sign/logo-AC-CORSE.png',
'custom_login_text' => 'Bienvenue dans le coffre-fort de la DRNE',
'default_language' => 'french',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;cb_select_all;',
'send_stats_time' => '1642598939',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '1',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '587',
'email_security' => 'tls',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Paris',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '1',
'secure_display_image' => '0',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '0',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_akey' => '',
'duo_ikey' => '',
'duo_skey' => '',
'duo_host' => '',
'teampass_version' => '',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '1',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '1',
'ldap_hosts' => 'annuaire.ac-corse.fr',
'ldap_bdn' => 'ou=personnel EN,ou=ac-corse,ou=education,o=gouv,c=fr',
'ldap_new_user_role' => '1',
'ldap_user_object_filter' => '',
'ldap_username' => 'cn=Directory Manager',
'ldap_password' => 'dirmanager',
'ldap_user_dn_attribute' => '',
'email_debug_level' => '0',
'onthefly-backup-key' => 'bebert86',
'ldap_dn_additional_user_dn' => '',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Firefox - 91.0

**Operating system:** Linux - 64bits

### Logs
[13-May-2022 15:01:01 Europe/Paris] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to decryptUserObjectKey() must be of the type string, null given, called in /var/www/html/teampass/sources/main.queries.php on line 2195 and defined in /var/www/html/teampass/sources/main.functions.php:2728
Stack trace:
#0 /var/www/html/teampass/sources/main.queries.php(2195): decryptUserObjectKey()
#1 /var/www/html/teampass/sources/main.queries.php(1768): continueReEncryptingUserSharekeysStep5()
#2 /var/www/html/teampass/sources/main.queries.php(408): continueReEncryptingUserSharekeys()
#3 /var/www/html/teampass/sources/main.queries.php(74): mainQuery()
#4 {main}
  thrown in /var/www/html/teampass/sources/main.functions.php on line 2728

#### Web server error log
```
 -  ()
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
