### ISSUE TITLE
[3.0.0.17] Generating keys - Encrypting keys - Personal items [0 - 100] - Stuck

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#3163]
### Steps to reproduce
1.Login as admin
2.Add new AD User

### Expected behaviour
Complete procedure

### Actual behaviour
Stuck on Generating Keys - Encrypting keys - Personal items [0 - 100]

<img width="609" alt="image" src="https://user-images.githubusercontent.com/4628571/168582069-3bcfa4c1-84fd-4242-b424-1b430ace8c8e.png">

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache/2.4.41 (Ubuntu)
**Database:**
mysql  Ver 15.1 Distrib 10.7.3-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
PHP 7.4.3
**Teampass version:** 
version 3.0.0.17
**Teampass configuration file:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp (1).txt](https://github.com/nilsteampassnet/TeamPass/files/8699591/tp.1.txt)

**Updated from an older Teampass or fresh install:**
Fresh

### Client configuration
**Browser:**
Chrome, Edge
**Operating system:**
Windows 11
#### Web server error log
```
Nothing in error.log

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
DevTools failed to load source map: Could not load content for http://192.168.xx.xx/plugins/summernote/summernote-bs4.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

```

**Comment by lollko** [comment]
Hi,

I have same issue 

when i check error log nothing happen , but if i check php. log i find somthing 

 PHP Fatal error:  Uncaught TypeError: base64_encode(): Argument #1 ($string) must be of type string, bool given in /var/www/TeamPass1/sources/main.functions.php:2738
Stack trace:
#0 /var/www/TeamPass1/sources/main.functions.php(2738): base64_encode()
#1 /var/www/TeamPass1/sources/main.queries.php(1893): decryptUserObjectKey()
#2 /var/www/TeamPass1/sources/main.queries.php(1747): continueReEncryptingUserSharekeysStep1()
#3 /var/www/TeamPass1/sources/main.queries.php(395): continueReEncryptingUserSharekeys()
#4 /var/www/TeamPass1/sources/main.queries.php(150): keyHandler()
#5 /var/www/TeamPass1/sources/main.queries.php(74): mainQuery()
#6 {main}
  thrown in /var/www/TeamPass1/sources/main.functions.php on line 2738

**Comment by ssudosu** [comment]
Hello,

I have same issue,

When I try to add a user through LDAP it is in a loop but the user receives the email with encryption code.
<img width="317" alt="teampass_loop" src="https://user-images.githubusercontent.com/104503132/169003523-5d7056c0-1546-49b3-a456-48e66447ea49.png">


After entering the LDAP user, no folders appear and it is in a loop looking for folders.
![teampass_folders_loop](https://user-images.githubusercontent.com/104503132/169003326-009272db-7c1b-4271-b7ac-fb89af91f913.png)

In the browser console I have these errors:
![teampass_error](https://user-images.githubusercontent.com/104503132/169003299-771aa0a6-4c1f-408d-b026-48413a127219.png)

Thank you.

**Comment by dsnt02518** [comment]
Looks like a missing semicolon - have created a pull request which should fix this (https://github.com/nilsteampassnet/TeamPass/pull/3172)

**Comment by dsnt02518** [comment]
Nope, that's not the only issue - apologies. I'll submit a new PR if I can work out what's really going on here.

**Comment by giuseppeursi** [comment]
Hi, i have the same problem. 
[errorlog.txt](https://github.com/nilsteampassnet/TeamPass/files/8786670/errorlog.txt)

Here devtool log

![image](https://user-images.githubusercontent.com/106282524/170701028-63e76e85-81c0-419f-b60e-c194d4bd96aa.png)

**Comment by maydond** [comment]
I had the same issue (Encrypting keys dialog stuck) after some time using TeamPass and fiilling up DB with items.
Results were variable, for example, new domain users received "welcome" letter and could use teampass, but could not see some passwords (items with large ID's that were not successfully encrypted during 30 seconds). Local users even did not receive emails and could not log in.

Maybe it is not the case that you are talking about, but sympthoms look similar.
In my case, the reason was the default 30 second PHP timeout, which was not enough to finish key encryption.  After changing php timeout and restarting PHP everything works fine, just needed to reencrypt data for users or just recreate them.

**Comment by ricain59** [comment]
Hello,

I have the same problem after check all users. 
On creating keys for the first users, freeeze on this step.
![image](https://user-images.githubusercontent.com/13002652/177294199-c7f0e56e-2a68-48a8-ab79-372caee090a3.png)

The log not show anything:
`==> /var/log/httpd/teampass-access_log <==
192.168.1.212 - - [05/Jul/2022:10:11:55 +0100] "POST /install/upgrade_run_3.0.0_users.php HTTP/1.1" 200 482 "https://x.x.x.x/install/upgrade.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

==> /var/log/httpd/ssl_access_log <==
192.168.1.212 - - [05/Jul/2022:10:11:55 +0100] "POST /install/upgrade_run_3.0.0_users.php HTTP/1.1" 200 482
`
On developper page on browser, don't get any errors: 
![image](https://user-images.githubusercontent.com/13002652/177294576-9772c4bd-6dfc-4365-b843-bf22d8e1750c.png)

**Comment by lollko** [comment]
bump, some news ?

**Comment by ricain59** [comment]
Any news?

**Comment by nratineau** [comment]
@lollko @ricain59 Had the same issue with the upgrade being stuck and worked around it by creating a brand new Admin user and using it to run the upgrade. Hopefully it will work for you.
Seems there is an issue with the upgrade process when it's trying to do the keys/items for the user you are running the upgrade with if this user has items/password associated in the DB.

**Comment by Kyogre** [comment]
For me "Encrypting keys - Personal items" stucks only if user have bad format of `Email` in personal info. If I edit the user and write some email in correct format like "someemail123@mail.com" and than generate new OTP - it will be done successfully, even if I write some fake email.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
