### ISSUE TITLE
Database import doesn't work (caution popup)

### ISSUE THREAD

**Issue by Lumed7** [nilsteampassnet/TeamPass#3180]
### Steps to reproduce
1. export database from older teampass [2.1.27.36]
2. On new server (same OS, same config), import database from web UI (page=backups) restaurer la base de données
3. Enter the "clé de chiffrement" used to encrypt the export on step 1)
4. Import the .sql file
5. Javascript alert says : FAIT - Database restore has been done. You now need to disconnect to refresh the session variables.
6. Error popup : 
```
Caution
[{"result":"db_restore" , "message":"Defuse\Crypto\Exception\IOException: Could not read from the file in /var/www/teampass/includes/libraries/Encryption/Encryption/File.php:708 Stack trace: #0 /var/www/teampass/includes/libraries/Encryption/Encryption/File.php(479): Defuse\Crypto\File::readBytes() #1 /var/www/teampass/includes/libraries/Encryption/Encryption/File.php(298): Defuse\Crypto\File::decryptResourceInternal() #2 /var/www/teampass/includes/libraries/Encryption/Encryption/File.php(89): Defuse\Crypto\File::decryptFileInternal() #3 /var/www/teampass/sources/main.functions.php(2323): Defuse\Crypto\File::decryptFileWithPassword() #4 /var/www/teampass/sources/main.functions.php(2230): defuseFileDecrypt() #5 /var/www/teampass/sources/backups.queries.php(288): prepareFileWithDefuse() #6 {main}"}]

```
### Server configuration
**Operating system**:
Debian 11

**Web server:**
Apache2

**Database:**
MariaDB 10.7.4

**PHP version:**
php8.1-fpm

**Teampass version:** 
3.0.0.17

**Teampass configuration file:**
```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass',
    'cpassman_url' => 'REDACTED',
    'favicon' => 'REDACTED',
    'path_to_upload_folder' => '/var/www/teampass/upload',
    'path_to_files_folder' => '/var/www/teampass/files',
    'url_to_files_folder' => 'REDACTED',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.17',
    'ldap_mode' => '1',
    'ldap_type' => 'OpenLDAP',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'uid',
    'ldap_ssl' => '1',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '636',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'REDACTED',
    'custom_login_text' => 'Bienvenue sur le teampass REDACTED',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1650699677',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'REDACTED',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => 'REDACTED',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => 'ldap-REDACTED',
    'ldap_password' => 'REDACTED',
    'ldap_username' => 'ou=REDACTED,o=REDACTED,c=co',
);
```

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox version 100

**Operating system:**
Windows 10 professional

#### Web server error log
```
[Tue May 24 11:08:09.396753 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(508): AH00831: socache_shmcb_store (0xc2 -> subcache 2)
[Tue May 24 11:08:09.396861 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(862): AH00847: insert happened at idx=0, data=(0:32)
[Tue May 24 11:08:09.396871 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(865): AH00848: finished insert, subcache: idx_pos/idx_used=0/1, data_pos/data_used=0/219
[Tue May 24 11:08:09.396878 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(530): AH00834: leaving socache_shmcb_store successfully
[Tue May 24 11:08:09.397081 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(508): AH00831: socache_shmcb_store (0xd8 -> subcache 24)
[Tue May 24 11:08:09.397109 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(862): AH00847: insert happened at idx=0, data=(0:32)
[Tue May 24 11:08:09.397114 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(865): AH00848: finished insert, subcache: idx_pos/idx_used=0/1, data_pos/data_used=0/219
[Tue May 24 11:08:09.397120 2022] [socache_shmcb:debug] [pid 63292] mod_socache_shmcb.c(530): AH00834: leaving socache_shmcb_store successfully
[Tue May 24 11:08:09.397547 2022] [core:debug] [pid 63292] vhost.c(1188): [client 10.41.121.10:42700] AH02417: Replacing host header 'teampass-pp.suisse.REDACTED.com' with host 'teampass-pp.suisse.REDACTED.com' given in the request uri, referer>
[Tue May 24 11:08:09.397677 2022] [ssl:debug] [pid 63292] ssl_engine_kernel.c(415): [client 10.41.121.10:42700] AH02034: Initial (No.1) HTTPS request received for child 0 (server teampass-pp.suisse.REDACTED.com:443), referer: https://teampa>
[Tue May 24 11:08:09.397785 2022] [authz_core:debug] [pid 63292] mod_authz_core.c(815): [client 10.41.121.10:42700] AH01626: authorization result of Require all granted: granted, referer: https://teampass-pp.suisse.REDACTED.com/index.php?pa>
[Tue May 24 11:08:09.397795 2022] [authz_core:debug] [pid 63292] mod_authz_core.c(815): [client 10.41.121.10:42700] AH01626: authorization result of <RequireAny>: granted, referer: https://teampass-pp.suisse.REDACTED.com/index.php?page=admin
[Tue May 24 11:08:09.397883 2022] [proxy:debug] [pid 63292] mod_proxy.c(1503): [client 10.41.121.10:42700] AH01143: Running scheme unix handler (attempt 0), referer: https://teampass-pp.suisse.REDACTED.com/index.php?page=admin
[Tue May 24 11:08:09.397899 2022] [proxy_fcgi:debug] [pid 63292] mod_proxy_fcgi.c(1054): [client 10.41.121.10:42700] AH01076: url: fcgi://localhost/var/www/teampass/index.php proxyname: (null) proxyport: 0, referer: https://teampass-pp.>
[Tue May 24 11:08:09.397923 2022] [proxy_fcgi:debug] [pid 63292] mod_proxy_fcgi.c(1063): [client 10.41.121.10:42700] AH01078: serving URL fcgi://localhost/var/www/teampass/index.php, referer: https://teampass-pp.suisse.REDACTED.com/index.ph>
[Tue May 24 11:08:09.397954 2022] [proxy:debug] [pid 63292] proxy_util.c(2532): AH00942: FCGI: has acquired connection for (*)
[Tue May 24 11:08:09.397964 2022] [proxy:debug] [pid 63292] proxy_util.c(2588): [client 10.41.121.10:42700] AH00944: connecting fcgi://localhost/var/www/teampass/index.php to localhost:8000, referer: https://teampass-pp.suisse.REDACTED.com/>
[Tue May 24 11:08:09.397972 2022] [proxy:debug] [pid 63292] proxy_util.c(2624): [client 10.41.121.10:42700] AH02545: fcgi: has determined UDS as /run/php/php8.1-fpm.sock, referer: https://teampass-pp.suisse.REDACTED.com/index.php?page=admin
[Tue May 24 11:08:09.398087 2022] [proxy:debug] [pid 63292] proxy_util.c(2811): [client 10.41.121.10:42700] AH00947: connected /var/www/teampass/index.php to httpd-UDS:0, referer: https://teampass-pp.suisse.REDACTED.com/index.php?page=admin
[Tue May 24 11:08:09.398145 2022] [proxy:debug] [pid 63292] proxy_util.c(3178): AH02823: FCGI: connection established with Unix domain socket /run/php/php8.1-fpm.sock (*)
[Tue May 24 11:08:09.419538 2022] [proxy:debug] [pid 63292] proxy_util.c(2547): AH00943: FCGI: has released connection for (*)
[Tue May 24 11:08:09.419948 2022] [deflate:debug] [pid 63292] mod_deflate.c(869): [client 10.41.121.10:42700] AH01384: Zlib: Compressed 133546 to 19609 : URL /index.php, referer: https://teampass-pp.suisse.REDACTED.com/index.php?page=admin
10.41.21.191 - - [24/May/2022:11:08:09 +0200] "GET /index.php?page=backups HTTP/1.1" 200 22392 "https://teampass-pp.suisse.REDACTED.com/index.php?page=admin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
[Tue May 24 11:08:09.533198 2022] [core:debug] [pid 63292] vhost.c(1188): [client 10.41.121.10:42700] AH02417: Replacing host header 'teampass-pp.suisse.REDACTED.com' with host 'teampass-pp.suisse.REDACTED.com' given in the request uri, referer>
[Tue May 24 11:08:09.533272 2022] [ssl:debug] [pid 63292] ssl_engine_kernel.c(415): [client 10.41.121.10:42700] AH02034: Subsequent (No.2) HTTPS request received for child 0 (server teampass-pp.suisse.REDACTED.com:443), referer: https://tea>
[Tue May 24 11:08:09.533363 2022] [authz_core:debug] [pid 63292] mod_authz_core.c(815): [client 10.41.121.10:42700] AH01626: authorization result of Require all granted: granted, referer: https://teampass-pp.suisse.REDACTED.com/index.php?pa>
[Tue May 24 11:08:09.533372 2022] [authz_core:debug] [pid 63292] mod_authz_core.c(815): [client 10.41.121.10:42700] AH01626: authorization result of <RequireAny>: granted, referer: https://teampass-pp.suisse.REDACTED.com/index.php?page=back>
[Tue May 24 11:08:09.533407 2022] [proxy:debug] [pid 63292] mod_proxy.c(1503): [client 10.41.121.10:42700] AH01143: Running scheme unix handler (attempt 0), referer: https://teampass-pp.suisse.REDACTED.com/index.php?page=backups
[Tue May 24 11:08:09.533417 2022] [proxy_fcgi:debug] [pid 63292] mod_proxy_fcgi.c(1054): [client 10.41.121.10:42700] AH01076: url: fcgi://localhost/var/www/teampass/sources/main.queries.php proxyname: (null) proxyport: 0, referer: https>
```

**Comment by Lumed7** [comment]
clarification : 
At first I tried to upgrade from 2.1.27.36 to 3.0.0.17, keeping the same database. But I couldn't login or create any new user because two fields were missing in the teampass_users table. (public_key and private_key)

So I dropped the database, upgraded (then teampass created the database including the 2 fields who were previously missing since I dropped the og database). Then I exported the database in sql and imported it via sql on my terminal.

It doesn't work :/ , same saltkey, same data, new database but with the same structure, the only difference is these new fields, and them being NULL on imported data from the original database

**Comment by Lumed7** [comment]
I also can't login with a user created via the web UI, 
Error message :"Caution Login credentials do not correspond!"

I can only log in with the admin account.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
