### ISSUE TITLE
Hung when click Login button

### ISSUE THREAD

**Issue by smallfish01** [nilsteampassnet/TeamPass#3183]
### Steps to reproduce
1. Type username/password and click Login
2.System hung, please check the screenshot:
![image](https://user-images.githubusercontent.com/4077255/170448292-80f30043-1459-4c8f-bdb2-6daf7e0f01a6.png)
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/8777506/tp.config.php.zip)

Btw, before this I change admin password from Mysql, is possible the password need encryption?

### Expected behaviour
Click Login button.

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Apache 2.4

**Database:** Mysql

**PHP version:**7.4

**Teampass version:** 3.0.0.17

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
apache error log:
[Thu May 26 16:53:12.042003 2022] [php7:error] [pid 2022] [client 192.168.13.79:62607] PHP Fatal error:  Uncaught DomainException: Unsupported Password Hash Supplied in /var/www/html/teampass/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash()\n#1 /var/www/html/teampass/sources/identify.php(1550): PasswordLib\\PasswordLib->verifyPasswordHash()\n#2 /var/www/html/teampass/sources/identify.php(351): checkCredentials()\n#3 /var/www/html/teampass/sources/identify.php(186): identifyUser()\n#4 {main}\n  thrown in /var/www/html/teampass/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: http://192.168.13.177/teampass/index.php

#### Log from the web-browser developer console (CTRL + SHIFT + i)
![image](https://user-images.githubusercontent.com/4077255/170451901-a0599db8-9a52-4b25-979a-bc4eefeae9a1.png)

**Comment by smallfish01** [comment]
I think the root cause was I changed admin password to plaintext.
I just re-install TeamPass and it works.

**Comment by gonzalodeniz** [comment]
In v3.1.2.55 I have the same error. My "pw" is encrypted. I have reinstalled but it does not fix it.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
