### ISSUE TITLE
[3.0.0.18] Update problem from 3.0.0.17

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#3185]
### Steps to reproduce
1)Download latest release from [Teampass](https://github.com/nilsteampassnet/TeamPass/releases/latest)
2)Unzip and overwrite existing files in Teampass folder
3)Browse to Teampass upgrade page by selecting url https://<your_teampass_instance>/install/upgrade.php

### Expected behaviour
Complete procedure

### Actual behaviour
Stuck on Finalization

![image](https://user-images.githubusercontent.com/4628571/170555826-06c4d89d-1c5e-4f91-a343-6c08dc429565.png)

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache/2.4.41 (Ubuntu)
**Database:**
mysql  Ver 15.1 Distrib 10.7.3-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
PHP 7.4.3
**Teampass version:** 
version 3.0.0.17
**Teampass configuration file:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp (1).txt](https://github.com/nilsteampassnet/TeamPass/files/8699591/tp.1.txt)

**Updated from an older Teampass or fresh install:**
Update from 3.0.0.17

### Client configuration
**Browser:**
Chrome, Edge
**Operating system:**
Windows 11
#### Web server error log
```
[Thu May 26 21:48:24.193520 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Use of undefined constant DB_SSL - assumed 'DB_SSL' (this will throw an Error in a future version of PHP) in /var/www/html/index.php on line 110
[Thu May 26 21:48:24.193553 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Use of undefined constant DB_CONNECT_OPTIONS - assumed 'DB_CONNECT_OPTIONS' (this will throw an Error in a future version of PHP) in /var/www/html/index.php on line 111
[Thu May 26 21:48:24.194708 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Illegal string offset 'key' in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 183
[Thu May 26 21:48:24.194722 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Illegal string offset 'key' in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 184
[Thu May 26 21:48:24.194736 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Illegal string offset 'cert' in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 184
[Thu May 26 21:48:24.194740 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Illegal string offset 'ca_cert' in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 184
[Thu May 26 21:48:24.194744 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Illegal string offset 'ca_path' in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 184
[Thu May 26 21:48:24.194748 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Illegal string offset 'cipher' in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 184
[Thu May 26 21:48:24.194762 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 187
[Thu May 26 21:48:24.195290 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  include(../../../config/tp.config.php): failed to open stream: No such file or directory in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 979
[Thu May 26 21:48:24.195305 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 979
[Thu May 26 21:48:24.195335 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): failed to open stream: No such file or directory in /var/www/html/sources/main.functions.php on line 1522
[Thu May 26 21:48:24.195343 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/sources/main.functions.php on line 1522
[Thu May 26 21:48:24.195360 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  include_once(/sources/SplClassLoader.php): failed to open stream: No such file or directory in /var/www/html/sources/main.functions.php on line 1533
[Thu May 26 21:48:24.195366 2022] [php7:warn] [pid 1470] [client 192.168.xx.136:64944] PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/sources/main.functions.php on line 1533
[Thu May 26 21:48:57.131353 2022] [php7:error] [pid 1507] [client 192.168.xx.136:65003] PHP Fatal error:  Uncaught Error: Class 'SplClassLoader' not found in /var/www/html/sources/main.functions.php:1535\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(983): prepareExchangedData()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(225): meekrodb_error_handler()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(195): MeekroDB->nonSQLError()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(648): MeekroDB->get()\n#4 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#5 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#6 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#7 /var/www/html/sources/main.functions.php(2065): DB::query()\n#8 /var/www/html/install/upgrade_ajax.php(924): handleConfigFile()\n#9 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 1535, referer: https://teampass/install/upgrade.php


```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
jquery.min.js:2          POST https://teampass/install/upgrade_ajax.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:191
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

ncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:199:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:191:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
complete @ upgrade.php:199
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:191
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:191
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2


```

**Comment by rrgadeev** [comment]
same thing 3.0.0.16 to 3.0.0.17

**Comment by samuellegendre** [comment]
@reginfo @rrgadeev I followed the dev's response on [issue #401803](https://github.com/nilsteampassnet/TeamPass/issues/3168) and it worked.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
