### ISSUE TITLE
After adding a user from ldap no folders for this user are listed

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3188]
Hi.
New day, new issue ;-)
After getting managed to add a user from ldap (see https://github.com/nilsteampassnet/TeamPass/issues/3155#issuecomment-1140252644), I set folders and roles and assigning a role to the new user.
After logging with this user the 'list folder' spinning forever an hangs on
main.queries.php with type=sending_statistics&type_category=action_system
In my php-fpm the following error occurs:
```
[28-May-2022 13:45:25 UTC] PHP Warning:  array_merge(): Expected parameter 2 to be an array, null given in /path/to/my/instance/sources/tree.php on line 647
[28-May-2022 13:45:25 UTC] PHP Fatal error:  Uncaught TypeError: in_array() expects parameter 2 to be array, null given in /path/to/my/instance/sources/tree.php:647
Stack trace:
#0 /path/to/my/instance/sources/tree.php(647): in_array()
#1 /path/to/my/instance/sources/tree.php(205): recursiveTree()
#2 {main}
  thrown in /path/to/my/instance/sources/tree.php on line 647
  ```

**Comment by samuellegendre** [comment]
Hey,

Let me know if you found something. I'm currently having the same problem from a fresh installation.

**Comment by nahpl** [comment]
Hi,

Hi, i have the same problem. Did you find any solution?

**Comment by CrazyNeo89** [comment]
Hi,

I have the same problem. Did you find any solution?

Log error:

[Sat Jun 18 10:04:19.242832 2022] [php:error] [pid 36580] [client 192.168.31.23:65445] PHP Fatal error:  Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, null given in /var/www/html/TeamPass/sources/tree.php>

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
