### ISSUE TITLE
LDAP problems inTeampass 3.0.0.17

### ISSUE THREAD

**Issue by FrannVazquez05** [nilsteampassnet/TeamPass#3193]
Good afternoon.

Steps to reproduce the error:

1) We configure LDAP and try the connection with outany problem.
2) Go to user tabs, clic on "LDAP synchronization"
3) It gives back this error:

Fatal error: Uncaught ErrorException: ldap_search(): Search: Invalid DN syntax in /var/www/html/includes/libraries/LdapRecord/Ldap.php:235 Stack trace: #0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}() #1 /var/www/html/includes/libraries/LdapRecord/Ldap.php(235): ldap_search() #2 /var/www/html/includes/libraries/LdapRecord/HandlesConnection.php(171): LdapRecord\Ldap->LdapRecord\{closure}() #3 /var/www/html/includes/libraries/LdapRecord/Ldap.php(237): LdapRecord\Ldap->executeFailableOperation() #4 /var/www/html/includes/libraries/LdapRecord/Query/Builder.php(656): LdapRecord\Ldap->search() #5 /var/www/html/includes/libraries/LdapRecord/Connection.php(394): LdapRecord\Query\Builder->LdapRecord\Query\{closure}() #6 /var/www/html/includes/libraries/LdapRecord/Connection.php(352): LdapRecord\Connection->runOperationCallback() #7 /var/www/html/includes/libraries/LdapRecord/Query/Builder.php(658): LdapRecord\Connection->run() #8 /var/www/html/includes/libraries/LdapRecord/Query/Builder.php(449): LdapRecord\Query\Bu in /var/www/html/includes/libraries/LdapRecord/LdapRecordException.php on line 26

Thanks in advance

[ 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by useronkel** [comment]
Hi Frann.
You are running in the same problem as I did.
My solution was to change a little bit code -> https://github.com/nilsteampassnet/TeamPass/issues/3155#issuecomment-1140252644

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
