### ISSUE TITLE
Problems with One-Time-Code and login after upgrade 

### ISSUE THREAD

**Issue by Benny1988** [nilsteampassnet/TeamPass#3195]
### Steps to reproduce
1. upgrade from 2.1.27 to 3.0.0.18
2. try one-time-code the first time
3. try to log in with ldap and local admin user

### Expected behaviour
Should accept one time code or log me into the application

### Actual behaviour
I get only the "In progress" overlay and nothing happens

### Server configuration
Debian Bullseye

**Web server:**
nginx 1.18.0

**Database:**
10.6.8-MariaDB-1:10.6.8+maria~bullseye

**PHP version:**
PHP 8.1

**Teampass version:** 
3.0.0.18

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome and Firefox latest version

**Operating system:**
Ubuntu

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
(index):2526 Uncaught ReferenceError: store is not defined
    at launchIdentify ((index):2526:9)
    at HTMLButtonElement.<anonymous> ((index):2109:13)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
launchIdentify @ (index):2526
(anonymous) @ (index):2109
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Insert the log here and especially the answer of the query that failed.
```

**Comment by Benny1988** [comment]
And when i enter the one time code and click on confirm, nothing happens.

**Comment by Benny1988** [comment]
We were able to solve the problem ourselves, it wasn't due to teampass, but to a misconfiguration of nginx.
