### ISSUE TITLE
Empty passwords after upgrading from Teampass 2 to Teampass 3

### ISSUE THREAD

**Issue by radekw1996** [nilsteampassnet/TeamPass#3198]
### Steps to reproduce
1. Upgrading Ubuntu with old Teampass 2.1.27.35 from 16 through 18 through 20 to 21 
2. Upgrading Teampass using this tutorial https://teampass.readthedocs.io/en/latest/install/upgrade/ (i didin't change anything in database)
3.

### Expected behaviour
Passwords should be visible

### Actual behaviour
Everything thing is fine, expect of password which are "empty" 

### Server configuration
**Operating system**: Ubuntu 21

**Web server:** Apache `2.4.48-3`

**Database:** MySQL 5.7

**PHP version:** PHP 8.0.8

**Teampass version:** Teampass 3.0.0.17

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:** Yes Teampass is upgradet from 2.1.27.35
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome 100

**Operating system:** Windows 11

#### Web server error log 
[Thu Jun 02 15:16:54.037902 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.037914 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_ajax.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.037926 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_run_3.0.0.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.037938 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_run_3.0.0_fields.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.037962 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_run_3.0.0_files.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.037986 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_run_3.0.0_logs.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.037998 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_run_3.0.0_passwords.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.038040 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_run_3.0.0_suggestions.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.038063 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_run_3.0.0_users.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
[Thu Jun 02 15:16:54.038075 2022] [php:warn] [pid 2603] [client secret:64210] PHP Warning:  unlink(/var/www/teampass/public_html/install/upgrade_scripts_manager.php): Permission denied in /var/www/teampass/public_html/sources/core.php on line 139, referer: https://teampass-test.secret.pl/install/upgrade.php
core.php

Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
Logs are empty

```
Insert the log here and especially the answer of the query that
```
[tp.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/8824598/tp.config.php.zip)

**Comment by radekw1996** [comment]
Interesting thing is that the proces of converting database was very short (my database is very large). As far as I know it can take even hours to convert. Does it make any difference that I made mysqldump with old date in to My Sql server, before starting process of converting database? I just wanted to have the latest version of all my passwords before I start converting.

**Comment by radekw1996** [comment]
I tried one more time but with this tutorial https://documentation.teampass.net/#/start?id=upgrading-from-2x-branch
And now I'm getting an error 
`PHP Fatal error:  Uncaught Defuse\\Crypto\\Exception\\BadFormatException: Encoded data is shorter than expected. in /var/www/teampass/public_html/includes/libraries/Encryption/Encryption/Encoding.php:225\nStack trace:\n#0 /var/www/teampass/public_html/includes/libraries/Encryption/Encryption/Key.php(49): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString()\n#1 /var/www/teampass/public_html/install/tp.functions.php(44): Defuse\\Crypto\\Key::loadFromAsciiSafeString()\n#2 /var/www/teampass/public_html/install/tp.functions.php(84): defuseCryption()\n#3 /var/www/teampass/public_html/install/upgrade_ajax.php(254): defuse_return_decrypted()\n#4 {main}\n  thrown in /var/www/teampass/public_html/includes/libraries/Encryption/Encryption/Encoding.php on line 225, referer: https://teampass-test.currenda.pl/install/upgrade.php`

**Comment by mikaelmantel** [comment]
For this error, i think you don't have your teampass-seckey.txt file in the new folder.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
