### ISSUE TITLE
User mode login problem - version 3.0.0.17 ad 3.0.0.18

### ISSUE THREAD

**Issue by Lucifersgirl** [nilsteampassnet/TeamPass#3218]
### Steps to reproduce
1. 
![image](https://user-images.githubusercontent.com/107415827/173374984-ba1826b4-6a98-4e90-b0de-8e886c206309.png)

2. Don`t have a form to login 
3. Admin mode work but when switched to user don`t

### Expected behaviour
I would like to all my users can login

### Actual behaviour
Can`t login in users account

### Server configuration
**Operating system: Ubuntu 20.04**

**Web server: Apache/2.4.41 (Ubuntu)** 

**Database:  mysql  Ver 8.0.27-0ubuntu0.20.04.1**

**PHP version: 7.4, 8.0** 

**Teampass version: 3.0.0.17 and 3.0.0.18** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser: chrome, opera gx**

**Operating system: Windows 11**

#### Web server error log
```
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Function name must be a string in /var/www/TeamPass/includes/core/login.php:77\nStack trace:\n#0 /var/www/TeamPass/index.php(1083): include()\n#1 {main}\n  thrown in /var/www/TeamPass/includes/core/login.php on line 77'
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
GET https://teampass.domain.pl/ 500 (Internal Server Error)
csrfprotector.js:152 TypeError: Cannot read properties of null (reading 'value')
    at Object._init (csrfprotector.js:150:86)
    at csrfprotector_init (csrfprotector.js:174:11)
    at csrfprotector.js:336:5
_init @ csrfprotector.js:152
csrfprotector_init @ csrfprotector.js:174
(anonimowa) @ csrfprotector.js:336
csrfprotector.js:153 [ERROR] [CSRF Protector] unable to parse blacklisted url fields.
_init @ csrfprotector.js:153
csrfprotector_init @ csrfprotector.js:174
(anonimowa) @ csrfprotector.js:336
VM30 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM30 content_script.js:1:1)
VM31 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM31 content_script.js:1:1)
VM32 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM32 content_script.js:1:1)
VM33 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM33 content_script.js:1:1)
VM34 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM34 content_script.js:1:1)
VM35 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM35 content_script.js:1:1)
VM36 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM36 content_script.js:1:1)
VM37 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM37 content_script.js:1:1)
VM38 content_script.js:1 Uncaught SyntaxError: Identifier 'WBSAutoFillFormTypeUndetermined' has already been declared (at VM38 content_script.js:1:1)
```

And from console network tab:

```
This site attempts to protect users against [Cross-Site Request Forgeries ](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29)attacks. In order to do so, you must have JavaScript enabled in your web browser otherwise this site will fail to work correctly for you. See details of your web browser for how to enable JavaScript.
```
I have JS enabled

**Comment by Lucifersgirl** [comment]
tp.config.php

 
```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass',
    'cpassman_url' => 'https://teampass.domain.pl',
    'favicon' => 'https://teampass.domain.pl/favicon.ico',
    'path_to_upload_folder' => '/var/www/teampass/upload',
    'path_to_files_folder' => '/var/www/teampass/files',
    'url_to_files_folder' => 'https://teampass.domain.pl/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.17',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1650964880',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.gmail.com',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'admin@neo-vinci.pl',
    'email_auth_pwd' => 'Ompdgt33!',
    'email_port' => '465',
    'email_security' => 'ssl',
    'email_server_url' => '',
    'email_from' => 'admin@neo-vinci.pl',
    'email_from_name' => 'TeamPass Neo-Vinci',
    'pwd_maximum_length' => '40',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '10',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
	'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Warsaw',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '1',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '7sK44WKdremDsxQwrhCxPC2aFhZWjguxY92ynqZA',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
);

```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
