### ISSUE TITLE
Encrypting keys - Journaux [0 - 100] / 698 ... Merci de patienter ! infinite

### ISSUE THREAD

**Issue by rafikberzi** [nilsteampassnet/TeamPass#3223]
### Steps to reproduce
1. Users/remove all more folders/replace roles by a new one
2.Encrypting keys - Journaux [0 - 100] / 698 ... Merci de patienter ! infinite
3. apache log : 

### Expected behaviour
Tell us what should happen
It should save and send an email to the user
### Actual behaviour
Tell us what happens instead
nothing
### Server configuration
**Operating system**:
linux
**Web server:**
apache
**Database:**
mysql
**PHP version:**
7.4
**Teampass version:** 
version 3.0.0.17
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome
**Operating system:**
mac os
#### Web server error log
```
Insert your webserver log here
```
[Wed Jun 15 17:30:39.104774 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to decryptUserObjectKey() must be of the type string, null given, called in /home/secure/public_html/TpM/sources/main.queries.php on line 1987 and defined in /home/secure/public_html/TpM/sources/main.functions.php:2738, referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104820 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: Stack trace:, referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104825 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: #0 /home/secure/public_html/TpM/sources/main.queries.php(1987): decryptUserObjectKey(), referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104829 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: #1 /home/secure/public_html/TpM/sources/main.queries.php(1762): continueReEncryptingUserSharekeysStep2(), referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104834 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: #2 /home/secure/public_html/TpM/sources/main.queries.php(397): continueReEncryptingUserSharekeys(), referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104838 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: #3 /home/secure/public_html/TpM/sources/main.queries.php(152): keyHandler(), referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104841 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: #4 /home/secure/public_html/TpM/sources/main.queries.php(74): mainQuery(), referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104845 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr: #5 {main}, referer: https://secure.hotello.com/TpM/index.php?page=users
[Wed Jun 15 17:30:39.104849 2022] [fcgid:warn] [pid 1480091:tid 140421422356224] [client 66.254.60.52:57731] mod_fcgid: stderr:   thrown in /home/secure/public_html/TpM/sources/main.functions.php on line 2738, referer: https://secure.hotello.com/TpM/index.php?page=users
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
csrfprotector.js:1          Failed to load resource: the server responded with a status of 404 (Not Found)


/TpM/sources/main.queries.php:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Échec du chargement de la carte source par les Outils de développement : Impossible de charger le contenu de https://secure.hotello.com/TpM/plugins/moment/moment.min.js.map : Erreur HTTP : code d'état 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
Insert the log here and especially the answer of the query that failed.
```
[secure.hotello.com-1655330458069.log](https://github.com/nilsteampassnet/TeamPass/files/8913495/secure.hotello.com-1655330458069.log)

[tp.config.php.log](https://github.com/nilsteampassnet/TeamPass/files/8913500/tp.config.php.log)

**Comment by rafikberzi** [comment]
I deleted the data in the log table and it resolved the issue.
