### ISSUE TITLE
LDAP configuration not working 

### ISSUE THREAD

**Issue by petafs** [nilsteampassnet/TeamPass#3226]
### Steps to reproduce
1.Try to configure LDAP connection

### Server configuration
**Operating system : Ubuntu 22.04
**Web server : Apache2 2.4.52
**Database : MYSQL 8.0.29
**PHP version : 8.1.2
**Teampass version : 3.0.0.17
**fresh install

#### Web server error log
```
[Fri Jun 17 09:30:27.169886 2022] [php:error] [pid 2137] [client 10.1.2.243:55773] PHP Fatal error:  Uncaught TypeError: Illegal offset type in /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php:495\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\\Connection->retryOnNextHost()\n#1 /var/www/html/teampass/sources/ldap.queries.php(168): LdapRecord\\Connection->connect()\n#2 {main}\n  thrown in /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php on line 495, referer: https://teampass.mutsoleil.local/index.php?page=ldap
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
![image](https://user-images.githubusercontent.com/107537809/174293579-e7777c51-26e9-41d3-9c85-13142386c111.png)

```

**Comment by petafs** [comment]
No ansewer, no help, no debug mode ?!?

**Comment by SpoCo-network1** [comment]
You should post a screenshot of what your ldap configuration looks like in the Settings > LDAP section.

**Comment by petafs** [comment]
Off course : 
![image](https://user-images.githubusercontent.com/107537809/174730180-2c863961-c3ed-45e8-a401-c0297afcf84d.png)
![image](https://user-images.githubusercontent.com/107537809/174731127-f94d2f54-8100-494c-9b48-69d3aadbd326.png)

**Comment by phmorais55** [comment]
After doing the configuration of the LDAP service several times, I identified that the Bug is in the User name attribute, which in the documentation says to put it as sAMAccountName as it is written, but when I copy the way it is written it does not synchronize with AD, by the irony of fate I wrote everything in lower case and saved it synced. so I understood that the BUG is there, it worked in my environment I don't know if it will work in others.

![image](https://user-images.githubusercontent.com/31416215/175662159-11a9f0b4-d554-46aa-ab5d-5cc9f7fb3f67.png)

**Comment by SpoCo-network1** [comment]
This was also what we had to do to get it working for us. I had asked for a post of the configuration namely for that reason, to see if the OP was running into the same issue we faced. So in conclusion: "samaccountname" must be LOWERCASE, despite the field description. I'm sure @nilsteampassnet will fix this is the next release, hopefully along with DUO support *hint *hint!

**Comment by nilsteampassnet** [comment]
Thank you for this.
I didn't realize this.
DUO will come but ... I'm a bit busy and DUO has fully changed its library so it will require full development.

**Comment by petafs** [comment]
Thank for you return,

Unfortunately, it doesn't change anything in my case.

I'had the same error : 
[Mon Jun 27 06:40:42.811466 2022] [php:error] [pid 84204] [client 10.1.2.247:56818] PHP Fatal error:  Uncaught TypeError: Illegal offset type in /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php:495\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\\Connection->retryOnNextHost()\n#1 /var/www/html/teampass/sources/ldap.queries.php(168): LdapRecord\\Connection->connect()\n#2 {main}\n  thrown in /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php on line 495, referer: https://teampass.mutsoleil.local/index.php?page=ldap

**Comment by jkreet** [comment]
> Thank for you return,
> 
> Unfortunately, it doesn't change anything in my case.
> 
> I'had the same error : [Mon Jun 27 06:40:42.811466 2022] [php:error] [pid 84204] [client 10.1.2.247:56818] PHP Fatal error: Uncaught TypeError: Illegal offset type in /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php:495\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\Connection->retryOnNextHost()\n#1 /var/www/html/teampass/sources/ldap.queries.php(168): LdapRecord\Connection->connect()\n#2 {main}\n thrown in /var/www/html/teampass/includes/libraries/LdapRecord/Connection.php on line 495, referer: https://teampass.mutsoleil.local/index.php?page=ldap

Same error
Have any fix?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
