### ISSUE TITLE
Reencryption stucks "In progress" (LDAP-Setup)

### ISSUE THREAD

**Issue by DasIgno** [nilsteampassnet/TeamPass#3231]
### Steps to reproduce
1. Import user from LDAP tree
2. Change users privileges from initial User to e.g. Manager
3. Log in with fresh imported user
4. Perform initial encryption process
5. Try to perform reencryption process caused by privileges change

### Expected behaviour
Reencryption proceeds successful, so the user is able to use TeamPass

### Actual behaviour
Reencryption runs into a never ending "In progress", so the user gets stuck after login. This behaviour is final. Logging in again results again in the reencryption process and that stucks "In progress". My only found solution is actually to delete the user in the database (simply deleting in admin-frontend doesn't seem to reset its encryption state) and reimport it again without increasing its privileges. In this case the initial encryption process runs fine and the user is ready to work. But I fear what happens at future upgrades, when reencryption of all users could be enforced.

### Server configuration
**Operating system**: Debian 11 (5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux)

**Web server:** nginx/1.18.0

**Database:** mysql Ver 15.1 Distrib 10.5.15-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**PHP version:** PHP 8.1.7 (cli) (built: Jun 14 2022 10:25:41) (NTS) (also tried 7.4)

**Teampass version:** 3.0.0.18 (fresh pulled master branch, also tried with 3.0.0.17)

**Teampass configuration file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/8950919/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** fresh install

### Client configuration
**Browser:** Firefox 91.10.0esr (64-Bit)

**Operating system:** Debian 11 (5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux)

#### Web server error log
```
2022/06/21 18:20:04 [error] 3646#3646: *26 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: base64_encode(): Argument #1 ($string) must be of type string, bool given in /var/www/foo.bar/TeamPass/sources/main.functions.php:2740
Stack trace:
#0 /var/www/foo.bar/TeamPass/sources/main.functions.php(2740): base64_encode()
#1 /var/www/foo.bar/TeamPass/sources/main.queries.php(1307): decryptUserObjectKey()
#2 /var/www/foo.bar/TeamPass/sources/main.queries.php(238): isUserPasswordCorrect()
#3 /var/www/foo.bar/TeamPass/sources/main.queries.php(140): passwordHandler()
#4 /var/www/foo.bar/TeamPass/sources/main.queries.php(74): mainQuery()
#5 {main}
  thrown in /var/www/foo.bar/TeamPass/sources/main.functions.php on line 2740" while reading response header from upstream, client: 1.2.3.4, server: pwd.foo.bar, request: "POST /sources/main.queries.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "pwd.foo.bar", referrer: "https://pwd.foo.bar/index.php?page=items"
```

**Comment by nilsteampassnet** [comment]
I have tried to reproduce following instruction and could not reproduce.
You confirm that at step 5, you are logged as an admin.
And as this admin, you change the role of the user.
At this point, the re-encryption starts.
And you observe the issue 
Correct?

**Comment by DasIgno** [comment]
I tried to reproduce the behaviour today and couldn't too. It seemed to be fixed without action, I don't know.

For the record, steps 1 and 2 were done as admin and before the new user logged in for the first time. Steps 3 to 5 were done as the new user. Days ago, as the issue existed, the user then performed the initial encryption with the initial key sent by mail and then directly ran into a reencryption triggered, I think, by the increased rights. And that reencryption failed with the reencryption key also sent by the system.

However, it works now. New users only receive one encryption key and don't run into a reencryption process, even if hey got increased rights before their first login.

**Comment by nilsteampassnet** [comment]
ok thanks for the feedback.

When an admin decides to change the user rights, the item keys are generated for the user using his public key. THis step takes a certain time. 
But when the user get logged and provide the random key, Teampass just uncrypt his private key with the random key (sent by mail) and encrypts it with the user password. Which goes very fast.

See https://documentation.teampass.net/#/encryption

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
