### ISSUE TITLE
Warnings and errors when login with user or manager (latest commit)

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3238]
Hi.
After updating to [d98489b](https://github.com/nilsteampassnet/TeamPass/commit/d98489bf33d340419002fe68f452bfcfa94dcb44) the loading symbol for passwords spins forever and the following errors/warnings occur with a normal user and a manager:
Normal user:
```
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in ./sources/main.functions.php on line 3489
PHP Warning:  include(../../../config/tp.config.php): failed to open stream: No such file or directory in ./includes/libraries/Database/Meekrodb/db.class.php on line 979
PHP Warning:  include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in ./includes/libraries/Database/Meekrodb/db.class.php on line 979
PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): failed to open stream: No such file or directory in ./sources/main.functions.php on line 1514
PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in ./sources/main.functions.php on line 1514
PHP Warning:  include_once(/sources/SplClassLoader.php): failed to open stream: No such file or directory in ./sources/main.functions.php on line 1525
PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in ./sources/main.functions.php on line 1525
```
After clicking somewhere else (Import/Search etc.) the folder list appears

When I try to login with a manager the following errors appear:
```
PHP Fatal error:  Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in ./sources/tree.php:971
Stack trace:
#0 ./sources/tree.php(971): array_keys()
#1 ./sources/tree.php(770): prepareNodeData()
#2 ./sources/tree.php(694): handleNode()
#3 ./sources/tree.php(207): recursiveTree()
#4 {main}
  thrown in ./sources/tree.php on line 971
  ```
This time it doesn't matter where I click, error stays and no folders are listed

Webconsole is clean (some Debug-Outputs, but no errors)
Attached tp.config
[tp.config.log](https://github.com/nilsteampassnet/TeamPass/files/8997921/tp.config.log)

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by useronkel** [comment]
In dev console the following html code appears:
```
<option value="0" disabled="disabled">Root</option><option value="16" data-parent-id="0">&nbsp;user1</option><option value="31" disabled="disabled" data-parent-id="0">&nbsp;folder3</option><option value="36" disabled="disabled" data-parent-id="31">&nbsp;&nbsp;folder4[folder3]</option>
```
It's the html I'm expecting to appear under folders ;-)
