### ISSUE TITLE
The password folders assigned to the user with type user are not seen

### ISSUE THREAD

**Issue by carlosmatthews** [nilsteampassnet/TeamPass#3240]
1-create a user of type normal user (vfx user)
2- create a role called vfx_edit, where you are assigned read permission for 2 folders with passwords already created.
3- in the user permissions by role, assign the role called vfx_edit.
4-I log in with the user but it never loads the folders.
5-with my administrator account I check the user to see what folders he has as visible, and it effectively indicates as visible the folders allowed for the role assigned to the user.
6- al mismo usuario le agregue permisos individuales para ver esas carpetas( no mediante rol) y tampoco puede mostrarlas.
7 - genere otro usuario con otro rol de similares caracteristicas pero tampoco me permite ver las carpetas de password cuando me logeo con este usuario.

![imagen](https://user-images.githubusercontent.com/68878024/176235216-0d142021-9af4-4e8e-ac40-6d71e98549e1.png)

### Server configuration
Debian 11

**Web server:**
Apache
**Database:**
mysql
**PHP version:**
7
**Teampass version:** 
3
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by useronkel** [comment]
I'm attaching me to this problem, got the same
After updating to [d9bccdf](https://github.com/nilsteampassnet/TeamPass/commit/d9bccdf5def6b7de880bb8dcfb19ff99f35626a3) the loading symbol for folder items passwords spins forever and the following errors/warnings occur:
```
PHP Fatal error:  Uncaught TypeError: array_keys() expects parameter 1 to be array, null given in ./sources/tree.php:971
Stack trace:
#0 ./sources/tree.php(971): array_keys()
#1 ./sources/tree.php(770): prepareNodeData()
#2 ./sources/tree.php(694): handleNode()
#3 ./sources/tree.php(207): recursiveTree()
#4 {main}
  thrown in ./sources/tree.php on line 971
  ```
In dev console the following html code appears:
```
<option value="0" disabled="disabled">Root</option><option value="16" data-parent-id="0">&nbsp;user1</option><option value="31" disabled="disabled" data-parent-id="0">&nbsp;folder3</option><option value="36" disabled="disabled" data-parent-id="31">&nbsp;&nbsp;folder4[folder3]</option>
```
It's the html code I'm expecting to appear under folders ;-)

**Comment by nilsteampassnet** [comment]
I cannot reproduce.
Would it be possible to overwrite your current TP files using latest commit.
Don't forget to run upgrade after this.

**Comment by useronkel** [comment]
Hi.
I've deleted the whole folder of teampass and reinstalled from scratch with commit [#283cbfb](https://github.com/nilsteampassnet/TeamPass/commit/283cbfb80e5026e3ae6f2716414a68bf0520f96b).
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/9173513/tp.config.php.txt)

Still no folders are listed and the loading icon spins forever. No errors or warning are in dev console neither in any logfile.
Attached my tp.config.php

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
