### ISSUE TITLE
Loading item

### ISSUE THREAD

**Issue by kolisayeed** [nilsteampassnet/TeamPass#3241]
tp.config.php

    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/TeamPass',
    'cpassman_url' => 'https://uat-pass',
    'favicon' => 'https://uat-pass/favicon.ico',
    'path_to_upload_folder' => '/var/www/TeamPass/upload',
    'path_to_files_folder' => '/var/www/TeamPass/files',
    'url_to_files_folder' => 'https://uat-pass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.18',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '1',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '1',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '1',
    'enable_email_notification_on_user_pw_change' => '1',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1653887598',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'dac-mail',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'naztech.teampass@naztech.us.com',
    'email_auth_pwd' => 'P@ssw0rd0',
    'email_port' => '587',
    'email_security' => 'tls',
    'email_server_url' => '',
    'email_from' => 'naztech.teampass@naztech.us.com',
    'email_from_name' => 'uat-pass',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '600',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Asia/Dhaka',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'nvZeb2WGhfgMDQL6XtayeUHQXLUSnjDgEcVBrwBg',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '1',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '1',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'can_create_root_folder' => '1',

PHP  Version: 8.1.2
MariaDB Version: 10.6.7

Apache error log:
[php:error] [pid 1696] [client 10.33.55.2:59841] PHP Fatal error:  Uncaught TypeError: base64_encode(): Argument #1 ($string) must be of type string, bool given in /var/www/TeamPass/sources/main.functions.php:2740\nStack trace:\n#0 /var/www/TeamPass/sources/main.functions.php(2740): base64_encode()\n#1 /var/www/TeamPass/sources/items.queries.php(2460): decryptUserObjectKey()\n#2 {main}\n  thrown in /var/www/TeamPass/sources/main.functions.php on line 2740, referer: https://uat-pass/index.php?page=items

Need help 
Thanks

**Comment by kevinsmartpm** [comment]
Hi, i an getting same error i add some more information:

![image](https://user-images.githubusercontent.com/108066583/176431314-14a806f6-887c-4dd4-a321-a109cb2bfa89.png)

Fatal error: Uncaught TypeError: base64_encode(): Argument #1 ($string) must be of type string, bool given in C:\xampp\htdocs\sources\main.functions.php:2740 Stack trace: #0 C:\xampp\htdocs\sources\main.functions.php(2740): base64_encode(false) #1 C:\xampp\htdocs\sources\items.queries.php(2460): decryptUserObjectKey('Zl4JAZg8osss1mF...', '') #2 {main} thrown in C:\xampp\htdocs\sources\main.functions.php on line 2740

Apache access log:
172.18.150.97 - - [29/Jun/2022:14:02:40 +0200] "GET /index.php?page=items HTTP/1.1" 200 382173
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/adminlte/css/adminlte.min.css HTTP/1.1" 200 1396747
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/pace-progress/themes/corner-indicator.css HTTP/1.1" 200 1799
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/select2/css/select2.min.css HTTP/1.1" 200 14983
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/fontawesome-free/css/all.css HTTP/1.1" 200 73625
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/select2/css/select2-bootstrap.min.css HTTP/1.1" 200 5159
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /includes/css/teampass.css HTTP/1.1" 200 4734
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/alertifyjs/css/alertify.min.css HTTP/1.1" 200 21412
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /includes/fonts/fonts.css HTTP/1.1" 200 1862
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/alertifyjs/css/themes/bootstrap.min.css HTTP/1.1" 200 1489
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/toastr/toastr.min.css HTTP/1.1" 200 6454
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /includes/css/ionicons.min.css HTTP/1.1" 200 51280
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/simplePassMeter/simplePassMeter.css HTTP/1.1" 200 1345
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/jstree/themes/default/style.min.css HTTP/1.1" 200 27353
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/radioforbuttons/bootstrap-buttons.min.css HTTP/1.1" 200 15611
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/icheck/skins/all.css HTTP/1.1" 200 1568
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/summernote/summernote-bs4.css HTTP/1.1" 200 23436
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css HTTP/1.1" 200 21100
172.18.150.97 - - [29/Jun/2022:14:02:41 +0200] "GET /plugins/timepicker/bootstrap-timepicker.min.css HTTP/1.1" 200 2410
172.18.150.97 - - [29/Jun/2022:14:02:42 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 6095
172.18.150.97 - - [29/Jun/2022:14:02:42 +0200] "GET /sources/tree.php?force_refresh=0 HTTP/1.1" 200 434
172.18.150.97 - - [29/Jun/2022:14:02:42 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 1911
172.18.150.97 - - [29/Jun/2022:14:02:42 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 55
172.18.150.97 - - [29/Jun/2022:14:02:42 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 175
172.18.150.97 - - [29/Jun/2022:14:02:42 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 123
172.18.150.97 - - [29/Jun/2022:14:02:43 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 251
172.18.150.97 - - [29/Jun/2022:14:02:43 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 175
172.18.150.97 - - [29/Jun/2022:14:02:44 +0200] "POST /sources/items.queries.php HTTP/1.1" 200 460
172.18.150.97 - - [29/Jun/2022:14:02:47 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 3
172.18.150.97 - - [29/Jun/2022:14:02:47 +0200] "POST /sources/main.queries.php HTTP/1.1" 200 3

un saludo

**Comment by nilsteampassnet** [comment]
New install? upgrade from 2.x?
On all items or only some?

**Comment by kevinsmartpm** [comment]
Hi, in my case is a new install.

**Comment by turekg** [comment]
I get this same error, constantly. Unusable.... Upgraded from 3.0.0.10 to 3.0.0.18

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
