### ISSUE TITLE
Uncaught TypeError: decryptUserObjectKey(): Argument #1 ($key) must be of type string, null given

### ISSUE THREAD

**Issue by BelgarathS** [nilsteampassnet/TeamPass#3245]
### Steps to reproduce
1. change users permission 
2. fails during re-encrypting

### Expected behaviour
No Error when re-encrypting data

### Actual behaviour
Tell us what happens instead
PHP Error is thrown

### Server configuration
**Operating system**:
Ubuntu 22.04 LTS

**Web server:**
apache2        2.4.52-1ubuntu4.1

**Database:**
mariadb-server 1:10.6.7-2ubuntu1

**PHP version:**
PHP 8.1.2 (cli) (built: Jun 13 2022 13:52:54) (NTS)

**Teampass version:** 
3.0.18

**Updated from an older Teampass or fresh install: updated
#### Web server error log
```
main.queries.php on line1995 and defined in /var/www/html/pass/sources/main.functions.php:2730\nStack trace:\n#0 /var/www/html/pass/sources/main.queries.php(1995): decryptUserObjectKey()\n#1 /var/www/html/pass/sources/main.queries.php(1770): continueReEncryptingUserSharekeysStep2()\n#2 /var/www/html/pass/sources/main.queries.php(397): continueReEncryptingUserSharekeys()\n#3 /var/www/html/pass/sources/main.queries.php(152): keyHandler()\n#4 /var/www/html/pass/sources/main.queries.php(74): mainQuery()\n#5 {main}\n  thrown in /var/www/html/pass/sources/main.functions.php on line 2730,
```

**Comment by maydond** [comment]
The same error for me.
In my case error is invoked after couple seconds when encrypting files (encrypting items goes OK before that).
My thought is maybe some encrypted files cause this error, maybe, after file owner was deleted from users, or something like that. When i try to download some of stored attachments, it looks like i get not the original file, but encrypted one. It takes more space than original, and is not opening correctly

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
