### ISSUE TITLE
Can´t create new Users

### ISSUE THREAD

**Issue by bpc80** [nilsteampassnet/TeamPass#3253]
### Page on which it happened
Users

### Steps to reproduce
1. +New
2.  Insert all fields
3. Push Submit

### Expected behaviour
Create new user

### Actual behaviour
the user was created in Database (table user)
when he try to encrypt the item for the new user, this error happend

[Wed Jul 13 10:38:47.993319 2022] [proxy_fcgi:error] [pid 16217] [client 192.168.241.62:63824] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: base64_encode(): Argument #1 ($string) must be of type string, bool given in /var/www/html/sources/main.functions.php:2740\nStack trace:\n#0 /var/www/html/sources/main.functions.php(2740): base64_encode()\n#1 /var/www/html/sources/main.queries.php(1903): decryptUserObjectKey()\n#2 /var/www/html/sources/main.queries.php(1757): continueReEncryptingUserSharekeysStep1()\n#3 /var/www/html/sources/main.queries.php(397): continueReEncryptingUserSharekeys()\n#4 /var/www/html/sources/main.queries.php(152): keyHandler()\n#5 /var/www/html/sources/main.queries.php(74): mainQuery()\n#6 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2740', referer: https://192.168.240.34/index.php?page=users

### Server configuration
**Operating system**: Linux barosrv15 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64

**Web server:** Apache/2.4.54 (Debian)

**Database:** 10.5.15-MariaDB-0+deb11u1

**PHP version:** 8.0.20

**Teampass version:** 3.0.0.18

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd-m-y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/html/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/html/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.18',
'ldap_mode' => '1',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '@xxxxx',
'ldap_domain_dn' => 'dc=xxxx,dc=de',
'ldap_domain_controler' => 'xxxxx',
'ldap_user_attribute' => 'samaccountname',
'ldap_ssl' => '1',
'ldap_tls' => '0',
'ldap_elusers' => '1',
'richtext' => '0',
'allow_print' => '1',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '1',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '5',
'utf8_enabled' => '1',
'restricted_to' => '1',
'restricted_to_roles' => '1',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '1',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => 'Willkommen bei der xxxxx Passwort Verwaltung',
'default_language' => 'german',
'send_stats' => '0',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '1',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => 'none',
'email_server_url' => 'https://<anonym_url>/',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '100',
'delay_item_edition' => '30',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,ini,key,pfx,crt',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip,ppk',
'upload_otherext' => 'sql,xml,ppk',
'upload_imageresize_options' => '0',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => '',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '60',
'send_stats_time' => '0',
'tree_counters' => '0',
'item_extra_fields' => '1',
'enable_attachment_encryption' => '1',
'copy_to_clipboard_small_icons' => '0',
'settings_offline_mode' => '0',
'offline_key_level' => '70',
'bck_script_filename' => 'bck_cpassman',
'bck_script_path' => '/teampass_backup',
'can_create_root_folder' => '0',
'timezone' => 'Europe/Berlin',
'menu_type' => 'context',
'duo' => '0',
'bck_script_key' => 'xxxxxxx,
'syslog_enable' => '1',
'syslog_host' => '192.168.250.18',
'syslog_port' => '514',
'google_authentication' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'saltkey_ante_2127' => 'xxxxxx',
'teampass_version' => '2.1.27',
'migration_to_2127' => 'done',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'agses_authentication_enabled' => '0',
'personal_saltkey_security_level' => '0',
'ldap_new_user_is_administrated_by' => '0',
'ldap_port' => '636',
'enable_http_request_login' => '0',
'admin_2fa_required' => '0',
'otv_is_enabled' => '0',
'ldap_and_local_authentication' => '1',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'files_with_defuse' => 'done',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'password_overview_delay' => '4',
'roles_allowed_to_print_select' => '[1]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '0',
'email_debug_level' => '0',
'ga_reset_by_user' => '',
'onthefly-backup-key' => '',
'onthefly-restore-key' => '',
'ldap_user_dn_attribute' => 'distinguishedname',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '',
'ldap_bdn' => 'DC=barolagerhaus,DC=de',
'ldap_hosts' => 'xxxxxx',
'ldap_password' => 'xxxxxx',
'ldap_username' => 'CN=xxxxxxxxx',
'api_token_duration' => '60',
'disable_show_forgot_pwd_link' => '0',
'ldap_new_user_role' => '1',

```

**Updated from an older Teampass or fresh install:**
we updated from 2.1.27.36

#### Web server error log
```
Undefined variable $post_data - /var/www/html/sources/main.queries.php (478)
```

#### Teampass 10 last system errors
```
 * 06-10-21 11:16:15 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 06-10-21 11:15:54 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 20-09-21 14:54:35 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 23-08-21 07:33:06 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 23-08-21 07:32:23 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 23-08-21 07:31:51 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 18-08-21 08:40:39 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 05-03-21 16:15:13 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 28-01-21 12:41:53 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php * 14-01-21 12:14:02 - Query: INSERT INTO `teampass_items` (`label`) VALUES ('duplicate')<br />Error: Field 'restricted_to' doesn't have a default value<br />@ /sources/items.queries.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by BenoitPel** [comment]
same pb for me

Server configuration

debian 10
apache 2.4
mariadb-server 10.3
php 7.4
version 3.0.0.17

Updated from an older Teampass

update from 2.1.27.36

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
