### ISSUE TITLE
LDAP no data to proceed message

### ISSUE THREAD

**Issue by AgentZoy** [nilsteampassnet/TeamPass#3255]
Hi
I have latest version of TeamPass installed on debian server
When I configured all options for LDAP I get message No Data to proceed
Also I cant find how to enable debug mode because there is no $debugLdap variable
_open file /sources/identify. php.
search for $debugLdap = 0; at the top of the file.
change its value from 0 to 1._

**Comment by AgentZoy** [comment]
In apache logs found
`PHP Fatal error:  Uncaught ErrorException: ldap_connect(): Could not create session handle: Bad parameter to an ldap routine in /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php:199\nStack trace:\n#0 [internal function]: LdapRecord\\Ldap->LdapRecord\\{closure}()\n#1 /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php(199): ldap_connect()\n#2 /var/www/TeamPass/includes/libraries/LdapRecord/HandlesConnection.php(171): LdapRecord\\Ldap->LdapRecord\\{closure}()\n#3 /var/www/TeamPass/includes/libraries/LdapRecord/Ldap.php(200): LdapRecord\\Ldap->executeFailableOperation()\n#4 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(166): LdapRecord\\Ldap->connect()\n#5 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(405): LdapRecord\\Connection->initialize()\n#6 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(255): LdapRecord\\Connection->auth()\n#7 /var/www/TeamPass/includes/libraries/LdapRecord/Connection.php(394): LdapRecord\\Connection->LdapRecord\\{closure}()\n#8 /var/www/TeamPass/includes/libraries in /var/www/TeamPass/includes/libraries/LdapRecord/LdapRecordException.php on line 26, referer: https://teampass.pfk.local/index.php?page=ldap
`

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
