### ISSUE TITLE
Update issue from 3.0.0.16 to 3.0.0.17 : Uncaught Error: Class 'SplClassLoader' not found

### ISSUE THREAD

**Issue by migirp** [nilsteampassnet/TeamPass#3261]
### Steps to reproduce
1. Follow the upgrade instruction to upgrade
2. The update gear never stops
3. 
![teampass_upgrade_error_01](https://user-images.githubusercontent.com/104768817/180444785-0a2ae464-d300-45b9-98d0-d8b1c92fd413.png)
4.
![teampass_upgrade_error_00](https://user-images.githubusercontent.com/104768817/180444817-a8fd9085-af75-4067-baea-92970872ec52.png)
5.
php-fpm error:
```
[22-Jul-2022 12:32:06 UTC] PHP Fatal error:  Uncaught Error: Class 'SplClassLoader' not found in /var/www/html/teampass/sources/main.functions.php:1535
Stack trace:
#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(983): prepareExchangedData()
#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(225): meekrodb_error_handler()
#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(195): MeekroDB->nonSQLError()
#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(648): MeekroDB->get()
#4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#5 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#6 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()
#7 /var/www/html/teampass/sources/main.functions.php(2066): DB::query()
#8 /var/www/html/teampass/install/upgrade_ajax.php(924): handleConfigFile()
#9 {main}
  thrown in /var/www/html/teampass/sources/main.functions.php on line 1535
```

### Server configuration
**Operating system**: Alma linux 8.6
**Web server:** Apache/2.4.37 (AlmaLinux)
**Database:** : MariaDB
**PHP version:**
```
[root@xxx teampass]# php-fpm --version
PHP 7.4.30 (fpm-fcgi) (built: Jun  7 2022 08:38:19)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies
```
**Teampass version:** 3.0.0.16 to 3.0.0.17

**Teampass configuration file:**
```
'cpassman_dir' => '/var/www/html/teampass',`
```

```
[root@xxx teampass]# ls -al /var/www/html/teampass/sources/SplClassLoader.php
-rw-rw-r--. 1 root root 4069 22 juil. 14:15 /var/www/html/teampass/sources/SplClassLoader.php
```

### Client configuration
**Browser:** Firefox on windows

**Comment by useronkel** [comment]
Upgrade to 3.0.0.18, there is a fix for it

**Comment by migirp** [comment]
The latest release on github is 3.0.0.17. When do you think 3.0.0.18 will be out ?
Thanks.

**Comment by useronkel** [comment]
Latest commit is 3.0.0.18 2 days ago:
![image](https://user-images.githubusercontent.com/14745069/181846547-247f97ec-8c27-4c58-91b5-f57916375534.png)

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
