### ISSUE TITLE
Error: Malformed UTF-8 data after create folder

### ISSUE THREAD

**Issue by samansohani78** [nilsteampassnet/TeamPass#3277]
### Steps to reproduce
1. login with admin
2. create folder
3.

### Expected behaviour
Next error occurred
Error: Malformed UTF-8 data

### Actual behaviour
Next error occurred
Error: Malformed UTF-8 data

### Server configuration
**Operating system**:
ubuntu 22.04

**Web server:**
nginx

**Database:**
mariadb 10.8
**PHP version:**
8.1.9
**Teampass version:** 
3.0.0.18
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
firefox
**Operating system:**

#### Web server error log
```
[08-Aug-2022 12:22:36 UTC] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'categories' doesn't have a default value in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php:682
Stack trace:
#0 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 [internal function]: MeekroDB->queryHelper()
#2 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): call_user_func_array()
#3 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#4 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()
#5 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()
#6 [internal function]: MeekroDB->insert()
#7 /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): call_user_func_array()
#8 /var/www/teampass/sources/folders.queries.php(683): DB::insert()
#9 {main}
  thrown in /var/www/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Error: Malformed UTF-8 data

Object { title: "sa", parentId: 0, complexity: 60, accessRight: "W", renewalPeriod: 12, addRestriction: 0, editRestriction: 0, icon: "", iconSelected: "" }
​
accessRight: "W"
​
addRestriction: 0
​
complexity: 60
​
editRestriction: 0
​
icon: ""
​
iconSelected: ""
​
parentId: 0
​
renewalPeriod: 12
​
title: "sa"
​
<prototype>: Object { … }
[index.php:2574:21](https://pass.dsadsdad.me/index.php?page=folders)
false [index.php:2585:29](https://pass.dasdda.me/index.php?page=folders)
Object { error: false, message: "", matrix: [], user_is_admin: 1, user_can_create_root_folder: 1, fullComplexity: (5) […] }
​
error: false
​
fullComplexity: Array(5) [ {…}, {…}, {…}, … ]
​
matrix: Array []
​
message: ""
​
user_can_create_root_folder: 1
​
user_is_admin: 1
​
<prototype>: Object { … }
[index.php:2770:25](https://pass.dasdasdasd.me/index.php?page=folders)
Object { error: false, subfolders: (1) […] }
​
error: false
​
subfolders: Array [ {…} ]
​
<prototype>: Object { … }
```

**Comment by jesusmanuel22** [comment]
Hi! I had the same problem!
I used the[ 3.0.0.17](https://github.com/nilsteampassnet/TeamPass/releases/tag/3.0.0.17) release version and it works!! Do you need 3.0.0.18 version? If you want, you can try [with this version 3.0.0.17](https://github.com/nilsteampassnet/TeamPass/releases/tag/3.0.0.17)

**Comment by alozano-sct** [comment]
Hi! I had the samen problem when i tried to Synchronize Ldap users.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
