### ISSUE TITLE
Console error when accessing profile page

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3279]
When accessing the profile page (admin), I get the following console error and the page stop working:
Commit: [#83294ac](https://github.com/nilsteampassnet/TeamPass/commit/83294ac828520256e93f7f23e50c684e657af048)
```
Uncaught TypeError: document.getElementById(...) is null
    _init https://example.com/includes/libraries/csrfp/js/csrfprotector.js:133
    csrfprotector_init https://example.com/includes/libraries/csrfp/js/csrfprotector.js:162
    <anonymous> https://example.com/includes/libraries/csrfp/js/csrfprotector.js:345
    EventListener.handleEvent* https://example.com/includes/libraries/csrfp/js/csrfprotector.js:344
csrfprotector.js:133:31
    _init https://example.com/includes/libraries/csrfp/js/csrfprotector.js:133
    csrfprotector_init https://example.com/includes/libraries/csrfp/js/csrfprotector.js:162
    <anonym> https://example.com/includes/libraries/csrfp/js/csrfprotector.js:345
    (Async: EventListener.handleEvent)
    <anonym> https://example.com/includes/libraries/csrfp/js/csrfprotector.js:344
```
The ID CSRFP_FIELD_TOKEN_NAME is not found...

**Comment by useronkel** [comment]
Also the error of
```
Next error occurred
Error: Malformed UTF-8 data
```
is also present, when I'm trying to use the LDAP Synchronization and add users from the ldap.
An error in users.queries.php appears with internal command
```
{
	"type": "get_list_of_users_in_ldap",
	"key": "somecrypticalphanumerics"
}

Fatal error: Uncaught ErrorException: ldap_search(): Search: Invalid DN syntax in /var/example.org/includes/libraries/LdapRecord/Ldap.php:235
Stack trace: #0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}()
#1 /var/example.org/includes/libraries/LdapRecord/Ldap.php(235): ldap_search()
#2 /var/example.org/includes/libraries/LdapRecord/HandlesConnection.php(171): LdapRecord\Ldap->LdapRecord\{closure}()
# #3 /var/example.org/includes/libraries/LdapRecord/Ldap.php(237): LdapRecord\Ldap->executeFailableOperation()
# #4 /var/example.org/includes/libraries/LdapRecord/Query/Builder.php(656): LdapRecord\Ldap->search()
#5 /var/example.org/includes/libraries/LdapRecord/Connection.php(394): LdapRecord\Query\Builder->LdapRecord\Query\{closure}()
# #6 /var/example.org/includes/libraries/LdapRecord/Connection.php(352): LdapRecord\Connection->runOperationCallback()
#7 /var/example.org/includes/libraries/Ld in /var/example.org/includes/libraries/LdapRecord/LdapRecordException.php on line 26
 ```
This is a similar error to 
Fixed it with changing line 2480 in sources/users.queries.php
```
 from: ->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true && empty($SETTINGS['ldap_dn_additional_user_dn'] === false) ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
 
 to: ->in((isset($SETTINGS['ldap_dn_additional_user_dn']) === true && !empty($SETTINGS['ldap_dn_additional_user_dn']) ? $SETTINGS['ldap_dn_additional_user_dn'].',' : '').$SETTINGS['ldap_bdn'])
 ```
 Similar to https://github.com/nilsteampassnet/TeamPass/issues/3258#issuecomment-1191619167

**Comment by useronkel** [comment]
Still not fixed

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
