### ISSUE TITLE
Can't update items in the latest 3.x version

### ISSUE THREAD

**Issue by BelgarathS** [nilsteampassnet/TeamPass#3282]
### Steps to reproduce
1.log in to the latest 3.0 code
2.try to edit any password
3.error message "At least one folder needs to be selected" - folder dropdown on detaisl page is empty and nopthing can be found

### Expected behaviour
you should be able to save changes

### Actual behaviour
changes can't be saved

### Server configuration
**Operating system**:
ubuntu 22.04

**Web server:**
2.4.52-1ubuntu4.1

**Database:**
mariadb 1:10.6.7-2ubuntu1.1

**PHP version:**
PHP 8.1.2

**Teampass version:** 
latest git 3.x branch

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
updated

### Client configuration
**Browser:**
Chrome Version 104.0.5112.79 (Official Build) (64-bit)
**Operating system:**
Ubuntu 22.04

#### Web server error log
Uncaught mysqli_sql_exception: Unknown column 'visible_folders' in 'field list' in /var/www/html/pass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/pass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/pass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/pass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/pass/includes/libraries/Database/Meekrodb/db.class.php(753): MeekroDB->query()\n#4 /var/www/html/pass/includes/libraries/Database/Meekrodb/db.class.php(66): MeekroDB->queryFirstRow()\n#5 /var/www/html/pass/sources/main.functions.php(3597): DB::queryFirstRow()\n#6 /var/www/html/pass/sources/items.queries.php(5947): loadFoldersListByCache()\n#7 {main}\n  thrown in /var/www/html/pass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: https://banda.pl/pass/index.php?page=items

#### Log from the web-browser developer console (CTRL + SHIFT + i)
N/A
Insert the log here and especially the answer of the query that failed.
N/A

**Comment by R0Wi** [comment]
Had the same problem. I did the following to **reproduce the issue:**

1. Create two folders `test1` and `test2`. Create a new role `testrole` and apply the folders `test1` and `test2` with write-permissions
2. Create a new user and add the "Default" group. Do not add any "Allowed folders" or "Denied folders"
3. Login with the newly created user (who does not have any permission on any folders. I get an error via UI popup:
```
Warning: Undefined array key "folders" in /var/www/html/teampass/sources/items.queries.php on line 6172
```
4.Close the popup and change the password as requested. You will then be presented with an "empty" UI
5. Add the role `testrole` to the newly created user via admin login
6. Refresh the page with the newly created user. You will see the two folders on the lefthand-side
7. Click on "New item". Inside the tab "Details" the folder listing will be empty. Logout and new login won't help.

**My current workaround:**
1. Logout with your non-admin-user
2. Clear your users cache entry inside `teampass_cache_tree` ( `DELETE FROM teampass_cache_tree WHERE user_id = ?` )
3. Login again. Folders are now correctly displayed inside the tree AND in the "Details" page of the "New item"-Dialog

So to me it looks like there is a problem with the tree-caching but I cannot narrow it further.

**Comment by BelgarathS** [comment]
@R0Wi This does not seem to be the same issue (however it is very related) as in my case the database field was missing completely, i.e change to database schema was required to address that.

**Comment by ozturkinc** [comment]
If you have special characters in your folder names, remove them. I had an "&" in one of my folder names and I think it was causing issues.

Once these characters are removed. Log out from teampass and clear the teampass_cache_tree (I suggest all of it). When you log back in it should be fine, if it was the same problem I was experiencing.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
