### ISSUE TITLE
SQL Error when loading password page as user

### ISSUE THREAD

**Issue by gmyx** [nilsteampassnet/TeamPass#3288]
### Steps to reproduce
1. New Install on Azure Ubuntu 22.2
2. Login as user

### Expected behaviour
See password / folder list

### Actual behaviour
Password / Folder list does not load, stays on Loading Data...

### Server configuration
**Operating system**:
Azure Ubuntu 22.2

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
8.1.9

**Teampass version:** 
Latest commit as of last week

#### Web server error log
```
[Mon Aug 22 14:38:42.849029 2022] [php:error] [pid 868] [client 198.103.167.20:55594] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'visible_folders' doesn't have a default value in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:682
Stack trace:
#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()
#4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()
#5 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()
#6 /var/www/html/teampass/sources/main.functions.php(3500): DB::insert()
#7 /var/www/html/teampass/sources/items.queries.php(6067): cacheTreeUserHandler()
#8 {main}
  thrown in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682, referer: http://gcdocs-teamppass-test.eastus.cloudapp.azure.com/teampass/index.php?page=items
```

**Comment by gmyx** [comment]
Might be related to #3264

**Comment by nilsteampassnet** [comment]
I don't understand why I don't have those errors on my test environment.
I will provide a fix and try to understand why such errors are not shown in my logs.

**Comment by gmyx** [comment]
I pulled the latest commit and now it works. Thanks!
