### ISSUE TITLE
Error when creating new users or changing a password for an existent user, after upgrade from 2.1.27.36 to 3.0.0.19

### ISSUE THREAD

**Issue by r4munoz** [nilsteampassnet/TeamPass#3332]
[teampass.atlas.local-1663775958951.log](https://github.com/nilsteampassnet/TeamPass/files/9618655/teampass.atlas.local-1663775958951.log)
[error.log](https://github.com/nilsteampassnet/TeamPass/files/9618657/error.log)
 
### Steps to reproduce
1. We made an upgrade from 2.1.27.36 to 3.0.0.19 acording the upgrade manual.
2. After the upgrade, some users are not capable to enter whit their previous credentials.
3. We have changed their passwords as an admin, but we receive the following error:

Uncaught TypeError: base64_encode() expects parameter 1 to be string, bool given in /var/www/html/teampass3/sources/main.functions.php:2759 Stack trace: #0 /var/www/html/teampass3/sources/main.functions.php(2759): base64_encode() #1 /var/www/html/teampass3/sources/main.queries.php(2049): decryptUserObjectKey() #2 /var/www/html/teampass3/sources/main.queries.php(1903): continueReEncryptingUserSharekeysStep1() #3 /var/www/html/teampass3/sources/main.queries.php(462): continueReEncryptingUserSharekeys() #4 /var/www/html/teampass3/sources/main.queries.php(154): keyHandler() #5 /var/www/html/teampass3/sources/main.queries.php(76): mainQuery() #6 {main} thrown in /var/www/html/teampass3/sources/main.functions.php on line 2759

4. We have reimported the teampass_users table data from a backup, but it remains the same and users are not capable to get into the system.

### Expected behaviour
Tell us what should happen
A previous existent user must enter normally to the system with their credentials after upgrading to 3.0.0.19
A succesfully new password creation for a user in the backend as an admin 
A succesfully new user creation from backend as an admin

### Actual behaviour
Tell us what happens instead
A previous user is not capable to get into Teampass with their credentials after the upgrade
Instead of creating a new user or asigning a new ecrypted password for an existent user, we receive a base64_encode error as mentioned above.

### Server configuration
**Operating system**:
Ubuntu 20.04.5

**Web server:**
Apache 2.4.41

**Database:**
MySQL 8.0.30

**PHP version:**
PHP 7.4.30

**Teampass version:** 
3.0.0.19

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
**<?php**
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass3',
    'cpassman_url' => 'https://teampass.atlas.local',
    'favicon' => 'https://teampass.atlas.local/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass3/upload',
    'path_to_files_folder' => '/var/www/html/teampass3/files',
    'url_to_files_folder' => 'https://teampass.atlas.local/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.19',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '10',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'spanish',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1661130320',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '60',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '600',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass3/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'America/Santo_Domingo',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'dvywHDF......', (Trunkated passkey on purpose)
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '[9]',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '1',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'enable_tasks_manager' => '0',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'max_last_items' => '10',
    'can_create_root_folder' => '1',
);

### Client configuration
**Browser:**
_Firefox (last), Google Chrome (last)_

**Operating system:**
_Windows 10, Windows Server 2019 and Ubuntu 20.04.5 LTS Workstation with GUI_

#### Web server error log
_error.log as an attachment_
```
#### Log from the web-browser developer console (CTRL + SHIFT + i)
_DevTools log as an attachment_
```
**Insert the log here and especially the answer of the query that failed.**
_Aparently Folders, roles and users seems to be as non existent items, even when they appear on tables and GUI._
```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
