### ISSUE TITLE
2.1.27 to 3.0.20 personnal folder: Encrypting keys [0 - 100] ... Merci de patienter ! Infinite

### ISSUE THREAD

**Issue by ArnOCP** [nilsteampassnet/TeamPass#3347]
### Steps to reproduce
1. After migrating 2.1.27 to 3.0.0.20 -> OK
2. Connect to user -> OK
3. Try to view the personnals items -> NOK

### Expected behaviour
I could see the personnals items

### Actual behaviour
The process of Encrypting keys still work for long time infinitively without success

### Server configuration
**Operating system**: Windows Server 2016

**Web server:** IIS

**Database:** MySQL 8.0.27

**PHP version:** 7.4.30

**Teampass version:**  3.0.0.20

**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/9674567/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** 
Updated from 2.1.27 to 3.0.0.20

### Client configuration
**Browser:** Firefox 102.3.0esr

**Operating system:** Windows 10 20H2

#### Web server error log
```
[php_errors.log](https://github.com/nilsteampassnet/TeamPass/files/9674577/php_errors.log)

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by futureweb** [comment]
Unfortunately also our installation won't access personal folders anymore after upgrade to latest 3.x Version

Error Log:
`[Tue Oct 04 09:47:49.580445 2022] [php7:error] [pid 3427] [client 62.99.238.122:55899] PHP Fatal error:  Uncaught Error: Call to a member function unlockKey() on string in /var/www/pw/html/sources/main.functions.php:282\nStack trace:\n#0 /var/www/pw/html/sources/main.queries.php(2549): defuse_validate_personal_key()\n#1 /var/www/pw/html/sources/main.queries.php(475): migrateTo3_DoUserPersonalItemsEncryption()\n#2 /var/www/pw/html/sources/main.queries.php(154): keyHandler()\n#3 /var/www/pw/html/sources/main.queries.php(76): mainQuery()\n#4 {main}\n  thrown in /var/www/pw/html/sources/main.functions.php on line 282, referer: https://mydom.tld/index.php?page=items`

**Comment by ServiceMRE** [comment]
Same problem here

**Comment by futureweb** [comment]
anyone any idea on this? As my Colleagues need to access their Personal Folders urgently ... otherwise I need to downgrade back to old 2.x Version Backup again which I really would like to prevent ...

**Comment by ServiceMRE** [comment]
In the file /source/main.functions.php, line 282:

replace :
```
    try {
        $user_key = $protected_key_encoded->unlockKey($psk);
        $user_key_encoded = $user_key->saveToAsciiSafeString();
```

by:
```
    try {
        $protected_key_encoded = \Defuse\Crypto\KeyProtectedByPassword::loadFromAsciiSafeString($protected_key_encoded);
        $user_key = $protected_key_encoded->unlockKey($psk);
        $user_key_encoded = $user_key->saveToAsciiSafeString();
```

**Comment by ArnOCP** [comment]
> In the file /source/main.functions.php, line 282:
> 
> replace :
> 
> ```
>     try {
>         $user_key = $protected_key_encoded->unlockKey($psk);
>         $user_key_encoded = $user_key->saveToAsciiSafeString();
> ```
> 
> by:
> 
> ```
>     try {
>         $protected_key_encoded = \Defuse\Crypto\KeyProtectedByPassword::loadFromAsciiSafeString($protected_key_encoded);
>         $user_key = $protected_key_encoded->unlockKey($psk);
>         $user_key_encoded = $user_key->saveToAsciiSafeString();
> ```

Thanks a lot it's work for me.
