### ISSUE TITLE
API Access to folders gives error

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3389]
Teampass 3.0.0.20, commit f1e8823
Authorization works. Using the bearer token with a request like
https://teampass.example.org/api/index.php/item/inFolders?folders={19}
Gives the following error:
```
Fatal error: Uncaught Exception: 
Unable to do prepared statement: SELECT id, label, description, pw, url, id_tree, login, email, viewed_no, fa_icon, inactif, perso FROM teampass_items WHERE id_tree IN () ORDER BY id ASC in /base_path/api/Model/Database.php:50
Stack trace:
#0 /base_path/api/Model/ItemModel.php(47): Database->select()
#1 /base_path/api/Controller/Api/ItemController.php(79): ItemModel->getItems()
#2 /base_path/api/inc/bootstrap.php(57): ItemController->inFoldersAction()
#3 /base_path/api/index.php(88): itemAction()
#4 {main} thrown in /base_path/api/Model/Database.php on line 50
```
API still in progress? :-)

**Comment by nilsteampassnet** [comment]
Yes in progress when I have time

**Comment by nilsteampassnet** [comment]
Typo error in the documentation.

Don't use {} to delimit the array of folders but []

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
