### ISSUE TITLE
Moving DB to new server 3.0.0.17

### ISSUE THREAD

**Issue by dwagnereh** [nilsteampassnet/TeamPass#3391]
### Steps to reproduce
1. install new server same version
2. go through setup as normal
3. backup old server
4. restore backup to new server
5. error is generated

### Expected behaviour
DB restore should process correctly

### Actual behaviour
Error displayed:
[{"result":"db_restore" , "message":"Defuse\Crypto\Exception\IOException: Could not read from the file in /srv/www/htdocs/teampass/includes/libraries/Encryption/Encryption/File.php:708 Stack trace: #0 /srv/www/htdocs/teampass/includes/libraries/Encryption/Encryption/File.php(479): Defuse\Crypto\File::readBytes() #1 /srv/www/htdocs/teampass/includes/libraries/Encryption/Encryption/File.php(298): Defuse\Crypto\File::decryptResourceInternal() #2 /srv/www/htdocs/teampass/includes/libraries/Encryption/Encryption/File.php(89): Defuse\Crypto\File::decryptFileInternal() #3 /srv/www/htdocs/teampass/sources/main.functions.php(2323): Defuse\Crypto\File::decryptFileWithPassword() #4 /srv/www/htdocs/teampass/sources/main.functions.php(2230): defuseFileDecrypt() #5 /srv/www/htdocs/teampass/sources/backups.queries.php(288): prepareFileWithDefuse() #6 {main}"}]

### Server configuration
**Operating system**: OpenSuse 15.3

**Web server:** Apache2

**Database:** mysql

**PHP version:**

**Teampass version:** 3.0.0.17

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** chrome

**Operating system:** windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/9912919/tp.config.php.txt)

[error_log.log](https://github.com/nilsteampassnet/TeamPass/files/9912928/error_log.log)
[mysqld.log](https://github.com/nilsteampassnet/TeamPass/files/9912932/mysqld.log)

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
