### ISSUE TITLE
Select users from specific LDAP groups

### ISSUE THREAD

**Issue by valterseu** [nilsteampassnet/TeamPass#3402]
Hello, 
I would like to know if is it possible to bring back the option to specify from what LDAP groups to select users if there are many LDAP groups to select from the specific ones. 

The issue is that LDAP fetches all of them and the systems allow only 1000 entries and on refresh, it only refreshes 1000 entries

Thanks.

**Comment by jvalters** [comment]
Hello, sorry for double post, but is there any news?

**Comment by marcosasjr** [comment]
i use a version 2.1.27.36 and use this function.
Update to Teampass 3.0.0.21 and this funtion not exist, any idea?

**Comment by jvalters** [comment]
Either they have forgotten about it or have removed :(

**Comment by Surekreal** [comment]
Any one have working TeamPass 3.0.x with working AD login ?

**Comment by jvalters** [comment]
I got it working, but since I have over 1000 accounts ( Printers/Servers/Devices, etc) then I cannot load users as users are after 1000, but AD default output on request is 1000 when I do a second request it fetches the same, that is why it is needed to add filters to TeamPass to fetch from Group or Groups specify only. As I understood in the past it was, but then for some unknown reason in development got removed as @nilsteampassnet isn't adding them back or providing a temporary hotfix/workaround for this. I think that this is a great project and can become something large and I would like to support this project by donating, but if nobody is listening to user Payne then there is no motivation for that :(

**Comment by nilsteampassnet** [comment]
Hum ... I do my best to handle this project to satisfy a lot of users, working night and off days freely, only for my own personal satisfaction to help people in something I trust. Keep in mind, there is no "they" but only one "he" ...
Just for your information branch 3.x is not based upon branch 2.x. It is a complete project from scratch using new libraries and yes this new branch has not yet all features previous one has. 
I will try to take time to add ad group search ...

**Comment by jvalters** [comment]
Hello, @nilsteampassnet thank you for your response. It doesn't work like expected have tried for several hours also if there are a lot of users also, could you please try to find the time? And once that all works I would like to donate and if you would like I would like to also invest my free time and create proper rocker images for Teampass to be able to grow. I have images ready Just need to update a few things Alpinae and Ubuntu based

**Comment by jvalters** [comment]
@nilsteampassnet  Checked there are service accounts that are like users and over 1000 users.

**Comment by Surekreal** [comment]
> Hum ... I do my best to handle this project to satisfy a lot of users, working night and off days freely, only for my own personal satisfaction to help people in something I trust. Keep in mind, there is no "they" but only one "he" ... Just for your information branch 3.x is not based upon branch 2.x. It is a complete project from scratch using new libraries and yes this new branch has not yet all features previous one has. But in current version, you can specify the groups you want to search in, and also a user object filter. ![image](https://user-images.githubusercontent.com/1197546/211551824-1f3b82e5-522b-4ae6-973b-bc9a67518739.png) Using those 2 fields, I believe it should be ok but perhaps have you more than 1000 real users in your AD which indeed would be a problem, you confirm?

So this field "User Object Filter" is for querying users that i actually want to have in TeamPass users right ?
I asked is AD/LDAP sync is working becouse i have error with this plugin. I have no problem when i do ldapsearch from host with TeamPass installed.

**Comment by jvalters** [comment]
It is working, but needs the filters to have a properly working not search all AD, but specific user group/groups if you search all AD and have too much then you will have an issue

**Comment by hoanbc** [comment]
Hello. 
I have same issue with user object filter. LDAP synchronization success but it show me all user in Active Directory (include user/group/computer)

![image](https://user-images.githubusercontent.com/26288807/211845749-47dc973e-9455-4fb6-aa6b-78f617b0f57f.png)

**Comment by jvalters** [comment]
@hoanbc  that is why we need @nilsteampassnet to find some time to add the filter, to filter the AD groups ( So that the solution doesn't search all AD and is limited to 1000 records), but it searches inside the specific groups. Hope, that @nilsteampassnet  will find the time soon, as once that is fixed I want to contribute to the project by donating and also by creating and maintaining Docker images.

**Comment by nilsteampassnet** [comment]
Started to work on and find out this case.

**Comment by Surekreal** [comment]
> 

I have configured LDAP block like this, test user FROM Security Group from AD works fine i see on tcpdump traffic so it works. 
But still i have problem with synchronization of users from Security Group (or whole AD) i have more than 1000 users is this the case ? Maybe we can help you @nilsteampassnet in some way to make this filter ?

I love your project, i used in other comapany but there i had less users ;-)

**Comment by jvalters** [comment]
> > 
> 
> 
> 
> I have configured LDAP block like this, test user FROM Security Group from AD works fine i see on tcpdump traffic so it works. 
> 
> But still i have problem with synchronization of users from Security Group (or whole AD) i have more than 1000 users is this the case ? Maybe we can help you @nilsteampassnet in some way to make this filter ?
> 
> 
> 
> When i try to login with user from Security Group from (User Object Filter) i don't even see any traffic to domain controler ... 
> 
> 
> 
> I love your project Nil, I used it in other comapany but there I had less users ;-)

I would suggest reading all comments before posting as @nilsteampassnet is already working on it!

**Comment by nilsteampassnet** [comment]
Did some changes in the code while clicking button "list users" in Users page > LDAP
![image](https://user-images.githubusercontent.com/1197546/212530137-a7b95404-c857-4fe4-b022-ea962edd8121.png)
It is not a fix but should force more AD objects to be parsed.
Please come back if this changes something as I cannot test with such big amount of objects.
If it is, I will have to optimize the code to provide the fix.

**Comment by nilsteampassnet** [comment]
I think the limitation for 1000 AD items doesn't come from Teampass.
Please check #3464
It seems an option in AD has to be set to higher this number.

**Comment by jvalters** [comment]
Many users have more than 1000 Users in AD which is why we need the group filter

**Comment by marcosasjr** [comment]
> I think the limitation for 1000 AD items doesn't come from Teampass. Please check #3464 It seems an option in AD has to be set to higher this number.

Thanks for the great support @nilsteampassnet .
Regarding the filter by group, the following is an example of how it occurs in version 2.1.27.36.

The AD has more than 2000 registered users, but a user group is created in the AD, example: Teampass-users, and only the users of the ad that are in this group are that the system finds and can log in.
Any user outside this AD group the system does not find and does not allow to perform login.

Here's the print:
![2023-01-16-84](https://user-images.githubusercontent.com/120220165/212689737-50659221-1eba-4f58-835e-a4d7566153a0.png)

**Comment by MCaceresA** [comment]
I'm try to set MaxPageSize to 2000 with ntdsutil and doesn't work,

in my case only list 600 items (Users/computer/groups) and dont apply configuration set in ser LDAP\Object Filter

**Comment by jvalters** [comment]
> I'm try to set MaxPageSize to 2000 with ntdsutil and doesn't work,
> 
> in my case only list 600 items (Users/computer/groups) and dont apply configuration set in ser LDAP\Object Filter

Please read the comments before you post. As that is why the group filter is needed.

**Comment by nilsteampassnet** [comment]
@jvalters 
I did a change by allowing a rawquery taking into account the parameter "User Object Filter" in a good way.
It requires to get adapted by removing the (& at begining as it was the case previously.

![image](https://user-images.githubusercontent.com/1197546/218250020-4233793f-e5b3-45c0-8025-f2ae7dd3c790.png)

Can you please give a try?

**Comment by MCaceresA** [comment]
> @jvalters I did a change by allowing a rawquery taking into account the parameter "User Object Filter" in a good way. It requires to get adapted by removing the (& at begining as it was the case previously.
> 
> ![image](https://user-images.githubusercontent.com/1197546/218250020-4233793f-e5b3-45c0-8025-f2ae7dd3c790.png)
> 
> Can you please give a try?

Hi Nils y tri to update from 3.0.22 to 3.0.23 to check this correction, however went i remove install folder to try appear this error en log:

[Tue Feb 14 15:44:03.304171 2023] [php:error] [pid 2924] [client 10.212.134.156:5045] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'nb_items_in_folder' in 'field list' in /var/www/html/TeamPass/includes/libraries/Tree/NestedTree/NestedTree.php:381\nStack trace:\n#0 /var/www/html/TeamPass/includes/libraries/Tree/NestedTree/NestedTree.php(381): mysqli_query()\n#1 /var/www/html/TeamPass/includes/libraries/Tree/NestedTree/NestedTree.php(414): Tree\\NestedTree\\NestedTree->getTreeWithChildren()\n#2 /var/www/html/TeamPass/sources/main.functions.php(503): Tree\\NestedTree\\NestedTree->rebuild()\n#3 /var/www/html/TeamPass/sources/main.functions.php(417): identAdmin()\n#4 /var/www/html/TeamPass/sources/core.php(452): identifyUserRights()\n#5 /var/www/html/TeamPass/index.php(111): require_once('...')\n#6 {main}\n  thrown in /var/www/html/TeamPass/includes/libraries/Tree/NestedTree/NestedTree.php on line 381, referer: https://teampass_bk.gp.com/index.php

**Comment by jvalters** [comment]
> @jvalters I did a change by allowing a rawquery taking into account the parameter "User Object Filter" in a good way. It requires to get adapted by removing the (& at begining as it was the case previously.
> 
> ![image](https://user-images.githubusercontent.com/1197546/218250020-4233793f-e5b3-45c0-8025-f2ae7dd3c790.png)
> 
> Can you please give a try?

Hello @nilsteampassnet , I tried, but I don't know why it now started creating "Honey Tokens" and with ((ObjectCategory=person)(sAMAccountName=*)(|(memberOf=group_name)) it didn't work. Or I wrote it wrong?

Please let me know 

Thanks.

**Comment by nilsteampassnet** [comment]
@jvalters 
i don't know on what object of your AD you want to query.
So the query needs to be adapted to the AD object structure.

**Comment by jvalters** [comment]
> @jvalters 
> 
> I don't know on what object of your AD you want to query.
> 
> So the query needs to be adapted to the AD object structure.

I tried with all possible Oject, that I use in Different systems, but the output is the same for my user when doing a test on the Ldap configuration page it shows user found, but when I go to Users > Ldap_sync it loads forever

I use LDAP in Grafana/Zabbix and etc

**Comment by jvalters** [comment]
Hello again. My apologies @nilsteampassnet  after playing around and doing several types of configuration entries I got it working. Thank you very much. Now I can get users, and add them, and also if a user changes the password it automatically changes in Teampass that all is nice. Would be nice to add some more automation in the future for users with groups that can log in to the system and their accounts are automatically created ( Grafana style ) and they get access to folders based on Group assigned to folders, but that is something that you could consider in the future ( maybe I will create a separate ticket for that ). 

But as you have kept your promise, @nilsteampassnet  I'm also keeping mine and do what I mentioned in the ticket. Thank you very much.

I guess this ticket can be closed.

**Comment by hoanbc** [comment]
> 

hi @jvalters , please post example your filter.

**Comment by madcoda9000** [comment]
Hello @jvalters could please post the filter you're using. I am interested in that too. As we have m,ore than 19000 objects

many thanks
sascha

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
