### ISSUE TITLE
the user's password cannot be changed

### ISSUE THREAD

**Issue by wease1** [nilsteampassnet/TeamPass#3468]
### Page on which it happened
index.php?page=users

### Steps to reproduce
1. Reset user password
2. click button Launch
3. wait for reset

### Expected behaviour
resetting the user's password and sending it to the mail

### Actual behaviour
the process stopped at a moment:

Encrypting keys - Logs [0 - 100] ... Please wait!
![image](https://user-images.githubusercontent.com/12623112/211182262-387f218d-8bb4-4aa6-8ac5-8a5ed42afc0d.png)

### Server configuration
**Operating system**: Linux pass 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64

**Web server:** Apache/2.4.54 (Debian)

**Database:** 5.5.5-10.5.15-MariaDB-0+deb11u1-log

**PHP version:** 7.4.33

**Teampass version:** 3.0.0.16

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '0',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd-M-Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '0',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/pass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/var/www/pass/upload',
'url_to_upload_folder' => 'https://<anonym_url>/upload',
'path_to_files_folder' => '/var/www/pass/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.16',
'ldap_mode' => '0',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'sAMAccountName',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '["1"]',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;cb_select_all;',
'send_stats_time' => '1512900881',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '0',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '20mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '1000',
'upload_imageresize_height' => '900',
'upload_imageresize_quality' => '99',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '1',
'default_session_expiration_time' => '600',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/pass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Europe',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'max_last_items' => '20',
'enable_massive_move_delete' => '0',
'copy_to_clipboard_small_icons' => '1',
'offline_key_level' => '25',
'bck_script_passkey' => '<removed>'
'teampass_version' => '2.1.27',
'ldap_port' => '389',
'enable_http_request_login' => '0',
'admin_2fa_required' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'password_overview_delay' => '9',
'roles_allowed_to_print_select' => '[1]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'email_debug_level' => '0',
'maintenance_mode' => '0',
'ldap_hosts' => 'na',
'ldap_bdn' => 'ou=na, cn=na,dc=na,dc=na',
'ldap_username' => 'na',
'ldap_password' => 'na',
'ldap_dn_additional_user_dn' => 'ou=na; cn=na',
'duo_ikey' => 'Admin',
'ldap_new_user_role' => '10',

```

**Updated from an older Teampass or fresh install:**
Update from 2.1.27.11

### Client configuration

**Browser:** Chrome - 93.0.4577.63

**Operating system:** Windows Server 2008 R2 / 7 - 64bits

### Logs

[mysqlLOG.zip](https://github.com/nilsteampassnet/TeamPass/files/10367799/mysqlLOG.zip)

#### Web server error log
```
Undefined index: path - /var/www/pass/sources/main.queries.php (1106)
```

#### Teampass 10 last system errors
```
                  144 Query    SELECT share_key, increment_id
            FROM dbpass_sharekeys_items
            WHERE object_id = 2392 AND user_id = 1
                   144 Query    INSERT INTO `dbpass_sharekeys_items` (`object_id`,`user_id`,`share_key`) VALUES (2392, 10000087, 'Yn9VAmOt8HgSt23Mc0pSEnaDKFTzk+ieKMfDT87Zdwd4ZflvF9DUJHypKPINST8e/L7YAFUAYLGtHKYVBkxr3bHLBCtio1tOGDQ4ovGd39OhdP1LsD327SzjEgWONV8eRx/hmaESx9qtV4hEXDENgJBKeC2F3xKwcbVK921q4P/LXqiyZPPCzgQMpJoVX45PoQNQw0tPmsSmK4S9HWC/ImLWUNbYgWNSQ11SNoRWg1/qdSRfuUWIFMKBOxxcqxlW1cl7diCs53bsw46cvozIsroO2KlW+7cr98WWQya41HOdnvf55BsGBQJ+EYM0Tb8BxZm7g85P8JJHucUFnw3VeoybNIDORayOD73Edqd7ae6yv3yUMDJZjT8gg8tuBxemT3My6kfuki1euIE+438j3RK1+w0Ydfp9wFo8sW4GRLjnVIpFWcGSN/WPhqevDLv8boKcjPdoes+Ws7LF5Pckm4VC7nkXSVe3q0cqeNFWq87aFTh2rgdYgGDLE6YsxwJf1VMhExFmK1YkJoBV/rIiX0EAfB85FqX29qEgpUoZRGi52PaLAzjcV9gtNHEgUGG2diOkcVJJg30NuH+m6XaN3SURjdvk5V6vCWF0mhWNUHks+I5ZmgCMbE5IKgtVop2UkCuButdNJYXmlaOXD8OiGJkAv4L5+9WoB0ZQGSmyQjI=')
                   144 Query    SELECT *
        FROM dbpass_items
        WHERE perso = 0
                   144 Quit
                   146 Connect  pass@localhost on dbpass using TCP/IP
                   146 Query    SET NAMES latin1
                   146 Query    SELECT login, key_tempo, admin, gestionnaire, can_manage_all_users FROM dbpass_users WHERE id = 1
                   146 Query    SELECT public_key
            FROM dbpass_users
            WHERE id = 10000087
                   146 Query    SELECT login, key_tempo, admin, gestionnaire, can_manage_all_users FROM dbpass_users WHERE id = 1
                   147 Connect  pass@localhost on dbpass using TCP/IP
                   147 Quit
                   146 Query    SELECT increment_id
        FROM dbpass_log_items
        WHERE raison LIKE "at_pw :%" AND encryption_type = "teampass_aes"
        LIMIT 0, 100
                   146 Query    SELECT share_key
            FROM dbpass_sharekeys_logs
            WHERE object_id = 1 AND user_id = 1
                   146 Quit
230108  8:28:21    148 Connect  pass@localhost on dbpass using TCP/IP
                   148 Query    SET NAMES latin1
                   148 Query    SELECT login, key_tempo, admin, gestionnaire, can_manage_all_users FROM dbpass_users WHERE id = 1
                   148 Query    SELECT label, date AS error_date
        FROM dbpass_log_system
        WHERE `type` LIKE 'error'
        ORDER BY `date` DESC
        LIMIT 0, 10
                   149 Connect  pass@localhost on dbpass using TCP/IP
                   149 Quit
                   148 Quit

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
[RresetUserPpassword.zip](https://github.com/nilsteampassnet/TeamPass/files/10367804/RresetUserPpassword.zip)

```

**Comment by nilsteampassnet** [comment]
please update to last commit

**Comment by wease1** [comment]
> please update to last commit

if update to latest commit im have new problem https://github.com/nilsteampassnet/TeamPass/issues/3434

**Comment by Emi94** [comment]
Hi, I have the same problem, can't change a user's password. It gets stuck at the same step as in the screenshot from the first comment.

Although I get a different error on my webserver:

> [Fri Feb 03 09:26:07.055077 2023] [php:error] [pid 3720] [client 172.17.16.10:54854] PHP Fatal error:  Uncaught TypeError: decryptUserObjectKey(): Argument #1 ($key) must be of type string, null given, called in /var/www/html/sources/main.queries.php on line 2167 and defined in /var/www/html/sources/main.functions.php:2830\nStack trace:\n#0 /var/www/html/sources/main.queries.php(2167): decryptUserObjectKey()\n#1 /var/www/html/sources/main.queries.php(1942): continueReEncryptingUserSharekeysStep2()\n#2 /var/www/html/sources/main.queries.php(464): continueReEncryptingUserSharekeys()\n#3 /var/www/html/sources/main.queries.php(155): keyHandler()\n#4 /var/www/html/sources/main.queries.php(77): mainQuery()\n#5 {main}\n  thrown in /var/www/html/sources/main.functions.php on line 2830, referer: https://teampass.domain.com/index.php?page=users

My environment:
 - ubuntu 20.04
 - apache 2.4.41
 - php 8.1
 - mariadb 10.9.4
 - teampass 3.0.0.22 (just upgraded to latest commit from master)

If you need other info from me, please let me know.
