### ISSUE TITLE
Unable to display/edit password item after upgrade 2.1.27 to 3.0.22 master

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#3473]
### Steps to reproduce
1. Upgrade 2.1.27 to 3.0.22 master
2. Logon and clic to open or edit any password item

### Expected behaviour
Password item should be displayed or edited.

### Actual behaviour
There is an error and nothing is shown, other things like username or password copy buttons work, therefore data has been upgraded correctly, also I can create password elements, but I cannot edit or display them after being created.

### Server configuration
**Operating system**: Debian 10

**Web server:** Apache2.4

**Database:** MariaDB10.3

**PHP version:**7.4/8.1

**Teampass version:** 3.0.22 github master version

**Teampass configuration file:**

```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'https://172.29.65.166',
    'favicon' => 'https://172.29.65.166/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'https://172.29.65.166/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.21',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => '',
    'send_stats_time' => '1669741856',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'localhost',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'teampass@localhost.local',
    'email_from_name' => 'TeamPass LocalHost Local',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '1',
    'create_item_without_password' => '1',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Madrid',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '1',
    'bck_script_passkey' => 'xxxxxxxxxxxxxxxxxxxxxx',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '[1,2,3]',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '1',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '600',
    'tasks_manager_refreshing_period' => '60',
    'maximum_number_of_items_to_treat' => '2000',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'can_create_root_folder' => '0',
);
```

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows11

#### Web server error log
```
No errors in apache log
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```


Caution
Next error occurred
SyntaxError: Unexpected end of JSON input

Informations:
- File: items.queries.php
- Function: show_details_item

Raw answer from server:



index.php?page=items:7548
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Object.success (index.php?page=items:7548:55)
    at c (jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
    at l (jquery.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
(anonymous)	@	index.php?page=items:7548
c	@	jquery.min.js:2
fireWith	@	jquery.min.js:2
l	@	jquery.min.js:2
(anonymous)	@	jquery.min.js:2
load (async)		
send	@	jquery.min.js:2
ajax	@	jquery.min.js:2
S.<computed>	@	jquery.min.js:2
Details	@	index.php?page=items:7393
(anonymous)	@	index.php?page=items:5337
dispatch	@	jquery.min.js:2
v.handle	@	jquery.min.js:2







1 requests
367 B transferred
0 B resources
type: 
show_details_item
data: 
eyJjaXBoZXJ0ZXh0IjoiVjZta2cweW1tVlE2WWZoMEh1QXhzcE5HTDNtanJlRVd5NUx2Mjl2TWdEVHVDWW9QMmJuTmMzUmJsVjRrYVcvbkdzYlIxV243cU9BM0svdzRPOTE5dDhDM2JkRExRMHpId2ErWldSclpBZUMwaVNqSmhpUzhmSmQvaWp6K1RtZjlaeUlhOXRVS3VoUkFIRG11RXpsa01ydE93bFQrcjlENHJwRHNiWnM3UjNlSEU3cjF5NlMyODZPSVQ3V093Wi9xIiwiaXYiOiJmZThkM2U5OWJmMmJjOWJlZmJjODE0NGNkYjU1ZTA1OSIsInNhbHQiOiIzYmQzOTQwMzg1ZjY2M2EzNTVhNDAxODgzMzNmYjZlMTJlZGRlZDUwMTQ1MTU2ZDBiYzRhMmM2YjA0MzNmNjZkMjZlZDc5MzM3NTZkMWUyMTI5MTM3YjZhZDgyZWQ4OTdiNjc2NjFhNTA3NmU0MmIxZmMzNWYxMGUxNTcwMzY5OTBjYjkzNzdhZDk0NTRkOTVkYzE3OWMwN2UzMzBkNGRkMmJmZDcwMzNkN2I1NDIwNGRjZDZkODQ1NTE5MmY2MTI2ZjM3YjEwNzI1ODRkZGViZDI5MWQyMDZhODQzYmU5MWJkNmU0MTViMjMzNjkxOGE3ODQ1ZThiOWVjMDhhOTkyNzg3NzZiOGRmYWI2ZDdkYjhmZDRiMGM2NDE0MjA2ZWMyZjYyYzUyOGE3NGFjMzlkMGRmMzEyNzBhOTg5YjViMjVmN2U0YmU2NGNmNjBjN2IxNjNlOGVkNTUxNTA4MjU3YTc4OTQwN2U3MGVlNzYwZjY4YmZiNDEzMjE1NTkwYmUzMzA0MmQ0YjFiMWE2YzdmMzc3NDg3M2M3NzE4ZDgwYzI5ZDE2Y2E1YzFjNzZmMmM5YjBkY2I2N2NhMDUzNzI5YzJhZDdhYjE0YTYwNjg0NDQzMDM2YzEyMmEzMWM1Y2ViNWZmYjIwMDIwYjQzNWI0YjI5NmMxZDViOTZkYmMwZiIsIml0ZXJhdGlvbnMiOjk5OX0=
key: 
RLuqyvSMuSdjrEMpq5RC2nsgFZ4RSDy3vnNkN2T7xe5pVQyT8c

```

**Comment by alarido** [comment]
I got a more detailed console log:

```
index.php?page=items:7309 EXPECTED ACTION on [object Object] is show -- 
index.php?page=items:4148 >>> #folders-tree-card -- 
index.php?page=items:7314 Request is running: false
index.php?page=items:7374 Last seen item 12258
index.php?page=items:7389 SEND
index.php?page=items:7390 {id: 12258, folder_id: 1441, salt_key_required: 0, expired_item: '', restricted: '', …}expired_item: ""folder_access_level: 30folder_id: 1441id: 12258page: "items"restricted: ""rights: 70salt_key_required: 0[[Prototype]]: Object
jquery.min.js:2 [Violation] 'click' handler took 420ms
index.php?page=items:7404 RECEIVED
index.php?page=items:7405 false
index.php?page=items:7548 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Object.success (index.php?page=items:7548:55)
    at c (jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29072)
    at l (jquery.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
(anonymous) @ index.php?page=items:7548
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
S.<computed> @ jquery.min.js:2
Details @ index.php?page=items:7393
(anonymous) @ index.php?page=items:5337
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

```

**Comment by alarido** [comment]
A combination of mysqldump with --no-data switch to get only the schema, diff to compare the differences between both of them, "grep -v" to filter out unneeded lines and finally manual comparison with the remaining things, for example in some cases after upgrades some columns are added and then not created in the same order as new installs, but are correctly defined and then they do work fine but diff shows them as a discrepancy.
