### ISSUE TITLE
Malformed UTF-8 data Ldap

### ISSUE THREAD

**Issue by Nathu2018** [nilsteampassnet/TeamPass#3533]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Nathu2018** [comment]
Warning: Illegal offset type in C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\Connection.php on line 495

Fatal error: Uncaught ErrorException: ldap_search(): Search: Operations error in C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\Ldap.php:235 Stack trace: #0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}(2, 'ldap_search(): ...', 'C:\\wamp64\\www\\T...', 235, Array) #1 C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\Ldap.php(235): ldap_search(Resource id #93, 'DC=am,DC=tsacor...', '(&(0=*))', Array, false, 0, 0, 0) #2 C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\HandlesConnection.php(171): LdapRecord\Ldap->LdapRecord\{closure}() #3 C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\Ldap.php(237): LdapRecord\Ldap->executeFailableOperation(Object(Closure)) #4 C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\Query\Builder.php(716): LdapRecord\Ldap->search('DC=am,DC=tsacor...', '(&(0=*))', Array, false, 0) #5 C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\Connection.php(394): LdapRecord\Query\Builder->LdapRecord\Query\{closure}(Object(LdapRecord\Ldap)) #6 C:\wamp64\www\TeamPass\includ in C:\wamp64\www\TeamPass\includes\libraries\LdapRecord\LdapRecordException.php on line 26

**Comment by Nathu2018** [comment]
When I getting same error for search Items Please help

**Comment by Nathu2018** [comment]
please help

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
