### ISSUE TITLE
issue with step 3 on a fresh install

### ISSUE THREAD

**Issue by Nicolcn** [nilsteampassnet/TeamPass#3535]
### Steps to reproduce
1. follow the instalation step given by the official website
2. try to finish install via the web interface

### Expected behaviour
Getting to step 4 of the install

### Actual behaviour
nothing hapenns

### Server configuration
**Operating system**: ubuntu server 22.04.1

**Web server:** Apache 2.4.52

**Database:** MariaDB 10.6.11

**PHP version:** 8.1.2

**Teampass version:** 3.0.0

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:** firefox

**Operating system:**windows 10

#### Web server error log
[php:error] [pid 18098] [client 192.168.9.140:56355] PHP fatal error : Uncaught msqli_sql_expception: Connexion refused in /var/www/html/TeamPass/install/install.queries.php:279\nStack trace:\n#0 /var/www/html/TeamPass/install/install.queries.php(279): mysqli_connect()\n#1 {main}\n thrown in /var/www/html/TeamPass/install/install.queries.php on line 279, referer: http://192.168.9.147/TeamPass/install/install.php

#### Log from the web-browser developer console (CTRL + SHIFT + i)
Failed to load resource: the server responded with a status of 404 (Not found)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Uncaught TypeError: Cannot read properties of null (reading '0')
    at object.complete
    at object.resolveWith
    at w
    at XMLHttpRequest.d

**Comment by jmbsa** [comment]
Same error using docker-compose:

`
teampass-web_1  | [24-Feb-2023 17:13:55] WARNING: [pool www] child 27 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: No such file or directory in /var/www/html/install/install.queries.php:279"
teampass-web_1  | [24-Feb-2023 17:13:55] WARNING: [pool www] child 27 said into stderr: "Stack trace:"
teampass-web_1  | [24-Feb-2023 17:13:55] WARNING: [pool www] child 27 said into stderr: "#0 /var/www/html/install/install.queries.php(279): mysqli_connect('localhost', 'teampass', 'teampass', 'teampass', '3306')"
teampass-web_1  | [24-Feb-2023 17:13:55] WARNING: [pool www] child 27 said into stderr: "#1 {main}"
teampass-web_1  | [24-Feb-2023 17:13:55] WARNING: [pool www] child 27 said into stderr: "  thrown in /var/www/html/install/install.queries.php on line 279"
teampass-web_1  | 2023/02/24 17:13:55 [error] 20#20: *24 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: No such file or directory in /var/www/html/install/install.queries.php:279
teampass-web_1  | Stack trace:
teampass-web_1  | #0 /var/www/html/install/install.queries.php(279): mysqli_connect('localhost', 'teampass', 'teampass', 'teampass', '3306')
teampass-web_1  | #1 {main}
teampass-web_1  |   thrown in /var/www/html/install/install.queries.php on line 279" while reading response header from upstream, client: 172.19.0.1, server: _, request: "POST /install/install.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8889", referrer: "http://localhost:8889/install/install.php"
teampass-web_1  | 172.19.0.1 - - [24/Feb/2023:17:13:55 +0000] "POST /install/install.queries.php HTTP/1.1" 500 5 "http://localhost:8889/install/install.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36"
`

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
