### ISSUE TITLE
In current version is a bug in the installation

### ISSUE THREAD

**Issue by JunkyDeveloper** [nilsteampassnet/TeamPass#3538]
### Steps to reproduce
1. Clone the newest commit from master

### Expected behaviour
Installation should work fine

### Actual behaviour
Error message: Teampass database is not up to date.
![issue](https://user-images.githubusercontent.com/56804181/220176701-40d64929-ea5c-490b-971e-8402e7d53217.PNG)

### More Informations
I started with the newest commit (bc7a0cb) here the installation failed with the error in the picture.
I went one commit back (0c2ef94e819b25d65854754bd00635a629d6e6cd). Here no error message but you can't login into the systems
With commit (435469a0fbb350e231e3f9884dc2467d984840cd) everything works fine.
I hope that will helps you to fix this bug :) 

### Server configuration
**Operating system**:

**Web server:**
apache2

**Database:**
8.0.32-0ubuntu0.20.04.2

**PHP version:**
8.0.32-0ubuntu0.20.04.2

**Teampass version:** 
Commit: bc7a0cb

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
fresh install

#### Web server error log
```
>
[Mon Feb 20 18:33:21.659621 2023] [mpm_prefork:notice] [pid 17743] AH00169: caught SIGTERM, shutting down
[Mon Feb 20 18:33:22.759147 2023] [mpm_prefork:notice] [pid 18630] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Mon Feb 20 18:33:22.759192 2023] [core:notice] [pid 18630] AH00094: Command line: '/usr/sbin/apache2'
[Mon Feb 20 18:34:05.816559 2023] [php:error] [pid 18633] [client 172.20.16.1:62714] PHP Fatal error:  Uncaught mysqli_sql_exception: Permission denied in /var/www/TeamPass/install/install.queries.php:279\nStack trace:\n#0 /var/www/TeamPass/install/install.queries.php(279): mysqli_con>
[Mon Feb 20 18:34:38.192149 2023] [php:error] [pid 18634] [client 172.20.16.1:62723] PHP Fatal error:  Uncaught mysqli_sql_exception: Permission denied in /var/www/TeamPass/install/install.queries.php:279\nStack trace:\n#0 /var/www/TeamPass/install/install.queries.php(279): mysqli_con>
[Mon Feb 20 18:34:38.236925 2023] [php:error] [pid 18636] [client 172.20.16.1:62724] PHP Fatal error:  Uncaught mysqli_sql_exception: Permission denied in /var/www/TeamPass/install/install.queries.php:279\nStack trace:\n#0 /var/www/TeamPass/install/install.queries.php(279): mysqli_con>
[Mon Feb 20 18:35:38.117907 2023] [php:error] [pid 19033] [client 172.20.16.1:62744] PHP Fatal error:  Uncaught mysqli_sql_exception: Key column 'id' doesn't exist in table in /var/www/TeamPass/install/install.queries.php:1138\nStack trace:\n#0 /var/www/TeamPass/install/install.querie>
[Mon Feb 20 18:35:57.897691 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897761 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897771 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897779 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897788 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897802 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897810 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897818 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897826 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897834 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897842 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897849 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897857 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897865 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897873 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897881 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897886 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2532, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897894 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897898 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2532, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897903 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2532, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897924 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897933 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897942 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897950 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897957 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897965 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897973 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897981 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897989 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.897993 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2532, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.898001 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php
[Mon Feb 20 18:35:57.898008 2023] [php:warn] [pid 19035] [client 172.20.16.1:62746] PHP Warning:  chmod(): Operation not permitted in /var/www/TeamPass/sources/main.functions.php on line 2518, referer: http://172.20.20.214/install/install.php

```

**Comment by nilsteampassnet** [comment]
Rooh ... stupid logic error from me.
Now fixed.

Please reopen on need.

**Comment by JunkyDeveloper** [comment]
Unfortunatly the issue is only half solved.
I make a new issue because I can't reopen that here
