### ISSUE TITLE
Error: Malformed UTF-8 data

### ISSUE THREAD

**Issue by c1thunder** [nilsteampassnet/TeamPass#3540]
### Steps to reproduce
1. Go to the main page
2. Filled in username and password
3. Click login

### Expected behaviour
It should be login

### Actual behaviour
Error: Malformed UTF-8 data

### Server configuration
Windows 10 Pro 

**Web server:**
Apachhe

**Database:**
MySQL
**PHP version:**
8.1
**Teampass version:** 
3.0.22
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

Next error occurred
Error: Malformed UTF-8 data

Raw answer from server:

Fatal error: Uncaught Error: Call to undefined function socket_create() in C:\xampp\htdocs\tp\sources\main.functions.php:1760 Stack trace: #0 C:\xampp\htdocs\tp\sources\main.functions.php(1821): send_syslog('action=user_con...', 'localhost', '514', 'teampass') #1 C:\xampp\htdocs\tp\sources\identify.php(854): logEvents(Array, 'user_connection', 'connection', '1', 'admin') #2 C:\xampp\htdocs\tp\sources\identify.php(425): handleLoginAttempts('1', 'admin', '1676966850', 'admin', Array) #3 C:\xampp\htdocs\tp\sources\identify.php(116): identifyUser('eyJjaXBoZXJ0ZXh...', Array) #4 {main} thrown in C:\xampp\htdocs\tp\sources\main.functions.php on line 1760

I just downloaded and deployed it as a fresh install. Please help

**Comment by Esware80** [comment]
I had same issue. I updated to MariaDB last version, and solved.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
