### ISSUE TITLE
Upgrade wizard doesn't move past first screen, replaces working settings.php with empty one (2.1.27/3.0.0.22 to 3.0.0.23)

### ISSUE THREAD

**Issue by lusky3** [nilsteampassnet/TeamPass#3553]
### Steps to reproduce
1. Try to upgrade a 2.1.27 database to 3.0.0.23 via `install/upgrade.php`
 
or

1. Upgrade 2.1.27 to 3.0.0.22 via `install/upgrade.php`
2. Try to upgrade 3.0.0.22 to [3.0.0.23](https://github.com/nilsteampassnet/TeamPass/commit/61bd0d651d3485c8015d3f6479b12606873c61b4) (latest commit)

### Expected behaviour
When submitting admin credentials at `install/upgrade.php`, upgrade wizard should proceed to next steps (env check and db upgrade).

### Actual behaviour
Submitting admin credentials at `install/upgrade.php` displays endless loading animation.
In the background, a working, populated `settings.php` is replaced with a blank one.

### Server configuration
**Operating system**:

Ubuntu 20.04.5

**Web server:**

nginx 1.22.1

**Database:**

Mariadb 10.11.2 (LTS)

**PHP version:**

PHP 8.1.16

**Teampass version:** 

[3.0.0.22](https://github.com/nilsteampassnet/TeamPass/releases/tag/3.0.0.22)

<hr>

**Teampass configuration file:**

**Updated from an older Teampass**

<details><summary>/var/www/teampass/include/config/config/tp.config.php</summary>
<p>

```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'Y-m-d',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass',
    'cpassman_url' => 'https://teampass.<mydomain>.com',
    'favicon' => 'https://teampass.<mydomain>.com/favicon.ico',
    'path_to_upload_folder' => '/var/www/teampass/upload',
    'url_to_upload_folder' => 'https://teampass.<mydomain>.com/upload',
    'path_to_files_folder' => '/var/www/teampass/files',
    'url_to_files_folder' => 'https://teampass.<mydomain>.com/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.22',
    'ldap_mode' => '0',
    'ldap_type' => 'posix-search',
    'ldap_suffix' => '@dc=<mydomain>,dc=net',
    'ldap_domain_dn' => 'dc=<mydomain>,dc=net',
    'ldap_domain_controler' => 'ops-liv-ipa01.<mydomain>.net',
    'ldap_user_attribute' => 'uid',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => 'dc=<mydomain>,dc=net',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '["["["["["["["["["1"]"]"]"]"]"]"]"]"]',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '3',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'https://teampass.<mydomain>.com/logo-bw.svg',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1513002112',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.sendgrid.net',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'apikey',
    'email_auth_pwd' => '<mysecret>',
    'email_port' => '465',
    'email_security' => 'ssl',
    'email_server_url' => '',
    'email_from' => 'its@<mydomain>.com',
    'email_from_name' => 'ITS',
    'pwd_maximum_length' => '100',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,asc',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip,gz,tgz,tar.gz,gzip',
    'upload_otherext' => 'sql,xml,key,csr,pem,crt,json,srl,xml,gpg,cer,keychain',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'Teampass 2FA',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => 'posixAccount',
    'bck_script_path' => '/var/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'America/Toronto',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'ldap_usergroup' => 'cn=users,cn=accounts,dc=<mydomain>,dc=net',
    'ldap_bind_dn' => 'uid=passwordmanager,cn=users,cn=accounts,dc=<mydomain>,dc=net',
    'ldap_bind_passwd' => '<mysecret>',
    'ldap_port' => '389',
    'bck_script_passkey' => '<really-long-secret>',
    'ga_reset_by_user' => '1',
    'password_overview_delay' => '4',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'copy_to_clipboard_small_icons' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'enable_tasks_manager' => '0',
    'task_maximum_run_time' => '300',
    'maximum_number_of_items_to_treat' => '300',
    'tasks_manager_refreshing_period' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
);
```

</p>
</details>

<details><summary>/var/www/teampass/include/config/settings.php.2023_02_23_17_38_19</summary>
<p>

```
<?php
// DATABASE connexion parameters
define("DB_HOST", "localhost");
define("DB_USER", "admin");
define("DB_PASSWD", "def50200aac[etc]8020dff9d");
define("DB_NAME", "teampass");
define("DB_PREFIX", "teampass_");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/teampass");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}
```

</p>
</details>

<details><summary> /var/www/teampass/include/config/settings.php</summary>
<p>

```
<?php
// DATABASE connexion parameters
define("DB_HOST", "");
define("DB_USER", "");
define("DB_PASSWD", "");
define("DB_NAME", "");
define("DB_PREFIX", "");
define("DB_PORT", "");
define("DB_ENCODING", "");
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/teampass");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}
```

</p>
</details>

<hr>

### Client configuration
**Browser:**

Edge 110.0.1587.50 (Official build) (64-bit)

**Operating system:**

Windows 11 22H2

#### Web server error log

```
2023/02/23 18:38:32 [error] 837#837: *725 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Defuse\Crypto\Exception\BadFormatException: Encoded data is shorter than expected. in /var/www/teampass/includes/libraries/Encryption/Encryption/Encoding.php:225
Stack trace:
#0 /var/www/teampass/includes/libraries/Encryption/Encryption/Key.php(49): Defuse\Crypto\Encoding::loadBytesFromChecksummedAsciiSafeString()
#1 /var/www/teampass/install/tp.functions.php(131): Defuse\Crypto\Key::loadFromAsciiSafeString()
#2 /var/www/teampass/install/tp.functions.php(171): defuseCryption()
#3 /var/www/teampass/install/upgrade_ajax.php(225): defuse_return_decrypted()
#4 {main}
  thrown in /var/www/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 225" while reading response header from upstream, client: 192.168.0.174, server: teampass.<domain>.com, request: "POST /install/upgrade_ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "teampass.<domain>.com", referrer: "https://teampass.<domain>.com/install/upgrade.php"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)

<details><summary> /var/www/teampass/include/config/settings.php</summary>
<p>

```
jquery.min.js:2 
     
POST https://teampass.<mydomain>.com/install/upgrade_ajax.php 500
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
VM157:1 
        
       Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
complete @ upgrade.php:216
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

</p>
</details>

Side Note: Replacing `/var/www/teampass/install` from 3.0.0.23 with `/var/www/teampass/install` from 3.0.0.22 allows the wizard to continue; could indicate something broke with the upgrade files between .22 and .23?

**Comment by antoweb** [comment]
same problem here

**Comment by antoweb** [comment]
In my browser console i see:

Uncaught SyntaxError: Expected ',' or '}' after property value in JSON at position 73
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)

**Comment by antoweb** [comment]
Now i receive error:
VM318:1 Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
complete @ upgrade.php:216
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
l @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
load (async)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by antoweb** [comment]
Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)

**Comment by rbartczak** [comment]
The same for me (fix don't work :( )
[Tue Feb 28 09:52:18.139354 2023] [php:error] [pid 1187] [client 10.10.45.3:7230] PHP Fatal error:  
Uncaught Error: Undefined constant "SECUREFILE" in /var/www/html/TeamPass/install/tp.functions.php:127
Stack trace:
#0 /var/www/html/TeamPass/install/tp.functions.php(171): defuseCryption()
#1 /var/www/html/TeamPass/install/upgrade_ajax.php(227): defuse_return_decrypted()
#2 {main}

thrown in /var/www/html/TeamPass/install/tp.functions.php on line 127, referer: https://teampass.xxx/install/upgrade.php


Browser console:
POST https://teampass.xxx/install/upgrade_ajax.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
VM486:1 Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)

**Comment by hieumphan** [comment]
Posting to say I have the same issue as well. I wanted to upgrade from 2.1.27 to the latest v3. Looked at other issue threads and everything I've tried did not work. 

My browser console and server logs have the same messages. I gave up with upgrading to V3 due to how little documentation there were to support a V2 -> V3 migration. If someone has a workaround to migrate a V2 instance into a V3 db, please share!

**Comment by Kyogre** [comment]
Same as [this](https://github.com/nilsteampassnet/TeamPass/issues/3553#issuecomment-1446578879). Trying to upgrade from 3.0.0.22 to latest.

**Comment by nilsteampassnet** [comment]
@Kyogre 
Just to understand well.
You are currently in version 3.0.022 and are experiencing this issue while upgrading to 3.0.0.23 latest commit, correct?

**Comment by antoweb** [comment]
I have this problem feom 2.1.27

**Comment by Kyogre** [comment]
> You are currently in version 3.0.022 and are experiencing this issue while upgrading to 3.0.0.23 latest commit, correct?

yes

> Can you please share your settings.php file before starting the upgrade to 3.0.0.23.

here it is: [settings.php from my 3.0.0.22.zip](https://github.com/nilsteampassnet/TeamPass/files/10968630/settings.php.from.my.3.0.0.22.zip)

**Comment by Kyogre** [comment]
> replaces working settings.php with empty one

Not in my case. My `settings.php` stays untouched.

**Comment by rbartczak** [comment]
Hello,
Still the same error:
Apache log:
[Mon Mar 20 08:23:40.277264 2023] [php:error] [pid 83434] [client 10.10.44.27:63670] PHP Fatal error:  Uncaught Error: Undefined constant "SECUREFILE" in /var/www/html/TeamPass/install/tp.functions.php:127
Stack trace:
#0 /var/www/html/TeamPass/install/tp.functions.php(171): defuseCryption()
#1 /var/www/html/TeamPass/install/upgrade_ajax.php(229): defuse_return_decrypted()
#2 {main}\n  thrown in /var/www/html/TeamPass/install/tp.functions.php on line 127, referer: https://teampass.xxx/install/upgrade.php

Console:
Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)


Settings:

<?php
// DATABASE connexion parameters
define("DB_HOST", "localhost");
define("DB_USER", "teamsqlp_xxx");
define("DB_PASSWD", "");
define("DB_NAME", "teampassxxx");
define("DB_PREFIX", "teampass_xxx");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/teampass");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);

when comparing the settings file with https://github.com/nilsteampassnet/TeamPass/blob/master/includes/.externals/settings.php
I don't have this line:
define("SALT", "");

**Comment by useronkel** [comment]
For me fixed with latest commit [1983379](https://github.com/nilsteampassnet/TeamPass/commit/1983379345e782954b426e3937fac644355e8038)

**Comment by mfraigneau** [comment]
Exact same error here.
Tried 3.0.0.22 to 3.0.2.
Tried 3.0.0.22 to 3.0.0.23.

**Comment by tuxlinuxbr** [comment]
Hi, Work for me. After add define('SECUREFILE', 'teampass-seckey.txt'); i need to set DB_ENCODING to utf8, before i haven't any encoding configured.

**Comment by mfraigneau** [comment]
Hello, worked also for me, but in addition, I had to add the same line "define('SECUREFILE', 'teampass-seckey.txt');" in the file includes/config/settings.php, without that, I wasn't able to logout properly (had error 500).

**Comment by antoweb** [comment]
> define('SECUREFILE', 'teampass-seckey.txt');

Now work also for me i missing to set utf8 in settings.phpo

**Comment by antoweb** [comment]
after click start receive this error in error log:
[Fri Apr 14 15:27:53.237635 2023] [php:error] [pid 6608] [client 10.21.20.51:51943] PHP Fatal error:  Uncaught mysqli_sql_exception: Data truncated for column 'complexity_level' at row 39 in /var/www/html/teampass/install/upgrade_run_3.0.0.php:1220\nStack trace:\n#0 /var/www/html/teampass/install/upgrade_run_3.0.0.php(1220): mysqli_query()\n#1 {main}\n  thrown in /var/www/html/teampass/install/upgrade_run_3.0.0.php on line 1220, referer: https://teampass3.discoverydam.com/teampass/install/upgrade.php


maybe is the encoding? i had to set define("DB_ENCODING", "utf8"); in settngs.php because with utf8mb3 wont work and cannot move to second step.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
