### ISSUE TITLE
Can't login with Admin and setup teampass 3 after upgrade from teampass 2

### ISSUE THREAD

**Issue by Voltecs** [nilsteampassnet/TeamPass#3564]
### Steps to reproduce
1. Update Teampass 2 to Teampass 3 following the instructions
2. Open the new server
3. Insert admin credentials and log in

### Expected behaviour
After pressing login, the upgrade setup should continue

### Actual behaviour
It appears a gear image, and the setup doesn't continue
and when i check the console, the error pasted below appears.

### Server configuration
**Operating system:**    Windows Server 2022

**Web server:**    WAMP 3.3.1/Apache 2.4.55.2

**Database:**    MySQL 5.7.31

**PHP version:**    PHP 7.4.33

**Teampass version:**    Teampass 3.0.0.22 (Updating from 2.1.27.36)

**Teampass configuration file:** attached

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows Server 2022

### Logs

I don't know which logs i need to post here, i am not much practical with WAMP and stuff...

#### Web server error log
```
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/10881150/tp.config.php.txt)

Insert your webserver log here


#### Log from the web-browser developer console (CTRL + SHIFT + i)
Uncaught SyntaxError: Unexpected token '<', "<br />
<fo"... is not valid JSON
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
Insert the log here and especially the answer of the query that failed.
```

**Comment by Kyogre** [comment]
I think it is duplicate of https://github.com/nilsteampassnet/TeamPass/issues/3553#issuecomment-1447803098

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
