### ISSUE TITLE
Upload attachment error

### ISSUE THREAD

**Issue by jofrey007** [nilsteampassnet/TeamPass#3633]
### Steps to reproduce
1. In Option I enabled all types of file extensions
2. Select file (in my case LP1.pem file)
3. Click to Start upload

### Expected behaviour
File is attached to selected item

### Actual behaviour
File is not attached and apache error message
[Fri Mar 31 14:09:04.650970 2023] [php:error] [pid 107731] [client 10.30.0.60:52594] PHP Fatal error:  Uncaught TypeError: htmlentities(): Argument #1 ($string) must be of type string, int given in /var/www/teampass/sources/upload.attachments.php:461\nStack trace:\n#0 /var/www/teampass/sources/upload.attachments.php(461): htmlentities()\n#1 /var/www/teampass/sources/upload.attachments.php(244): handleAttachmentError()\n#2 {main}\n  thrown in /var/www/teampass/sources/upload.attachments.php on line 461, referer: https://teampass.irsys.sk/index.php?page=items

### Server configuration
**Operating system**: Debian 11

**Web server:** Apache

**Database:**10.5.18-MariaDB-0+deb11u1

**PHP version:**8.1.16

**Teampass version:** 3.0.0.23

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**Fresh
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**Chrome

**Operating system:**Windows

#### Web server error log
```
[Fri Mar 31 14:09:04.650970 2023] [php:error] [pid 107731] [client 10.30.0.60:52594] PHP Fatal error:  Uncaught TypeError: htmlentities(): Argument #1 ($string) must be of type string, int given in /var/www/teampass/sources/upload.attachments.php:461\nStack trace:\n#0 /var/www/teampass/sources/upload.attachments.php(461): htmlentities()\n#1 /var/www/teampass/sources/upload.attachments.php(244): handleAttachmentError()\n#2 {main}\n  thrown in /var/www/teampass/sources/upload.attachments.php on line 461, referer: https://teampass.irsys.sk/index.php?page=items
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Is this extension allowed?

**Comment by jofrey007** [comment]
I allowed all extensions in options - see step 1 in Steps to reproduce

**Comment by Saibamen** [comment]
@jofrey007: Please retest in 3.0.3

**Comment by jofrey007** [comment]
> @jofrey007: Please retest in 3.0.3

I am still using version 3.0.0.23, I have plan to upgrade, but I dont know when.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
