### ISSUE TITLE
Export CSV from 2.1.27 to import in 3.0.3

### ISSUE THREAD

**Issue by lopo215** [nilsteampassnet/TeamPass#3644]
### Steps to reproduce
1. export csv from teampass 2.1.27
2. import in teampass 3.0.3
3.

### Expected behaviour
file imported

### Actual behaviour
reading file.... loop...

### Server configuration
 Ubuntu 22.04.2 LTS

**Web server:**
apache2
**Database:**
mariadb mysql 10.6
**PHP version:**
PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
**Teampass version:** 
3.0.3
**Teampass configuration file:**
sudo git clone https://github.com/nilsteampassnet/TeamPass.git
standard no change

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://192.168.1.113/teampass',
    'favicon' => 'http://192.168.1.113/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://192.168.1.113/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.3',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1678690712',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'CQuZtfKQ6xJsQBbtGBfsUCCE9g85By73TD5zrC2L',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1681282712',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
);

### Client configuration
**Browser:**
Versione 111.0.5563.147 (Build ufficiale) (a 64 bit)
**Operating system:**
win 10 pro
#### Web server error log
```

fab@tmpss:/var/www/html/teampass$ cat /var/log/apache2/error.log
[Wed Apr 12 06:52:46.836190 2023] [mpm_event:notice] [pid 3170:tid 140177618528128] AH00489: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Wed Apr 12 06:52:46.836458 2023] [core:notice] [pid 3170:tid 140177618528128] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 12 06:53:32.932249 2023] [mpm_event:notice] [pid 3170:tid 140177618528128] AH00492: caught SIGWINCH, shutting down gracefully
[Wed Apr 12 06:53:33.021389 2023] [mpm_prefork:notice] [pid 10827] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Wed Apr 12 06:53:33.021667 2023] [core:notice] [pid 10827] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 12 06:53:33.321406 2023] [mpm_prefork:notice] [pid 10827] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Apr 12 06:53:33.495811 2023] [mpm_prefork:notice] [pid 10867] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Wed Apr 12 06:53:33.496152 2023] [core:notice] [pid 10867] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 12 06:55:05.268243 2023] [mpm_prefork:notice] [pid 10867] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Apr 12 06:55:05.511638 2023] [mpm_prefork:notice] [pid 14519] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Wed Apr 12 06:55:05.511761 2023] [core:notice] [pid 14519] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 12 06:57:24.344884 2023] [mpm_prefork:notice] [pid 14519] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Apr 12 06:57:24.560570 2023] [mpm_prefork:notice] [pid 15432] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Wed Apr 12 06:57:24.560696 2023] [core:notice] [pid 15432] AH00094: Command line: '/usr/sbin/apache2'
[Wed Apr 12 06:58:33.170844 2023] [php:error] [pid 15437] [client 192.168.1.37:63054] PHP Fatal error:  Uncaught mysqli_sql_exception: Key column 'increment_id' doesn't exist in table in /var/www/html/teampass/install/install.queries.php:1227\nStack trace:\n#0 /var/www/html/teampass/install/install.queries.php(1227): mysqli_query()\n#1 {main}\n  thrown in /var/www/html/teampass/install/install.queries.php on line 1227, referer: http://192.168.1.113/teampass/install/install.php
sh: 1: locate: not found
[Wed Apr 12 06:58:59.264097 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264420 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264455 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264487 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264520 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264548 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264569 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264589 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264629 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264650 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264669 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264687 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264707 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264726 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264745 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264764 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264776 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264796 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264808 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264820 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264891 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264912 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264931 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264949 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.264978 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265085 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265117 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265136 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265154 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265165 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265184 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265202 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265219 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265286 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265336 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265357 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265376 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265387 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265406 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265437 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265449 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265495 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265508 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265527 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265545 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265563 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265580 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265597 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265615 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265632 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265650 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265668 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265686 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265703 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265721 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265747 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2518, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 06:58:59.265760 2023] [php:warn] [pid 15433] [client 192.168.1.37:63055] PHP Warning:  chmod(): Operation not permitted in /var/www/html/teampass/sources/main.functions.php on line 2532, referer: http://192.168.1.113/teampass/install/install.php
[Wed Apr 12 07:06:23.947202 2023] [php:warn] [pid 15445] [client 192.168.1.37:63320] PHP Warning:  Undefined array key "mbstring" in /var/www/html/teampass/includes/libraries/portable-utf8-master/src/voku/helper/UTF8.php on line 5582, referer: http://192.168.1.113/teampass/index.php?page=import
[Wed Apr 12 07:06:24.135351 2023] [php:warn] [pid 15445] [client 192.168.1.37:63320] PHP Warning:  Undefined array key 1 in /var/www/html/teampass/sources/import.queries.php on line 172, referer: http://192.168.1.113/teampass/index.php?page=import
[Wed Apr 12 07:06:24.135366 2023] [php:warn] [pid 15445] [client 192.168.1.37:63320] PHP Warning:  Undefined array key 2 in /var/www/html/teampass/sources/import.queries.php on line 173, referer: http://192.168.1.113/teampass/index.php?page=import
[Wed Apr 12 07:06:24.135369 2023] [php:warn] [pid 15445] [client 192.168.1.37:63320] PHP Warning:  Undefined array key 3 in /var/www/html/teampass/sources/import.queries.php on line 174, referer: http://192.168.1.113/teampass/index.php?page=import
[Wed Apr 12 07:06:24.135372 2023] [php:warn] [pid 15445] [client 192.168.1.37:63320] PHP Warning:  Undefined array key 4 in /var/www/html/teampass/sources/import.queries.php on line 175, referer: http://192.168.1.113/teampass/index.php?page=import
[Wed Apr 12 07:06:24.135399 2023] [php:error] [pid 15445] [client 192.168.1.37:63320] PHP Fatal error:  Uncaught Goodby\\CSV\\Import\\Standard\\Exception\\StrictViolationException: Column size should be 1, but 2 columns given in /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php:119\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php(42): Goodby\\CSV\\Import\\Standard\\Interpreter->checkRowConsistency()\n#1 /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php(68): Goodby\\CSV\\Import\\Standard\\Interpreter->interpret()\n#2 /var/www/html/teampass/sources/import.queries.php(178): Goodby\\CSV\\Import\\Standard\\Lexer->parse()\n#3 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php on line 119, referer: http://192.168.1.113/teampass/index.php?page=import

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
FortiClient Chromebook WebFilter Loaded
index.php?page=import:2060 Loading settings result:
index.php?page=import:2061 Object
index.php:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
index.php?page=import:2193 Refresh last item seen result
index.php?page=import:2194 Object
index.php?page=import:869 Get user info results:
index.php?page=import:870 Object
index.php?page=import:2604 Object
index.php?page=import:2636 START IMPORT
/teampass/sources/import.queries.php:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
DevTools failed to load source map: Could not load content for http://192.168.1.113/teampass/plugins/summernote/summernote-bs4.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

```

**Comment by Johnybe** [comment]
Hello,

Same issue : 

Perform an upgrade from 2.1.26 to 3.0.9

RHEL 7.9
PHP 8.3

After CSV export from 2.1.26 it's impossible to import in 3.0.9

PHP Fatal error:  Uncaught Goodby\\CSV\\Import\\Standard\\Exception\\StrictViolationException: Column size should be 1, but 2 columns given in /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php:119\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php(42): Goodby\\CSV\\Import\\Standard\\Interpreter->checkRowConsistency(Array)\n#1 /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php(68): Goodby\\CSV\\Import\\Standard\\Interpreter->interpret(Array)\n#2 /var/www/html/teampass/sources/import.queries.php(177): Goodby\\CSV\\Import\\Standard\\Lexer->parse('/var/www/html/t...', Object(Goodby\\CSV\\Import\\Standard\\Interpreter))\n#3 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php on line 119, referer: https://XX.XX..XX.XX/teampass/index.php?page=import

**Comment by DaveWebb2** [comment]
I too have this issue in version 3.1.2.141 so it hasn't been fixed in over a year.

**Comment by danfossi** [comment]
Same issue here:

Debian 12.1
PHP 8.2.28
TeamPass 3.1.4.25
