### ISSUE TITLE
Error upgrading from 3.0.0.22 => 3.0.5

### ISSUE THREAD

**Issue by danyelex** [nilsteampassnet/TeamPass#3664]
### Steps to reproduce
1. upgrading from 3.0.0.22 to 3.0.5 (but i tried any version between both)
2. run /install/upgrade.php

### Expected behaviour
At first request of admin account and clicking on start, nothing append.

### Actual behaviour
in /var/log/apache2/teampass_error.log appear:
`
[Fri Apr 14 16:40:09.630273 2023] [php7:error] [pid 2555] [client 192.168.192.54:45583] PHP Fatal error:  Uncaught Defuse\\Crypto\\Exception\\BadFormatException: Encoded data is shorter than expected. in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php:225\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Encryption/Encryption/Key.php(49): Defuse\\Crypto\\Encoding::loadBytesFromChecksummedAsciiSafeString()\n#1 /var/www/html/teampass/install/tp.functions.php(131): Defuse\\Crypto\\Key::loadFromAsciiSafeString()\n#2 /var/www/html/teampass/install/tp.functions.php(171): defuseCryption()\n#3 /var/www/html/teampass/install/upgrade_ajax.php(229): defuse_return_decrypted()\n#4 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Encryption/Encryption/Encoding.php on line 225, referer: https://teampass.eglue.it/install/upgrade.php
`

### Server configuration
Ubuntu 20.04  Linux 5.4.0-139-generic

**Web server:**
Apache/2.4.41

**Database:**
mysql  Ver 8.0.32-0ubuntu0.20.04.2

**PHP version:**
PHP 7.4.3-4ubuntu2.17

**Teampass version:** 
3.0.5

**Teampass configuration file:**
`<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://teampass.eglue.it',
    'favicon' => 'https://teampass.eglue.it/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'https://teampass.eglue.it/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://teampass.eglue.it/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.22',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '@nuovacs.local',
    'ldap_domain_dn' => 'DC=NuovaCS,DC=local',
    'ldap_domain_controler' => '192.168.192.3',
    'ldap_user_attribute' => 'samaccountname',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'https://teampass.eglue.it/logo.png',
    'custom_login_text' => 'Utilizzare Chrome!!',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1500382708',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtprelay.nuovacs.local',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => 'teampass.nuovacs.local',
    'email_from' => 'teampass-noreply@nuovacs.it',
    'email_from_name' => 'teampass-noreply@nuovacs.it',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'Teampass Eglue',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '15',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '1',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Rome',
    'bck_script_key' => 'B4ckup5ecur3Â£',
    'teampass_version' => '2.1.27',
    'personal_saltkey_security_level' => '0',
    'ldap_new_user_is_administrated_by' => '0',
    'ldap_port' => '389',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'admin_2fa_required' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'ldap_new_user_role' => '7',
    'password_overview_delay' => '4',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '[]',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'copy_to_clipboard_small_icons' => '1',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => 'distinguishedname',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '(&(objectCategory=Person)(sAMAccountName=*))',
    'ldap_bdn' => 'DC=NuovaCS,DC=local',
    'ldap_hosts' => '192.168.192.3',
    'ldap_password' => 'Wysiswy9!',
    'ldap_username' => 'NUOVACS\ad_reader',
    'disable_show_forgot_pwd_link' => '1',
    'bck_script_passkey' => 'def50200b7b728f57b532477e9bf556cfe01c2a61e2606a2e1c0fed82f1c019c935e0a44675287547435a8dc54bde203416f2c0b418e08bd518f61ae303f8637a220788d774dc3fefe708ab29db51c57994e0c601c2901407c46003674b688f2815a3fb2a8e6195787e58ca9b48db5609690656ed237e29b1ae4b42c',
    'api_token_duration' => '60',
    'enable_tasks_manager' => '0',
    'task_maximum_run_time' => '300',
    'maximum_number_of_items_to_treat' => '300',
    'tasks_manager_refreshing_period' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
);
`

**Comment by danyelex** [comment]
maybe like #3655

**Comment by Len16-53** [comment]
See: https://github.com/nilsteampassnet/TeamPass/discussions/3631
My problem is resolved with this.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
