### ISSUE TITLE
Item being corrupted if image attached to it

### ISSUE THREAD

**Issue by AKorolkovs** [nilsteampassnet/TeamPass#3670]
### Steps to reproduce
1. create item
2. edit item and add image
3. click save.
4. check infinite "Reading folder" message
5. press cancel and try to open item you created in step 1.  You'll see infinite "Loading item" message.

### Expected behaviour
You should be able to add image or get and error if image can't be uploaded.

### Actual behaviour
Item getting corrupt - you no longer can open it to view, edit or delete

### Server configuration
**Operating system**:
Ubuntu 22.04
**Web server:**
Apache/2.4.52 (Ubuntu)
**Database:**
mariadb  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper
**PHP version:**
PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
**Teampass version:** 
3.0.3
**Teampass configuration file:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/11260988/tp.config.php.txt)
**Updated from an older Teampass or fresh install:**
updated from v2

### Client configuration
**Browser:**
Chrome, Firefox, Edge, Safari
**Operating system:**
macOS 13.3.1
#### Web server error log
`[Tue Apr 18 10:45:13.732211 2023] [proxy_fcgi:error] [pid 1237609] [client 10.128.149.84:53871] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: base64_encode(): Argument #1 ($string) must be of type string, bool given in /var/www/teampass.hostname.com/sources/main.functions.php:2803\nStack trace:\n#0 /var/www/teampass.hostname.com/sources/main.functions.php(2803): base64_encode()\n#1 /var/www/teampass.hostname.com/sources/items.queries.php(2487): doDataDecryption()\n#2 {main}\n  thrown in /var/www/teampass.hostname.com/sources/main.functions.php on line 280
3', referer: https://teampass.hostname.com/index.php?page=items`

#### Log from the web-browser developer console (CTRL + SHIFT + i)
![image](https://user-images.githubusercontent.com/129317064/232755672-70f86619-a291-4d92-b024-7814b57664a6.png)

**Comment by AKorolkovs** [comment]
Similar error #3549 #3241 #3224 and many other.
Please dig into this as we are losing data

**Comment by owirtifo** [comment]
I have the same problem.
