### ISSUE TITLE
Edit items does not work

### ISSUE THREAD

**Issue by EtherOrcsDAO** [nilsteampassnet/TeamPass#3685]
### Steps to reproduce
1.  Log in as an account who has the ability to edit a folder in Teampass
2. Expand the folders until an item appears on the right
3. Click on the pencil, nothing happens.

### Expected behaviour
The item should be expanded and all data within the item can be seen and edited.

### Actual behaviour
Nothing happens, at all.  New items can still be added without an issue, but once an item is added and saved, it cannot be re-edited.

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Nginx
**Database:**
Maria/MySQL
**PHP version:**
8.1.2
**Teampass version:** 
3.0.7
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
Fresh Install

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
Nothing in the logs showing an issue.

**Comment by EtherOrcsDAO** [comment]
I added a second item, problem persists.  When I click the pencil to edit, a brief blue box appears in the bottom right, and then disappears.  When I clicked copy on the password for the second Item I created, now it's forever thinking.

![image](https://user-images.githubusercontent.com/125311353/235325604-4688dca4-5300-4161-ba30-8a6b97b81c5c.png)

Any idea @nilsteampassnet  where to look?  Teampass has no logs, outside of "user logged on" and "user created item with ID 2".

**Comment by EtherOrcsDAO** [comment]
Looking in NGINX Logs I see this:

`#0 /var/www/html/TeamPass/sources/main.functions.php(2800): base64_encode()
#1 /var/www/html/TeamPass/sources/items.queries.php(4168): doDataDecryption()
#2 {main}
  thrown in /var/www/html/TeamPass/sources/main.functions.php on line 2800" while reading response header from upstream, client: IP ADDRESS HERE, server: safe.ServerNAME.com, request: "POST /sources/items.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "safe.ServerNAME.com", referrer: "https://safe.ServerNAME.com/index.php?page=items"
`

**Comment by anhenrique** [comment]
we have the same error with some users

**Comment by Nachtlichtermeer** [comment]
please test with 'english' as language
i had some similar problems with user-settings

**Comment by stvilla** [comment]
I'm having the same issue with some users. Any update?

**Comment by yong-sheng-03** [comment]
I have the same issue but only with a few users. Have tried deleting the user and re-importing it from AD but issue still persists. 

The user is able to create new item but unable to edit or open an item (similar to above where blue box appears with no action). 

Following error found in apache error log:

[php:warn] PHP Warning:  Undefined array key "id" in /var/www/teampass/TeamPass/sources/items.logs.php on line 109, referer: http://*.*.*.*/index.php?page=items&group=14&id=292
[php:warn] PHP Warning:  Undefined array key "id" in /var/www/teampass/TeamPass/sources/items.logs.php on line 112, referer: http://*.*.*.*/index.php?page=items&group=14&id=292
[php:warn] PHP Warning:  Undefined array key "id" in /var/www/teampass/TeamPass/sources/items.logs.php on line 109, referer: http://*.*.*.*/index.php?page=items&group=14&id=292
[php:warn] PHP Warning:  Undefined array key "id" in /var/www/teampass/TeamPass/sources/items.logs.php on line 112, referer: http://*.*.*.*/index.php?page=items&group=14&id=292

Please advise on further action.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
