### ISSUE TITLE
After upgrade from 3.0.0.17 to 3.0.7, newly create AD users cannot log in

### ISSUE THREAD

**Issue by hitenmandalia** [nilsteampassnet/TeamPass#3697]
When upgrading TeamPass 3.0.0.17 to the latest version of 3.0.7 release (as of 02 May 2023), existing users seem to be able to log in fine.  However, when adding a new user from Active Directory, they are unable to log in.  The log in screen just stays with the in progress circle.  The logs show the following error:

[Tue May 02 13:41:47.549215 2023] [php7:error] [pid 41] [client 172.17.0.1:51584] PHP Fatal error:  Uncaught LdapRecord\\Auth\\UsernameRequiredException: A username must be specified. in /var/www/TeamPass/includes/libraries/LdapRecord/Auth/Guard.php:66\nStack trace:\n#0 /var/www/TeamPass/sources/identify.php(1267): LdapRecord\\Auth\\Guard->attempt()\n#1 /var/www/TeamPass/sources/identify.php(2348): authenticateThroughAD()\n#2 /var/www/TeamPass/sources/identify.php(317): identifyDoLDAPChecks()\n#3 /var/www/TeamPass/sources/identify.php(115): identifyUser()\n#4 {main}\n  thrown in /var/www/TeamPass/includes/libraries/LdapRecord/Auth/Guard.php on line 66, referer: http://xxx.xxx.xxx/index.php

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
