### ISSUE TITLE
An error occurred during LDAP configuration 

### ISSUE THREAD

**Issue by tengdagg** [nilsteampassnet/TeamPass#3733]
LDAP configuration completed click on the perform button does not respond, Teampass version 3.0.8 and 3.0.9 Both have been tried, browser developer mode view /sources/ldap.queries.php 500 internal server error, PHP version 8.2.6, check the error log.

**php-fpm Log**

PHP Fatal error:  Uncaught TypeError: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 96 and defined in /var/www/html/includes/libraries/Carbon/Traits/Creator.php:894
Stack trace:
#0 /var/www/html/includes/libraries/Carbon/Traits/Creator.php(96): Carbon\Carbon::setLastErrors()
#1 /var/www/html/includes/libraries/Carbon/Traits/Creator.php(250): Carbon\Carbon->__construct()
#2 /var/www/html/includes/libraries/LdapRecord/Connection.php(495): Carbon\Carbon::now()
#3 /var/www/html/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\Connection->retryOnNextHost()
#4 /var/www/html/sources/ldap.queries.php(168): LdapRecord\Connection->connect()
#5 {main}
  thrown in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 894
  
 **Screenshots** 
![image](https://github.com/nilsteampassnet/TeamPass/assets/66817449/cfedecc4-fb79-4cf7-b382-246c0ff8ada8)
always  In progress

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
