### ISSUE TITLE
Configuring LDAP Login Authentication 500 Internal Server Error 

### ISSUE THREAD

**Issue by tengdagg** [nilsteampassnet/TeamPass#3738]
**### Steps to reproduce**
1.Configuring LDAP Login Authentication
**### Expected behaviour**
Tell us what should happen
Configure LDAP user login to get the users in it
**### Actual behaviour**
When I configured LDAP, I filled in all the information, which worked fine in 3.0.6, but the user could not import it, so I replaced 3.0.8 and 3.0.9 to test it and it kept showing in progress when I clicked the perform button, and I saw sources/ldap.series.php POST in browser developer mode 500 Internal Server Error 

### Server configuration
**Operating system**:
Rocky 8.5
Memory 8g
CPU 4 cores
Hard disk 100G
**Web server:**
nginx version: nginx/1.23.3
**Database:**
mysql  Ver 15.1 Distrib 10.3.35-MariaDB
**PHP version:**
PHP 8.2.6 (cli)
**Teampass version:** 
3.0.8 & 3.0.9
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'https://xxx.xxx.xxx.xxx',
    'favicon' => 'https://xxx.xxx.xxx.xxx/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'https://xxx.xxx.xxx.xxx/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.8',
    'ldap_mode' => '0',
    'ldap_type' => 'OpenLDAP',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'sAMAccountName',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1682242952',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '1',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'uyFMYpkazN6bg5Tq9rjdsuYgjKduV3aGrzGpXyuc',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => 'dn',
    'ldap_dn_additional_user_dn' => 'DC=test,DC=com',
    'ldap_user_object_filter' => 'SAMAccountName=*',
    'ldap_bdn' => 'DC=test,DC=com',
    'ldap_hosts' => 'xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx',
    'ldap_password' => 'xxxxxxxx',
    'ldap_username' => 'xxxxxxxxx',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1684834952',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
### Client configuration
**Browser:**
Chrome 113.0.5672.127
**Operating system:**

#### Web server error log
```
PHP Fatal error:  Uncaught TypeError: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 96 and defined in /var/www/html/includes/libraries/Carbon/Traits/Creator.php:894
Stack trace:
#0 /var/www/html/includes/libraries/Carbon/Traits/Creator.php(96): Carbon\Carbon::setLastErrors()
#1 /var/www/html/includes/libraries/Carbon/Traits/Creator.php(250): Carbon\Carbon->__construct()
#2 /var/www/html/includes/libraries/LdapRecord/Connection.php(495): Carbon\Carbon::now()
#3 /var/www/html/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\Connection->retryOnNextHost()
#4 /var/www/html/sources/ldap.queries.php(168): LdapRecord\Connection->connect()
#5 {main}
  thrown in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 894
Insert your webserver log here
```
xxx.xxxx.xxx.xxx - - [24/May/2023:09:26:41 +0800] "GET /plugins/jqueryUI/jquery-ui.min.css HTTP/1.1" 200 32130 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/simplePassMeter/simplePassMeter.css HTTP/1.1" 200 1345 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/radioforbuttons/bootstrap-buttons.min.css HTTP/1.1" 200 15611 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/icheck/skins/all.css HTTP/1.1" 200 1568 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/toggles/css/toggles.css HTTP/1.1" 200 485 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/toggles/css/toggles-modern.css HTTP/1.1" 200 1657 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/adminlte/css/adminlte.min.css.map HTTP/1.1" 200 3846965 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/popper/umd/popper.min.js.map HTTP/1.1" 200 123754 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/bootstrap/js/bootstrap.bundle.min.js.map HTTP/1.1" 200 311239 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/adminlte/js/adminlte.min.js.map HTTP/1.1" 200 135565 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:41 +0800] "GET /plugins/toastr/toastr.js.map HTTP/1.1" 200 25633 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:42 +0800] "POST /sources/main.queries.php HTTP/1.1" 200 1415 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:42 +0800] "GET /plugins/DOMPurify/purify.min.js.map HTTP/1.1" 200 89108 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:42 +0800] "POST /sources/main.queries.php HTTP/1.1" 200 66 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:42 +0800] "POST /sources/admin.queries.php HTTP/1.1" 200 1243 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:43 +0800] "POST /sources/main.queries.php HTTP/1.1" 200 1107 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
xxx.xxxx.xxx.xxx  - - [24/May/2023:09:26:43 +0800] "POST /sources/admin.queries.php HTTP/1.1" 200 871 "https://xxx.xxxx.xxx.xxx /index.php?page=ldap" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
DevTools failed to load source map: Could not load content for chrome-extension://hcdecchpaljedbebgdehfcjcmmplojpp/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
index.php:1 Mixed Content: The page at 'https://xxxxxx/index.php?page=ldap' was loaded over HTTPS, but requested an insecure element 'https://172.20.0.50/includes/images/teampass-logo2-home.png'. This request was not upgraded to HTTPS because its URL's host is an IP address.
index.php:104 Mixed Content: The page at 'https://xxxxxx/index.php?page=ldap' was loaded over HTTPS, but requested an insecure element 'https://172.20.0.50/includes/images/teampass-logo2-home.png'. This request was not upgraded to HTTPS because its URL's host is an IP address.
index.php?page=ldap:2486 Loading settings result:
index.php?page=ldap:2487 {enable_favourites: '1', enable_pf_feature: '0', ldap_user_attribute: 'sAMAccountName', google_authentication: '0', duo: '0', …}
DevTools failed to load source map: Could not load content for chrome-extension://hcdecchpaljedbebgdehfcjcmmplojpp/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
index.php?page=ldap:2957 {field: 'ldap_new_user_is_administrated_by', value: '1'}
index.php?page=ldap:2619 Refresh last item seen result
index.php?page=ldap:2620 {error: '', existing_suggestions: 0, html_json: Array(0)}
index.php?page=ldap:1179 Get user info results:
index.php?page=ldap:1180 {error: false, message: '', queryResults: {…}}
index.php?page=ldap:2982 {error: false, misc: '1 ; 1'}
index.php?page=ldap:3006 ldap-test-config
jquery.min.js:2     POST https://xxxxxx/sources/ldap.queries.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
S.<computed> @ jquery.min.js:2
(anonymous) @ index.php?page=ldap:3017
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Insert the log here and especially the answer of the query that failed.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
