### ISSUE TITLE
TEAMPASS USERS.QUERIS.PHP BUG ?? 

### ISSUE THREAD

**Issue by dylantellier93** [nilsteampassnet/TeamPass#3742]
### Page on which it happened

Bonjour,
Nous rencontrons un problème après la mise à jour de Teampass.
J'essaie d'ajouter un utilisateur via Synchronisation LDAP, je fais réaliser puis ça tourne dans le vide. et rien ne se produit.

J'ai vérifié les logs dans /var/log/apache2/error.log voici le message que j'obtiens : 

 AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect integer value: '["0"]' for column `teampassdb`.`teampass_users`.`isAdministratedByRole` at row 1 in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(360): MeekroDB->query()\n#4 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()\n#5 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()\n#6 /var/www/html/TeamPass/sources/users.queries.php(2775): DB::insert()\n#7 {main}\n  thrown in /var/www/html/TeamPass/includes/libr...', referer: https://teampass.ght-gpne.fr/TeamPass/index.php?page=users

Il y a un problème aussi, quand je tente la modification d'un utilisateurs juste en changeant sont rôle par exemple, ça ne prend pas en compte, en revanche 0 messages d'erreur dans le error.log.
 

### Steps to reproduce
1. Utilisateurs 
2. Synchronisation LDAP
3. Actions + Ajouter un nouvel utilisateur dans TeamPass
4. Choisir le Roles
5. Réaliser

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Linux AG-TEAMPASS 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64

**Web server:** Apache/2.4.38 (Debian)

**Database:** 10.3.38-MariaDB-0+deb10u1

**PHP version:** 8.2.6

**Teampass version:** 3.0.9

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '1',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/TeamPass',
'cpassman_url' => 'https://<anonym_url>/TeamPass
'favicon' => 'https://<anonym_url>/TeamPass/favicon.ico',
'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
'path_to_files_folder' => '/var/www/html/TeamPass/files',
'url_to_files_folder' => 'https://<anonym_url>/TeamPass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '1',
'encryptClientServer' => '1',
'cpassman_version' => '3.0.0.22',
'ldap_mode' => '1',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => 'samaccountname',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '1',
'anyone_can_modify_bydefault' => '1',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '1',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => '',
'custom_login_text' => '',
'default_language' => 'french',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1666915920',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => 'https://<anonym_url>/TeamPass/',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '1',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '<removed>'
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass GPNE',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '30',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/TeamPass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => '<removed>'
'syslog_port' => '514',
'manager_move_item' => '1',
'create_item_without_password' => '1',
'otv_is_enabled' => '1',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'UTC',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '["0"]',
'disable_show_forgot_pwd_link' => '1',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '1',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_ikey' => '<removed>'
'duo_skey' => '<removed>'
'duo_host' => '<removed>'
'duo_failmode' => 'secure',
'teampass_version' => '3.0.9',
'roles_allowed_to_print_select' => '[2]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '[1,2,6]',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '0',
'email_debug_level' => '0',
'ga_reset_by_user' => '0',
'onthefly-backup-key' => '<removed>'
'onthefly-restore-key' => '<removed>'
'ldap_user_dn_attribute' => 'distinguishedname',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '(objectCategory=Person)(sAMAccountName=*)(memberof=CN=TEAMPASS,OU=TEAMPASS,OU=APPLICATIONS,OU=GHT,OU=SITES,DC=GHT-GPNE,DC=FR)',
'ldap_bdn' => 'DC=GHT-GPNE,DC=FR',
'ldap_hosts' => '<removed>'
'ldap_password' => '<removed>'
'ldap_username' => 'CN=svc_ag_teampass,OU=Comptes de Services,OU=GHT,OU=SITES,DC=GHT-GPNE,DC=FR',
'api_token_duration' => '60',
'enable_tasks_manager' => '1',
'task_maximum_run_time' => '300',
'tasks_manager_refreshing_period' => '20',
'maximum_number_of_items_to_treat' => '100',
'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
'can_create_root_folder' => '1',
'ldap_new_user_role' => '1',
'max_last_items' => '20',
'item_creation_templates' => '0',
'enable_tasks_log' => '0',
'enable_ad_users_with_ad_groups' => '1',
'enable_ad_user_auto_creation' => '0',
'ldap_group_object_filter' => '',
'ldap_guid_attibute' => 'objectguid',
'sending_emails_job_frequency' => '2',
'user_keys_job_frequency' => '1',
'items_statistics_job_frequency' => '5',
'maintenance_job_frequency' => '59',
'maintenance_job_tasks' => '[]',
'upgrade_timestamp' => '1685223949',

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:**  - 

**Operating system:**  - bits

#### Web server error log
```
 -  ()
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Knoppix1** [comment]
Exactement même soucis ici ! fresh install, Mariadb 10.11.3
Il aime pas le '["0"]' qui devrait etre "0" je suppose ? peut être un changement avec les version récente de mariadb ?
Merci pour le travaille que vous fournissait :) hâte de pouvoir tester cette v3 enfin !

**Comment by NaumovAlexey** [comment]
The same error. Workaround by [dylantellier93] is working
