### ISSUE TITLE
Passwords items are getting blank after an admin change a user password

### ISSUE THREAD

**Issue by jussara-ti** [nilsteampassnet/TeamPass#3743]
### Steps to reproduce
1. Create a new user
2. With that user, create items and store passwords in user personal folder
3. With an admin account, change login password of the user
4. Login with the new password
5. Check if the items created before are still visible

### Expected behaviour
after logging user can see and use their stored passwords normally

### Actual behaviour
after logging all stored passwords created before the passoword change went blank. User can't see or use their stored passwords.
This only happens if one admin change the user password, but not when the user himself change it.

![Captura de tela 2023-05-29 083313](https://github.com/nilsteampassnet/TeamPass/assets/60328341/3a4cd0da-e39b-4b98-b17b-91dee49cdaf3)

![Captura de tela 2023-05-29 083405](https://github.com/nilsteampassnet/TeamPass/assets/60328341/7d0b6b49-68fc-4509-80ff-c7c1a4b4b0d5)

### Server configuration
**Operating system**: Debian Linux 11

**Web server:** Apache/2.4.56 (Debian)

**Database:** MariaDB

**PHP version:** PHP 7.4.33

**Teampass version:** 3.0.5

**Teampass configuration file:** 
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'https://<anonym_url>
'favicon' => 'https://<anonym_url>/favicon.ico',
'path_to_upload_folder' => '/opt/teampass/upload',
'path_to_files_folder' => '/opt/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'teampass_version' => '3.0.5',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '0',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '5',
'utf8_enabled' => '1',
'restricted_to' => '1',
'restricted_to_roles' => '1',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '1',
'custom_logo' => 'includes/images/logo-jussara.png',
'custom_login_text' => 'Gerenciador de senhas Jussara',
'default_language' => 'portuguese_br',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1677338004',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '1',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '587',
'email_security' => 'tls',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '0',
'proxy_ip' => '<removed>'
'proxy_port' => '',
'upload_maxfilesize' => '1mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '30',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => '<removed>'
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'America/Sao_Paulo',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '0',
'offline_key_level' => '38',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'bck_script_passkey' => '<removed>'
'admin_2fa_required' => '1',
'password_overview_delay' => '4',
'copy_to_clipboard_small_icons' => '1',
'duo_ikey' => '<removed>'
'duo_skey' => '<removed>'
'duo_host' => '<removed>'
'duo_failmode' => 'secure',
'roles_allowed_to_print_select' => '',
'clipboard_life_duration' => '20',
'mfa_for_roles' => '',
'tree_counters' => '0',
'settings_offline_mode' => '0',
'settings_tree_counters' => '0',
'enable_massive_move_delete' => '0',
'email_debug_level' => '0',
'ga_reset_by_user' => '',
'onthefly-backup-key' => '<removed>'
'onthefly-restore-key' => '<removed>'
'ldap_user_dn_attribute' => '',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '',
'ldap_bdn' => '',
'ldap_hosts' => '<removed>'
'ldap_password' => '<removed>'
'ldap_username' => '',
'api_token_duration' => '300',
'enable_tasks_manager' => '1',
'task_maximum_run_time' => '600',
'tasks_manager_refreshing_period' => '20',
'maximum_number_of_items_to_treat' => '100',
'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
'enable_tasks_log' => '1',
'upgrade_timestamp' => '1681412108',
'enable_ad_users_with_ad_groups' => '0',
'enable_ad_user_auto_creation' => '0',
'ldap_group_object_filter' => '',
'ldap_guid_attibute' => 'objectguid',
'new_api_key_label' => 'Script Actions',
```

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
@jussara-ti 
You should update to latest commit.
Lot of changes have been introduced regarding this.

**Comment by jussara-ti** [comment]
I updated to the latest commit [2b998b6](https://github.com/nilsteampassnet/TeamPass/commit/2b998b6a0f69df7bf98d2c148238e75f0f8bd402)

First of all I saw that you implemented a suggestion that I gave you of make the actions automatic and scheduleable. Thanks, I appreciate it!

Now, returning to the error, it keeps happening in the latest version, just like I reported before
In the apache log I have this:
```
[Wed May 31 11:22:38.251253 2023] [php7:notice] [pid 2274] [client 192.168.1.225:53724] PHP Notice:  Undefined offset: 1 in /var/www/html/teampass/pages/tasks.php on line 207, referer: https://192.168.2.235/index.php?page=users
[Wed May 31 11:22:38.251362 2023] [php7:notice] [pid 2274] [client 192.168.1.225:53724] PHP Notice:  Undefined offset: 1 in /var/www/html/teampass/pages/tasks.php on line 225, referer: https://192.168.2.235/index.php?page=users
[Wed May 31 11:22:38.251407 2023] [php7:notice] [pid 2274] [client 192.168.1.225:53724] PHP Notice:  Undefined offset: 1 in /var/www/html/teampass/pages/tasks.php on line 261, referer: https://192.168.2.235/index.php?page=users
```
When the admin clicks to change the user password and the task are running there's no error in the browser console
But when the user itself  wants to change his password and fill the password change form (in the window below) there's an error in the browser console:
![Captura de tela 2023-05-31 095025](https://github.com/nilsteampassnet/TeamPass/assets/60328341/a16f52b7-0d5b-4a45-86ec-f01aa2ac3267)
```
Uncaught TypeError: ((S.event.special[o.origType] || {}).handle || o.handler).apply is not a function
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```
Don't know if this error shown in browser console is related, because when the user itself changes their password all works fine, the error only occours when an admin change the user password, like I said before

Thanks for the attention

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
