### ISSUE TITLE
Undefined array key "mbstring" 

### ISSUE THREAD

**Issue by titanmusk** [nilsteampassnet/TeamPass#3762]
### Steps to reproduce
1.Fresh Teampass install on Debian GNU/Linux 11 (bullseye) with PHP 8.2 and 10.5.19-MariaDB-0+deb11u2 Debian 11
2. Configure LDAP Authentication
3. Test current configuration

### Expected behaviour
the Admin user should be authenticated

### Actual behaviour
**Web server:**
Apache/2.4.56 (Debian)

**Teampass version:** 
 3.0.9

#### Web server error log
```
Tue Jun 20 14:18:43.944237 2023] [proxy_fcgi:error] [pid 57217] [client 192.168.0.65:47082] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "mbstring" in /var/www/html/TeamPass/includes/libraries/portable-utf8-master/src/voku/helper/UTF8.php on line 5582; PHP message: PHP Fatal error:  Uncaught TypeError: Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /var/www/html/TeamPass/includes/libraries/Carbon/Traits/Creator.php on line 96 and defined in /var/www/html/TeamPass/includes/libraries/Carbon/Traits/Creator.php:894\nStack trace:\n#0 /var/www/html/TeamPass/includes/libraries/Carbon/Traits/Creator.php(96): Carbon\\Carbon::setLastErrors()\n#1 /var/www/html/TeamPass/includes/libraries/Carbon/Traits/Creator.php(250): Carbon\\Carbon->__construct()\n#2 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(495): Carbon\\Carbon::now()\n#3 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\\Connection->retryOnNextHost()\n#4 /var/www/html/TeamPass/sources/ldap.queries.php(168): LdapRecord\\Connection->connect()\n#5 {main}\n  thrown in /var/www/html/TeamPass/includes/libraries/Carbon/Traits/Creator.php on line 894', referer: http://10.7.1.155/index.php?page=ldap
```

**Comment by titanmusk** [comment]
![001-2023-06-20-2023-06-20 17-23-27](https://github.com/nilsteampassnet/TeamPass/assets/53436340/2e6d955a-9a8b-4e53-a22f-9ca3a4a87d29)

**Comment by ftoledo** [comment]
hi all!
I dont use ldap (for now) and see same warnings in docker logs:

```
[30-Jun-2023 15:25:19] WARNING: [pool www] child 27 said into stderr: "NOTICE: PHP message: PHP Warning:  Undefined array key "mbstring" in /var/www/html/includes/libraries/portable-utf8-master/src/voku/helper/UTF8.php on line 5582"
```

**Comment by AKorolkovs** [comment]
Have you tried to comment /var/www/html/includes/libraries/portable-utf8-master/src/voku/helper/UTF8.php function on line 5582 ?

**Comment by titanmusk** [comment]
i switch php to 7.4 because in 8.2 mbstring extension not found, on php7.4fpm same issue with "undefined array key 'mbstring'" i comment line 5582 and the error disappears

I have filled in all fields, but sync with ldap not going 
![001-2023-07-04-2023-07-04 12-41-10](https://github.com/nilsteampassnet/TeamPass/assets/53436340/c8129788-b3bc-403e-b37b-7688b9aea07b)

go to ldap settings
![001-2023-07-04-2023-07-04 12-44-33](https://github.com/nilsteampassnet/TeamPass/assets/53436340/c437ecae-51c6-4b94-8a7a-b7c0248a07a9)
```
[Tue Jul 04 09:32:36.341246 2023] [php7:error] [pid 126662] [client 192.168.0.65:57090] PHP Fatal error:  Uncaught ErrorException: ldap_search(): Search: Bad search filter in /var/www/html/TeamPass/includes/libraries/LdapRecord/Ldap.php:235\nStack trace:\n#0 [internal function]: LdapRecord\\Ldap->LdapRecord\\{closure}()\n#1 /var/www/html/TeamPass/includes/libraries/LdapRecord/Ldap.php(235): ldap_search()\n#2 /var/www/html/TeamPass/includes/libraries/LdapRecord/HandlesConnection.php(171): LdapRecord\\Ldap->LdapRecord\\{closure}()\n#3 /var/www/html/TeamPass/includes/libraries/LdapRecord/Ldap.php(237): LdapRecord\\Ldap->executeFailableOperation()\n#4 /var/www/html/TeamPass/includes/libraries/LdapRecord/Query/Builder.php(716): LdapRecord\\Ldap->search()\n#5 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(394): LdapRecord\\Query\\Builder->LdapRecord\\Query\\{closure}()\n#6 /var/www/html/TeamPass/includes/libraries/LdapRecord/Connection.php(352): LdapRecord\\Connection->runOperationCallback()\n#7 /var/www/html/TeamPass/includes/libraries/LdapRecord/Query/Builder.php(718): LdapRecord\\Connection->run()\n#8 /var/www/html/T in /var/www/html/TeamPass/includes/libraries/LdapRecord/LdapRecordException.php on line 26, referer: http://10.0.0.4/index.php?page=users

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
