### ISSUE TITLE
Cant recieve E-mail

### ISSUE THREAD

**Issue by djbotelho** [nilsteampassnet/TeamPass#3786]
### Steps to reproduce
1. Create new user
2.
3.

### Expected behaviour
Recieve First time password by email

### Actual behaviour
I never recieve the e-mail to get the password when creating an user, but the test e-mail and google authentication work.

### Server configuration
debian 11.6

**Web server:**
apache2
**Database:**
mariadb
**PHP version:**
7.4.33
**Teampass version:** 
3.0.9
**Teampass configuration file:**

<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '1',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/TeamPass',
    'cpassman_url' => 'http://10.10.90.45/TeamPass',
    'favicon' => 'http://10.10.90.45/TeamPass/icon2.ico',
    'path_to_upload_folder' => '/var/www/html/TeamPass/upload',
    'path_to_files_folder' => '/var/www/html/TeamPass/files',
    'url_to_files_folder' => 'http://10.10.90.45/TeamPass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.9',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '1',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'https://en.wikipedia.org/wiki/File:Blank_button.svg',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1685291710',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'smtp.office365.com',
    'email_smtp_auth' => '1',
    'email_auth_username' => 'daniel.botelho@*****.********',
    'email_auth_pwd' => '*********',
    'email_port' => '587',
    'email_security' => 'tls',
    'email_server_url' => '',
    'email_from' => 'daniel.botelho@*****.********',
    'email_from_name' => 'Daniel Botelho',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '1000mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/TeamPass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '1234',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '1',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '1234',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '500',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '1',
    'upgrade_timestamp' => '1687883710',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '1',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => 'hourly;11:09',
    'clean_orphan_objects_task' => 'daily;23:30',
    'purge_temporary_files_task' => 'daily;23:45',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
    'can_create_root_folder' => '1',
    'rebuild_config_file_task' => 'hourly;00:48',
);

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by djbotelho** [comment]
![Picture1](https://github.com/nilsteampassnet/TeamPass/assets/113935790/23c02356-527c-48c4-95d0-e4d45360d198)

**Comment by nilsteampassnet** [comment]
OK so user received the email.
So not a defect

**Comment by djbotelho** [comment]
> OK so user received the email. So not a defect

But is it supposed to take so long to get a password?
Is there any setting that i should Change?

**Comment by djbotelho** [comment]
Im pretending to create more than 100 users

**Comment by nilsteampassnet** [comment]
It depends on the number of items you have in your database and the power of your server.
The email is sent to the user when his account is ready meaning that all item keys are ready.
But taking 2 hours makes me think that your server hasn't enough CPUs and/or RAM.

**Comment by pankajmishra15** [comment]
I'm experiencing a critical issue with TeamPass version 3.1.3.13 related to user creation and email notifications. Here's a detailed overview:

**Issue Summary:**

**Problem:** After creating a new user, the expected email notification isn't sent.
**Observations:**

- Test emails function correctly, indicating that the SMTP configuration is likely correct.
- Even after setting up a fresh TeamPass instance with an empty database, the issue persists.
- issue which i found in error logs

thrown in /teampass/vendor/peppeocchi/php-cron-scheduler/src/GO/Job.php on line 395
[18-Feb-2025 11:02:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function GO\exec() in /teampass/vendor/peppeocchi/php-cron-scheduler/src/GO/Job.php:395
Stack trace:
#0 /teampass/vendor/peppeocchi/php-cron-scheduler/src/GO/Scheduler.php(177): GO\Job->run()
#1 /teampass/sources/scheduler.php(107): GO\Scheduler->run()
#2 {main}
  thrown in /teampass/vendor/peppeocchi/php-cron-scheduler/src/GO/Job.php on line 395

**Steps Taken:**

**Verified SMTP Settings:**

Confirmed that test emails are sent successfully, suggesting proper SMTP configuration.
**Checked Cron Jobs:**

Ensured that the cron job for scheduler.php is set up and running as expected.
**Reviewed User Management Settings:**

Verified that user roles and permissions are correctly assigned during creation.
Consulted Documentation and Community Forums:

Searched for similar issues but found no recent reports matching this problem.
**Impact:**

_**This issue hampers the onboarding process, as new users don't receive their login credentials via email, rendering them unable to access the system.**_

**### Request for Assistance:**

I'm seeking guidance or solutions from the community to resolve this matter promptly. If anyone has encountered a similar issue or has insights into potential causes and fixes, your input would be greatly appreciated.

Thank you for your support.
