### ISSUE TITLE
Cant login using LDAP

### ISSUE THREAD

**Issue by NaumovAlexey** [nilsteampassnet/TeamPass#3787]
### Steps to reproduce
1. update to 3.0.10
2. try to login with LDAP user
3.

### Expected behaviour
Should log in normally

### Actual behaviour
See banner In progress.
If login as admin, in logs see that user logged in normally

### Server configuration
Operating system: Linux 5.15.0-69-generic https://github.com/nilsteampassnet/TeamPass/issues/76 SMP Fri Mar 17 17:19:29 UTC 2023 x86_64

Web server: Apache/2.4.52 (Ubuntu)

Database: 8.0.32-0ubuntu0.22.04.2

PHP version: 8.1.2-1ubuntu2.11

Teampass version: 3.0.10

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
[Tue Jul 11 15:51:27.359046 2023] [proxy_fcgi:error] [pid 2691744] [client 172.16.<>:7915] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Data too long for column 'process_type' at row 1 in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682\nStack trace:\n#0 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()\n#1 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#2 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#3 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(361): MeekroDB->query()\n#4 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace()\n#5 /var/www/html/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert()\n#6 /var/www/html/sources/identify.php(756): DB::insert()\n#7 /var/www/html/sources/identify.php(114): identifyUser()\n#8 {main}\n  thrown in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php on line 682', referer: https://teampass.<domain>/




Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Please upgrade to latest commit to get rid of the error you have in your logs
This will not solve the ldap issue anyhow.

I would need to test on your server, possible?

**Comment by NaumovAlexey** [comment]
I have already updated to latest commit.
But in browser developer mode I see this error
![image](https://github.com/nilsteampassnet/TeamPass/assets/35455601/ea3305c1-e2d0-4294-a39d-f6619ac74a7b)

**Comment by tuxlinuxbr** [comment]
Hi, 

After upgrade from 3.0.9 to 3.0.10 (6f22a379a9bc004e0285797a1043a4c08fea6006) I have the same problem. Some users, get HTTP 500 and in the log I get :

```
 child 22 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Data too long for column 'process_type' at row 1 in /var/www/html/includes/libraries/Database/Meekrodb/db.class.php:682"
"POST /sources/identify.php HTTP/1.1" 500 5 "https://teampass.domain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
```

**Comment by rafikberzi** [comment]
Same issue, need to delete from teampass_cache_tree each time he logout to re-login..

**Comment by nilsteampassnet** [comment]
> I have already updated to latest commit.
> 
OK but did you run the upgrade? 
This should fix the column size

**Comment by tuxlinuxbr** [comment]
Yes. I did.

**Comment by NaumovAlexey** [comment]
In neighbor topic  found a solution for this trouble 
https://github.com/nilsteampassnet/TeamPass/issues/3795#issuecomment-1643863719

**Comment by tuxlinuxbr** [comment]
Solution on #3795 work fine! 

Thank you!

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
