### ISSUE TITLE
Database Import

### ISSUE THREAD

**Issue by djbotelho** [nilsteampassnet/TeamPass#3797]
Im trying to import everthing manually from v2 to v3 using mysql workbench.

Ive sucessfully imported folders, roles, users , roles permissions and passwords.

The passwords appear on the database but they dont show in the application. Do you know what seems to be the problem?
Im using the table teampass_items

![image](https://github.com/nilsteampassnet/TeamPass/assets/113935790/f06c54e5-141e-492f-80ff-118ec6bb327a)

**Comment by nilsteampassnet** [comment]
This is not possible.
Must use upgrade process

**Comment by djbotelho** [comment]
> This is not possible. Must use upgrade process

Is it possible to upgrade on CentOS?

**Comment by djbotelho** [comment]
Can you explain the correct way to export items from the old version to the new one?

I tried using the web interface but it didnt work. When I import it stays on "Reading file" forever.

Thank you

![image](https://github.com/nilsteampassnet/TeamPass/assets/113935790/b3a2dfe2-93bd-494b-9303-2af351d30ebc)

![image](https://github.com/nilsteampassnet/TeamPass/assets/113935790/7128da71-c715-42ad-9419-a7e83b559bb8)

**Comment by nilsteampassnet** [comment]
You can do this way.
Please check the data format with help.
What is the Apache log error you get when importing?

**Comment by djbotelho** [comment]
Column size should be 1, but 2 columns given in /var/www/html/TeamPass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php:119\nStack trace:\n#0 /var/www/html/TeamPass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php(42): Goodby\\CSV\\Import\\Standard\\Interpreter->checkRowConsistency()\n#1 /var/www/html/TeamPass/includes/libraries/Goodby/CSV/Import/Standard/Lexer.php(68): Goodby\\CSV\\Import\\Standard\\Interpreter->interpret()\n#2 /var/www/html/TeamPass/sources/import.queries.php(177): Goodby\\CSV\\Import\\Standard\\Lexer->parse()\n#3 {main}\n  thrown in /var/www/html/TeamPass/includes/libraries/Goodby/CSV/Import/Standard/Interpreter.php on line 119, referer: http://10.10.90.45/TeamPass/index.php?page=import
 
 
 I think this might be the problem?

**Comment by DaveWebb2** [comment]
The upgrade doesn't work for me so I've tried importing from .CSV and get the same error as you - did you find a solution?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
