### ISSUE TITLE
Upgrade from 2.1.27.35 to 3.0.9 Fails on Finalize step with PHP error

### ISSUE THREAD

**Issue by alandmoore** [nilsteampassnet/TeamPass#3815]
### Steps to reproduce
1.  Start with 2.1.27.35 Teampass
2. Follow instructions to upgrade to 3.0.9
3. Finalize step does not complete

### Expected behaviour

The finalize step should have finished

### Actual behaviour

The finalize step did not finish

### Server configuration
**Operating system**: Debian 12

**Web server:** Apache 2.4.57

**Database:** Maria DB 10.11.3

**PHP version:** 8.2

**Teampass version:** 3.0.9

**Teampass configuration file:**
```
<?php
// DATABASE connexion parameters
define("DB_HOST", "localhost");
define("DB_USER", "teampass_admin");
define("DB_PASSWD", "redacted");
define("DB_NAME", "teampass");
define("DB_PREFIX", "teampass_");
define("DB_PORT", 3306);
define("DB_ENCODING", "utf8");
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    'MYSQLI_OPT_CONNECT_TIMEOUT' => 10
));
define("SECUREPATH", "/srv/teampass-etc");
define("SECUREFILE", "teampass-seckey.txt");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}

```

**Updated from an older Teampass or fresh install:** Updated

### Client configuration
**Browser:** Firefox

**Operating system:** Arch Linux

#### Web server error log

This error appears at fail time:
```
PHP Fatal error:  Uncaught TypeError: mysqli::options(): Argument #1 ($option) must be of type int, string given in /srv/www/html-3.0.9-post-bookworm/includes/libraries/Database/Meekrodb/db.class.php:188\nStack trace:\n#0 /srv/www/html-3.0.9-post-bookworm/includes/libraries/Database/Meekrodb/db.class.php(188): mysqli->options()\n#1 /srv/www/html-3.0.9-post-bookworm/includes/libraries/Database/Meekrodb/db.class.php(648): MeekroDB->get()\n#2 /srv/www/html-3.0.9-post-bookworm/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#3 /srv/www/html-3.0.9-post-bookworm/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#4 /srv/www/html-3.0.9-post-bookworm/includes/libraries/Database/Meekrodb/db.class.php(65): MeekroDB->query()\n#5 /srv/www/html-3.0.9-post-bookworm/sources/main.functions.php(2134): DB::query()\n#6 /srv/www/html-3.0.9-post-bookworm/install/upgrade_ajax.php(886): handleConfigFile()\n#7 {main}\n  thrown in /srv/www/html-3.0.9-post-bookworm/includes/libraries/Database/Meekrodb/db.class.php on line 188, referer: https://teampass.williamson-tn.org/install/upgrade.php

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. upgrade.php
[NoScript]:0 Prompt Hook installation https://teampass.williamson-tn.org/install/upgrade.php log.js:32:13
TypeError: e.matches is not a function modules.min.js:5:8413
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ jquery.min.js:2:81867
Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
    complete https://teampass.williamson-tn.org/install/upgrade.php:200
    jQuery 6
    <anonymous> https://teampass.williamson-tn.org/install/upgrade.php:192
    jQuery 2
upgrade.php:200:26
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://1acc4778-780e-45f0-9143-3509278e1f81/content_scripts/modules.min.js
Source Map URL: purify.min.js.map
```

[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/12292729/tp.config.php.txt)

**Comment by alandmoore** [comment]
Through some debugging, I think I've determined that the option that's throwing the error is `MYSQLI_OPT_CONNECT_TIMEOUT`.  This is specified as an integer in my settings file, so not sure how it's becoming a string.

**Comment by alandmoore** [comment]
So, I managed to work around this by not setting MSQLI_OPT_CONNECT_TIMEOUT in my settings file, though I still had to define DB_CONNECT_OPTIONS as an empty array or I'd get an error about it not being defined.

My site is upgraded for now, but it would be nice to be able to set the timeout.

**Comment by alandmoore** [comment]
Well, one more thing (sorry for all the comments); even though I finished I'm still getting forwarded to the upgrade wizard trying to access my site.  So something didn't quite finish up here.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
