### ISSUE TITLE
item password is not copied

### ISSUE THREAD

**Issue by Andre-SMedina** [nilsteampassnet/TeamPass#3830]
Steps to reproduce
1. create user through ldap
2. copy password that was granted access by manager

Expected behaviour
copy to clipboard

Actual behaviour
nothing

 Server configuration
debian 11:

**Web server:**
apache 2.4.57
**Database:**
Mariadb 10.11.4
**PHP version:**
PHP 8.2.7
**Teampass version:** 
3.0.10
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**

### Client configuration
google chrome

**Operating system:**
ubuntu 22.04.3 LTS

### Logs

Uncaught TypeError: t.hasAttribute is not a function
    at t.exports (clipboard.min.js:7:7732)
    at l (clipboard.min.js:7:1050)
    at s (clipboard.min.js:7:2002)
    at r.value (clipboard.min.js:7:4820)
    at HTMLBodyElement.<anonymous> (clipboard.min.js:7:4705)
    at HTMLBodyElement.<anonymous> (clipboard.min.js:7:5866)
t.exports @ clipboard.min.js:7
l @ clipboard.min.js:7
s @ clipboard.min.js:7
value @ clipboard.min.js:7
(anonymous) @ clipboard.min.js:7
(anonymous) @ clipboard.min.js:7

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by Andre-SMedina** [comment]
when copying a password using a non-LDAP created user, password copying works

**Comment by nilsteampassnet** [comment]
On what page is the copy buton you are using (list or item)?

**Comment by Andre-SMedina** [comment]
list. Item don't open.

Em sex., 18 de ago. de 2023 às 09:26, Nils Laumaillé <
***@***.***> escreveu:

**Comment by nilsteampassnet** [comment]
If item doesn't open then you have a more global issue.
Please reinstall, clear the browser cache, something is wrong somewhere in your Teampass instance.

**Comment by Youen-MB** [comment]
Hi, I have same problem, for the 2 users I created. 
Impossible to copy here: 
![image](https://github.com/nilsteampassnet/TeamPass/assets/62390131/9b725314-e84a-4f36-a073-9de4c3e08617)

I had try in 2 computers, clear cache. It's a fresh install with SSL certificate auto signed (for the moment)

**Comment by aleks001** [comment]
I have this same issue as Youen, funny enough though If i go through the folder list and copy a password then when I go back to the search list it starts working.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
