### ISSUE TITLE
Error with LHS menu

### ISSUE THREAD

**Issue by bradsyd** [nilsteampassnet/TeamPass#3858]
### Steps to reproduce
When logging in the menu items on the pages TASKS and INFORMATION do not work.
The links all point to that same page.
If I manually change the page to another poage I can navigate as long as I don't click on the 2 menu items above.

### Expected behaviour
Tell us what should happen
When logging in the menu items on the pages TASKS and INFORMATION do not work.
The links all point to that same page.
If I manually change the page to another poage I can navigate as long as I don't click on the 2 menu items above.

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**
what exactly do you want here

**PHP version:**
8.2

**Teampass version:** 
3.0.10.45

**Teampass configuration file:**

[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/12564275/tp.config.txt)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
FRESH install

### Client configuration
**Browser:**
Brave AND Chrome

**Operating system:**
Windows 10

#### Web server error log
```
No errors

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```

Insert the log here and especially the answer of the query that failed.
```Request URL:
https://www.groupsolutions.com.au/teampass/index.php?page=admin
Request Method:
GET
Status Code:
500
Remote Address:
43.250.142.59:443
Referrer Policy:
strict-origin-when-cross-origin

**Comment by bradsyd** [comment]
SERVER ERROR

[09-Sep-2023 10:37:34 Australia/Sydney] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /home/groupsol/public_html/teampass/sources/core.php on line 375
[09-Sep-2023 10:37:34 Australia/Sydney] PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /home/groupsol/public_html/teampass/sources/core.php on line 375
[09-Sep-2023 10:37:34 Australia/Sydney] PHP Fatal error:  Uncaught Error: Call to undefined function TiBeN\CrontabManager\exec() in /home/groupsol/public_html/teampass/includes/libraries/TiBeN/CrontabManager/CrontabAdapter.php:73
Stack trace:
#0 /home/groupsol/public_html/teampass/includes/libraries/TiBeN/CrontabManager/CrontabRepository.php(169): TiBeN\CrontabManager\CrontabAdapter->readCrontab()
#1 /home/groupsol/public_html/teampass/includes/libraries/TiBeN/CrontabManager/CrontabRepository.php(61): TiBeN\CrontabManager\CrontabRepository->readCrontab()
#2 /home/groupsol/public_html/teampass/pages/admin.php(182): TiBeN\CrontabManager\CrontabRepository->__construct()
#3 /home/groupsol/public_html/teampass/index.php(966): include('/home/groupsol/...')
#4 {main}
  thrown in /home/groupsol/public_html/teampass/includes/libraries/TiBeN/CrontabManager/CrontabAdapter.php on line 73

**Comment by bradsyd** [comment]
GET https://www.groupsolutions.com.au/teampass/index.php?page=admin 500
csrfprotector.js:134 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at Object._init (csrfprotector.js:134:27)
    at csrfprotector_init (csrfprotector.js:162:8)
    at csrfprotector.js:345:2

**Comment by nilsteampassnet** [comment]
Something is broken in the installation.
Try to overwrite the files by using latest commit.

**Comment by pstevens71** [comment]
I have this same issue.  Both on a fresh install and an upgrade install.  The lh side menu or the user menu does not work.

The only error message I get is this in console.  I've checked for PHP errors and there is something there about cron, but I don't think it's relevant.  I reset my permissions, not sure what else to try.

Failed to load resource: the server responded with a status of 500 ()

**Comment by pstevens71** [comment]
SOLVED!!!!

The issue is  line 73 calls the exec() function in PHP.  My Godaddy VPS had this disabled by default.  To enable:
1) Go to Multi PHP Manager
2) Beside PHP-FPM click on Manage Settings
3) Click on user domain settings
4) click the appropriate domain
5) you can click on the "x" exec() to remove it from disabled function.
6) restart your server, problem solved.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
