### ISSUE TITLE
Cant Delete local user

### ISSUE THREAD

**Issue by jforasetto** [nilsteampassnet/TeamPass#3872]
### Steps to reproduce
Fresh install on ubuntu server 22.04 updated& upgraded 
1.Go to User Menu 
2. Select user drop down menu 
3. Delete

### Expected behaviour
Should delete a user locally without any ldap connection.

### Actual behaviour
Dont delete user selected and dont print any message. 

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**
PHP version: 8.1.23

**Teampass version:** 
Current version loaded 3.0.10.50
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Google Chrome Version 116.0.5845.179 (Build officiel) (64 bits) 

**Operating system:**
Ubuntu 22.04.3 LTS

PHP version: 8.1.23
Memory limit: 256M
Memory usage: 584.15 KB
Maximum time execution: 60
Maximum file size upload: 100M

Server version: 10.6.12-MariaDB-0ubuntu0.22.04.1
Database size: 1.00MB

#### Web server error log
Delete User
```
2023/09/19 14:39:58 [error] 718#718: *458 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate entry 'test1_deleted' for key 'login' in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php:682
Stack trace:
#0 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#2 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#3 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(319): MeekroDB->query()
#4 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(83): MeekroDB->update()
#5 /var/www/html/TeamPass/sources/users.queries.php(422): DB::update()
#6 {main}
  thrown in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 682" while reading response header from upstream, client: 192.168.12.12, server: teampass.efixo.com, request: "POST /sources/users.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "192.168.1.9:8080", referrer: "http://192.168.1.9:8080/index.php?page=users"
2023/09/19 14:39:58 [error] 718#718: *458 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Duplicate entry 'test1_deleted' for key 'login' in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php:682
Stack trace:
#0 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query()
#1 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()
#2 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()
#3 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(319): MeekroDB->query()
#4 /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php(83): MeekroDB->update()
#5 /var/www/html/TeamPass/sources/users.queries.php(422): DB::update()
#6 {main}
  thrown in /var/www/html/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 682" while reading response header from upstream, client: 192.168.12.12, server: teampass.efixo.com, request: "POST /sources/users.queries.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "192.168.1.9:8080", referrer: "http://192.168.1.9:8080/index.php?page=users"

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
DevTools failed to load source map: Could not load content for http://192.168.1.9:8080/plugins/moment/moment.min.js.map: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
jquery.min.js:2     POST http://192.168.1.9:8080/sources/users.queries.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
S.<computed> @ jquery.min.js:2
(anonymous) @ index.php?page=users:4226
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
