### ISSUE TITLE
New LDAP user doesn't show up in the users list under the admin menu

### ISSUE THREAD

**Issue by aleks001** [nilsteampassnet/TeamPass#3881]
### Steps to reproduce
1. login to teampass as admin
2. Go to users, the LDAP Synchronisation and wait for users to be populated (It's working up to this part, users are displayed form the ldap tree)
3. Find the user you want and click the "Add user in Teampass" Icon
4. Wait for all the tasks to complete in the task manager (This is also super slow)
5. Go to users list and the user isn't there

### Expected behaviour
User should be in the user list. The user can actually log in and it works but I just can't see it or make any changes to it apart from turning LDAP synchronization off and on.

### Actual behaviour
Tell us what happens instead
User is created and has the right privileges, but I can't see it under users or edit any of its roles etc
![image](https://github.com/nilsteampassnet/TeamPass/assets/15863500/2b5c2fed-68af-44ea-9f61-bdbaf57c8c1a)
![image](https://github.com/nilsteampassnet/TeamPass/assets/15863500/5d686c42-f3b8-456f-81a8-2238dcc21655)

### Server configuration
**Operating system**:
docker php-apache 8.1 image

**Web server:**
docker php-apache 8.1 image

**Database:**
mysql 8.0.33

**PHP version:**
8.1

**Teampass version:** 
3.0.10.50

**Teampass configuration file:**
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/12654760/tp.config.zip)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
This is actually a fresh install of teampass that I'm testing

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 11

#### Web server error log
```
There are no errors or entries added at all to the web server log when you click the perform button.

Insert your webserver log here
```
#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```
There are no errors or entries added at all to the console log when you click the perform button.

**Comment by geokh** [comment]
Im facing the same issue any news?

**Comment by aleks001** [comment]
The way I found around this is to first create a local user manually and then synchronise the user, but this is just a workaround.

**Comment by geokh** [comment]
How to sync a local user with AD ?

**Comment by aleks001** [comment]
This is only for teampass 3.0 and above. So create your user then go to the ldap synchronisation menu and flip the toggle switch on next to the username

**Comment by geokh** [comment]
I get this error when i create the user matching the one i have issue with
Next error occurred
Error: Malformed UTF-8 data

Raw answer from server:

Fatal error: Uncaught mysqli_sql_exception: Duplicate entry 'kalfodeh@ccc.net' for key 'login' in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:682 Stack trace: #0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(682): mysqli->query('INSERT INTO `te...', 0) #1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper('assoc', '%l INTO %b %lb ...', 'INSERT', 'teampass_users', Array, Array) #2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall(Array, Array, 'assoc') #3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(360): MeekroDB->query('%l INTO %b %lb ...', 'INSERT', 'teampass_users', Array, Array) #4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(365): MeekroDB->insertOrReplace('INSERT', 'teampass_users', Array) #5 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(79): MeekroDB->insert('teampass_users', Array) #6 /var/www/html/teampass/sources/users.queries.php(205): DB::insert('teampass_users', Array) #7 {main} thrown in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 682

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
