### ISSUE TITLE
Unable to configure connection to Active Directory and sync objects

### ISSUE THREAD

**Issue by koznov** [nilsteampassnet/TeamPass#3894]
Greetings!

I've installed docker version of TeamPass to Ubuntu 22.04 server and facing issues with connection to Active Directory servers. I've checked that server is available and another products succesfully obtained data from AD.

### Steps to reproduce
1. Install TeamPass with default options via docker compose
2. Authenticate using local administrator account to TeamPass
3. Configure connection to Active Directory server with pointing to Domain Contoller using 389 non secure connection
4. Add domain account info to fields: username to use for Testing purpose and Username password
5. Click on Perform

### Expected behaviour
TeamPass can find information about user and didn't give any error. You can proceed with synchorinize of users via Users -> LDAP synchronization -> List Users.

### Actual behaviour
After clicking Perform button to check connectivity in interface only blue Information taskbar "In progress" appears with endless circle. 
<img width="365" alt="image" src="https://github.com/nilsteampassnet/TeamPass/assets/16073136/6d5fb632-0904-414c-8725-b4188143a04b">

LDAP synchronization of Users stucked in status "In progress" with endless circle.
### Server configuration
**Operating system**:
Ubuntu 22.04.3 LTS
**Web server:**
Nginx proxy from docker compose (nginx-proxy:alpine)
**Database:**
MariaDB from docker compose (alpine-mariadb:latest)
**PHP version:**
8.2.7 (built in docker image teampass:latest)
**Teampass version:** 
Current version loaded 3.0.10.62

**Teampass configuration file:**

**Fresh docker installation:**
```php
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html',
    'cpassman_url' => 'https://teampass.sclabs.cloud',
    'favicon' => 'http://teampass.sclabs.cloud/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/upload',
    'path_to_files_folder' => '/var/www/html/files',
    'url_to_files_folder' => 'http://teampass.sclabs.cloud/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.0.10',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'sAMAccountName',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1694012187',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Berlin',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'CLEARED_PASSKEY',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => 'distinguishedname',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '(sAMAccountName=%(user)s)',
    'ldap_bdn' => 'OU=SC-Users,DC=sclabs,DC=cloud',
    'ldap_hosts' => 'dc01.sclabs.cloud',
    'ldap_password' => 'CLEARED_PASSWORD',
    'ldap_username' => 'CN=sa-teampass,OU=ServiceAccounts,OU=SC-Users,DC=sclabs,DC=cloud',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1696604187',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '(objectClass=group)',
    'ldap_guid_attibute' => 'objectGUID',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => '',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
    'maximum_session_expiration_time' => '60',
    'items_ops_job_frequency' => '1',
);
``` 
### Client configuration
**Browser:**
Google Chrome Version 117.0.5938.88 (Official Build) (arm64)

**Operating system:**
MacOS 13.2 (22D49)
** docker compose configuration **

```dockerfile
version: "3"
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    networks:
      - frontend
      - backend
    ports:
      - "443:443"
    volumes:
      - /etc/ssl/nginx:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro

  teampass-web:
    image: dormancygrace/teampass:latest
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: teampass.sclabs.cloud
      VIRTUAL_PORT: 80
      CERT_NAME: teampass.sclabs.cloud
    volumes:
      - ./teampass-html:/var/www/html
    # uncomment ports to use without proxy
    #ports:
    #  - 80:80
    networks:
      - teampass-internal
      - backend
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql_secure_installation
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: CLEARED_PASSWORD
      MYSQL_USER: teampass
    volumes:
      - ./teampass-db:/var/lib/mysql
    networks:
      - teampass-internal

networks:
  frontend:
  backend:
  teampass-internal:
``` 

#### Web server error log
```php
06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Constant FILTER_SANITIZE_STRING is deprecated in /var/www/html/sources/ldap.queries.php on line 106"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\CarbonInterface::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/CarbonInterface.php on line 2977"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:148"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::getTimezone() should either be compatible with DateTime::getTimezone(): DateTimeZone|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Date.php on line 634"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::setDate($year, $month, $day) should either be compatible with DateTime::setDate(int $year, int $month, int $day): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Date.php on line 1401"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::setISODate($year, $week, $day = 1) should either be compatible with DateTime::setISODate(int $year, int $week, int $dayOfWeek = 1): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Date.php on line 1417"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::setTime($hour, $minute, $second = 0, $microseconds = 0) should either be compatible with DateTime::setTime(int $hour, int $minute, int $second = 0, int $microsecond = 0): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Date.php on line 1452"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::setTimestamp($unixTimestamp) should either be compatible with DateTime::setTimestamp(int $timestamp): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Date.php on line 1466"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::setTimezone($value) should either be compatible with DateTime::setTimezone(DateTimeZone $timezone): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Date.php on line 1524"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::format($format) should either be compatible with DateTime::format(string $format): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Converter.php on line 78"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::createFromFormat($format, $time, $tz = null) should either be compatible with DateTime::createFromFormat(string $format, string $datetime, ?DateTimeZone $timezone = null): DateTime|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 660"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::getLastErrors() should either be compatible with DateTime::getLastErrors(): array|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 902"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::diff($date = null, $absolute = false) should either be compatible with DateTime::diff(DateTimeInterface $targetObject, bool $absolute = false): DateInterval, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Difference.php on line 120"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::modify($modify) should either be compatible with DateTime::modify(string $modifier): DateTime|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Modifiers.php on line 432"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::__set_state($dump) should either be compatible with DateTime::__set_state(array $array): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Serialization.php on line 94"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::__wakeup() should either be compatible with DateTime::__wakeup(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Serialization.php on line 128"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::add($unit, $value = 1, $overflow = null) should either be compatible with DateTime::add(DateInterval $interval): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Units.php on line 196"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Traits\Date::sub($unit, $value = 1, $overflow = null) should either be compatible with DateTime::sub(DateInterval $interval): DateTime, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Units.php on line 355"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Carbon::format($format) should either be compatible with DateTimeInterface::format(string $format): string, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Converter.php on line 78"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Carbon::getTimezone() should either be compatible with DateTimeInterface::getTimezone(): DateTimeZone|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Date.php on line 634"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Carbon::diff($date = null, $absolute = false) should either be compatible with DateTimeInterface::diff(DateTimeInterface $targetObject, bool $absolute = false): DateInterval, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Difference.php on line 120"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Return type of Carbon\Carbon::__wakeup() should either be compatible with DateTimeInterface::__wakeup(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/includes/libraries/Carbon/Traits/Serialization.php on line 128"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/ldap.queries.php:0"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/sources/ldap.queries.php:149"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 96 and defined in /var/www/html/includes/libraries/Carbon/Traits/Creator.php:894"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "Stack trace:"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "#0 /var/www/html/includes/libraries/Carbon/Traits/Creator.php(96): Carbon\Carbon::setLastErrors(false)"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "#1 /var/www/html/includes/libraries/Carbon/Traits/Creator.php(250): Carbon\Carbon->__construct(NULL, NULL)"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "#2 /var/www/html/includes/libraries/LdapRecord/Connection.php(495): Carbon\Carbon::now()"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "#3 /var/www/html/includes/libraries/LdapRecord/Connection.php(268): LdapRecord\Connection->retryOnNextHost(Object(LdapRecord\Auth\BindException), Object(Closure))"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "#4 /var/www/html/sources/ldap.queries.php(181): LdapRecord\Connection->connect()"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "#5 {main}"
[06-Oct-2023 15:26:40] WARNING: [pool www] child 19 said into stderr: "  thrown in /var/www/html/includes/libraries/Carbon/Traits/Creator.php on line 894"
192.168.224.2 - - [06/Oct/2023:15:26:40 +0000] "POST /sources/ldap.queries.php HTTP/1.1" 500 13 "https://teampass.sclabs.cloud/index.php?page=ldap" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
``` 

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
index.php?page=ldap:2512 Loading settings result:
index.php?page=ldap:2513 {enable_favourites: '1', enable_pf_feature: '0', ldap_user_attribute: 'sAMAccountName', insert_manual_entry_item_history: '0', google_authentication: '0', …}
index.php?page=ldap:3048 {field: 'ldap_new_user_is_administrated_by', value: '0'}
index.php:1 Mixed Content: The page at 'https://teampass.sclabs.cloud/index.php?page=ldap' was loaded over HTTPS, but requested an insecure favicon 'http://teampass.sclabs.cloud/favicon.ico'. This request has been blocked; the content must be served over HTTPS.
index.php?page=ldap:3073 {error: false, misc: '1 ; 0', message: ''}
index.php?page=ldap:2695 Refresh last item seen result
index.php?page=ldap:2696 {error: '', existing_suggestions: 0, html_json: Array(0)}
index.php?page=ldap:1203 Get user info results:
index.php?page=ldap:1204 {error: false, message: '', queryResults: {…}}
index.php?page=ldap:3097 ldap-test-config
jquery.min.js:2     POST https://teampass.sclabs.cloud/sources/ldap.queries.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
S.<computed> @ jquery.min.js:2
(anonymous) @ index.php?page=ldap:3108
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by koznov** [comment]
HAR file is uploaded to https://drive.google.com/file/d/1XmW3Wkj4vUL2Sc3UuQk11G7H2sDWd6Yp

**Comment by koznov** [comment]
I've fallback to version 3.0.7 and start experimenting with options. I've removed special symbols from the password and at first sight search now works (thanks for the hint to @mrocaruano via https://github.com/nilsteampassnet/TeamPass/issues/3412#issuecomment-1320177214). Furthermore, I will upgrade installation to latest version and provide feedback that bug related to special symbols in password.

**Comment by koznov** [comment]
After correcting LDAP settings Users and Groups are synced. Problem was with special symbols in password of account that used for sync.
