### ISSUE TITLE
getting Ajax error in task manager

### ISSUE THREAD

**Issue by mtna-matt-wolfe** [nilsteampassnet/TeamPass#3907]
### Steps to reproduce
1.  Click Tasks 
2. error pop up
3.

### Expected behaviour
List currently running Tasks

### Actual behaviour
the followinf pop up occurs

DataTables warning: table id=table-tasks_in_progress - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### Server configuration
 Ubuntu 22.04.2 LTS

**Web server:**
Apache
**Database:**
mysql

**PHP version:**
8
**Teampass version:** 
3.0.9
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Edge
**Operating system:**
Windows 11
#### Web server error log
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Please share error from apache log file.

**Comment by killmenowkid** [comment]
Double check that the address you are accessing from matches the configured URL in settings>option as well as your webserver/proxy. I was getting this error due to a missmatch. correcting the URL in settings>options resolved it for me

**Comment by Dung3on-MaStr** [comment]
encounter the same error after installation and configuration when accessing the tasks page on version 3.1.2

``PHP Fatal error:  Uncaught MeekroDBException: Table 'teampass.teampass_background_tasks' doesn't exist in /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php:934\nStack trace:\n#0 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(895): MeekroDB->queryHelper()\n#1 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(1011): MeekroDB->queryAllLists()\n#2 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(1032): MeekroDB->queryFirstList()\n#3 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->queryFirstField()\n#4 /var/www/html/TeamPass/sources/logs.datatables.php(878): DB::__callStatic()\n#5 {main}\n  thrown in /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php on line 934, referer: https://teampass.cg38.local/index.php?page=tasks````

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
