### ISSUE TITLE
PHP Fatal error:  Uncaught mysqli_sql_exception: Too many connections

### ISSUE THREAD

**Issue by aleks001** [nilsteampassnet/TeamPass#3919]
### Steps to reproduce
This happens in the background there is not a set of of individual steps I can complete. What I can see is it is generating a tone of session in the mysql database from the teampass host till it hits the max_connections limit, it doesn't seem to matter how many users there are on the system and it will generate an infinite amount of sessions it seems, increase the cap doesn't help it just reaches it again. My guess is that it's something to do with the cron system regarding the users.

### Expected behaviour
Shouldn't be creating so many sessions.

### Actual behaviour
The application crashes periodically.

### Server configuration

Operating system:
docker php-apache 8.1 image

Web server:
docker php-apache 8.1 image

Database:
mysql 8.0.33

PHP version:
8.1

Teampass version:
3.0.10.50

Teampass configuration file:
[tp.config.zip](https://github.com/nilsteampassnet/TeamPass/files/12654760/tp.config.zip)

Client configuration
Browser:
Chrome

Operating system:
Windows 11

#### Web server error log
```
[Tue Oct 31 09:02:48.248876 2023] [php:error] [pid 2649675] [client 10.89.0.21:48906] PHP Fatal error:  Uncaught mysqli_sql_exception: Too many connections in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php:192\nStack trace:\n#0 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(192): mysqli->real_connect()\n#1 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(648): MeekroDB->get()\n#2 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(637): MeekroDB->queryHelper()\n#3 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(638): MeekroDB->prependCall()\n#4 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(753): MeekroDB->query()\n#5 /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php(66): MeekroDB->queryFirstRow()\n#6 /var/www/html/teampass/sources/checks.php(178): DB::queryFirstRow()\n#7 /var/www/html/teampass/sources/items.queries.php(43): checkUser()\n#8 {main}\n  thrown in /var/www/html/teampass/includes/libraries/Database/Meekrodb/db.class.php on line 192, referer: https://host/teampass/index.php?page=items



#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
None
Insert the log here and especially the answer of the query that failed.
```
None, something in the background is doing this

**Comment by whosht** [comment]
Affects me as well. In mariadb I also see that teampass has a lot of open connections when doing "show processlist;"
I am at 64c0768c92c8bb19f2a308ca318b37f699b62ef1 (3.0.10.81).

**Comment by whosht** [comment]
This seems to have something to do with the background Tasks. I see a lot of processes when they run (100 - as many as limitted by the database):
```
~# ps -Af | grep teampass
www-data 1535004       1  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___user_keys_creation.php
www-data 1535012       1  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___items_handler.php
www-data 1535021 1535004  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___user_keys_creation.php
www-data 1535022 1535012  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___items_handler.php
www-data 1535023 1535021  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___user_keys_creation.php
www-data 1535024 1535022  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___items_handler.php
www-data 1535030 1535023  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___user_keys_creation.php
www-data 1535031 1535024  0 17:00 ?        00:00:00 /usr/bin/php8.2 /var/www/html/teampass/scripts/background_tasks___items_handler.php
```
and so on.

**Comment by Arash9703** [comment]
Linked with the background crontab !?
 
The grep u are doing is it in mysql ?

**Comment by whosht** [comment]
@Arash9703: The background tasks are running through the cron job - but this is not important as I can reproduce the same behaviour by running it manually e.g. `su -mc "/usr/bin/php sources/scheduler.php" www-data` or by calling key management only with `su -mc "/usr/bin/php scripts/background_tasks___user_keys_creation.php" www-data`
(The latter was used a few weeks ago to check whats wrong and to finish user creation due to a misbehaviour which results in an entry in the database being left with a wrong value, when timeout for background task execution exceeded - I haven't elaborated that good enough yet to open a new issue).

`ps -Af | grep teampass` is run in a shell (list Linux processes and filter everything with `teampass` string in it)

**Comment by aleks001** [comment]
This most likely affects everyone and most people are just not noticing it. Probably linked with the amount of passwords you have or users. It is quite a serious issue that needs addressing as it will cause other processes to error out randomly when the database limit is hit.

**Comment by Arash9703** [comment]
I will check this out in mine , and get back to you.

**Comment by Arash9703** [comment]
It seems like i haven't got any extra processus in mine . 
# as usuel 
![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/8d4b125a-4497-4ec2-b128-f9d4368c9192)

# as root 
![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/54ca4756-cb26-45ee-88d9-526f7613fc6f)


# and mysql : 
![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/ab901657-efa0-4289-9ed1-5194d6974473)


![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/e66532b8-beec-43b5-88d1-eefdde0d3423)

**Comment by aleks001** [comment]
I should have mentioned but they are not constantly there. You have to keep running those commands around the time the scheduler runs to catch it. I usually just keep running it every 10-20 seconds for a minute or two to catch it happening.

**Comment by whosht** [comment]
@aleks001: the schedular has a granularity of minutes (from cron). The time the tasks run is configurable. The default is to run some tasks every minute, some every 2 minutes, one every 5 minutes, 5 Tasks are undefined (e.g. personal folder creation).
How long they run is configurable too (default 300 seconds, x items per run).

@Arash9703: Did you check right after cron startet e.g. user creation? This is best reproducible for me if user creation process is configured to run every minute.

**Comment by aleks001** [comment]
@whosht I've tried messing with a lot of those settings and nothing seems to help or change what I'm seeing. So I'm not sure exactly what it is that's causing this.

**Comment by Arash9703** [comment]
@whosht , I did created a test local user and loged in in order to synchronise vault clés to the serveur, "in the meantime i kept running the shell grep teampass" and didn't faced it neither in MySQL neither on debian server.

**Comment by whosht** [comment]
@Arash9703: Do you have any hints where I can start debugging in the scripts? E.g. in scripts/background_tasks___user_keys_creation.php

When I look at the process list excerpt, I posted, I see the first process of scripts/background_tasks___user_keys_creation.php
has a parent PID of 1 which can be explained because it is started by the scheduler.php itself which has already been ended/terminated.
The next scripts/background_tasks___user_keys_creation.php process is started by the first process, the next one by the second and so on. So there must be some place that calls (or forks or whatever) scripts/background_tasks___user_keys_creation.php either iterative or recursively.

**Comment by Arash9703** [comment]
No clue :(   maybe `php/usr/bin` ! 

check my task manager config , maybe changing this might help the background task  !

![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/701fa59f-3774-4b0c-92d5-800b7355b5a2)

**Comment by Arash9703** [comment]
> This most likely affects everyone and most people are just not noticing it. Probably linked with the amount of passwords you have or users. It is quite a serious issue that needs addressing as it will cause other processes to error out randomly when the database limit is hit.

It took me a little time, indeed I agree with @whosht  and @aleks001 . The issue does exist & as @aleks001 mentionned this could be à little serious as its relie with mysql ! 

I guess @nilsteampassnet  needs to check this out before the latest 3.0.10 release.

![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/cca92809-7021-4095-8074-67188f78ecbc)


![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/42f06421-0867-4f30-9806-2911ccd5deb7)

@nilsteampassnet pour info : 
![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/45489854-f3bf-4254-a56d-82a0a542da92)

**Comment by nilsteampassnet** [comment]
Hi
The issue is solved but not yet committed.
The next commit is a huge one and I'm testing it.
The fix is quite simple, I will post tomorrow morning how to do it manually.

**Comment by Arash9703** [comment]
@nilsteampassnet 
I've noticed that disabled Active Directory users can log in to their vault. Is this expected behavior? 
If so, it might be necessary for Teampass administrators to perform additional checks when employees leave the team.

Teampass currently checks for account existence but doesn't verify the account's active status. Should we create an issue to discuss and address this?

Your input would be appreciated.

**Comment by cgkelleher88** [comment]
@nilsteampassnet did you manage to post the manual fix for this issue - i have the issue on version 3.0.10.67 and still after upgrade to latest. should it be fixed with upgrade?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
