### ISSUE TITLE
Can't Create New Install on 3.0.10

### ISSUE THREAD

**Issue by kcbieng** [nilsteampassnet/TeamPass#3922]
### Steps to reproduce
1. Start a fresh install
2. Navigate to /install/install.php
3. Click Start Button

### Expected behaviour
Should Perform pre-install checks

### Actual behaviour
Pre-install checks fail with 500 error from install.queries.php. PHP indicates error with undefined constant.

### Server configuration
Fresh Docker Container
Alpine Linux v3.18

PHP version: 8.2.7
Memory limit: 128M
Memory usage: 577.30 KB
Maximum time execution: 120
Maximum file size upload: 100M

Server version: 10.11.5-MariaDB
Database size: 0.95MB

**Teampass version:**
3.0.10

**Teampass configuration file:**
Fresh INstall

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Brave/Chrome

**Operating system:**
Windows 11

#### Web server error log
```
WARNING: [pool www] child 71 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "DB_PASSWD" in /var/www/html/sources/main.functions.php:4350"
2023-11-03 09:42:38 teampass-teampass-web-1  | [03-Nov-2023 14:42:38] WARNING: [pool www] child 71 said into stderr: "Stack trace:"
2023-11-03 09:42:38 teampass-teampass-web-1  | [03-Nov-2023 14:42:38] WARNING: [pool www] child 71 said into stderr: "#0 /var/www/html/sources/main.functions.php(60): loadClasses()"
2023-11-03 09:42:38 teampass-teampass-web-1  | [03-Nov-2023 14:42:38] WARNING: [pool www] child 71 said into stderr: "#1 /var/www/html/install/install.queries.php(114): require_once('/var/www/html/s...')"
2023-11-03 09:42:38 teampass-teampass-web-1  | [03-Nov-2023 14:42:38] WARNING: [pool www] child 71 said into stderr: "#2 {main}"
2023-11-03 09:42:38 teampass-teampass-web-1  | [03-Nov-2023 14:42:38] WARNING: [pool www] child 71 said into stderr: "  thrown in /var/www/html/sources/main.functions.php on line 4350"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```

--- PREPARATION---
2
{"absolute_path":"/var/www/html","url_path":"https://teampass.domain.local"}
[object Object]
0
true
folder*install
-------

jquery.min.js:18 
        
        
       POST https://teampass.domain.local/install/install.queries.php 500 (Internal Server Error)
send @ jquery.min.js:18
ajax @ jquery.min.js:18
doGetJson @ install.js:265
checkPage @ install.js:149
onclick @ install.php:110
install.js:282 

--- RECEPTION---
[object Object]
-------
```

**Comment by kcbieng** [comment]
Whoops, looks like this is a dupe of issue 3906.

**Comment by useronkel** [comment]
Got a similar exception, but php-fpm wasn't configured correct.
Solving this lead me into
Step 2:
```
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    parseJSON jQuery
    doGetJson https://example.com/install/install.js:288
    jQuery 2
    doGetJson https://example.com/install/install.js:281
    checkPage https://example.com/install/install.js:149
    onclick https://example.com/install/install.php:1
```
Devconsole shows at request:
```
POST /install/install.queries.php HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: de-DE,en;q=0.8,de;q=0.5,en-US;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest
Content-Length: 407
Origin: https://example.com
DNT: 1
Connection: keep-alive
Referer: https://example.com/install/install.php
Cookie: teampass_session=sdhfgsfhgsdfhg
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```
and the answer is:
```
Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 8.1.0". 
```

**Comment by kcbieng** [comment]
> Got a similar exception, but php-fpm wasn't configured correct. Solving this lead me into Step 2:
> 
> ```
> Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
>     parseJSON jQuery
>     doGetJson https://example.com/install/install.js:288
>     jQuery 2
>     doGetJson https://example.com/install/install.js:281
>     checkPage https://example.com/install/install.js:149
>     onclick https://example.com/install/install.php:1
> ```
> 
> Devconsole shows at request:
> 
> ```
> POST /install/install.queries.php HTTP/1.1
> Host: example.com
> User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
> Accept: application/json, text/javascript, */*; q=0.01
> Accept-Language: de-DE,en;q=0.8,de;q=0.5,en-US;q=0.3
> Accept-Encoding: gzip, deflate, br
> Content-Type: application/x-www-form-urlencoded
> X-Requested-With: XMLHttpRequest
> Content-Length: 407
> Origin: https://example.com
> DNT: 1
> Connection: keep-alive
> Referer: https://example.com/install/install.php
> Cookie: teampass_session=sdhfgsfhgsdfhg
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: cors
> Sec-Fetch-Site: same-origin
> ```
> 
> and the answer is:
> 
> ```
> Composer detected issues in your platform:
> Your Composer dependencies require a PHP version ">= 8.1.0". 
> ```
> 
> On the host is php 8.0, no newer version available (rhel-8)

This appears to be a different issue.

**Comment by useronkel** [comment]
> This appears to be a different issue.

Yeah, you're right. Creating a new issue

**Comment by Sivolen** [comment]
hi!
I have same problem, my php version PHP 8.2.12 (cli) (built: Oct 26 2023 17:33:49) (NTS)
Does anyone know how to fix this problem?

**Comment by kcbieng** [comment]
@nilsteampassnet I am still getting this error when attempting to perform a fresh install. Running this in fresh docker containers built with the docker-compose.yml

Web Server Error Log:
```
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP Warning:  include_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/main.functions.php on line 55"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/install/install.queries.php:0"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/install/install.queries.php:41"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP Warning:  include_once(): Failed opening '/var/www/html/sources/../includes/config/tp.config.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/sources/main.functions.php on line 55"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/install/install.queries.php:0"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/install/install.queries.php:41"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class "TeampassClasses\SuperGlobal\SuperGlobal" not found in /var/www/html/install/install.queries.php:45"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "Stack trace:"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "#0 {main}"
2023-12-05 16:41:39 teampass-teampass-web-1  | [05-Dec-2023 22:41:39] WARNING: [pool www] child 79 said into stderr: "  thrown in /var/www/html/install/install.queries.php on line 45"
```

Browser Console Log:


```
--- PREPARATION---
2
{"absolute_path":"/var/www/html","url_path":"http://teampass.spp.kcbieng.org"}
[object Object]
0
true
folder*install
-------

jquery.min.js:18 
        
        
       Failed to load resource: the server responded with a status of 500 ()
send @ jquery.min.js:18
ajax @ jquery.min.js:18
doGetJson @ install.js:265
checkPage @ install.js:149
onclick @ install.php:111
install.js:282 

--- RECEPTION---
[object Object]
-------

install.js:262 
```

**Comment by kcbieng** [comment]
I'm not sure but I think I got this to work with 3.1.7, so I'll close this.

**Comment by wdio-v5** [comment]
Eureka, the answer’s here! https://preprocessor.space/questions/displaying-extra-details-by-utilizing-an-onclick-event-and-javascript-function
