### ISSUE TITLE
LDAP Query error in 3.0.10

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#3936]
After solving installation issues, there is a new one with ldap authentication.
I'm using OpenLDAP, but TP seems to set always samaccountname for filtering
Edith says: This occures in checking account for test

Regardless of configured server type, the following error appears:
```
Object { 
error: true, 
message: "error caught - LdapRecord\\Query\\ObjectNotFoundException: No LDAP query results for filter: [(samaccountname=username)] in: [] in /var/www/html/example.com/vendor/directorytree/ldaprecord/src/Query/ObjectNotFoundException.php:32
Stack trace:
#0 /var/www/html/example.com/vendor/directorytree/ldaprecord/src/Query/Builder.php(872): LdapRecord\\Query\\ObjectNotFoundException::forQuery()
#1 /var/www/html/example.com/vendor/directorytree/ldaprecord/src/Query/Builder.php(790): LdapRecord\\Query\\Builder->throwNotFoundException()
#2 /var/www/html/example.com/sources/ldap.queries.php(176): LdapRecord\\Query\\Builder->firstOrFail()
#3 {main}" }
index.php:3190:29
```
LDAP-Settings are:
```
'ldap_mode' => '1',
'ldap_type' => 'OpenLDAP',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '1',
'ldap_search_base' => '0',
'ldap_port' => '389',
'ldap_object_class' => '0',
'ldap_and_local_authentication' => '1',
'ldap_user_dn_attribute' => 'dn',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '(objectclass=person),(uid=*)',
'ldap_bdn' => 'dc=de',
'ldap_hosts' => 'ldap.example.com,bck.ldap.example.com',
'ldap_password' => 'secret',
'ldap_username' => '123456',
'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_ALLOW',
'ldap_group_object_filter' => '',
'ldap_guid_attibute' => 'memberUid',
```

**Comment by useronkel** [comment]
Hi Nils.
Sometimes I have to end my work at a certain time ;-)
You are absolutely right :-)
