### ISSUE TITLE
Can't login with LDAP

### ISSUE THREAD

**Issue by volrod64** [nilsteampassnet/TeamPass#3953]
HELLO, 

I would love if you could help me : here my issue 
 
### Steps to reproduce
1. Connect with one user from LDAP
2. Wait a long time
3. Nothing happen

### Expected behaviour
I want my user to connect

### Actual behaviour
It doesn't connect

### Server configuration
Ubuntu 20.04.6 LTS

**Web server:**
Nxing
**Database:**
10.3.38-MariaDB
**PHP version:**
PHP version: 8.1.23

**Teampass version:** 
3.0.10.50
**Teampass configuration file:**
```
root@teampassv3:~# cat /var/www/html/TeamPass/sources/ldap.activedirectory.php
<?php

declare(strict_types=1);

/**
 * Teampass - a collaborative passwords manager.
 * ---
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * ---
 *
 * @project   Teampass
 * @file      ldap.activedirectory.php
 * ---
 *
 * @author    Nils Laumaillé (nils@teampass.net)
 *
 * @copyright 2009-2023 Teampass.net
 *
 * @license   https://spdx.org/licenses/GPL-3.0-only.html#licenseText GPL-3.0
 * ---
 *
 * @see       https://www.teampass.net
 */

use LdapRecord\Connection;
use LdapRecord\Container;
use LdapRecord\Models\ActiveDirectory\User;

require_once 'SecureHandler.php';
session_name('teampass_session');
session_start();
if (isset($_SESSION['CPM']) === false || (int) $_SESSION['CPM'] !== 1) {
    //die('Hacking attempt...');
}

/**
 * Get the user's AD groups.
 *
 * @param string $userDN
 * @param LdapRecord\Connection $connection
 * @param array $SETTINGS
 *
 * @return bool
 */
function userIsEnabled(string $userDN, Connection $connection): bool #I CHANGED IT BECAUSE OF A TICKET FROM HERE MAYBE I DID BAD
{
    // init
    $groupsArr = [];

    try {
        Container::addConnection($connection);

        // get id attribute
        if (isset($SETTINGS['ldap_guid_attibute']) ===true && empty($SETTINGS['ldap_guid_attibute']) === false) {
            $idAttribute = $SETTINGS['ldap_guid_attibute'];
        } else {
            $idAttribute = 'objectguid';
        }

        // Get user groups from AD
        require_once '../includes/libraries/LdapRecord/Models/ActiveDirectory/User.php';
        $user = User::find($userDN);
        $groups = $user->groups()->get();
        foreach ($groups as $group) {
            array_push(
                $groupsArr,
                $group[$idAttribute][0]
            );
        }
    } catch (\LdapRecord\Auth\BindException $e) {
        // Do nothing
    }

    return [
        'error' => false,
        'message' => '',
        'userGroups' => $groupsArr,
    ];
}

```
**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome / Firefox / Opera

**Operating system:**
Windows 10 / Windows 11

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Get 2FA Methods answer: [hidden.com:2634:29](https://hidden.com/)
Object { agses: false, google: false, yubico: false, duo: false }
[hidden.com:2635:29](https://hidden.com/)
Data submitted to identifyUser: [https://hidden.com:2699:29](https://hidden.com/)
Object { login: "me", pw: "ratio", duree_session: "1500", screenHeight: 485, randomstring: "skibidipapa", TimezoneOffset: 0, client: "", user_2fa_selection: "" }
​
TimezoneOffset: 0
​
client: ""
​
duree_session: "1500"
​
login: "thatsmemario"
​
pw: "brolikemypassorwhat"
​
randomstring: "justrying"
​
screenHeight: 485
​
user_2fa_selection: ""
​
<prototype>: Object { … }
[hidden.com:2700:29](https://hidden.com)
XHRPOST
https://hidden.com/sources/checks.php
[HTTP/1.1 200 OK 10ms]

Session existance check: [hidden.com:2722:33](https://hidden.com/)
Object { status: true }
[hidden.com2723:33](hidden.com/)
XHRPOST
https://hidden.com/sources/identify.php
[HTTP/1.1 200 OK 31ms]

Identification answer: [hidden.com:2758:41](https://hidden.com/)
SESSION KEY is: idon'tknowihideitjustbcs [teampass.seilks.cloud:2759:41](https://hiddent.com/)
Object { value: "", user_admin: 0, initial_url: "", pwd_attempts: 1, error: true, message: "LDAP error: Error : User could not be authentificated" }
​
error: true
​
initial_url: ""
​
message: "LDAP error: Error : User could not be authentificated"
​
pwd_attempts: 1
​
user_admin: 0
​
value: ""
​
<prototype>: Object { … }
```

Thanks a lot and have a nice day :)

Edit : typo

**Comment by MarceloRochac** [comment]
I have the same problem, in apache error log:

`[Wed Nov 22 19:12:58.608580 2023] [php:error] [pid 70827] [client 192.168.1.44:51738] PHP Fatal error:  Uncaught TypeError: getUserADGroups(): Argument #1 ($userDN) must be of type string, null given, called in /var/www/html/teampass/sources/identify.php on line 1313 and defined in /var/www/html/teampass/sources/ldap.activedirectory.php:42\nStack trace:\n#0 /var/www/html/teampass/sources/identify.php(1313): getUserADGroups()\n#1 /var/www/html/teampass/sources/identify.php(2330): authenticateThroughAD()\n#2 /var/www/html/teampass/sources/identify.php(295): identifyDoLDAPChecks()\n#3 /var/www/html/teampass/sources/identify.php(131): identifyUser()\n#4 {main}\n  thrown in /var/www/html/teampass/sources/ldap.activedirectory.php on line 42, referer: http://site/teampass/index.php
`

**Comment by GodPT** [comment]
@volrod64 the configuration file that they need is located in the /TeamPass/Includes/Config since its where the ldap configuration is.

Can you upload or copy and paste that? (removing any sensitive information)

**Comment by GodPT** [comment]
> I have the same problem, in apache error log:
> 
> `[Wed Nov 22 19:12:58.608580 2023] [php:error] [pid 70827] [client 127.0.0.1:51738] PHP Fatal error: Uncaught TypeError: getUserADGroups(): Argument #1 ($userDN) must be of type string, null given, called in /var/www/html/teampass/sources/identify.php on line 1313 and defined in /var/www/html/teampass/sources/ldap.activedirectory.php:42\nStack trace:\n#0 /var/www/html/teampass/sources/identify.php(1313): getUserADGroups()\n#1 /var/www/html/teampass/sources/identify.php(2330): authenticateThroughAD()\n#2 /var/www/html/teampass/sources/identify.php(295): identifyDoLDAPChecks()\n#3 /var/www/html/teampass/sources/identify.php(131): identifyUser()\n#4 {main}\n thrown in /var/www/html/teampass/sources/ldap.activedirectory.php on line 42, referer: http://site/teampass/index.php `

This looks like that the username is either empty or not correctly configured, can you add a printscreen of the configuration? (removing sensitive information)

**Comment by MarceloRochac** [comment]
@mfsrf01 Below is the screenshots, the error only happens on the login page, testing through the Ldap configuration page or trying to insert users from AD  works normally
<img width="883" alt="tpprsc_1" src="https://github.com/nilsteampassnet/TeamPass/assets/77128288/ed42d9ff-69e6-4a98-950f-c547e2dc4b2b">
<img width="896" alt="tpprsc_2" src="https://github.com/nilsteampassnet/TeamPass/assets/77128288/31b4b82b-b8ec-4416-ac60-407b9cac646a">
<img width="884" alt="tpprsc_3" src="https://github.com/nilsteampassnet/TeamPass/assets/77128288/ec105211-4129-4fbf-a112-f86f51374d78">

**Comment by MarceloRochac** [comment]
> > I have the same problem, in apache error log:
> > `[Wed Nov 22 19:12:58.608580 2023] [php:error] [pid 70827] [client 127.0.0.1:51738] PHP Fatal error: Uncaught TypeError: getUserADGroups(): Argument #1 ($userDN) must be of type string, null given, called in /var/www/html/teampass/sources/identify.php on line 1313 and defined in /var/www/html/teampass/sources/ldap.activedirectory.php:42\nStack trace:\n#0 /var/www/html/teampass/sources/identify.php(1313): getUserADGroups()\n#1 /var/www/html/teampass/sources/identify.php(2330): authenticateThroughAD()\n#2 /var/www/html/teampass/sources/identify.php(295): identifyDoLDAPChecks()\n#3 /var/www/html/teampass/sources/identify.php(131): identifyUser()\n#4 {main}\n thrown in /var/www/html/teampass/sources/ldap.activedirectory.php on line 42, referer: http://site/teampass/index.php `
> 
> This looks like that the username is either empty or not correctly configured, can you add a printscreen of the configuration? (removing sensitive information)

Below is the screenshot, the error only happens on the login page, testing through the Ldap configuration page or trying to insert AD users works normally
<img width="902" alt="tpprsc_1" src="https://github.com/nilsteampassnet/TeamPass/assets/77128288/c139fe83-4a10-42b2-aa67-61eb46a6fcb9">
<img width="893" alt="tpprsc_2" src="https://github.com/nilsteampassnet/TeamPass/assets/77128288/5f9a7dee-7a4e-411a-ac25-eff38360fefa">
<img width="884" alt="tpprsc_3" src="https://github.com/nilsteampassnet/TeamPass/assets/77128288/940bc2d5-a2d0-4dee-a76f-ba7394ae19fb">

**Comment by mfsrf01** [comment]
> @mfsrf01 Below is the screenshots, the error only happens on the login page, testing through the Ldap configuration page or trying to insert users from AD works normally <img alt="tpprsc_1" width="883" src="https://user-images.githubusercontent.com/77128288/285229579-ed42d9ff-69e6-4a98-950f-c547e2dc4b2b.png"> <img alt="tpprsc_2" width="896" src="https://user-images.githubusercontent.com/77128288/285229581-31b4b82b-b8ec-4416-ac60-407b9cac646a.png"> <img alt="tpprsc_3" width="884" src="https://user-images.githubusercontent.com/77128288/285229588-ec105211-4129-4fbf-a112-f86f51374d78.png">

Can you try without the "User Distinguished name", "Additional User DN" and "User Object Filter"? Check if its the same error or if it changed.

**Comment by volrod64** [comment]
I actually have the same as mister  My user is authenticated, but if bad password i have an error. So it work this way, but not in login
<img width="884" alt="285229588-ec105211-4129-4fbf-a112-f86f51374d78" src="https://github.com/nilsteampassnet/TeamPass/assets/94232342/00a6f9e8-1e53-4cd7-84da-b50bf6073440">

**Comment by volrod64** [comment]
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '5',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/tp',
    'hide things'
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '1',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '@hide.local',
    'ldap_domain_dn' => 'dc=hide,dc=local',
    'ldap_domain_controler' => 'iphidden',
    'ldap_user_attribute' => 'samaccountname',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => 'ou=users,dc=hide',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '1',
    'show_description' => '0',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'grosseteub.png',
    'custom_login_text' => 'Identifiant WINDOWS',
    'default_language' => 'french',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1577203423',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'mx.hide',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'noreply@hide.com',
    'email_from_name' => 'teampass',
    'pwd_maximum_length' => '50',
    'google_authentication' => '0',
    'delay_item_edition' => '30',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,html',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '1',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '1500',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => 'posixAccount',
    'bck_script_path' => '/root/mysql_backup',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'hide',
    'syslog_port' => 'hide',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Paris',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '70',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'hide',
    'admin_2fa_required' => '1',
    'bck_script_key' => 'hide',
    'max_last_items' => '30',
    'can_create_root_folder' => '1',
    'settings_offline_mode' => '1',
    'ldap_new_user_role' => '4',
    'ldap_bind_dn' => 'cn=Manager,dc=hide',
    'ldap_bind_passwd' => 'hide',
    'ldap_usergroup' => '',
    'ldap_hosts' => '172.16.3.81,172.16.3.82',
    'ldap_bdn' => 'ou=Users,ou=hide,dc=hide,dc=local',
    'ldap_username' => 'cn=openvpn,cn=users,dc=hide,dc=local',
    'ldap_password' => 'hide',
    'ldap_user_dn_attribute' => 'distinguishedname',
    'ldap_user_object_filter' => '',
    'ldap_group_object_filter' => '',
);

**Comment by volrod64** [comment]
```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '5',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/tp',
    'hide things'
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '1',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '@hide.local',
    'ldap_domain_dn' => 'dc=hide,dc=local',
    'ldap_domain_controler' => 'iphidden',
    'ldap_user_attribute' => 'samaccountname',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => 'ou=users,dc=hide',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '1',
    'show_description' => '0',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => 'grosseteub.png',
    'custom_login_text' => 'Identifiant WINDOWS',
    'default_language' => 'french',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1577203423',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'mx.hide',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'noreply@hide.com',
    'email_from_name' => 'teampass',
    'pwd_maximum_length' => '50',
    'google_authentication' => '0',
    'delay_item_edition' => '30',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,html',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '1',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '1500',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => 'posixAccount',
    'bck_script_path' => '/root/mysql_backup',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'hide',
    'syslog_port' => 'hide',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Paris',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '70',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '1',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'hide',
    'admin_2fa_required' => '1',
    'bck_script_key' => 'hide',
    'max_last_items' => '30',
    'can_create_root_folder' => '1',
    'settings_offline_mode' => '1',
    'ldap_new_user_role' => '4',
    'ldap_bind_dn' => 'cn=Manager,dc=hide',
    'ldap_bind_passwd' => 'hide',
    'ldap_usergroup' => '',
    'ldap_hosts' => '172.16.3.81,172.16.3.82',
    'ldap_bdn' => 'ou=Users,ou=hide,dc=hide,dc=local',
    'ldap_username' => 'cn=openvpn,cn=users,dc=hide,dc=local',
    'ldap_password' => 'hide',
    'ldap_user_dn_attribute' => 'distinguishedname',
    'ldap_user_object_filter' => '',
    'ldap_group_object_filter' => '',
);

```

**Comment by volrod64** [comment]
```
root@teampassv3:/var/www/html/tp# cat /var/www/html/tp/sources/ldap.activedirectory.php
<?php

declare(strict_types=1);

/**
 * Teampass - a collaborative passwords manager.
 * ---
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * ---
 *
 * @project   Teampass
 * @file      ldap.activedirectory.php
 * ---
 *
 * @author    Nils Laumaillé (nils@teampass.net)
 *
 * @copyright 2009-2023 Teampass.net
 *
 * @license   https://spdx.org/licenses/GPL-3.0-only.html#licenseText GPL-3.0
 * ---
 *
 * @see       https://www.teampass.net
 */

use LdapRecord\Connection;
use LdapRecord\Container;
use LdapRecord\Models\ActiveDirectory\User;

require_once 'SecureHandler.php';
session_name('teampass_session');
session_start();
if (isset($_SESSION['CPM']) === false || (int) $_SESSION['CPM'] !== 1) {
    //die('Hacking attempt...');
}

/**
 * Get the user's AD groups.
 *
 * @param string $userDN
 * @param LdapRecord\Connection $connection
 * @param array $SETTINGS
 *
 * @return bool
 */
function userIsEnabled(string $userDN, Connection $connection): bool
{
    // init
    $groupsArr = [];

    try {
        Container::addConnection($connection);

        // get id attribute
        if (isset($SETTINGS['ldap_guid_attibute']) ===true && empty($SETTINGS['ldap_guid_attibute']) === false) {
            $idAttribute = $SETTINGS['ldap_guid_attibute'];
        } else {
            $idAttribute = 'objectguid';
        }

        // Get user groups from AD
        require_once '../includes/libraries/LdapRecord/Models/ActiveDirectory/User.php';
        $user = User::find($userDN);
        $groups = $user->groups()->get();
        foreach ($groups as $group) {
            array_push(
                $groupsArr,
                $group[$idAttribute][0]
            );
        }
    } catch (\LdapRecord\Auth\BindException $e) {
        // Do nothing
    }

    return [
        'error' => false,
        'message' => '',
        'userGroups' => $groupsArr,
    ];
}

```

**Comment by mfsrf01** [comment]
> 1,172.16.3.82',
>     'ldap_bdn' => 'ou=Users,ou=hide,dc=hide,dc=local',
>     'ldap_username' => 'cn=openvpn,cn=users,dc=hide,dc=local',
>     'ldap_password' => 'hide',
>     'ldap_user_dn_attribute' => 'distingu

You have two hosts, try only with one.
I couldn't connect with twi, but with 1 works just fine.

**Comment by volrod64** [comment]
I did delete one in Teampass GUI, but the problem still persist. Thanks for your help tho !

**Comment by volrod64** [comment]
![Git1](https://github.com/nilsteampassnet/TeamPass/assets/94232342/6732fc0f-24b6-4f1e-8678-ac400f569f64)
![Git2](https://github.com/nilsteampassnet/TeamPass/assets/94232342/dafc6cc6-ccff-4ffe-8ba6-b4d5692e97a5)
Ignore pic one, I changed the URL and put only one.

**Comment by mfsrf01** [comment]
> ![Git1](https://user-images.githubusercontent.com/94232342/285248103-6732fc0f-24b6-4f1e-8678-ac400f569f64.png) ![Git2](https://user-images.githubusercontent.com/94232342/285248114-dafc6cc6-ccff-4ffe-8ba6-b4d5692e97a5.png) Ignore pic one, I changed the URL and put only one.

What error occurs? Did you manage to import the user?

**Comment by volrod64** [comment]
> > ![Git1](https://user-images.githubusercontent.com/94232342/285248103-6732fc0f-24b6-4f1e-8678-ac400f569f64.png) ![Git2](https://user-images.githubusercontent.com/94232342/285248114-dafc6cc6-ccff-4ffe-8ba6-b4d5692e97a5.png) Ignore pic one, I changed the URL and put only one.
> 
> What error occurs? Did you manage to import the user?

Nothing happen. When I try with the LDAP test button in the bottom, It detect if my user/password is good or wrong.
But when I do the same in login page, it load without error, forever
![Capture d'écran 2023-11-23 161854](https://github.com/nilsteampassnet/TeamPass/assets/94232342/633068cb-ea21-43fc-817e-ff4e88516439)

**Comment by volrod64** [comment]
Hey,
Did I do something incorrect ?
Thanks in advance.

**Comment by oshkurin** [comment]
@volrod64 you need Active Directory user with read rights, check is that user can access DC (network connectivity) and is that user can read directory, for example:
ldapsearch -x -h 172.16....... -p 389 -D "openvpn@domain_name" -W -b "dc=domain,dc=name,dc=com" cn

If check passed - let's add users from AD. Go to LDAP settins in TeamPass, enable LDAP configuration
![image](https://github.com/nilsteampassnet/TeamPass/assets/41479577/f26fd08b-178c-4dbb-aeb2-f3bbbb1ffc4b)

After that go to Users page in TeamPass and press LDAP synchronization
![image](https://github.com/nilsteampassnet/TeamPass/assets/41479577/f0d93501-ad0a-435a-ac51-e017e0744127)

After that you can add users from AD:
![image](https://github.com/nilsteampassnet/TeamPass/assets/41479577/45ad309c-2d34-46d3-a49c-5bcc8d4fd52f)

**Comment by volrod64** [comment]
Thanks for trying to help !
As you can see on this picture 
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/a123590c-bc8b-4597-b7c8-5eba320eaa7e)
Users are actually synced properly, and added to teampass. The issue is that when I tryna connect with an account frm my active directory, It load forever.
When I use this
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/35127bbc-405d-49f8-9797-4dc2ab069306)
To test an account, It look fine. When I try to connect to the site, I can't

Any idea ? Thanks once again for the support :)

**Comment by oshkurin** [comment]
@volrod64 
have you added a user?
![image](https://github.com/nilsteampassnet/TeamPass/assets/41479577/6b62647a-af67-4980-b1a5-429b81888943)

**Comment by volrod64** [comment]
All those users are " newly " synced with the Active Directory.
The user I tried to login with is already synced with teampass
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/4b2d72d1-87aa-45ff-a083-99cb9b9b1049)
On the login page, I have this 
![image](https://github.com/nilsteampassnet/TeamPass/assets/94232342/7c9f4629-d55f-44ee-80bf-17ebcb179288)
Loading forever.
But If I put the wrong password, I got an error " wrong login/password "

**Comment by nilsteampassnet** [comment]
@oshkurin, Thank you for providing your support 👍

@volrod64 
When you try to get logged into TP using this AD user, can you check if this generates an error inside the Apache error log file.
I'm pretty sure, you have one.
Can you share with us please

**Comment by ecunhar** [comment]
Hello @nilsteampassnet and @oshkurin,

I would like to inform you that I am also facing the same problem, where LDAP Sync is working correctly, but I cannot LOG IN to Teampass.

Below is evidence of LDAP Sync working normally:
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/98c6d948-186d-4576-90d8-ac54e3e084ed)

Here is the LDAP configuration:
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/3cdc30bd-be18-45d0-9b3c-015a298fde11)
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/3c2f020c-f9f1-427c-b058-d353be89f0d6)
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/4466769c-876c-4890-b892-fdaf48bc742a)

Now what happens when I try to perform an LDAP connection test through a legitimate user:
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/8ae2eb6a-b7d3-4fa8-ab82-7c3930257fe2)

Below is the Apache error log:
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/847c5079-1561-48f3-9d1b-44dee456a18c)

Now when I try to LOGIN with a legitimate user registered with Teampass through LDAP Sync:
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/82453bca-8d4a-42f5-9690-b6e1a3ea3383)

Below is the Apache error log in LOGIN:
![image](https://github.com/nilsteampassnet/TeamPass/assets/155410048/bbf6b881-88c1-40dd-beb8-d15c6538bd35)


Personally, I have been working and using Teampass for a few years and since I came across this problem, so far I haven't found any solution, so I hope I can contribute to resolving this issue, as I really like the tool and wouldn't want to trade for the competition on the market. .


Below is information about my environment:

Teampass: 3.1.1.17
SO: Ubuntu Server 22.04.3 LTS
PHP: 8.1.2-1ubuntu2.14
Apache: Apache/2.4.52 (Ubuntu)
DB: mysql  Ver 8.0.35-0ubuntu0.22.04.1


Thank you very much for your attention and I am at your disposal.


Happy New Year!!!!

**Comment by raimundoa** [comment]
I have same problem

[Sat Jan 20 00:53:59.986281 2024] [php:error] [pid 26719] [client 45362] PHP Fatal error:  Uncaught TypeError: getUserADGroups(): Argument #1 ($userDN) must be of type string, null given, called in /var/www/html/TeamPass/sources/identify.php on line 1313 and defined in /var/www/html/TeamPass/sources/ldap.activedirectory.php:42\nStack trace:\n#0 /var/www/html/TeamPass/sources/identify.php(1313): getUserADGroups()\n#1 /var/www/html/TeamPass/sources/identify.php(2330): authenticateThroughAD()\n#2 /var/www/html/TeamPass/sources/identify.php(295): identifyDoLDAPChecks()\n#3 /var/www/html/TeamPass/sources/identify.php(131): identifyUser()\n#4 {main}\n  thrown in /var/www/html/TeamPass/sources/ldap.activedirectory.php on line 42, referer: http://teampass.client.local/index.php

I can see my users of the active directory, but I received this error when loggin user.

**Comment by raimundoa** [comment]
![Screenshot from 2024-01-23 00-17-42](https://github.com/nilsteampassnet/TeamPass/assets/143142757/1476d9ec-ae61-4d91-b8c1-42ccccc5328a)
![Screenshot from 2024-01-23 00-15-32](https://github.com/nilsteampassnet/TeamPass/assets/143142757/2bd0c8ef-2bec-4d40-8542-6f1c9ba15dfc)
![Screenshot from 2024-01-23 00-16-40](https://github.com/nilsteampassnet/TeamPass/assets/143142757/8a230e7e-1aa0-4c02-8970-46265f05dd71)
![Screenshot from 2024-01-23 00-16-14](https://github.com/nilsteampassnet/TeamPass/assets/143142757/7b0d5c85-efa4-48b1-aa63-a020d9c20992)

**Comment by gonzalodeniz** [comment]
This solution worked for me.
https://github.com/nilsteampassnet/TeamPass/issues/4080#issuecomment-1971814974

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
