### ISSUE TITLE
Teampass 2.1.26-latest-3 to 2.1.27.(latest)

### ISSUE THREAD

**Issue by arteMatth** [nilsteampassnet/TeamPass#3960]
### Steps to reproduce
1. Download 2.1.27.(latest) package on your server
2. Unzip package into Teampass folder (could be another name) and overwrite existing files and folders,
3. Before starting the upgrade, run the SQL query: ALTER TABLE `teampass_misc` CHANGE `id` `increment_id` INT(12) NOT NULL AUTO_INCREMENT;
4. http://your_domain/install/upgrade.php
5. Now follow the upgrade pages

### Expected behaviour
Following the Documentation (https://teampass.readthedocs.io/en/latest/install/upgrade/)
After following all the upgrade steps Teampass 2.1.27 should be installed. 

### Actual behaviour
On the first try upgrading Teampass I was able to press the Next-Button on Step 5 (Miscellaneous), but after that I could only enter the http://your-domain/install/upgrade.php and couldn't access the http://your-domain/index.php. 
I thought I made a mistake so I deleted the teampass folder and used a backup of this folder to start from the beginning again. 
I followed all the steps of (https://teampass.readthedocs.io/en/latest/install/upgrade/) again. Now everytime the launch-button gets pressed at Step 5 (Miscellaneous) I get an error in the browser console: 
POST http://your-domain/install/upgrade_ajax.php 500 (Internal Server Error) 

And if I press the launch-button a second time I get a different error: 
Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at eval (eval at xhrObject.onreadystatechange (upgrade.js:59:17), <anonymous>:1:112)
    at xhrObject.onreadystatechange (upgrade.js:59:17)

### Server configuration
**Operating system**:
Ubuntu 22.04
**Web server:**
Apache/2.4.10
**Database:**
MySQL
**PHP version:**
PHP 5.6.33
**Teampass version:** 
2.1.26-lates-3
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Updated from Version 2.1.25 to 2.1.26-latest-3, which is working fine. 
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 11
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by arteMatth** [comment]
/
