### ISSUE TITLE
You have an error in your SQL syntax

### ISSUE THREAD

**Issue by mreinders** [nilsteampassnet/TeamPass#3974]
There are problems with get items api. 

I'm trying to get items by ID or label, but getting the understanding error in my php-fpm logging:

PHP Fatal error:  Uncaught Exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) ORDER BY i.id ASC' at line 3 in teampass/api/Model/Database.php:51
Stack trace:
#0 /var/www/html/teampass/api/Model/ItemModel.php(52): Database->select()
#1 /var/www/html/teampass/api/Controller/Api/ItemController.php(221): ItemModel->getItems()
#2 /var/www/html/teampass/api/inc/bootstrap.php(59): ItemController->getAction()
#3 /var/www/html/teampass/api/index.php(93): itemAction()
#4 {main}
  thrown in /var/www/html/teampass/api/Model/Database.php on line 51

Teampass is running on RockyLinux 9 with php 8.1 and mariadb 10.11. I tried the API also with php 8.2, but shows the same behaviour. When I remove the query (all code behind the "?"), then all visible passwords are showing up:

{
    "error": "Item id, label or description is mandatory"
}[
    {
        "id": 1,
        "label": "test",
        "description": "",
        "pwd": "test",
        "url": "",
        "login": "test",
        "email": "",
        "viewed_no": 0,
        "fa_icon": "",
        "inactif": 0,
        "perso": 0,
        "id_tree": 1,
        "folder_label": "Qonnected",
        "path": ""
    }
]

What do we have to do to query the database from API?

**Comment by mreinders** [comment]
I managed to solve the issue with a workarround for the getItems api.

I changed the line 193 from:
$sql_constraint = ' AND (i.id_tree IN ('.$userData['folders_list'].') OR i.id IN ('.$userData['restricted_items_list'].'))';

to:
$sql_constraint = ' AND (i.id_tree IN ('.$userData['folders_list'].'))';

It looks like the restricted_items_list variable produces the above error.

**Comment by Nathu2018** [comment]
![Screenshot 2024-09-17 171237](https://github.com/user-attachments/assets/b59c4b3c-1cea-4e95-9378-3e283c7f3377)

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
