### ISSUE TITLE
Upgrading from 2.1.27.36 to 3.1.0

### ISSUE THREAD

**Issue by fGoncalvess** [nilsteampassnet/TeamPass#3983]
### Steps to reproduce
1. Upgraded from 2.1.27.26 to 2.1.27.36
2. Follow the preparations for the upgrade using https://documentation.teampass.net/#/install/upgrade
3. Start the upgrade process to 3.0.10

### Expected behaviour
The Upgrade should happen successfully

### Actual behaviour
When I insert my user and password and press the start button, I get a spinning cog wheel that should be the processing of the action. 
![image](https://github.com/nilsteampassnet/TeamPass/assets/139380685/43161c34-3595-42fe-a8b2-8c88dd642077)
When I open the developer tools, I see a error 500 in the upgrade_ajax.php:

```POST https://teampass.reload.pt/teampass_v3/install/upgrade_ajax.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2```

And a "SyntaxError: Unexpected end of JSON Input":
```Uncaught SyntaxError: Unexpected end of JSON input
    at Function.parse [as parseJSON] (<anonymous>)
    at Object.complete (upgrade.php:216:26)
    at c (jquery.min.js:2:28327)
    at Object.fireWith (jquery.min.js:2:29072)
    at l (jquery.min.js:2:80029)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82355)
    at Object.send (jquery.min.js:2:82714)
    at Function.ajax (jquery.min.js:2:78291)
    at HTMLInputElement.<anonymous> (upgrade.php:208:18)
    at HTMLInputElement.dispatch (jquery.min.js:2:43064)
    complete @ upgrade.php:216
     c @ jquery.min.js:2
     fireWith @ jquery.min.js:2
     l @ jquery.min.js:2
     (anonymous) @ jquery.min.js:2
     send @ jquery.min.js:2
     ajax @ jquery.min.js:2
     (anonymous) @ upgrade.php:208
     dispatch @ jquery.min.js:2
     v.handle @ jquery.min.js:2
     load (async)
     send @ jquery.min.js:2
     ajax @ jquery.min.js:2
     (anonymous) @ upgrade.php:208
     dispatch @ jquery.min.js:2
     v.handle @ jquery.min.js:2
``` 

### Server configuration
**Operating system**: Ubuntu Server 18.04.1 LTS

**Web server:**Apache/2.4.29 (Ubuntu)

**Database:**5.7.42-0ubuntu0.18.04.1

**PHP version:**7.2.24

**Teampass version:**2.1.27.36 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

```<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '0',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://teampass.reload.pt/teampass',
    'favicon' => 'https://teampass.reload.pt/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'https://teampass.reload.pt/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://teampass.reload.pt/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '1',
    'ldap_type' => 'windows',
    'ldap_suffix' => '@reload.pt',
    'ldap_domain_dn' => 'DC=reload,DC=pt',
    'ldap_domain_controler' => 'srvdc04.reload.pt',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '5',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1535280759',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '192.168.33.9',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'teampass@securnet.pt',
    'email_from_name' => 'Teampass ',
    'pwd_maximum_length' => '40',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'Securnet TeamPass ',
    'api' => '1',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '1',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '2',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'ldap_new_user_role' => '1',
    'bck_script_passkey' => 'JZUPqDg394LVvWBWVeNPPtrZLKB85c5fW426UJwL',
    'ga_reset_by_user' => '1',
    'yubico_authentication' => '0',
    'teampass_version' => '2.1.27',
    'admin_2fa_required' => '0',
    );
```

### Client configuration
**Browser:** Edge 120

**Operating system:** Windows 11

#### Web server error log
```
[Fri Dec 15 10:48:40.408583 2023] [php7:emerg] [pid 4281] [client 192.168.102.68:52934] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/teampass_v3/sources/main.functions.php on line 649
[Fri Dec 15 10:48:44.456484 2023] [php7:warn] [pid 4280] [client 192.168.102.68:52933] PHP Warning:  require_once(/var/www/html/teampass/includes/config/settings.php): failed to open stream: No such file or directory in /var/www/html/teampass_v2/index.php on line 58
[Fri Dec 15 10:48:44.456613 2023] [php7:error] [pid 4280] [client 192.168.102.68:52933] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/teampass/includes/config/settings.php' (include_path='.:/usr/share/php') in /var/www/html/teampass_v2/index.php on line 58
[Fri Dec 15 10:49:24.570947 2023] [php7:emerg] [pid 17211] [client 192.168.102.68:52946] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/teampass_v3/sources/main.functions.php on line 649
[Fri Dec 15 10:53:15.989371 2023] [autoindex:error] [pid 17229] [client 192.168.102.78:56866] AH01276: Cannot serve directory /var/www/html/teampass_v3/install/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Fri Dec 15 10:53:41.962637 2023] [php7:emerg] [pid 4280] [client 192.168.102.78:56901] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/teampass_v3/sources/main.functions.php on line 649, referer: https://teampass.reload.pt/teampass_v3/install/upgrade.php
[Fri Dec 15 11:07:08.675975 2023] [php7:emerg] [pid 17228] [client 192.168.102.78:57410] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/teampass_v3/sources/main.functions.php on line 649, referer: https://teampass.reload.pt/teampass_v3/install/upgrade.php
[Fri Dec 15 11:14:18.964221 2023] [php7:emerg] [pid 17229] [client 192.168.102.78:57764] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/teampass_v3/sources/main.functions.php on line 649, referer: https://teampass.reload.pt/teampass_v3/install/upgrade.php
[Fri Dec 15 11:26:25.185622 2023] [php7:emerg] [pid 17211] [client 192.168.102.78:58324] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/teampass_v3/sources/main.functions.php on line 649, referer: https://teampass.reload.pt/teampass_v3/install/upgrade.php
[Fri Dec 15 11:26:27.236541 2023] [php7:emerg] [pid 17237] [client 192.168.102.78:58327] PHP Parse error:  syntax error, unexpected ')' in /var/www/html/teampass_v3/sources/main.functions.php on line 649, referer: https://teampass.reload.pt/teampass_v3/install/upgrade.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
POST https://teampass.reload.pt/teampass_v3/install/upgrade_ajax.php 500 (Internal Server Error)
send @ jquery.min.js:2
ajax @ jquery.min.js:2
(anonymous) @ upgrade.php:208
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2`
```

**Comment by Arash9703** [comment]
I have same problem here  while upgrading to 3.1.1

![image](https://github.com/nilsteampassnet/TeamPass/assets/143269985/c25d4a46-67d1-428f-b87e-e4ad25ec99d1)

**Comment by jucabalasilva** [comment]
Me too. Show this messages from www-error.log

```
[18-Dec-2023 09:49:48 America/Sao_Paulo] PHP Warning:  include_once(/var/www/TeamPass-3.0.10/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/TeamPass-3.0.10/sources/main.functions.php on line 55
[18-Dec-2023 09:49:48 America/Sao_Paulo] PHP Warning:  include_once(): Failed opening '/var/www/TeamPass-3.0.10/sources/../includes/config/tp.config.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/TeamPass-3.0.10/sources/main.functions.php on line 55
[18-Dec-2023 09:49:48 America/Sao_Paulo] PHP Warning:  require_once(/var/www/TeamPass-3.0.10/sources/../includes/config/settings.php): Failed to open stream: No such file or directory in /var/www/TeamPass-3.0.10/sources/main.functions.php on line 4276
[18-Dec-2023 09:49:48 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/TeamPass-3.0.10/sources/../includes/config/settings.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/TeamPass-3.0.10/sources/main.functions.php:4276
Stack trace:
#0 /var/www/TeamPass-3.0.10/sources/main.functions.php(61): loadClasses()
#1 /var/www/TeamPass-3.0.10/install/upgrade_ajax.php(29): require_once('...')
#2 {main}
  thrown in /var/www/TeamPass-3.0.10/sources/main.functions.php on line 4276
```

**Comment by fGoncalvess** [comment]
Quick Update:

-  I did notice that I had package versions, that wouldn't work with 3.1.0, so I updated to Ubuntu 22.04, MariaDB to 11.2 and PHP to 8.2.13;
- The website looks the same when I try to start the upgrade process;
- On the Webserver, each time I try to start the upgrade I get this error message on /var/log/apache2/error.log:

    ´´´PHP Fatal error:  Uncaught Error: Undefined constant "DB_PASSWD" in 
      /var/www/html/teampass_v3/sources/main.functions.php:4297\nStack trace:\n#0 
      /var/www/html/teampass_v3/sources/main.functions.php(61): loadClasses()\n#1 
      /var/www/html/teampass_v3/install/upgrade_ajax.php(29): require_once('...')\n#2 {main}\n  thrown in 
      /var/www/html/teampass_v3/sources/main.functions.php on line 4297, referer: 
      https://teampass.reload.pt/teampass_v3/install/upgrade.php´´´

Assuming this DB_PASSWD is the password that I defined for my DB user and it's in the include/config/settings.php, since this is a copy of a VM in production, I changed the DB User Password when reconfiguring MariaDB. My question now is, how can I change the password in the settings.php to the new one, since the password in encrypted in the file?

**Comment by deanbruhn** [comment]
I am getting this same issue. I am running php 8.1 and have tried 8.2 since the upgrade told me it was needed and MariaDB 10.7.8. I am getting the same error with the spinning gear, and nothing happening.

**Comment by Roadster850** [comment]
I have the same issue from an upgrade. Has anyone found a way past the error: PHP Fatal error:  Uncaught Error: Undefined constant "DB_PASSWD"

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
