### ISSUE TITLE
Reload after creating new folder not working

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#4016]
TP-Version: 3.1.1.46
After creating a new folder the redirect to Folders should work.
Instead the content page stays empty and the following error appears in error.log:
```
Stack trace:
#0 /var/www/html/teampass-dev/sources/folders.queries.php(148): in_array()
#1 {main}
  thrown in /var/www/html/teampass-dev/sources/folders.queries.php on line 148
[20-Jan-2024 11:53:57 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, int given in /var/www/html/teampass-dev/sources/folders.queries.php:1539
Stack trace:
#0 /var/www/html/teampass-dev/sources/folders.queries.php(1539): in_array()
#1 {main}
  thrown in /var/www/html/teampass-dev/sources/folders.queries.php on line 1539
```
Choosing Folder from the navigation tab leads to working folders and the new created folder is also visible
Thx

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
