### ISSUE TITLE
Login with LDAP credentials not working, get a http 500

### ISSUE THREAD

**Issue by useronkel** [nilsteampassnet/TeamPass#4017]
TP-Version: 3.1.1.46

Synchronizing users with LDAP and adding a user to TP seems to work.
When I try to login, I get the following error in error.log:
```
[20-Jan-2024 12:22:35 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: TeampassClasses\PasswordManager\PasswordManager::migratePassword(): Argument #3 ($userId) must be of type int, string given, called in /var/www/html/teampass-dev/sources/identify.php on line 1389 and defined in /var/www/html/teampass-dev/vendor/teampassclasses/passwordmanager/src/PasswordManager.php:60
Stack trace:
#0 /var/www/html/teampass-dev/sources/identify.php(1389): TeampassClasses\PasswordManager\PasswordManager->migratePassword()
#1 /var/www/html/teampass-dev/sources/identify.php(1298): finalizeAuthentication()
#2 /var/www/html/teampass-dev/sources/identify.php(2243): authenticateThroughAD()
#3 /var/www/html/teampass-dev/sources/identify.php(328): identifyDoLDAPChecks()
#4 /var/www/html/teampass-dev/sources/identify.php(162): identifyUser()
#5 /var/www/html/teampass-dev/sources/identify.php(194): handleAuthAttempts()
#6 {main}
  thrown in /var/www/html/teampass-dev/vendor/teampassclasses/passwordmanager/src/PasswordManager.php on line 60
```

**Comment by nilsteampassnet** [comment]
@useronkel 
THis has been fixed in latest commit (3.1.1.48)

**Comment by useronkel** [comment]
Works like a charm :-)

**Comment by useronkel** [comment]
Works like a charm :-)
