### ISSUE TITLE
[ERROR] ANSWER FROM SERVER IS EMPTY. during first installation with docker compose - Teampass 3.1.1

### ISSUE THREAD

**Issue by raphaeldallorto** [nilsteampassnet/TeamPass#4022]
### Steps to reproduce
1. Fresh installation of Teampass 3.1.1 with docker-compose
2.
3.

### Expected behaviour
Installation should take place normally

### Actual behaviour
"[ERROR] Answer from server is empty." popup while installation procedure

### Server configuration
**Operating system: Ubuntu Server 20.04

**Web server: nginx

**Database: MariaDB 10.11.6

**PHP version:8.2

**Teampass version: 3.1.1

**Teampass configuration file:**

**Updated from an older Teampass or fresh install: fresh install

**Docker version:** Docker version 20.10.23

### Client configuration
**Browser:** Chrome 120.0.6099.216 64 Bits

**Operating system:** Windows 11 23H2

#### Web server error log
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initial setup...
Initialized empty Git repository in /var/www/html/.git/
From https://github.com/nilsteampassnet/TeamPass
 * [new branch]        PHP_7.4      -> origin/PHP_7.4
 * [new branch]        dependabot/github_actions/jitsecurity-controls/jit-github-action-4.0.6 -> origin/dependabot/github_actions/jitsecurity-controls/jit-github-action-4.0.6
 * [new branch]        develop      -> origin/develop
 * [new branch]        master       -> origin/master
 * [new branch]        teampass_2   -> origin/teampass_2
 * [new branch]        wip_sessions -> origin/wip_sessions
 * [new tag]           2.1            -> 2.1
 * [new tag]           2.1.20         -> 2.1.20
 * [new tag]           2.1.23.1       -> 2.1.23.1
 * [new tag]           2.1.23.2       -> 2.1.23.2
 * [new tag]           2.1.23.3       -> 2.1.23.3
 * [new tag]           2.1.23.4       -> 2.1.23.4
 * [new tag]           2.1.24.0       -> 2.1.24.0
 * [new tag]           2.1.24.1       -> 2.1.24.1
 * [new tag]           2.1.24.2       -> 2.1.24.2
 * [new tag]           2.1.24.3       -> 2.1.24.3
 * [new tag]           2.1.24.4       -> 2.1.24.4
 * [new tag]           2.1.25.0       -> 2.1.25.0
 * [new tag]           2.1.25.1       -> 2.1.25.1
 * [new tag]           2.1.25.2       -> 2.1.25.2
 * [new tag]           2.1.26         -> 2.1.26
 * [new tag]           2.1.26-RC1     -> 2.1.26-RC1
 * [new tag]           2.1.26-final   -> 2.1.26-final
 * [new tag]           2.1.26-final-2 -> 2.1.26-final-2
 * [new tag]           2.1.26-final-3 -> 2.1.26-final-3
 * [new tag]           2.1.26.0       -> 2.1.26.0
 * [new tag]           2.1.26.1       -> 2.1.26.1
 * [new tag]           2.1.26.10      -> 2.1.26.10
 * [new tag]           2.1.26.11      -> 2.1.26.11
 * [new tag]           2.1.26.12      -> 2.1.26.12
 * [new tag]           2.1.26.13      -> 2.1.26.13
 * [new tag]           2.1.26.14      -> 2.1.26.14
 * [new tag]           2.1.26.15      -> 2.1.26.15
 * [new tag]           2.1.26.16      -> 2.1.26.16
 * [new tag]           2.1.26.17      -> 2.1.26.17
 * [new tag]           2.1.26.18      -> 2.1.26.18
 * [new tag]           2.1.26.19      -> 2.1.26.19
 * [new tag]           2.1.26.2       -> 2.1.26.2
 * [new tag]           2.1.26.20      -> 2.1.26.20
 * [new tag]           2.1.26.3       -> 2.1.26.3
 * [new tag]           2.1.26.4       -> 2.1.26.4
 * [new tag]           2.1.26.5       -> 2.1.26.5
 * [new tag]           2.1.26.6       -> 2.1.26.6
 * [new tag]           2.1.26.7       -> 2.1.26.7
 * [new tag]           2.1.26.8       -> 2.1.26.8
 * [new tag]           2.1.26.9       -> 2.1.26.9
 * [new tag]           2.1.26_RC1     -> 2.1.26_RC1
 * [new tag]           2.1.27.0       -> 2.1.27.0
 * [new tag]           2.1.27.1       -> 2.1.27.1
 * [new tag]           2.1.27.10      -> 2.1.27.10
 * [new tag]           2.1.27.11      -> 2.1.27.11
 * [new tag]           2.1.27.12      -> 2.1.27.12
 * [new tag]           2.1.27.13      -> 2.1.27.13
 * [new tag]           2.1.27.14      -> 2.1.27.14
 * [new tag]           2.1.27.15      -> 2.1.27.15
 * [new tag]           2.1.27.16      -> 2.1.27.16
 * [new tag]           2.1.27.17      -> 2.1.27.17
 * [new tag]           2.1.27.18      -> 2.1.27.18
 * [new tag]           2.1.27.19      -> 2.1.27.19
 * [new tag]           2.1.27.2       -> 2.1.27.2
 * [new tag]           2.1.27.20      -> 2.1.27.20
 * [new tag]           2.1.27.21      -> 2.1.27.21
 * [new tag]           2.1.27.22      -> 2.1.27.22
 * [new tag]           2.1.27.23      -> 2.1.27.23
 * [new tag]           2.1.27.24      -> 2.1.27.24
 * [new tag]           2.1.27.25      -> 2.1.27.25
 * [new tag]           2.1.27.26      -> 2.1.27.26
 * [new tag]           2.1.27.27      -> 2.1.27.27
 * [new tag]           2.1.27.28      -> 2.1.27.28
 * [new tag]           2.1.27.29      -> 2.1.27.29
 * [new tag]           2.1.27.3       -> 2.1.27.3
 * [new tag]           2.1.27.30      -> 2.1.27.30
 * [new tag]           2.1.27.31      -> 2.1.27.31
 * [new tag]           2.1.27.32      -> 2.1.27.32
 * [new tag]           2.1.27.33      -> 2.1.27.33
 * [new tag]           2.1.27.34      -> 2.1.27.34
 * [new tag]           2.1.27.35      -> 2.1.27.35
 * [new tag]           2.1.27.36      -> 2.1.27.36
 * [new tag]           2.1.27.4       -> 2.1.27.4
 * [new tag]           2.1.27.5       -> 2.1.27.5
 * [new tag]           2.1.27.6       -> 2.1.27.6
 * [new tag]           2.1.27.7       -> 2.1.27.7
 * [new tag]           2.1.27.8       -> 2.1.27.8
 * [new tag]           2.1.27.9       -> 2.1.27.9
 * [new tag]           3.0.0.0        -> 3.0.0.0
 * [new tag]           3.0.0.10       -> 3.0.0.10
 * [new tag]           3.0.0.11       -> 3.0.0.11
 * [new tag]           3.0.0.12       -> 3.0.0.12
 * [new tag]           3.0.0.13       -> 3.0.0.13
 * [new tag]           3.0.0.14       -> 3.0.0.14
 * [new tag]           3.0.0.15       -> 3.0.0.15
 * [new tag]           3.0.0.16       -> 3.0.0.16
 * [new tag]           3.0.0.17       -> 3.0.0.17
 * [new tag]           3.0.0.18       -> 3.0.0.18
 * [new tag]           3.0.0.19       -> 3.0.0.19
 * [new tag]           3.0.0.2        -> 3.0.0.2
 * [new tag]           3.0.0.20       -> 3.0.0.20
 * [new tag]           3.0.0.21       -> 3.0.0.21
 * [new tag]           3.0.0.22       -> 3.0.0.22
 * [new tag]           3.0.0.23       -> 3.0.0.23
 * [new tag]           3.0.0.3        -> 3.0.0.3
 * [new tag]           3.0.0.5        -> 3.0.0.5
 * [new tag]           3.0.0.6        -> 3.0.0.6
 * [new tag]           3.0.0.7        -> 3.0.0.7
 * [new tag]           3.0.0.8        -> 3.0.0.8
 * [new tag]           3.0.0.9        -> 3.0.0.9
 * [new tag]           3.0.1          -> 3.0.1
 * [new tag]           3.0.10         -> 3.0.10
 * [new tag]           3.0.2          -> 3.0.2
 * [new tag]           3.0.3          -> 3.0.3
 * [new tag]           3.0.4          -> 3.0.4
 * [new tag]           3.0.5          -> 3.0.5
 * [new tag]           3.0.6          -> 3.0.6
 * [new tag]           3.0.7          -> 3.0.7
 * [new tag]           3.0.8          -> 3.0.8
 * [new tag]           3.0.9          -> 3.0.9
 * [new tag]           3.1.0          -> 3.1.0
 * [new tag]           3.1.1          -> 3.1.1
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

branch 'master' set up to track 'origin/master'.
Already on 'master'
mkdir: can't create directory '/var/www/html/includes/libraries/csrfp/log': File exists
Teampass is not configured yet. Open it in a web browser to run the install process.
Use /var/www/html/sk for the absolute path of your saltkey.
When setup is complete, restart this image to remove the install directory.
Changed current directory to /root/.composer
Cannot use hirak/prestissimo's latest version 0.3.10 as it requires php ^5.3.2 || ^7.0 which is not satisfied by your platform.

Installation failed, deleting ./composer.json.

In RequireCommand.php line 225:

  No composer.json present in the current directory (./composer.json), this m
  ay be the cause of the following exception.


In PackageDiscoveryTrait.php line 317:

  Package hirak/prestissimo has requirements incompatible with your PHP versi
  on, PHP extensions and Composer version:
    - hirak/prestissimo 0.3.10 requires php ^5.3.2 || ^7.0 which does not mat
  ch your installed version 8.2.7.
    - hirak/prestissimo 0.3.10 requires composer-plugin-api ^1.0.0 which does
   not match your installed version 2.3.0.


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
Class PasswordLib\PasswordLib located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/PasswordLib.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Factory located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Factory.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Mixer located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Mixer.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\AbstractMixer located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/AbstractMixer.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Generator located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Generator.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Mixer\Hash located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Mixer/Hash.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Source located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Source.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Source\MTRand located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Source/MTRand.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Source\MicroTime located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Source/MicroTime.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Source\Rand located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Source/Rand.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Source\CAPICOM located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Source/CAPICOM.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Source\UniqID located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Source/UniqID.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Random\Source\URandom located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Random/Source/URandom.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Factory located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Factory.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Password located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Password.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\PHPBB located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/PHPBB.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\SHA512 located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/SHA512.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\Hash located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/Hash.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\PHPASS located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/PHPASS.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\PBKDF located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/PBKDF.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\APR1 located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/APR1.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\MD5 located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/MD5.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\Blowfish located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/Blowfish.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\Drupal located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/Drupal.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\SHA256 located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/SHA256.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\Joomla located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/Joomla.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Password\Implementation\Crypt located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Password/Implementation/Crypt.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Hash\Hash located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Hash/Hash.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\Strength located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/Strength.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\BigMath located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/BigMath.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\AutoLoader located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/AutoLoader.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\Enum located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/Enum.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\BigMath\PHPMath located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/BigMath/PHPMath.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\BigMath\GMP located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/BigMath/GMP.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\BigMath\BCMath located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/BigMath/BCMath.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\BaseConverter located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/BaseConverter.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Core\AbstractFactory located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Core/AbstractFactory.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Key\Factory located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Key/Factory.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Key\Derivation\PBKDF\PBKDF2 located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Key/Derivation/PBKDF/PBKDF2.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Key\Derivation\PBKDF located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Key/Derivation/PBKDF.php does not comply with psr-0 autoloading standard. Skipping.
Class PasswordLib\Key\Derivation\AbstractDerivation located in ./vendor/passwordlib/passwordlib/lib/PasswordLib_alpha2/Key/Derivation/AbstractDerivation.php does not comply with psr-0 autoloading standard. Skipping.
32 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
2024-01-23 11:51:11,124 INFO Included extra file "/etc/supervisor/conf.d/crond.conf" during parsing
2024-01-23 11:51:11,125 INFO Set uid to user 0 succeeded
2024-01-23 11:51:11,135 INFO RPC interface 'supervisor' initialized
2024-01-23 11:51:11,135 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2024-01-23 11:51:11,135 INFO supervisord started with pid 1
2024-01-23 11:51:12,138 INFO spawned: 'php-fpm' with pid 60
2024-01-23 11:51:12,141 INFO spawned: 'nginx' with pid 61
2024-01-23 11:51:12,155 INFO spawned: 'crond' with pid 62
crond: crond (busybox 1.36.1) started, log level 8
2024/01/23 11:51:12 [notice] 61#61: using the "epoll" event method
2024/01/23 11:51:12 [notice] 61#61: nginx/1.24.0
2024/01/23 11:51:12 [notice] 61#61: OS: Linux 5.4.0-163-generic
2024/01/23 11:51:12 [notice] 61#61: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/01/23 11:51:12 [notice] 61#61: start worker processes
2024/01/23 11:51:12 [notice] 61#61: start worker process 63
[23-Jan-2024 11:51:12] NOTICE: fpm is running, pid 60
[23-Jan-2024 11:51:12] NOTICE: ready to handle connections
2024-01-23 11:51:13,348 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-23 11:51:13,348 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-23 11:51:13,348 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
crond: USER nginx pid  67 cmd php /var/www/html/sources/scheduler.php
PHP Warning:  require_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/scheduler.php on line 34
PHP Stack trace:
PHP   1. {main}() /var/www/html/sources/scheduler.php:0

Warning: require_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/scheduler.php on line 34

Call Stack:
    0.0002     417376   1. {main}() /var/www/html/sources/scheduler.php:0

PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php:34
Stack trace:
#0 {main}
  thrown in /var/www/html/sources/scheduler.php on line 34

Fatal error: Uncaught Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php on line 34

Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php on line 34

Call Stack:
    0.0002     417376   1. {main}() /var/www/html/sources/scheduler.php:0

crond: USER nginx pid  68 cmd php /var/www/html/sources/scheduler.php
PHP Warning:  require_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/scheduler.php on line 34
PHP Stack trace:
PHP   1. {main}() /var/www/html/sources/scheduler.php:0

Warning: require_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/scheduler.php on line 34

Call Stack:
    0.0002     417376   1. {main}() /var/www/html/sources/scheduler.php:0

PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php:34
Stack trace:
#0 {main}
  thrown in /var/www/html/sources/scheduler.php on line 34

Fatal error: Uncaught Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php on line 34

Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php on line 34

Call Stack:
    0.0002     417376   1. {main}() /var/www/html/sources/scheduler.php:0

192.168.0.11 - - [23/Jan/2024:11:53:11 -0300] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
192.168.0.11 - - [23/Jan/2024:11:53:11 -0300] "GET /install/install.php HTTP/1.1" 200 4922 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
192.168.0.11 - - [23/Jan/2024:11:53:18 -0300] "POST /install/install.php HTTP/1.1" 200 6423 "https://teampass.saude.es.gov.br/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP Warning:  include_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/main.functions.php on line 58"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/install/install.queries.php:0"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/install/install.queries.php:51"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP Warning:  include_once(): Failed opening '/var/www/html/sources/../includes/config/tp.config.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/sources/main.functions.php on line 58"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/install/install.queries.php:0"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/install/install.queries.php:51"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP Warning:  Undefined variable $session in /var/www/html/includes/config/settings.php on line 28"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/install/install.queries.php:0"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/install/install.queries.php:51"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   3. loadClasses($className = 'DB') /var/www/html/sources/main.functions.php:64"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP   4. require_once() /var/www/html/sources/main.functions.php:4314"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function has() on null in /var/www/html/includes/config/settings.php:28"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "Stack trace:"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "#0 /var/www/html/sources/main.functions.php(4314): require_once()"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "#1 /var/www/html/sources/main.functions.php(64): loadClasses('DB')"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "#2 /var/www/html/install/install.queries.php(51): require_once('/var/www/html/s...')"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "#3 {main}"
[23-Jan-2024 11:53:21] WARNING: [pool www] child 65 said into stderr: "  thrown in /var/www/html/includes/config/settings.php on line 28"
192.168.0.11 - - [23/Jan/2024:11:53:21 -0300] "POST /install/install.queries.php HTTP/1.1" 500 5 "https://teampass.saude.es.gov.br/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
crond: USER nginx pid  69 cmd php /var/www/html/sources/scheduler.php
PHP Warning:  require_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/scheduler.php on line 34
PHP Stack trace:
PHP   1. {main}() /var/www/html/sources/scheduler.php:0

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
jquery.min.js:18         
       POST https://xxxx.com/install/install.queries.php 500 (Internal Server Error)
```

Note: I noticed that the image dormancygrace/teampass:latest does not have the PHP extension mcrypt

**Comment by ToFz80** [comment]
Hi

Same problem with fresh install on DEBIAN 
APACHE 2.4.57
PHP 8.2.7
MARIADB 10.11.4

**Comment by vmaglietta** [comment]
I can confirm the same @raphaeldallorto  behavior trying to install Teampass on an Azure Web App following this learning path:
https://github.com/Azure-Samples/multicontainerwordpress.

here the error:
`PHP Fatal error: Uncaught Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php:34`

**Comment by Aprendiz011** [comment]
I have the same problem as raphaeldallorto.

Server configuration

**Operating system: Ubuntu Server 20.04

**Webserver: nginx

**Database: MariaDB 10.11.6

**PHP version:8.1

**Teampass version: 3.1.1

![image](https://github.com/nilsteampassnet/TeamPass/assets/125315542/0cbf9f0f-8e64-4827-b79f-3cf7cdedd8bc)
<img width="947" alt="Captura de tela 2024-01-29 110347" src="https://github.com/nilsteampassnet/TeamPass/assets/125315542/3d6e082c-19f7-43cd-ae85-6e9cdd912864">

**Comment by stav3ng3r** [comment]
Hi, getting the same error on docker install:

**Operating system: Ubuntu Server 20.04

**Webserver: nginx

**Database: MariaDB 10.11.6

**PHP version:8.2.7

**Teampass version: 3.1.1

`teampass-teampass-web-1  | Fatal error: Uncaught Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php on line 34
teampass-teampass-web-1  | 
teampass-teampass-web-1  | Error: Failed opening required '/var/www/html/sources/../includes/config/tp.config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/sources/scheduler.php on line 34`

**Comment by clipseman** [comment]
I also have the same problem: [ERROR] Answer from server is empty. at the 1st time installation version 3.1.1

**Comment by jnatschev** [comment]
there are issues.
i attempted a docker-compose installation and:
- PHP Warning:  require_once(/var/www/html/sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/sources/scheduler.php on line 34

- "  thrown in /var/www/html/includes/config/settings.php on line 28"
- "Next" button unavailable
![teampass_failure](https://github.com/nilsteampassnet/TeamPass/assets/8773561/9275d63d-7db2-4fa8-a841-7cb5eef17284)


- "Start" button results in the answer from server is empty
-

**Comment by aguinaldoabbj** [comment]
Same problem here. Am I wrong, or the only registered tag in dockerhub is the "latest" tag ? So there's no way back?

**Comment by Hubertvivien** [comment]
I also have encountered the same problem

**Comment by fgcle** [comment]
Hello all, I'm a little late to the party. But the ticket description (version 3.1.1, answer from server is empty) took me here. I believe my problem is the same, even if I did not try any of the Docker ways. My attempt was:

* System Linux Mint 20 (partly Debian, partly Ubuntu), Nginx and PHP 8.1 (FPM)
* required PHP modules installed by Debian packages
* created database (MariaDB 10.6.16) and user, assigned all privileges
* Downloaded 'master.zip' tarball, unpacked into web root, changed ownership to webserver user (here: www-data:www-data)
* made webroot writable for everyone (umm, really?)
* created missing directories according to what the docker start script does (<webroot>/sk and <webroot>/includes/libraries/csrfp/log)
* copied the csrf sample config into the expected real file name and corrected the jsURL variable to the full URL
* pointed the browser to /install/install.php (TeamPass is located directly at the webroot)

Whatever I do: the NEXT button is greyed out, and pressing the START button yields 'empty response' as already described.

The web server log schows the PHP error
```
PHP Warning:  include_once(/var/www/html/includes/config/tp.config.php): Failed to open stream: No such file or directory in /var/www/html/index.php
```

I tried to find relevant information in the docs, without success. Can somebody please explain:

What is this file `tp.config.php`? Am I supposed to supply it, or which process is supposed to create it for me? What should it contain?

I'm not too much into such kind of web application. But if somebody tells me where to look or what to do -- I think I can do it.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
