### ISSUE TITLE
Unabel to peform restore from backup

### ISSUE THREAD

**Issue by BadRobotKZ** [nilsteampassnet/TeamPass#4025]
Unable to restore backup from another server with same version. Infinite message "In progress"

### Steps to reproduce
1. Open Setting -> Backup
2. Choose filename and Encryption key
3. Click "Perform restore"

### Expected behaviour
Restored folders and passwords

### Actual behaviour
Infinite message "In progress"

### Server configuration
**Operating system**: Oracle Linux Server release 9.2 x86_64

**Web server:** Apache/2.4.57 (Oracle Linux Server) 

**Database:**  10.5.22-MariaDB MariaDB Server

**PHP version:**8.1.14

**Teampass version:** 3.1.0.11

**Teampass configuration file:**

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
[25-Jan-2024 05:38:52 UTC] PHP Fatal error:  Uncaught MeekroDBException: Unknown table 'tpdb2._install' in /var/www/html/TeamPass-3.1.0/vendor/sergeytsalkov/meekrodb/db.class.php:911
Stack trace:
#0 /var/www/html/TeamPass-3.1.0/vendor/sergeytsalkov/meekrodb/db.class.php(1020): MeekroDB->queryHelper()
#1 /var/www/html/TeamPass-3.1.0/vendor/sergeytsalkov/meekrodb/db.class.php(120): MeekroDB->queryRaw()
#2 /var/www/html/TeamPass-3.1.0/sources/backups.queries.php(339): DB::__callStatic()
#3 {main}
  thrown in /var/www/html/TeamPass-3.1.0/vendor/sergeytsalkov/meekrodb/db.class.php on line 911

```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
