### ISSUE TITLE
3.1.1.60 - OTP Bug

### ISSUE THREAD

**Issue by deanbruhn** [nilsteampassnet/TeamPass#4042]
### Steps to reproduce
1. Login to TeamPass
2. Edit or Create a new item, and enable OTP storage 
3. Save the item
4. Open the item to view the OTP code

### Expected behaviour
Tell us what should happen

TeamPass should show me an OTP code

### Actual behaviour
Tell us what happens instead
TeamPass shows me "None" or the field is blank. 

### Server configuration
**Operating system**:
Debain 11

**Web server:**
Apache 2

**Database:**
10.7.8-MariaDB

**PHP version:**
PHP 8.2.14 

**Teampass version:** 
3.1.1.60

**Teampass configuration file:**
Uploaded

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

Updated from 3.1.1.40. Issue was present on 3.1.1.40 as well.

### Client configuration
**Browser:**
Latest Safari & Latest Firefox

**Operating system:**
macOS Sonoma 14.2.1

#### Web server error log
```
[Fri Feb 02 15:01:21.501940 2024] [proxy_fcgi:error] [pid 734821] [client 209.82.178.42:51740] AH01071: Got error 'PHP message: access: W - edit: 1 - delete: 1', referer: https://pass.cloudclarity.me/index.php?page=items
[Fri Feb 02 15:01:21.912815 2024] [proxy_fcgi:error] [pid 734486] [client 209.82.178.42:51741] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to decode the secret. Is it correctly base32 encoded? in /var/www/html/vendor/spomky-labs/otphp/src/OTP.php:130\nStack trace:\n#0 /var/www/html/vendor/spomky-labs/otphp/src/OTP.php(60): OTPHP\\OTP->getDecodedSecret()\n#1 /var/www/html/vendor/spomky-labs/otphp/src/TOTP.php(76): OTPHP\\OTP->generateOTP()\n#2 /var/www/html/vendor/spomky-labs/otphp/src/TOTP.php(81): OTPHP\\TOTP->at()\n#3 /var/www/html/sources/items.queries.php(3581): OTPHP\\TOTP->now()\n#4 {main}\n  thrown in /var/www/html/vendor/spomky-labs/otphp/src/OTP.php on line 130', referer: https://pass.cloudclarity.me/index.php?page=items

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
POST
	https://<OMITTED>/sources/items.queries.php
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred1.02 kB (0 B size)
Referrer Policystrict-origin-when-cross-origin
DNS ResolutionDNS over HTTPS

	
Cache-Control
	no-cache, must-revalidate
Connection
	close
Content-Length
	0
Content-Type
	text/html; charset=utf-8
Date
	Fri, 02 Feb 2024 21:08:43 GMT
Server
	Apache/2.4.56 (Debian)
	
Accept
	*/*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	en-US,en;q=0.5
Connection
	keep-alive
Content-Length
	57
Content-Type
	application/x-www-form-urlencoded; charset=UTF-8
Cookie
	PHPSESSID=e7rfljcve6retbtbki7via5an5; c502b90ce41a57d04ba266d910163f8f7a337af4bb0b03c358=29fed5f79dcd376f7da7c50f75f86d04f025e42d456edd43b5; jstree_select=523
Host
	<OMITTED>
Origin
	https://<OMITTED>
Referer
	https://<OMITTED>/index.php?page=items
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	cors
Sec-Fetch-Site
	same-origin
User-Agent
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0
X-Requested-With
	XMLHttpRequest
```

[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/14145419/tp.config.txt)

**Comment by deanbruhn** [comment]
Ignore, the OTP secret was bad. Can you make it so when you try and save a bad code, it gives you and error.
