### ISSUE TITLE
Error during windows server install

### ISSUE THREAD

**Issue by ivory-mischke** [nilsteampassnet/TeamPass#4058]
### Steps to reproduce
I took a base install of Windows Server 2019 and installed wampserver. then followed these steps to install TeamPass: https://teampass.readthedocs.io/en/latest/install/install-windows/

### Expected behaviour
Install of TeamPass

### Actual behaviour
Error during install

### Server configuration
**Operating system**:
Server 2019
**Web server:**
Apache 2.4.54.2
**Database:**
MySQL 8.0.31
**PHP version:**
PHP 8.1.13
**Teampass version:** 
3.1.0
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
This file does not exist on my system and is one of the errors i get during installation

### Client configuration
**Browser:**
chrome
**Operating system:**
server 2019

#### Web server error log
PHP log file says this:
Stack trace:
#0 C:\wamp64\www\teampass\index.php(59): csrfProtector::init()
#1 {main}
  thrown in C:\wamp64\www\teampass\includes\libraries\csrfp\libs\csrf\csrfprotector.php on line 151
[16-Feb-2024 14:24:19 UTC] PHP Warning:  include_once(C:\wamp64\www\teampass\sources/../includes/config/tp.config.php): Failed to open stream: No such file or directory in C:\wamp64\www\teampass\sources\main.functions.php on line 55
[16-Feb-2024 14:24:19 UTC] PHP Stack trace:
[16-Feb-2024 14:24:19 UTC] PHP   1. {main}() C:\wamp64\www\teampass\install\install.queries.php:0
[16-Feb-2024 14:24:19 UTC] PHP   2. require_once() C:\wamp64\www\teampass\install\install.queries.php:41
[16-Feb-2024 14:24:19 UTC] PHP Warning:  include_once(): Failed opening 'C:\wamp64\www\teampass\sources/../includes/config/tp.config.php' for inclusion (include_path='.;C:\php\pear') in C:\wamp64\www\teampass\sources\main.functions.php on line 55
[16-Feb-2024 14:24:19 UTC] PHP Stack trace:
[16-Feb-2024 14:24:19 UTC] PHP   1. {main}() C:\wamp64\www\teampass\install\install.queries.php:0
[16-Feb-2024 14:24:19 UTC] PHP   2. require_once() C:\wamp64\www\teampass\install\install.queries.php:41
[16-Feb-2024 14:24:19 UTC] PHP Warning:  include(C:\wamp64\www\teampass\vendor\composer/../teampassclasses/superglobal/src/SuperGlobal.php): Failed to open stream: No such file or directory in C:\wamp64\www\teampass\vendor\composer\ClassLoader.php on line 571
[16-Feb-2024 14:24:19 UTC] PHP Stack trace:
[16-Feb-2024 14:24:19 UTC] PHP   1. {main}() C:\wamp64\www\teampass\install\install.queries.php:0
[16-Feb-2024 14:24:19 UTC] PHP   2. Composer\Autoload\ClassLoader->loadClass($class = 'TeampassClasses\\SuperGlobal\\SuperGlobal') C:\wamp64\www\teampass\install\install.queries.php:45
[16-Feb-2024 14:24:19 UTC] PHP   3. Composer\Autoload\includeFile($file = 'C:\\wamp64\\www\\teampass\\vendor\\composer/../teampassclasses/superglobal/src/SuperGlobal.php') C:\wamp64\www\teampass\vendor\composer\ClassLoader.php:428
[16-Feb-2024 14:24:19 UTC] PHP Warning:  include(): Failed opening 'C:\wamp64\www\teampass\vendor\composer/../teampassclasses/superglobal/src/SuperGlobal.php' for inclusion (include_path='C:\wamp64\www\teampass\vendor/phpseclib/phpseclib/phpseclib;.;C:\php\pear') in C:\wamp64\www\teampass\vendor\composer\ClassLoader.php on line 571
[16-Feb-2024 14:24:19 UTC] PHP Stack trace:
[16-Feb-2024 14:24:19 UTC] PHP   1. {main}() C:\wamp64\www\teampass\install\install.queries.php:0
[16-Feb-2024 14:24:19 UTC] PHP   2. Composer\Autoload\ClassLoader->loadClass($class = 'TeampassClasses\\SuperGlobal\\SuperGlobal') C:\wamp64\www\teampass\install\install.queries.php:45
[16-Feb-2024 14:24:19 UTC] PHP   3. Composer\Autoload\includeFile($file = 'C:\\wamp64\\www\\teampass\\vendor\\composer/../teampassclasses/superglobal/src/SuperGlobal.php') C:\wamp64\www\teampass\vendor\composer\ClassLoader.php:428
[16-Feb-2024 14:24:19 UTC] PHP Fatal error:  Uncaught Error: Class "TeampassClasses\SuperGlobal\SuperGlobal" not found in C:\wamp64\www\teampass\install\install.queries.php:45
Stack trace:
#0 {main}
  thrown in C:\wamp64\www\teampass\install\install.queries.php on line 45

#### Log from the web-browser developer console (CTRL + SHIFT + i)
![image](https://github.com/nilsteampassnet/TeamPass/assets/29526406/f07685d1-876d-492b-8c1b-9ec851361689)

Insert the log here and especially the answer of the query that failed.
Uncaught SyntaxError: Unexpected token '<', "<br />
<fo"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16:11709)
    at Object.<anonymous> (install.js:286:22)
    at Object.resolveWith (jquery.min.js:16:15493)
    at Object.done [as complete] (jquery.min.js:16:15379)
    at doGetJson (install.js:279:6)
    at checkPage (install.js:147:17)
    at HTMLInputElement.onclick (install.php:111:119)

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
