### ISSUE TITLE
Unable to create a new folder in fresh install using docker 

### ISSUE THREAD

**Issue by mohanmadavan** [nilsteampassnet/TeamPass#4076]
### Steps to reproduce
1. Git clone latest and run docker-compose up 
2. Install teampass and login
3. Go to folders and create new folder 

### Expected behaviour
New folder will be created

### Actual behaviour
I am getting 500 error "POST /sources/folders.queries.php HTTP/1.1" 500 5 "http://test.test.com/index.php?page=items"

### Server configuration
Alpine Linux v3.18

PHP version: 8.2.7
Memory limit: 128M
Memory usage: 530.93 KB
Maximum time execution: 120
Maximum file size upload: 100M

Server version: 10.11.6-MariaDB
Database size: 0.97MB

**Teampass version:** 
3.1.2.12

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
2024-02-28 14:49:36 172.23.0.1 - - [28/Feb/2024:09:19:36 +0000] "POST /sources/main.queries.php HTTP/1.1" 200 63 "http://mohan.test.com/index.php?page=items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
2024-02-28 14:49:36 172.23.0.1 - - [28/Feb/2024:09:19:36 +0000] "POST /sources/main.queries.php HTTP/1.1" 200 1148 "http://mohan.test.com/index.php?page=items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
2024-02-28 14:49:37 172.23.0.1 - - [28/Feb/2024:09:19:37 +0000] "POST /sources/items.queries.php HTTP/1.1" 200 924 "http://mohan.test.com/index.php?page=items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "NOTICE: PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sources/folders.class.php on line 176"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/sources/folders.queries.php:0"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "NOTICE: PHP message: PHP   2. FolderManager->createNewFolder($params = ['title' => 'test', 'parent_id' => 0, 'complexity' => 0, 'duration' => 0, 'create_auth_without' => 0, 'edit_auth_without' => 0, 'icon' => '', 'icon_selected' => '', 'access_rights' => 'W', 'user_is_admin' => 0, 'user_accessible_folders' => [0 => 0], 'user_is_manager' => 1, 'user_can_create_root_folder' => 1, 'user_can_manage_all_users' => 0, 'user_id' => 10000000, 'user_roles' => '1']) /var/www/html/sources/folders.queries.php:564"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "NOTICE: PHP message: PHP   3. FolderManager->getParentFolderData($parent_id = 0) /var/www/html/sources/folders.class.php:84"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught MeekroDBException: Column 'personal_folder' cannot be null in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php:934"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "Stack trace:"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#0 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper(Array, Array)"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#1 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(549): MeekroDB->query('%l INTO %b %lc ...', 'INSERT', 'teampass_nested...', Array, Array)"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#2 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(554): MeekroDB->insertOrReplace('INSERT', 'teampass_nested...', Array)"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#3 /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->insert('teampass_nested...', Array)"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#4 /var/www/html/sources/folders.class.php(237): DB::__callStatic('insert', Array)"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#5 /var/www/html/sources/folders.class.php(91): FolderManager->createFolder(Array, Array)"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#6 /var/www/html/sources/folders.queries.php(564): FolderManager->createNewFolder(Array)"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "#7 {main}"
2024-02-28 14:49:53 [28-Feb-2024 09:19:53] WARNING: [pool www] child 36 said into stderr: "  thrown in /var/www/html/vendor/sergeytsalkov/meekrodb/db.class.php ..."
2024-02-28 14:49:53 172.23.0.1 - - [28/Feb/2024:09:19:53 +0000] "POST /sources/folders.queries.php HTTP/1.1" 500 5 "http://mohan.test.com/index.php?page=items" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
