### ISSUE TITLE
Folder creating issue

### ISSUE THREAD

**Issue by abhii1997** [nilsteampassnet/TeamPass#4077]
<!--
I'm having some problems creating folders. I deployed Teampass 3.1.2.12, created users, and configured SMTP. However, I can't create folders; during the folder creation process, it continuously displays an "in progress" message.

### Actual behaviour
I'm having some problems creating folders. I deployed Teampass 3.1.2.12, created users, and configured SMTP. However, I can't create folders; during the folder creation process, it continuously displays an "in progress" message.

### Server configuration
**Operating system**: Rocky9

**Web server:**

**Database:*MariaDB*

**PHP version:*8.2.16*

**Teampass version:*3.1.2.12* 

**Teampass configuration file:**

**Comment by abhii1997** [comment]
I'm having some problems creating folders. I deployed Teampass 3.1.2.12, created users, and configured SMTP. However, I can't create folders; during the folder creation process, it continuously displays an "in progress" message.

**Comment by cke-gh-mateusz-galus** [comment]
Same problem, version 3.1.2.12

**Comment by abhii1997** [comment]
@nilsteampassnet ,
Help me solve the issue of folder creation in Teampass 3.1.2.12 on rocky9.3. During the creation process, it shows 'in progress' but does not create. The 'in progress' status continues indefinitely.

**Comment by tigerlinux** [comment]
Same here... OS is Ubuntu 22.04lts - PHP 8.1

**Comment by holzzi** [comment]
Same here Ubuntu 22.04 PHP 8.1 Apache, Maria DB

It seems to be the "nullable" fields in the Database.

**Comment by aives1291** [comment]
Same issue here.
Could track it down to:

```
2024/03/06 20:07:11 [error] 958#958: *1502 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/TeamPass/sources/folders.class.php on line 176PHP message: PHP Fatal error:  Uncaught MeekroDBException: Column 'personal_folder' cannot be null in /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php:934
Stack trace:
#0 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()
#1 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(550): MeekroDB->query()
#2 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(554): MeekroDB->insertOrReplace()
#3 /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->insert()
#4 /var/www/html/TeamPass/sources/folders.class.php(248): DB::__callStatic()
#5 /var/www/html/TeamPass/sources/folders.class.php(91): FolderManager->createFolder()
#6 /var/www/html/TeamPass/sources/folders.queries.php(564): FolderManager->createNewFolder()
#7 {main}
  thrown in /var/www/html/TeamPass/vendor/sergeytsalkov/meekrodb/db.class.php on line 934" while reading response header from upstream, server:
```


Any idea how to fix it or for a temporary workaround?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
