### ISSUE TITLE
"Column 'folder' cannot be null" when importing CSV

### ISSUE THREAD

**Issue by WEBudoGT** [nilsteampassnet/TeamPass#4113]
### Steps to reproduce
1. Prepare CSV file with the following columns: "label","login","password","url","comments" on the first row and respective values on every row (all enclosed by double quotes and separated by comma).
2. Import CSV on Teampass GUI checking both options and using Root folder.

### Expected behaviour
All contacts should be imported

### Actual behaviour
Stucked on "Please wait" on the GUI.
Apache logs report this error:
PHP Fatal error:  Uncaught MeekroDBException: Column 'folder' cannot be null in /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php:934\nStack trace:\n#0 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()\n#1 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(549): MeekroDB->query()\n#2 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(554): MeekroDB->insertOrReplace()\n#3 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->insert()\n#4 /var/www/html/teampass/sources/import.queries.php(414): DB::__callStatic()\n#5 {main}\n  thrown in /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php on line 934, referer: https://oursite.tld/teampass/index.php?page=import

### Server configuration
**Operating system**:
Debian 11

**Web server:**
Apache/2.4.56

**Database:**
Mariadb 10.5.23

**PHP version:**
PHP 8.3.4

**Teampass version:** 
3.1.2

**Teampass configuration file:**
Attached

**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
Chrome

**Operating system:**
MacOS

### Logs
**Web server error log**
```PHP Fatal error:  Uncaught MeekroDBException: Column 'folder' cannot be null in /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php:934\nStack trace:\n#0 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()\n#1 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(549): MeekroDB->query()\n#2 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(554): MeekroDB->insertOrReplace()\n#3 /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->insert()\n#4 /var/www/html/teampass/sources/import.queries.php(414): DB::__callStatic()\n#5 {main}\n  thrown in /var/www/html/teampass/vendor/sergeytsalkov/meekrodb/db.class.php on line 934, referer: https://oursite.tld/teampass/index.php?page=import
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
N/A
```

[teampass.config.php.zip](https://github.com/nilsteampassnet/TeamPass/files/14712036/teampass.config.php.zip)

**Comment by nilsteampassnet** [comment]
@WEBudoGT 
Did you indicate the folder destination?
Can you provide a screen capture?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
