### ISSUE TITLE
LDAP Roles synchronization

### ISSUE THREAD

**Issue by jordi-firewall** [nilsteampassnet/TeamPass#4124]
### Steps to reproduce
1. Click on Roles --> LDAP synchronization

### Expected behaviour

There should appear a list with the AD groups mapped or not with a role.

### Actual behaviour
 
An error message instead of showing the list:
![image](https://github.com/nilsteampassnet/TeamPass/assets/134803571/9451a6a5-2b64-4316-b6b0-78c9c4947523)

### Server configuration
**Operating system**:
Ubuntu 22.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
8.1
**Teampass version:** 
3.1.2.29
**Teampass configuration file:**
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/teampass',
    'cpassman_url' => 'http://192.168.10.21',
    'favicon' => 'http://192.168.10.21/favicon.ico',
    'path_to_upload_folder' => '/var/www/teampass/upload',
    'path_to_files_folder' => '/var/www/teampass/files',
    'url_to_files_folder' => 'http://192.168.10.21/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.1.2',
    'ldap_mode' => '1',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => 'samaccountname',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1709686174',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'qg5gCavNYq3QmrxbSZnxW6w5vhXkFjeLyQHefgdC',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => 'distinguishedname',
    'ldap_dn_additional_user_dn' => 'OU=Users',
    'ldap_user_object_filter' => '(sAMAccountName=*) ',
    'ldap_bdn' => 'OU=neodev,DC=ad,DC=neodev,DC=cat',
    'ldap_hosts' => 'ad.neodev.cat',
    'ldap_password' => 'aS34Rf@#5',
    'ldap_username' => 'ldap',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1712278174',
    'enable_ad_users_with_ad_groups' => '1',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => 'hourly;00:00',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
    'maximum_session_expiration_time' => '60',
    'items_ops_job_frequency' => '1',
    'enable_refresh_task_last_execution' => '1',
    'ldap_group_objectclasses_attibute' => 'top,groupofuniquenames',
    'pwd_default_length' => '14',
    'tasks_log_retention_delay' => '30',
    'oauth2_azure' => '0',
    'oauth2_azure_clientId' => '',
    'oauth2_azure_clientSecret' => '',
    'oauth2_azure_urlAuthorize' => '',
    'oauth2_azure_urlAccessToken' => '',
    'oauth2_azure_urlResourceOwnerDetails' => '',
    'oauth2_azure_scopes' => 'openid,profile,email',
);

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu Desktop 20.04

#### Web server error log
```
Insert your webserver log here
```
[Fri Apr 05 03:11:06.428995 2024] [mpm_prefork:notice] [pid 18449] AH00171: Graceful restart requested, doing restart
[Fri Apr 05 03:11:06.509314 2024] [mpm_prefork:notice] [pid 18449] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Fri Apr 05 03:11:06.509355 2024] [core:notice] [pid 18449] AH00094: Command line: '/usr/sbin/apache2'
[Fri Apr 05 03:13:25.442484 2024] [php:error] [pid 18981] [client 192.168.10.12:46004] PHP Fatal error:  Uncaught MeekroDBException: Table 'teampass.teampass_background_tasks' doesn't exist in /var/www/teampass/vendor/sergeytsalkov/meekrodb/db.class.php:934\nStack trace:\n#0 /var/www/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()\n#1 /var/www/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(550): MeekroDB->query()\n#2 /var/www/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(554): MeekroDB->insertOrReplace()\n#3 /var/www/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->insert()\n#4 /var/www/teampass/sources/users.queries.php(3123): DB::__callStatic()\n#5 {main}\n  thrown in /var/www/teampass/vendor/sergeytsalkov/meekrodb/db.class.php on line 934, referer: http://192.168.10.21/index.php?page=users
[Fri Apr 05 05:42:51.467487 2024] [mpm_prefork:notice] [pid 18449] AH00170: caught SIGWINCH, shutting down gracefully
[Fri Apr 05 05:42:51.596110 2024] [mpm_prefork:notice] [pid 21744] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Fri Apr 05 05:42:51.596159 2024] [core:notice] [pid 21744] AH00094: Command line: '/usr/sbin/apache2'
[Fri Apr 05 06:22:32.372428 2024] [mpm_prefork:notice] [pid 21744] AH00170: caught SIGWINCH, shutting down gracefully
[Fri Apr 05 06:22:32.507082 2024] [mpm_prefork:notice] [pid 22597] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Fri Apr 05 06:22:32.507147 2024] [core:notice] [pid 22597] AH00094: Command line: '/usr/sbin/apache2'

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
![image](https://github.com/nilsteampassnet/TeamPass/assets/134803571/277fdda1-4d44-46bd-85e0-c32925dd76d6)

Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
