### ISSUE TITLE
Uncaught mysqli_sql_exception: Incorrect table definition; there can be only one auto column and it must be defined as a key

### ISSUE THREAD

**Issue by netphantm** [nilsteampassnet/TeamPass#4150]
### Steps to reproduce
1. git pull
2. call https://my.site/install/upgrade.php in browser
3.

### Expected behaviour
upgrade of the db and teampass..

### Actual behaviour
upgrade stopping at:
18:45:52 - upgrade_run_3.0.0.php - Loop #1 is now running ...

### Server configuration
**Operating system**:
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
**Web server:**
nginx
**Database:**
mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

**PHP version:**
PHP 8.2.18 (cli) (built: Apr 11 2024 20:37:16) (NTS)

**Teampass version:** 
don't really know anymore, last update was wayy back. how can I find that out now?

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/15052809/tp.config.php.txt)

### Client configuration
**Browser:**
firefox 124.0.2 (64-bit)
**Operating system:**
on Ubuntu 23.10
#### Web server error log
```
2024/04/21 18:45:37 [error] 34847#34847: *267 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Incorrect table definition; there can be only one auto column and it must be defined as a key in /var/www/tp/install/tp.functions.php:217
Stack trace:
#0 /var/www/tp/install/tp.functions.php(217): mysqli_query()
#1 /var/www/tp/install/upgrade_run_3.0.0.php(1395): addColumnIfNotExist()
#2 {main}
  thrown in /var/www/tp/install/tp.functions.php on line 217" while reading response header from upstream, client: 80.141.22.211, server: tp.my.site, request: "POST /install/upgrade_run_3.0.0.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "tp.my.site"

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
This page is in Almost Standards Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
[upgrade.php](https://tp.my.site/install/upgrade.php)
Object { finish: "0", scriptname: "upgrade_run_3.0.0.php", parameter: "user_id" }
```

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
