### ISSUE TITLE
Search: not all items will be found

### ISSUE THREAD

**Issue by edelmanns** [nilsteampassnet/TeamPass#4158]
### Page on which it happened

Items

### Steps to reproduce
enter an string in the search field.

### Expected behaviour
All items with the search string will be found.
e.g. TeamViewer

### Actual behaviour
Only new Items with the search string will be found.

### Server configuration
**Operating system**: Linux svlap038pi 5.15.0-92-generic #102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64

**Web server:** Apache/2.4.52 (Ubuntu)

**Database:** 11.2.2-MariaDB-log

**PHP version:** 8.1.2-1ubuntu2.14

**Teampass version:** 3.0.10.153

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '0',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '1',
'number_of_used_pw' => '0',
'manager_edit' => '1',
'cpassman_dir' => '/var/www/html/teampass',
'cpassman_url' => 'https://<anonym_url>/
'favicon' => 'https://<anonym_url>//favicon.ico',
'path_to_upload_folder' => '/var/www/html/teampass/upload',
'url_to_upload_folder' => 'https://<anonym_url>//upload',
'path_to_files_folder' => '/var/www/html/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>//files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '1',
'ldap_type' => 'ActiveDirectory',
'ldap_suffix' => '@my.COM',
'ldap_domain_dn' => 'DC=DE,DC=my,DC=COM',
'ldap_domain_controler' => 'server1,server2',
'ldap_user_attribute' => 'userprincipalname',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_search_base' => '0',
'ldap_port' => '389',
'richtext' => '0',
'allow_print' => '1',
'roles_allowed_to_print' => '["21"]',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '5',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => 'https://<anonym_url>/CENIT_Logo_2022.png',
'custom_login_text' => 'Use company e-mail:',
'default_language' => 'english',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
'send_stats_time' => '1529316305',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '1',
'personal_saltkey_cookie_duration' => '120',
'email_smtp_server' => '<removed>'
'email_smtp_auth' => '',
'email_auth_username' => '<removed>'
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => '',
'email_from' => '<removed>'
'email_from' => '<removed>'
'pwd_maximum_length' => '40',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '<removed>'
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx,ppk',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '0',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass 3 for CENIT AG',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '360',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/var/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => '<removed>'
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Berlin',
'enable_attachment_encryption' => '1',
'personal_saltkey_security_level' => '50',
'ldap_new_user_is_administrated_by' => '0',
'disable_show_forgot_pwd_link' => '1',
'offline_key_level' => '48',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '1',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '1',
'ldap_new_user_role' => '7',
'copy_to_clipboard_small_icons' => '1',
'item_creation_templates' => '0',
'settings_offline_mode' => '1',
'can_create_root_folder' => '0',
'max_last_items' => '7',
'teampass_version' => '3.0.10',
'enable_massive_move_delete' => '1',
'admin_2fa_required' => '0',
'password_overview_delay' => '4',
'roles_allowed_to_print_select' => '[41]',
'clipboard_life_duration' => '30',
'mfa_for_roles' => '',
'tree_counters' => '1',
'settings_tree_counters' => '0',
'email_debug_level' => '0',
'ga_reset_by_user' => '',
'onthefly-backup-key' => '<removed>'
'onthefly-restore-key' => '<removed>'
'ldap_user_dn_attribute' => 'distinguishedname',
'ldap_dn_additional_user_dn' => '',
'ldap_user_object_filter' => '(objectCategory=Person)(userPrincipalName=*)',
'ldap_bdn' => 'ou=my,dc=DE,dc=my,dc=COM',
'ldap_hosts' => '<removed>'
'ldap_password' => '<removed>'
'ldap_username' => 'cn=binduser,ou=my,ou=ServiceAccounts,ou=ADM Users,dc=de,dc=my,dc=com',
'api_token_duration' => '60',
'enable_tasks_manager' => '1',
'task_maximum_run_time' => '300',
'maximum_number_of_items_to_treat' => '300',
'tasks_manager_refreshing_period' => '100',
'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
'enable_tasks_log' => '0',
'enable_ad_users_with_ad_groups' => '0',
'enable_ad_user_auto_creation' => '0',
'ldap_group_object_filter' => '',
'ldap_guid_attibute' => 'objectguid',
'sending_emails_job_frequency' => '2',
'user_keys_job_frequency' => '1',
'items_statistics_job_frequency' => '5',
'reload_cache_table_task' => '',
'rebuild_config_file' => '',
'purge_temporary_files_task' => '',
'clean_orphan_objects_task' => '',
'users_personal_folder_task' => '',
'maximum_session_expiration_time' => '360',
'items_ops_job_frequency' => '1',
'upgrade_timestamp' => '1709021954',
'duo_ikey' => '<removed>'

```

**Updated from an older Teampass or fresh install:**

Update from 2 to 3

### Client configuration

**Browser:**  Chrome

**Operating system:**  Windows 10 64 bits

#### Web server error log
```
Constant FILTER_SANITIZE_STRING is deprecated - /var/www/html/teampass/vendor/elegantweb/sanitizer/src/Filters/EscapeHTML.php (18)
```

#### Teampass 10 last system errors
```
 * 11/07/2023 20:03:59 - Query: INSERT INTO `teampass_log_system` (`type`,`date`,`label`,`qui`,`field_1`) VALUES ('user_mngt', 1689098639, NULL, '10000034', '10000104')<br />Error: Column 'label' cannot be null<br />@ /teampass/sources/users.queries.php * 23/05/2022 10:43:30 - Query: UPDATE `teampass_users` SET `login`='amara', `name`='Rajalakshmi', `lastname`='Amara', `email`='r.amara@cenit.com', `disabled`=0, `isAdministratedByRole`='28', `groupes_interdits`='0', `groupes_visibles`='45;538;540;1192;1140;542;926;558;965;1067;1068;1176;1085;1104;1254;1190;1240;1086;1105;1106;559;367;46;34;48;170;172;797;171;1092;1093;1094;1097;568;569;798;572;521;525;799;524;573;574;800;577;284;288;876;285;175;177;801;176;465;466;802;469;578;579;803;582;583;584;804;587;460;464;805;463;588;589;806;592;593;594;811;597;180;182;893;181;368;359;369;357;527;355;362;363;354;360;796;496;497;807;500;598;599;808;602;1059;1060;1061;1064;149;153;809;150;603;604;810;607;1241;1242;1247;1249;1248;1243;1246;120;124;812;123;781;782;813;785;346;347;351;352;814;348;407;409;815;411;608;609;818;612;265;269;865;266;412;413;816;416;501;502;817;505;475;476;819;479;480;481;820;484;49;613;614;821;617;618;619;822;622;190;192;825;191;1053;1054;1055;1058;195;197;823;196;623;624;824;627;200;202;826;201;1258;1259;1260;1263;205;207;827;206;628;629;828;632;633;634;830;637;211;213;829;212;417;418;831;421;638;639;1236;1237;1238;970;972;971;973;832;642;221;223;833;222;493;125;129;834;127;643;644;835;647;216;218;841', `fonction_id`='28' WHERE id = 10000155<br />Error: Duplicate entry 'amara' for key 'login'<br />@ /teampass/sources/users.queries.php * 23/05/2022 10:42:40 - Query: UPDATE `teampass_users` SET `login`='amara', `name`='Rajalakshmi', `lastname`='Amara', `email`='r.amara@cenit.com', `disabled`=0, `isAdministratedByRole`='28', `groupes_interdits`='0', `groupes_visibles`='45;538;540;1192;1140;542;926;558;965;1067;1068;1176;1085;1104;1254;1190;1240;1086;1105;1106;559;367;46;34;48;170;172;797;171;1092;1093;1094;1097;568;569;798;572;521;525;799;524;573;574;800;577;284;288;876;285;175;177;801;176;465;466;802;469;578;579;803;582;583;584;804;587;460;464;805;463;588;589;806;592;593;594;811;597;180;182;893;181;368;359;369;357;527;355;362;363;354;360;796;496;497;807;500;598;599;808;602;1059;1060;1061;1064;149;153;809;150;603;604;810;607;1241;1242;1247;1249;1248;1243;1246;120;124;812;123;781;782;813;785;346;347;351;352;814;348;407;409;815;411;608;609;818;612;265;269;865;266;412;413;816;416;501;502;817;505;475;476;819;479;480;481;820;484;49;613;614;821;617;618;619;822;622;190;192;825;191;1053;1054;1055;1058;195;197;823;196;623;624;824;627;200;202;826;201;1258;1259;1260;1263;205;207;827;206;628;629;828;632;633;634;830;637;211;213;829;212;417;418;831;421;638;639;1236;1237;1238;970;972;971;973;832;642;221;223;833;222;493;125;129;834;127;643;644;835;647;216;218;841', `fonction_id`='28' WHERE id = 10000155<br />Error: Duplicate entry 'amara' for key 'login'<br />@ /teampass/sources/users.queries.php * 08/06/2021 12:22:42 - Query: INSERT INTO `teampass_log_system` (`type`,`date`,`label`,`qui`,`field_1`) VALUES ('user_mngt', 1623147762, NULL, '10000034', '10000125')<br />Error: Column 'label' cannot be null<br />@ /teampass/sources/users.queries.php * 08/06/2021 12:11:22 - Query: INSERT INTO `teampass_log_system` (`type`,`date`,`label`,`qui`,`field_1`) VALUES ('user_mngt', 1623147082, NULL, '10000034', '10000125')<br />Error: Column 'label' cannot be null<br />@ /teampass/sources/users.queries.php
```

**Comment by s1mm0n** [comment]
We've had the same issue:

Please check if your cache table is in UTF8 format, if not:

ALTER TABLE teampass.teampass_cache CONVERT TO CHARACTER SET utf8

after this run
/var/www/teampass/scripts# php task_maintenance_reload_cache_table.php

**Comment by edelmanns** [comment]
Hello,

thanks for fast answer.

the table was created as follows:
CREATE TABLE `teampass_cache_tree` (
  `increment_id` smallint(32) NOT NULL AUTO_INCREMENT,
  `data` longtext DEFAULT NULL,
  `visible_folders` longtext NOT NULL,
  `timestamp` varchar(50) NOT NULL,
  `user_id` int(12) NOT NULL,
  `folders` longtext DEFAULT NULL,
  PRIMARY KEY (`increment_id`),
  KEY `CACHE` (`increment_id`,`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=249 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci

should be OK.

The command is shown an error:

root@server1:/var/www/html/teampass/scripts# php task_maintenance_reload_cache_table.php
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/teampass/sources/main.functions.php:858
Stack trace:
#0 /var/www/html/teampass/sources/main.functions.php(787): cacheTableRefresh()
#1 /var/www/html/teampass/scripts/task_maintenance_reload_cache_table.php(82): updateCacheTable()
#2 /var/www/html/teampass/scripts/task_maintenance_reload_cache_table.php(66): reloadCacheTable()
#3 {main}
  thrown in /var/www/html/teampass/sources/main.functions.php on line 858

main.functions.php is line 858:
 if (count($user) > 0) {
What is my misstage?

**Comment by s1mm0n** [comment]
As this function has changed in the latest Teampass Update 3.1.2 you may consider to update to the latest version.

**Comment by killmenowkid** [comment]
I am having the same issue with not all items displaying on a search. I can find the items by manually parsing the list, but cant search for them. For example there are multiple server that start with the same 4 letter sequence. When I search that sequence only about half are displayed. This behavior was exhibited on 3.0.10.50 and continues after upgrading to 3.1.1. My database is on utm8mb3_general_ci 

@edelmanns For LDAP issue resolutions see issues #4080 and #4131. I was also on the 3.0.10 line and had LDAP issues after upgrading to fix other bugs

**Comment by edelmanns** [comment]
Hello,

now we using the version 3.1.1.74.
The script  php task_maintenance_reload_cache_table.php is running.
I think this issue is solved.
