### ISSUE TITLE
Table 'teampass.teampass_background_tasks' doesn't exist

### ISSUE THREAD

**Issue by xavier8854** [nilsteampassnet/TeamPass#4159]
### Steps to reproduce
1. Navigate as admin to Settings->Tasks
2. See alert "DataTables warning: table id=table-tasks_in_progress - Ajax error. For more information about this error, please see http://datatables.net/tn/7"
3. see logfile (below)

### Expected behaviour
Navigate to Settings->Tasks

### Actual behaviour
Alert "DataTables warning: table id=table-tasks_in_progress - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

### Server configuration
**Operating system**:
RHEL9
**Web server:**
Apache 2.4
**Database:**
MariaDB 10.11
**PHP version:**
8.1
**Teampass version:** 
master from GitHub
**Teampass configuration file:**
```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://*****/teampass',
    'favicon' => 'https://*****/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://*****/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.1.2',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'french',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1711442898',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'localhost',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => 'teampass@ac-nancy-metz.fr',
    'email_from_name' => 'Teampass Administrator',
    'pwd_maximum_length' => '80',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '1',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/Paris',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => '*****',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '1',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '1',
    'upgrade_timestamp' => '1714034898',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_group_object_filter' => '',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => '',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
    'maximum_session_expiration_time' => '60',
    'items_ops_job_frequency' => '1',
    'enable_refresh_task_last_execution' => '1',
    'ldap_group_objectclasses_attibute' => 'top,groupofuniquenames',
    'pwd_default_length' => '14',
    'tasks_log_retention_delay' => '30',
    'oauth2_enabled' => '0',
    'oauth2_client_id' => '',
    'oauth2_client_secret' => '',
    'oauth2_client_endpoint' => '',
    'oauth2_client_token' => '',
    'oauth2_client_scopes' => 'openid,profile,email',
    'oauth2_client_appname' => 'Login with Azure',
);
```
**Updated from an older Teampass or fresh install:**
Fresh install

### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu 23.10
#### Web server error log
```
[25-Apr-2024 11:07:35 Europe/Paris] PHP Fatal error:  Uncaught MeekroDBException: Table 'teampass.teampass_background_tasks' doesn't exist in /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php:934
Stack trace:
#0 /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php(895): MeekroDB->queryHelper()
#1 /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php(1011): MeekroDB->queryAllLists()
#2 /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php(1032): MeekroDB->queryFirstList()
#3 /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->queryFirstField()
#4 /var/www/html/teampass.git/sources/logs.datatables.php(884): DB::__callStatic()
#5 {main}
  thrown in /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php on line 934
[25-Apr-2024 11:07:35 Europe/Paris] PHP Fatal error:  Uncaught MeekroDBException: Table 'teampass.teampass_background_tasks' doesn't exist in /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php:934
Stack trace:
#0 /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()
#1 /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->query()
#2 /var/www/html/teampass.git/sources/tasks.queries.php(166): DB::__callStatic()
#3 /var/www/html/teampass.git/sources/tasks.queries.php(134): loadLastTasksExec()
#4 {main}
  thrown in /var/www/html/teampass.git/vendor/sergeytsalkov/meekrodb/db.class.php on line 934
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
<span class="message-body-wrapper"><div class="url-preview"><div class="properties-view"><div class="tree-container">
GET |  
-- | --
scheme | https
host | *****
filename | /teampass/sources/logs.datatables.php
 
action | tasks_in_progress
draw | 5
columns[0][data] | 0
columns[0][name] |  
columns[0][searchable] | true
columns[0][orderable] | true
columns[0][search][value] |  
columns[0][search][regex] | false
columns[1][data] | 1
columns[1][name] |  
columns[1][searchable] | true
columns[1][orderable] | true
columns[1][search][value] |  
columns[1][search][regex] | false
columns[2][data] | 2
columns[2][name] |  
columns[2][searchable] | true
columns[2][orderable] | true
columns[2][search][value] |  
columns[2][search][regex] | false
columns[3][data] | 3
columns[3][name] |  
columns[3][searchable] | true
columns[3][orderable] | true
columns[3][search][value] |  
columns[3][search][regex] | false
columns[4][data] | 4
columns[4][name] |  
columns[4][searchable] | true
columns[4][orderable] | true
columns[4][search][value] |  
columns[4][search][regex] | false
order[0][column] | 1
order[0][dir] | asc
start | 0
length | 10
search[value] |  
search[regex] | false
_ | 1714035994478
 
Address | *****:443

</span><div class="webconsole-input-buttons"></div><div class="jsterm-input-container devtools-input" aria-live="off" tabindex="-1"><div class="CodeMirror cm-s-mozilla CodeMirror-wrap" style="--caret-blink-time: 530ms;"><div style="overflow: hidden; position: relative; width: 3px; height: 0px; top: 3px; left: 32px;"><textarea style="position: absolute; bottom: -1em; padding: 0px; width: 1px; height: 1em; outline: none;" wrap="off" autocorrect="off" autocapitalize="none" spellcheck="false" tabindex="0"></textarea></div><div class="CodeMirror-scroll" tabindex="-1" draggable="true"><div class="CodeMirror-sizer" style="margin-left: 0px; margin-bottom: 0px; border-right-width: 50px; min-height: 20px; padding-right: 0px; padding-bottom: 0px;"><div style="position: relative; top: 0px;"><div class="CodeMirror-lines" role="presentation"><div style="position: relative; outline: none;" role="presentation"><div class="CodeMirror-measure"><pre class="CodeMirror-line-like"><span></span></pre></div><div class="CodeMirror-measure"></div><div style="position: relative; z-index: 1;"></div><div class="CodeMirror-cursors"><div class="CodeMirror-cursor" style="left: 4px; top: 0px; height: 14px;"></div></div><div class="CodeMirror-code" role="presentation"><pre class=" CodeMirror-line " role="presentation"><span role="presentation"><span cm-text="">​</span></span></pre></div></div></div></div></div><div style="position: absolute; height: 50px; width: 1px; border-bottom: 0px solid transparent; top: 20px;"></div></div></div></div><div class="eager-evaluation-result"></div>
```

**Comment by xavier8854** [comment]
Confirmed in the database :
```
MariaDB [teampass]> show tables;
+--------------------------------+
| Tables_in_teampass             |
+--------------------------------+
| teampass_api                   |
| teampass_automatic_del         |
| teampass_cache                 |
| teampass_cache_tree            |
| teampass_categories            |
| teampass_categories_folders    |
| teampass_categories_items      |
| teampass_defuse_passwords      |
| teampass_emails                |
| teampass_export                |
| teampass_files                 |
| teampass_items                 |
| teampass_items_change          |
| teampass_items_edition         |
| teampass_items_otp             |
| teampass_kb                    |
| teampass_kb_categories         |
| teampass_kb_items              |
| teampass_languages             |
| teampass_ldap_groups_roles     |
| teampass_log_items             |
| teampass_log_system            |
| teampass_misc                  |
| teampass_nested_tree           |
| teampass_notification          |
| teampass_otv                   |
| teampass_restriction_to_roles  |
| teampass_rights                |
| teampass_roles_title           |
| teampass_roles_values          |
| teampass_sharekeys_fields      |
| teampass_sharekeys_files       |
| teampass_sharekeys_items       |
| teampass_sharekeys_logs        |
| teampass_sharekeys_suggestions |
| teampass_suggestion            |
| teampass_tags                  |
| teampass_templates             |
| teampass_tokens                |
| teampass_users                 |
+--------------------------------+
40 rows in set (0.000 sec)
```

**Comment by execcr** [comment]
Same problem here on latest commit [f851d99](https://github.com/nilsteampassnet/TeamPass/commit/f851d99b522d71434648d5ba0361b3305c49d7c4)

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
