### ISSUE TITLE
First  Time User - "In Progress" - No QR Code Generated

### ISSUE THREAD

**Issue by riharvey414** [nilsteampassnet/TeamPass#4169]
### Steps to reproduce
1. Create new user
2. Generate MFA code from Admin Console
3. Login w/ username, password, and one-time Google Auth code

### Expected behaviour
New User - First time login w/ MFA
Generate Google Auth Code

### Actual behaviour
Page just spins on "Loading"
![image](https://github.com/nilsteampassnet/TeamPass/assets/168458887/496168ba-72b5-4bad-9f12-589216835946)

### Server configuration
**Operating system**:
Red Hat Enterprise Linux 9.3 (Plow

**Web server:**
Apache/2.4.57 (Red Hat Enterprise Linux)

**Database:**
Ver 8.0.36 for Linux on x86_64 (Source distribution)

**PHP version:**
PHP 8.3.6 (cli) (built: Apr 10 2024 14:21:20) (NTS gcc x86_64)

**Teampass version:** 
![image](https://github.com/nilsteampassnet/TeamPass/assets/168458887/b7c70ce2-4028-457d-8407-34fe2912d028)

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome 

**Operating system:**
Version 124.0.6367.92 (Official Build) (64-bit)

#### Web server error log
```
Insert your webserver log here
```

[30-Apr-2024 09:33:29 America/New_York] PHP Fatal error:  Uncaught TypeError: RobThree\Auth\Providers\Qr\QRServerProvider::getQRCodeImage(): Return value must be of type string, false returned in /var/www/html/
teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php:36
Stack trace:
#0 /var/www/html/teampass/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(120): RobThree\Auth\Providers\Qr\QRServerProvider->getQRCodeImage()
#1 /var/www/html/teampass/sources/identify.php(1659): RobThree\Auth\TwoFactorAuth->getQRCodeImageAsDataUri()
#2 /var/www/html/teampass/sources/identify.php(2377): googleMFACheck()
#3 /var/www/html/teampass/sources/identify.php(355): identifyDoMFAChecks()
#4 /var/www/html/teampass/sources/identify.php(130): identifyUser()
#5 {main}
  thrown in /var/www/html/teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php on line 36

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
![image](https://github.com/nilsteampassnet/TeamPass/assets/168458887/4605225b-6d26-4416-b8df-1d3f1c6e8a4c)
![image](https://github.com/nilsteampassnet/TeamPass/assets/168458887/4969c0fe-0b0d-45ba-bdc8-3bf11fa96e41)

```

**Comment by nilsteampassnet** [comment]
@riharvey414 
I cannot reproduce.
Can you please perform the next query and provide me the output?
`SELECT `ga`,`ga_temporary_code` FROM `teampass_users` WHERE login='tester';`
Thank you

**Comment by riharvey414** [comment]
![image](https://github.com/nilsteampassnet/TeamPass/assets/168458887/7ffbf57b-75fe-4697-ab66-0fd2d2586b5c)

@nilsteampassnet This machine is on a VLAN that doesn't have internet access. Would that have anything to do with it? I did add proxy settings in the options, but that didn't seem to fix.

![image](https://github.com/nilsteampassnet/TeamPass/assets/168458887/8279cfd5-ea68-4112-812d-0de6ee322545)

**Comment by nilsteampassnet** [comment]
> This machine is on a VLAN that doesn't have internet access
THis is the reason.
After code review, the QR code is generated using Google, so it requires an internet access.
THis proxy parameters don't work in many cases.
I should remove them.
Prefer to set up your proxy at server level

**Comment by riharvey414** [comment]
Ok, thanks for the quick response! I'll do that and report back.

**Comment by Kyogre** [comment]
Can somebody tell url (domain) which needs to be accessed?
We also have VM that has restricted internet access, so we need to manually open access to needed web-resources.

**Comment by rokx** [comment]
I found this in the readme file of robthree/twofactorauth

> Warning:
> By default, this package uses the lib/Providers/QRServerProvider.php as QR code generator. This provider is not suggested for applications where absolute security is needed, because it uses an external service for the QR code generation.
> 
> You can make use of the included [Endroid](https://robthree.github.io/TwoFactorAuth/qr-codes/endroid.html) or [Bacon](https://robthree.github.io/TwoFactorAuth/qr-codes/bacon.html) providers which generate locally.

I think internet connectivity should not be needed for QR code generation.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
