### ISSUE TITLE
Unable to save settings - no save button on page

### ISSUE THREAD

**Issue by jpgrazi** [nilsteampassnet/TeamPass#4186]
### Steps to reproduce
1.
2.
3.

### Expected behavior
When any setting is changed, it should be written to tp.config.php after pushing the save button on page and affectively applied. 

### Actual behavior
When settings are changed (take off from maintenance for example) the setting seems to be changed but there is no save button on the page, and when the page is left and reloaded (assuming a autosave function on page closure),  the setting is still as before... unchanged.  If the tp.config.php file is reviewed, the setting haven't been changed there either. If the setting is changed manually on the file, the setting is effectively applied. 

### Server configuration
SLES 15 sp5

**Web server:**
apache2 2.4

**Database:**
mariaDB 10.11

**PHP version:**
php 8.3

**Teampass version:** 
teampass 3.1.2

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
Migrated to SLES 15 sp5 on its original version 2.1.27 (version 2.1.27 worked fine on SLES 15 with php5.6, ,mariaDB 10.6 and apache 2 2.4), and then updated from version 2.1.27 to 3.1.1.
The update process didn't finish but it updated the Database, So I did a fresh install (ver 3.1.1) and uploaded a DB dump from updated database.
 
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/srv/www/htdocs/teampass',
    'cpassman_url' => 'https://emantpsappd01.ea.holcim.net/teampass',
    'favicon' => 'https://emantpsappd01.ea.holcim.net/teampass/favicon.ico',
    'path_to_upload_folder' => '/srv/www/htdocs/teampass/upload',
    'path_to_files_folder' => '/srv/www/htdocs/teampass/files',
    'url_to_files_folder' => 'https://emantpsappd01.ea.holcim.net/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.1.2',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1712671770',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'bck_script_path' => '/srv/www/htdocs/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'tvzfNmxtMbvkwfCmzbsSWRmMe8F9ZLs5KkqtXM2N',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1715263770',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => '',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
    'maximum_session_expiration_time' => '60',
    'items_ops_job_frequency' => '1',
    'enable_refresh_task_last_execution' => '1',
    'ldap_group_objectclasses_attibute' => 'top,groupofuniquenames',
    'pwd_default_length' => '14',
    'tasks_log_retention_delay' => '30',
    'oauth2_enabled' => '0',
    'oauth2_client_id' => '',
    'oauth2_client_secret' => '',
    'oauth2_client_endpoint' => '',
    'oauth2_client_token' => '',
    'oauth2_client_scopes' => 'openid,profile,email',
    'oauth2_client_appname' => 'Login with Azure',
);

### Client configuration
**Browser:**
firefox 126.0 64 bits
chrome 124.0.6367.203 (Build oficial) (64 bits)
firefox 114.0.2 (64-bit) to take web browser logs

**Operating system:**
Windows 11

#### Web server error log
[Logs.zip](https://github.com/nilsteampassnet/TeamPass/files/15324045/Logs.zip)
Insert your webserver log here
[Logs.zip](https://github.com/nilsteampassnet/TeamPass/files/15324045/Logs.zip)

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
Object { error: false, message: "", tables: '{"0":"teampass_api","1":"teampass_automatic_del","2":"teampass_background_subtasks","3":"teampass_background_tasks","4":"teampass_background_tasks_logs","5":"teampass_cache","6":"teampass_cache_tree","7":"teampass_categories","8":"teampass_categories_folders","9":"teampass_categories_items","10":"teampass_defuse_passwords","11":"teampass_emails","12":"teampass_export","13":"teampass_files","14":"teampass_items","15":"teampass_items_change","16":"teampass_items_edition","17":"teampass_items_otp","18":"teampass_kb","19":"teampass_kb_categories","20":"teampass_kb_items","21":"teampass_languages","22":"teampass_ldap_groups_roles","23":"teampass_log_items","24":"teampass_log_system","25":"teampass_misc","26":"teampass_nested_tree","27":"teampass_notification","28":"teampass_otv","29":"teampass_restriction_to_roles","30":"teampass_rights","31":"teampass_roles_title","32":"teampass_roles_values","33":"teampass_sharekeys_fields","34":"teampass_sharekeys_files","35":"teampass_sharekeys_items","36":"teampass_sharekeys_logs","37":"teampass_sharekeys_suggestions","38":"teampass_suggestion","39":"teampass_tags","40":"teampass_templates","41":"teampass_tokens","42":"teampass_users"}' }
​
error: false
​
message: ""
​
tables: '{"0":"teampass_api","1":"teampass_automatic_del","2":"teampass_background_subtasks","3":"teampass_background_tasks","4":"teampass_background_tasks_logs","5":"teampass_cache","6":"teampass_cache_tree","7":"teampass_categories","8":"teampass_categories_folders","9":"teampass_categories_items","10":"teampass_defuse_passwords","11":"teampass_emails","12":"teampass_export","13":"teampass_files","14":"teampass_items","15":"teampass_items_change","16":"teampass_items_edition","17":"teampass_items_otp","18":"teampass_kb","19":"teampass_kb_categories","20":"teampass_kb_items","21":"teampass_languages","22":"teampass_ldap_groups_roles","23":"teampass_log_items","24":"teampass_log_system","25":"teampass_misc","26":"teampass_nested_tree","27":"teampass_notification","28":"teampass_otv","29":"teampass_restriction_to_roles","30":"teampass_rights","31":"teampass_roles_title","32":"teampass_roles_values","33":"teampass_sharekeys_fields","34":"teampass_sharekeys_files","35":"teampass_sharekeys_items","36":"teampass_sharekeys_logs","37":"teampass_sharekeys_suggestions","38":"teampass_suggestion","39":"teampass_tags","40":"teampass_templates","41":"teampass_tokens","42":"teampass_users"}'

**Comment by jpgrazi** [comment]
teampass is version 3.1.2   there  are some mentions for version 3.1.1 in my post, but it is actually version 3.1.2

**Comment by jpgrazi** [comment]
the rest of the requested info.. sorry but something happened when I pasted it before>
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/srv/www/htdocs/teampass',
    'cpassman_url' => 'https://emantpsappd01.ea.holcim.net/teampass',
    'favicon' => 'https://emantpsappd01.ea.holcim.net/teampass/favicon.ico',
    'path_to_upload_folder' => '/srv/www/htdocs/teampass/upload',
    'path_to_files_folder' => '/srv/www/htdocs/teampass/files',
    'url_to_files_folder' => 'https://emantpsappd01.ea.holcim.net/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'teampass_version' => '3.1.2',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1712671770',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'bck_script_path' => '/srv/www/htdocs/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'tvzfNmxtMbvkwfCmzbsSWRmMe8F9ZLs5KkqtXM2N',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'duo_failmode' => 'secure',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
    'tree_counters' => '0',
    'settings_offline_mode' => '0',
    'settings_tree_counters' => '0',
    'enable_massive_move_delete' => '0',
    'email_debug_level' => '0',
    'ga_reset_by_user' => '',
    'onthefly-backup-key' => '',
    'onthefly-restore-key' => '',
    'ldap_user_dn_attribute' => '',
    'ldap_dn_additional_user_dn' => '',
    'ldap_user_object_filter' => '',
    'ldap_bdn' => '',
    'ldap_hosts' => '',
    'ldap_password' => '',
    'ldap_username' => '',
    'api_token_duration' => '60',
    'last_folder_change' => '',
    'enable_tasks_manager' => '1',
    'task_maximum_run_time' => '300',
    'tasks_manager_refreshing_period' => '20',
    'maximum_number_of_items_to_treat' => '100',
    'ldap_tls_certifacte_check' => 'LDAP_OPT_X_TLS_NEVER',
    'enable_tasks_log' => '0',
    'upgrade_timestamp' => '1715263770',
    'enable_ad_users_with_ad_groups' => '0',
    'enable_ad_user_auto_creation' => '0',
    'ldap_guid_attibute' => 'objectguid',
    'sending_emails_job_frequency' => '2',
    'user_keys_job_frequency' => '1',
    'items_statistics_job_frequency' => '5',
    'users_personal_folder_task' => '',
    'clean_orphan_objects_task' => '',
    'purge_temporary_files_task' => '',
    'rebuild_config_file' => '',
    'reload_cache_table_task' => '',
    'maximum_session_expiration_time' => '60',
    'items_ops_job_frequency' => '1',
    'enable_refresh_task_last_execution' => '1',
    'ldap_group_objectclasses_attibute' => 'top,groupofuniquenames',
    'pwd_default_length' => '14',
    'tasks_log_retention_delay' => '30',
    'oauth2_enabled' => '0',
    'oauth2_client_id' => '',
    'oauth2_client_secret' => '',
    'oauth2_client_endpoint' => '',
    'oauth2_client_token' => '',
    'oauth2_client_scopes' => 'openid,profile,email',
    'oauth2_client_appname' => 'Login with Azure',
);


### Client configuration
**Browser:**
firefox 126.0 64 bits
chrome 124.0.6367.203 (Build oficial) (64 bits)

**Operating system:**
Windows 11

**Comment by nilsteampassnet** [comment]
@jpgrazi 
Do you have any error in your apache error log file?

**Comment by jpgrazi** [comment]
Hello Nils. Thks for your answer.. I've attched the apache error log to this case... but seems is not be here..and yes.. I have a lot of errors there. 
[error_log.zip](https://github.com/nilsteampassnet/TeamPass/files/15378324/error_log.zip)

the last two when I try to change settings:
 
[Mon May 20 16:23:34.506746 2024] [php:error] [pid 6841] [client 10.61.33.204:51172] PHP Fatal error:  Uncaught MeekroDBException: Unknown column 'updated_at' in 'field list' in /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php:934\nStack trace:\n#0 /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()\n#1 /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(490): MeekroDB->query()\n#2 /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->update()\n#3 /srv/www/htdocs/teampass/sources/admin.queries.php(2168): DB::__callStatic()\n#4 {main}\n  thrown in /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php on line 934, referer: https://emantpsappd01.ea.holcim.net/teampass/index.php?page=options
[Mon May 20 16:23:47.004004 2024] [php:error] [pid 10370] [client 10.61.33.204:51171] PHP Fatal error:  Uncaught MeekroDBException: Unknown column 'created_at' in 'field list' in /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php:934\nStack trace:\n#0 /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(890): MeekroDB->queryHelper()\n#1 /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(549): MeekroDB->query()\n#2 /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(554): MeekroDB->insertOrReplace()\n#3 /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->insert()\n#4 /srv/www/htdocs/teampass/sources/admin.queries.php(2146): DB::__callStatic()\n#5 {main}\n  thrown in /srv/www/htdocs/teampass/vendor/sergeytsalkov/meekrodb/db.class.php on line 934, referer: https://emantpsappd01.ea.holcim.net/teampass/index.php?page=2fa

Thanks in advance for you help.

**Comment by jpgrazi** [comment]
From the errors in my previous comment, seems to be related to database tables not well formed. As a comment I should say that I have updated from version 2.1.27 but the update never finished..  it never showed the final step when the link to open the new site is populated.  So I took a mysqldump, then I removed the php code, the DB and did a fresh install. After that I recover the dump that I obtained from the updated database.  I didn't get any.. errors, maybe the update process for the database was wrong.

**Comment by jpgrazi** [comment]
Hello. Any comments on my last info? I really appreciate your comments or directions on watt to do.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
