### ISSUE TITLE
Scheduler not working error with CronExpression.php

### ISSUE THREAD

**Issue by kgoyat** [nilsteampassnet/TeamPass#4202]
### Steps to reproduce
N/A

### Expected behaviour
Scheduler processing tasks

### Actual behaviour
Scheduler not processing task

### Server configuration
Debian 12.5

PHP 8.2.7

**Database:**

10.11.6-MariaDB-0+deb12u1 Debian 12

Teampass version: 3.1.2.45

/var/www/html/teampass/scripts# /usr/bin/php /var/www/html/teampass/sources/scheduler.php
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid CRON field value */0 at position 0 in /var/www/html/teampass/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php:241
Stack trace:
#0 /var/www/html/teampass/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php(222): Cron\CronExpression->setPart()
#1 /var/www/html/teampass/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php(188): Cron\CronExpression->setExpression()
#2 /var/www/html/teampass/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php(154): Cron\CronExpression->__construct()
#3 /var/www/html/teampass/vendor/peppeocchi/php-cron-scheduler/src/GO/Traits/Interval.php(17): Cron\CronExpression::factory()
#4 /var/www/html/teampass/vendor/peppeocchi/php-cron-scheduler/src/GO/Traits/Interval.php(54): GO\Job->at()
#5 /var/www/html/teampass/sources/scheduler.php(47): GO\Job->everyMinute()
#6 {main}
  thrown in /var/www/html/teampass/vendor/dragonmantank/cron-expression/src/Cron/CronExpression.php on line 241

**Comment by dumitru2002** [comment]
The issue happened because the cron timer was set to '0' in the 'tasks -> settings menu' 
Change it to '1' and it will work like a charm

For some reason it worked perfectly find on  my docker installation, but not so good on my VM rocky 9.5
