### ISSUE TITLE
Error in isEnable() function of ActiveDirectoryExtra class

### ISSUE THREAD

**Issue by gonzalodeniz** [nilsteampassnet/TeamPass#4300]
### Steps to reproduce
1. Configure LDAP
2. Test current configuration > Perform

### Expected behaviour
Successful test

### Actual behaviour
```
Caution
×
Next error occurred
Error: Malformed UTF-8 data

Raw answer from server:

Fatal error: Uncaught Error: Call to a member function isEnabled() on null in /var/www/html/teampass/vendor/teampassclasses/ldapextra/src/ActiveDirectoryExtra.php:137 Stack trace: #0 /var/www/html/teampass/sources/ldap.queries.php(180): TeampassClasses\LdapExtra\ActiveDirectoryExtra->userIsEnabled() #1 {main} thrown in /var/www/html/teampass/vendor/teampassclasses/ldapextra/src/ActiveDirectoryExtra.php on line 137
```

### Server configuration
**Operating system**: Ubuntu 22:04

**Web server:** Apache/2.4.52 (Ubuntu) 

**Database:** mariadb:10.11.8

**PHP version:** 8.2

**Teampass version:** 3.1.2.60

**Teampass configuration file:**
```
<?php
// DATABASE connexion parameters
define("DB_HOST", "teampass3_mariadb");
define("DB_USER", "teampass");
define("DB_PASSWD", "teampass");
define("DB_NAME", "teampass");
define("DB_PREFIX", "teampass_");
define("DB_PORT", "3306");
define("DB_ENCODING", "utf8");
define("DB_SSL", false); 

define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/www/html/teampass/includes");
define("SECUREFILE", "teampass-seckey.txt");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");


if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}

```

**Updated from an older Teampass or fresh install:** Updated from 2.1.27.36 to 3.1.2.55 and from 3.1.2.55 to 3.1.2.60
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
```
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '1',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '1',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://localhost:3080/teampass',
    'favicon' => 'http://localhost:3080/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'http://localhost:3080/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://localhost:3080/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => 'ActiveDirectory',
    'ldap_suffix' => '',
    'ldap_domain_dn' => '',
    'ldap_domain_controler' => '',
    'ldap_user_attribute' => 'samaccountname',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '1',
    'roles_allowed_to_print' => '3',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'spanish',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1549975959',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass_',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'Europe/London',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '1',
    'offline_key_level' => '60',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'xxxxxxxx',
    'admin_2fa_required' => '1',
    'ldap_new_user_role' => '3',
    'settings_offline_mode' => '1',
    'ldap_username' => 'ldap.sistemas',
    'ldap_hosts' => 'myserverldap.loc',
    'ldap_bdn' => 'OU=users,OU=system,dc=company,dc=loc',
    'ldap_password' => 'mypassword',
    'ldap_user_dn_attribute' => 'distinguishedname',
);
```

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 11

#### Web server error log
```
[Wed Sep 04 18:48:42.042533 2024] [php:error] [pid 22] [client 172.xx.xx.xx:39940] PHP Fatal error:  Uncaught Error: Call to a member function isEnabled() on null in /var/www/html/teampass/vendor/teampassclasses/ldapextra/src/ActiveDirectoryExtra.php:137\nStack trace:\n#0 /var/www/html/teampass/sources/ldap.queries.php(180): TeampassClasses\\LdapExtra\\ActiveDirectoryExtra->userIsEnabled()\n#1 {main}\n  thrown in /var/www/html/teampass/vendor/teampassclasses/ldapextra/src/ActiveDirectoryExtra.php on line 137, referer: http://localhost:3080/teampass/index.php?page=ldap
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
ldap-test-config  index.php?page=ldap:3324
false   index.php?page=ldap:3343
```

**Comment by gonzalodeniz** [comment]
In the file: **TeamPass/vendor/teampassclasses/ldapextra/src/ActiveDirectoryExtra.php**

```    
function userIsEnabled(string $userDN, Connection $connection): bool
    {
        $isEnabled = false;
        try {
            Container::addConnection($connection);
            $user = User::find($userDN);
            $isEnabled = $user->isEnabled();
        } catch (\LdapRecord\Auth\BindException $e) {
            // Do nothing
        }
        return $isEnabled;
    }
```

This command return $user: NULL and the $userDN contains a valid value
`      $user = User::find($userDN);`

I don't know if the error could be here, that it loads the OpenLDAP USER library instead of ActiveDirectory:
`Line 30: use LdapRecord\Models\OpenLDAP\User;`

**Comment by gonzalodeniz** [comment]
It doesn't matter if you use ldap_type=ActiveDirectory or OpenLdap; querying User::find($userDN) always returns null.

**Comment by gonzalodeniz** [comment]
This solution worked for me.
https://github.com/nilsteampassnet/TeamPass/issues/4080#issuecomment-1971814974
