### ISSUE TITLE
Installation error in v3.1.2.61 and later

### ISSUE THREAD

**Issue by gonzalodeniz** [nilsteampassnet/TeamPass#4310]
Versions v3.1.2.61 and later return this console error in the update window. I don't understand why.
Version v3.1.2.60 works correctly.
```
install.js:260 

--- PREPARATION---
2
{"absolute_path":"/var/www/html/teampass","url_path":"http://localhost:3080/teampass"}
[object Object]
0
true
folder*install
-------

install.js:280 

--- RECEPTION---
[object Object]
-------

install.php:1 Uncaught SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Function.parseJSON (jquery.min.js:16:11709)
    at Object.<anonymous> (install.js:286:22)
    at Object.resolveWith (jquery.min.js:16:15493)
    at Object.done [as complete] (jquery.min.js:16:15379)
    at doGetJson (install.js:279:6)
    at checkPage (install.js:147:17)
    at HTMLInputElement.onclick (install.php:111:119)
```

**Comment by gonzalodeniz** [comment]
I must have done something wrong in the previous installation. It is working fine. I'm sorry for that.
