### ISSUE TITLE
After upgrade from 2.1.27.36 to 3.1.1.26 settings/fields page with admin user is not working and items page with other user same error

### ISSUE THREAD

**Issue by JoseJHoy** [nilsteampassnet/TeamPass#4398]
### Steps to reproduce
1. Upgrade 2.1.27.36 to 3.1.1.26
2. Login with admin user
3. Click in settings/fields

or
2.Login with any other user 
3.Automatically goes to items page and same error directly

### Expected behaviour
Fields page with admin or Items with other user should work

### Actual behaviour
Instead Fields page with admin user become white and nothing happens 
or after any other user logins Items page says Loading in Folders and Loading data in the botton right and nothing happens.

### Server configuration
Debian GNU/Linux 11 (bullseye)

**Web server:**
Apache2-2.4.62
**Database:**
10.11.9-MariaDB-deb11
**PHP version:**
 8.2.24
**Teampass version:** 
3.1.1.26
**Teampass configuration file:**

Attached
[settings.php.txt](https://github.com/user-attachments/files/17246524/settings.php.txt)
[tp.config.php.txt](https://github.com/user-attachments/files/17246525/tp.config.php.txt)

### Client configuration
**Browser:**
CHROME Version 129.0.6668.89 (Official Build) (64-bit)
**Operating system:**
Windows 11
#### Web server error log

[Thu Oct 03 16:53:15.551744 2024] [php:error] [pid 1517:tid 1517] [client 10.178.1.253:11584] PHP Fatal error:  Uncaught Error: Attempt to modify property "children" on null in XXXXXXXXXXXXXXXX/vendor/teampassclasses/nestedtree/src/NestedTree.php:397\nStack trace:\n#0 XXXXXXXXXXXXXXXX/vendor/teampassclasses/nestedtree/src/NestedTree.php(410): TeampassClasses\\NestedTree\\NestedTree->getTreeWithChildren()\n#1 XXXXXXXXXXXXXXXX/pages/fields.php(84): TeampassClasses\\NestedTree\\NestedTree->rebuild()\n#2 XXXXXXXXXXXXXXXX/index.php(956): include('...')\n#3 {main}\n  thrown in XXXXXXXXXXXXXXXX/vendor/teampassclasses/nestedtree/src/NestedTree.php on line 397, referer: https://XXXXXXXX/index.php?page=admin

#### Log from the web-browser developer console (CTRL + SHIFT + i)

![imagen](https://github.com/user-attachments/assets/af213767-ef8b-40b1-987c-962e847e222b)

@nilsteampassnet Could you help us please?

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
