### ISSUE TITLE
Fixing error in SQL syntax on /api/index.php/item/get?id=xxx

### ISSUE THREAD

**Issue by ego-kyriarchos** [nilsteampassnet/TeamPass#4404]
Hi, I fixed the item Module on Teampass REST API.

### The query:
curl -s -X GET -k 'https://teampass.lan/api/index.php/item/get?id=841' -H "Authorization: Bearer ${TOKEN}"

### Error on php:
```bash
tail -f /var/log/php-fpm/www-error.log
[08-Oct-2024 15:00:56 UTC] PHP Fatal error:  Uncaught Exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')) ORDER BY i.id ASC' at line 3 in /var/www/html/teampass/api/Model/Database.php:51
Stack trace:
#0 /var/www/html/teampass/api/Model/ItemModel.php(47): Database->select()
#1 /var/www/html/teampass/api/Controller/Api/ItemController.php(221): ItemModel->getItems()
#2 /var/www/html/teampass/api/inc/bootstrap.php(59): ItemController->getAction()
#3 /var/www/html/teampass/api/index.php(91): itemAction()
#4 {main}
  thrown in /var/www/html/teampass/api/Model/Database.php on line 51
```

### Solution on
/var/www/html/teampass/api/Controller/Api/ItemController.php

```php
	$sql_constraint = ' AND (i.id_tree IN ('.$userData['folders_list'].')'; #OR i.id IN ('.$userData['restricted_items_list'].'))';
	if (!empty($userData['restricted_items_list'])) {
		$sql_constraint = $sql_constraint.'OR i.id IN ('.$userData['restricted_items_list'].')';
	}
	$sql_constraint = $sql_constraint.')';
```

**Comment by nilsteampassnet** [comment]
Thank you
