### ISSUE TITLE
Some admin pages stuck at Loading...

### ISSUE THREAD

**Issue by lipocky** [nilsteampassnet/TeamPass#4472]
### Steps to reproduce
1.
2.
3.

Some pages of the Admin user such Users, Tasks, Renewal, Logs, Database. The pages are displayed, but without data. The browser was cleaned from cookies, tested on multiple browsers.

This is happening after upgrade from v2.1.27.36 to v3.1.2.134 on a new clean server by copying over the mariadb 10.6.20 upgraded to 10.11.6 yet before Teampass installation.

During infinite Loading there is no warning/error in php logs. 

It might be important to mention that the teampass upgrade process was buggy and not straightforward. In order to get through all teampass db upgrade steps I had to temporarily set $maxTimestamp to null in public function getLastModificationTimestamp() in ./vendor/teampassclasses/configmanager/src/ConfigManager.php after showing up this exception below in php.log, otherwise the upgrade process got stuck.
The Users page was buggy also in v3.1.1 with error DataTables warning: table id=table-users - Ajax error. For more information about this error, please see http://datatables.net/tn/7, where ConfigManager did not exist in the code yet.

[17-Nov-2024 18:24:24 UTC] PHP Fatal error:  Uncaught MeekroDBException: Unknown column 'created_at' in 'field list' in /var/www/html/teampass-3.1.2/vendor/sergeytsalkov/meekrodb/db.class.php:934
Stack trace:
#0 /var/www/html/teampass-3.1.2/vendor/sergeytsalkov/meekrodb/db.class.php(895): MeekroDB->queryHelper()
#1 /var/www/html/teampass-3.1.2/vendor/sergeytsalkov/meekrodb/db.class.php(1011): MeekroDB->queryAllLists()
#2 /var/www/html/teampass-3.1.2/vendor/sergeytsalkov/meekrodb/db.class.php(1032): MeekroDB->queryFirstList()
#3 /var/www/html/teampass-3.1.2/vendor/sergeytsalkov/meekrodb/db.class.php(116): MeekroDB->queryFirstField()
#4 /var/www/html/teampass-3.1.2/vendor/teampassclasses/configmanager/src/ConfigManager.php(134): DB::__callStatic()
#5 /var/www/html/teampass-3.1.2/vendor/teampassclasses/configmanager/src/ConfigManager.php(48): TeampassClasses\ConfigManager\ConfigManager->getLastModificationTimestamp()
#6 /var/www/html/teampass-3.1.2/vendor/teampassclasses/configmanager/src/ConfigManager.php(40): TeampassClasses\ConfigManager\ConfigManager->loadConfiguration()
#7 /var/www/html/teampass-3.1.2/sources/main.functions.php(65): TeampassClasses\ConfigManager\ConfigManager->__construct()
#8 /var/www/html/teampass-3.1.2/install/upgrade_ajax.php(203): require_once('...')
#9 {main}
  thrown in /var/www/html/teampass-3.1.2/vendor/sergeytsalkov/meekrodb/db.class.php on line 934

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Red Hat Enterprise Linux 8.10

**Web server:** Apache HTTPD 2.4.37

**Database:**  MariaDB 10.11 LTS

**PHP version:** 8.4

**Teampass version:** 3.1.1.26

**Teampass configuration file:**
Final version:
<?php
// DATABASE connexion parameters
define("DB_HOST", "localhost");
define("DB_USER", "teampass_admin");
define("DB_PASSWD", "<censored>");
define("DB_NAME", "teampass");
define("DB_PREFIX", "teampass_");
define("DB_PORT", "3306");
define("DB_ENCODING", "");
//define("DB_SSL", false); // if DB over SSL then comment this line
// if DB over SSL then uncomment the following lines
define("DB_SSL", array(
    "key" => "",
    "cert" => "",
    "ca_cert" => "",
    "ca_path" => "",
    "cipher" => ""
));
define("DB_CONNECT_OPTIONS", array(
    MYSQLI_OPT_CONNECT_TIMEOUT => 10
));
define("SECUREPATH", "/var/www/html/teampass/includes");
define("SECUREFILE", "teampass-seckey.txt");
define("IKEY", "");
define("SKEY", "");
define("HOST", "");

if (isset($_SESSION['settings']['timezone']) === true) {
    date_default_timezone_set($_SESSION['settings']['timezone']);
}

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

From v2.1.27.36 
<?php
global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '1',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'https://teampass.server/teampass',
    'favicon' => 'https://teampass.server/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'url_to_upload_folder' => 'https://teampass.server/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'https://teampass.server/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '0',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '2.1.27',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '1',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1534850321',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => 'mail.teampass.server',
    'email_smtp_auth' => '0',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '25',
    'email_security' => '',
    'email_server_url' => 'teampass.server',
    'email_from' => 'it-system@teampass.server',
    'email_from_name' => 'Teampass',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml,dar',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for ChangeMe',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '1',
    'syslog_host' => '10.112.187.82',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => <censored>,
    'bck_script_key' => '',
    'teampass_version' => '2.1.27',
    'admin_2fa_required' => '0',
    );

### Client configuration
**Browser:** Microsoft Edge, Google Chrome

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)

Attached

```
![image](https://github.com/user-attachments/assets/3b90f20b-3010-45ff-b6c7-8b24d35f2bf3)

![image](https://github.com/user-attachments/assets/d1972162-71db-47f6-aaea-3f3365d14fd5)

![image](https://github.com/user-attachments/assets/cd4b06a0-009d-44d1-ac4c-0554a32da7d6)

**Comment by corentin-soriano** [comment]
Can you give us the result of (where teampass_ is your table prefix):
```sql
SHOW CREATE TABLE teampass_misc;
```

This will probably fix your issue (can give you sql error if duplicate column):
```sql
ALTER TABLE teampass_misc ADD COLUMN created_at VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE teampass_misc ADD COLUMN updated_at VARCHAR(255) NULL DEFAULT NULL;
```

Can you restart the update process first (`install/upgrade.php`)? It should add all missing columns.
