### ISSUE TITLE
Fresh Install failing.

### ISSUE THREAD

**Issue by hitenmandalia** [nilsteampassnet/TeamPass#4479]
### Steps to reproduce

1.  Attempt to install fresh 
2.
3.

### Expected behaviour
Should be able to pass the check screen

### Actual behaviour
Nothing happens on screen.  Errors shown

### Server configuration
**Operating system**: Alpine Linux

**Web server:** Nginx

**Database:** MySQL 8

**PHP version:** 8.1

**Teampass version:** 

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

Install never goes past the Checks screen:

![image](https://github.com/user-attachments/assets/798e3afb-0a41-4688-9123-6f7e6d966ecd)
![image](https://github.com/user-attachments/assets/26370f7d-bd15-4daf-b9d9-afbec0b4bace)

``
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "NOTICE: PHP message: PHP Notice:  file_get_contents(): Read of 12288 bytes failed with errno=21 Is a directory in /var/www/html/vendor/teampassclasses/sessionmanager/src/SessionManager.php on line 44"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "NOTICE: PHP message: PHP Stack trace:"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "NOTICE: PHP message: PHP   1. {main}() /var/www/html/install/install.queries.php:0"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "NOTICE: PHP message: PHP   2. require_once() /var/www/html/install/install.queries.php:57"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "NOTICE: PHP message: PHP   3. TeampassClasses\SessionManager\SessionManager::getSession() /var/www/html/sources/main.functions.php:62"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "NOTICE: PHP message: PHP   4. file_get_contents($filename = '/') /var/www/html/vendor/teampassclasses/sessionmanager/src/SessionManager.php:44"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Defuse\Crypto\Exception\BadFormatException: Encoded data is shorter than expected. in /var/www/html/vendor/defuse/php-encryption/src/Encoding.php:233"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "Stack trace:"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "#0 /var/www/html/vendor/defuse/php-encryption/src/Key.php(53): Defuse\Crypto\Encoding::loadBytesFromChecksummedAsciiSafeString('\xDE\xF0\x00\x00', Object(SensitiveParameterValue))"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "#1 /var/www/html/vendor/teampassclasses/sessionmanager/src/SessionManager.php(44): Defuse\Crypto\Key::loadFromAsciiSafeString(Object(SensitiveParameterValue))"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "#2 /var/www/html/sources/main.functions.php(62): TeampassClasses\SessionManager\SessionManager::getSession()"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "#3 /var/www/html/install/install.queries.php(57): require_once('/var/www/html/s...')"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "#4 {main}"
2024-11-21 15:53:18 [21-Nov-2024 15:53:18] WARNING: [pool www] child 61 said into stderr: "  thrown in /var/www/html/vendor/defuse/php-encryption/src/Encoding.php on line 233"
2024-11-21 15:53:18 172.17.0.1 - - [21/Nov/2024:15:53:18 +0000] "POST /install/install.queries.php HTTP/1.1" 500 5 "https://xxx.xxx.xxx/install/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
``
```

**Comment by corentin-soriano** [comment]
Can you give us the result of (where teampass_ is your table prefix):
```sql
SHOW CREATE TABLE teampass_misc;
```

This will probably fix your issue (can give you sql error if duplicate column):
```sql
ALTER TABLE teampass_misc ADD COLUMN created_at VARCHAR(255) NULL DEFAULT NULL;
ALTER TABLE teampass_misc ADD COLUMN updated_at VARCHAR(255) NULL DEFAULT NULL;
```

Can you restart the update process first (`install/upgrade.php`)? It should add all missing columns.

**Comment by corentin-soriano** [comment]
Sorry, I was wrong, this post was for another issue.

@nilsteampassnet I think this is related to the session encryption because SECUREPATH and SECUREFILE are not defined at this point of install process.
I think we should disable encryption during initial installation or create these files earlier (and declare the constants).

**Comment by hitenmandalia** [comment]
thank you @corentin-soriano

**Comment by stanislavefremov** [comment]
Agree with @corentin-soriano. I also had to manually create SECUREFILE, populate it with a key string and set up SECUREPATH and SECUREFILE variables in the config. Then the installation went through.

**Comment by hitenmandalia** [comment]
@stanislavefremov could you possibly guide me on how you did this? Where did you create the files, how did you determine what variables to user etc?

**Comment by stanislavefremov** [comment]
@hitenmandalia I am not sure it's a best way to solve the issue, it's rather a workaround for me and at least it worked. The issue I noticed that even during the fresh install the system is using Sessions and Sessions in turn require secure folder and secure key to exist, though they normally are created later by the install process. So:
1) Generate a seckey. It should look something like this: def00000e7753e0d155cc5a7d5979b09d6f3f68f499b401abf42c9006dca7da82d62e46331803c7bc253f11fa3632f5fa7172766203fb172f6d759780bd683b5bc68b16d
I used the same packed which is used in Teampass, it's https://packagist.org/packages/defuse/php-encryption. Something like this:
use Defuse\Crypto\Key;
$key = Key::createNewRandomKey();
$new_salt = $key->saveToAsciiSafeString();
But you can use other generators, even find something online.
2) Create the secure folder and secure file. In my case I created 'sk' directory in the project root of /var/www/html and a file called teampass-seckey.txt inside the sk folder.
3) Put the generated seckey to the teampass-seckey.txt file.
4) Open includes/config/settings.php config file or just copy it from settings.sample.php, and change 2 constants like that:
define("SECUREPATH", "/var/www/html/sk");
define("SECUREFILE", "teampass-seckey.txt");
5) Go back to the installation process and restart it. 
After that the installation should proceed further. 
Just in case, save the seckey. Though the installer will generate another key and replace your settings.php file with new data. At this point you should backup your sk folder and maybe settings.php.

**Comment by hitenmandalia** [comment]
@stanislavefremov thank you for taking the time to write this up.   I will give it a go.

**Comment by nilsteampassnet** [comment]
@hitenmandalia 
Please update using branch master.
A fiw has been committed.

**Comment by Cash-xmlwriter** [comment]
> [@hitenmandalia](https://github.com/hitenmandalia) Please update using branch master. A fiw has been committed.





https://phps.space/questions/set-a-value-to-a-variable-within-a-function
