### ISSUE TITLE
Error generate 2FA QR-code

### ISSUE THREAD

**Issue by DobroFenix** [nilsteampassnet/TeamPass#4519]
### Steps to reproduce
1. activate MFA from control panel
2. I receive a code for the first login by mail
3. I enter TeamPass with the correct one-time code from the mail.
4. Get error generate QR-code

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
Operating system:
RHEL 8

Web server:
nginx 1.14.1
Database:
MySQL 15.1

PHP version:
8.3.14 (php-fpm, user:nginx)
Teampass version:
5.1.3.1

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
2024/12/05 16:28:57 [error] 4120179#0: *911469 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: RobThree\Auth\Providers\Qr\QRServerProvider::getQRCodeImage(): Return value must be of type string, false returned in /var/www/teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php:36
Stack trace:
#0 /var/www/teampass/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(120): RobThree\Auth\Providers\Qr\QRServerProvider->getQRCodeImage()
#1 /var/www/teampass/sources/identify.php(1611): RobThree\Auth\TwoFactorAuth->getQRCodeImageAsDataUri()
#2 /var/www/teampass/sources/identify.php(2489): googleMFACheck()
#3 /var/www/teampass/sources/identify.php(344): identifyDoMFAChecks()
#4 /var/www/teampass/sources/identify.php(85): identifyUser()
#5 {main}
  thrown in /var/www/teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php on line 36" while reading response header from upstream, client: 192.168.78.5, server: uib-t-logproxy, request: "POST /sources/identify.php HTTP/1.1", upstream: "fastcgi://unix:/var/opt/remi/php83/run/php-fpm/www.sock:", host: "uib-t-logproxy", referrer: "https://uib-t-logproxy/index.php"
2024/12/05 16:29:56 [error] 4120179#0: *911469 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: RobThree\Auth\Providers\Qr\QRServerProvider::getQRCodeImage(): Return value must be of type string, false returned in /var/www/teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php:36
Stack trace:
#0 /var/www/teampass/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(120): RobThree\Auth\Providers\Qr\QRServerProvider->getQRCodeImage()
#1 /var/www/teampass/sources/identify.php(1611): RobThree\Auth\TwoFactorAuth->getQRCodeImageAsDataUri()
#2 /var/www/teampass/sources/identify.php(2489): googleMFACheck()
#3 /var/www/teampass/sources/identify.php(344): identifyDoMFAChecks()
#4 /var/www/teampass/sources/identify.php(85): identifyUser()
#5 {main}
  thrown in /var/www/teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php on line 36" while reading response header from upstream, client: 192.168.78.5, server: uib-t-logproxy, request: "POST /sources/identify.php HTTP/1.1", upstream: "fastcgi://unix:/var/opt/remi/php83/run/php-fpm/www.sock:", host: "uib-t-logproxy", referrer: "https://uib-t-logproxy/index.php"
2024/12/05 17:06:46 [error] 4120179#0: *934259 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: RobThree\Auth\Providers\Qr\QRServerProvider::getQRCodeImage(): Return value must be of type string, false returned in /var/www/teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php:36
Stack trace:
#0 /var/www/teampass/vendor/robthree/twofactorauth/lib/TwoFactorAuth.php(120): RobThree\Auth\Providers\Qr\QRServerProvider->getQRCodeImage()
#1 /var/www/teampass/sources/identify.php(1611): RobThree\Auth\TwoFactorAuth->getQRCodeImageAsDataUri()
#2 /var/www/teampass/sources/identify.php(2489): googleMFACheck()
#3 /var/www/teampass/sources/identify.php(344): identifyDoMFAChecks()
#4 /var/www/teampass/sources/identify.php(85): identifyUser()
#5 {main}
  thrown in /var/www/teampass/vendor/robthree/twofactorauth/lib/Providers/Qr/QRServerProvider.php on line 36" while reading response header from upstream, client: 192.168.78.5, server: uib-t-logproxy, request: "POST /sources/identify.php HTTP/1.1", upstream: "fastcgi://unix:/var/opt/remi/php83/run/php-fpm/www.sock:", host: "uib-t-logproxy", referrer: "https://uib-t-logproxy/index.php"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

![image](https://github.com/user-attachments/assets/aed56eed-c313-4790-a9e8-b8e5cef8e8f9)

**Comment by DobroFenix** [comment]
It's settled.
A third-party service is used to generate QR codes for which Internet access is needed.
